# -*- coding: utf-8 -*-
"""Appendix - Rapid revision, glossary, legal timeline, mnemonic index"""

BLOCKS = [

('ch', ("A", "Rapid Revision Bank",
        "Mnemonic index \u2022 Legal timeline \u2022 Glossary \u2022 Latin maxims \u2022 One-page answer skeletons")),

('h2', "A.1  Master Index of All Mnemonics in These Notes"),
('tbl', (["Ch.", "Mnemonic", "Stands for"],
         [["1", "**KASSA-CARD**", "Characteristics of a profession: Knowledge, Autonomy, Specialised education, Service, Accountability, Code of ethics, Association, Registration, Development"],
          ["1", "**A-CHIEVER**", "Attributes of professionalism: Altruism, Competence/Compassion, Honesty, Integrity of records, Excellence, Values, Empathy, Responsibility"],
          ["2", "**DIGNITY**", "Decision-making respected, Identity preserved, Gentleness, No discrimination, Information honest, Trust/confidentiality, Your privacy"],
          ["3", "**A-B-N-J**", "The four principles: Autonomy, Beneficence, Non-maleficence, Justice (the *Georgetown Mantra*)"],
          ["3", "**C-D-U-V-A**", "Valid consent: Competence, Disclosure, Understanding, Voluntariness, Authorisation"],
          ["3", "**FOUR-BOX**", "Jonsen's method: Medical indications, Patient preferences, Quality of life, Contextual features"],
          ["4", "**S-M-C-R-F**", "Communication process: Sender, Message, Channel, Receiver, Feedback (+ Noise, Environment)"],
          ["4", "**SOLER**", "Listening posture: Squarely, Open posture, Lean forward, Eye contact, Relax"],
          ["4", "**RESPECT**", "Active listening: Reflect, Eye contact, Summarise, Paraphrase, Empathise, Clarify, Take notes"],
          ["4", "**7 C's**", "Clear, Concise, Concrete, Correct, Coherent, Complete, Courteous"],
          ["4", "**P-P-P-S-C-O-P**", "Barriers: Physical, Physiological, Psychological, Semantic, Cultural, Organisational, Personal"],
          ["4", "**SBAR**", "Situation, Background, Assessment, Recommendation"],
          ["5", "**TRUST**", "Truthfulness, Respect, Understanding, Secrecy, Technical competence"],
          ["5", "**I-C-C-R-E-D-S**", "Patient rights: Information, Consent, Confidentiality, Refusal/Redressal, Emergency care, Discrimination-free, Second opinion/Safety/Scale of charges"],
          ["6", "**Five R's**", "Right result, right patient, right time, right person, right route"],
          ["6", "**SPIKES**", "Setting, Perception, Invitation, Knowledge, Emotions/Empathy, Strategy & Summary"],
          ["6", "**COURTS PLEASE**", "Exceptions to confidentiality (see Ch. 6)"],
          ["7", "**4 D's**", "Negligence: Duty, Dereliction, Direct causation, Damage"],
          ["7", "**S-C-Q-D-I**", "Legal shields: SOPs, Consent, Quality control, Documentation, Insurance"],
          ["8", "**S-I-C-H-R-E**", "Consumer rights: Safety, Information, Choice, Hearing, Redressal, Education"],
          ["8", "**B-C-P-E-P-W**", "Lab hazards: Biological, Chemical, Physical, Ergonomic, Psychosocial, Waste"],
          ["8", "**P-W-E-H-P-L**", "Insurance: Professional indemnity, Workmen's compensation, ESI, Health, Personal accident, Life"],
          ["9", "**PLANNED**", "Prioritise, List, Avoid procrastination, No (say it), Note/review, Eliminate interruptions, Delegate/Deadline"],
          ["9", "**4 D's of paperwork**", "Do it, Delegate it, Defer it, Dump it"],
          ["10", "**E-D-R**", "Burnout: Emotional exhaustion, Depersonalisation, Reduced accomplishment"],
          ["10", "**S-T-R-E-S-S-E-D**", "Sleep, Time management, Relaxation, Exercise, Social support, Say no, Eat well, Diversion/Doctor"],
          ["11", "**LEADERSHIP**", "Listening, Empathy, Accountability, Decision-making, Example, Responsibility, Self-awareness, Humility, Initiative, Professional competence"],
          ["11", "**TEAMWORK**", "Trust, Effective communication, Accountability, Mutual respect, Well-defined roles, One goal, Recognition, Knowledge sharing"],
          ["11", "**Form-Storm-Norm-Perform-Adjourn**", "Tuckman's stages of team development"]],
         [0.8, 3.6, 12.8],
         "Every mnemonic in one place \u2014 write these on your rough sheet the moment the exam begins")),

('h2', "A.2  Legal and Historical Timeline \u2014 Dates You Must Not Confuse"),
('tbl', (["Year", "Event / Statute / Case", "One-line significance"],
         [["c. 400 BC", "**Hippocratic Oath**", "First codified medical oath; *primum non nocere*; confidentiality"],
          ["1803", "**Percival's Code**", "First modern written code of medical ethics"],
          ["1847", "**AMA Code of Ethics**", "First national professional code (USA)"],
          ["1872", "**Indian Contract Act**", "Basis of the requirement of free consent"],
          ["1875", "**Indian Majority Act**", "Age of majority = 18 years \u2192 age of consent for treatment"],
          ["1897", "**Epidemic Diseases Act**", "State powers during an epidemic; **amended 2020** \u2014 violence against health workers made a cognizable, non-bailable offence"],
          ["1923", "**Workmen's / Employee's Compensation Act**", "Employer's liability for occupational injury and disease"],
          ["1936", "**Selye \u2014 General Adaptation Syndrome**", "Alarm \u2192 Resistance \u2192 Exhaustion"],
          ["1939", "**Lewin's leadership styles**", "Autocratic, democratic, laissez-faire"],
          ["1940", "**Drugs and Cosmetics Act**", "Regulation of diagnostic kits, reagents; blood-bank licensing"],
          ["1947", "**Nuremberg Code**", "**Voluntary informed consent is absolutely essential** in human experimentation"],
          ["1948", "**Declaration of Geneva**; **UDHR**; **ESI Act (India)**", "Modern physician's oath; 'all human beings are born free and equal in dignity and rights'; employees' social security"],
          ["1949", "**International Code of Medical Ethics** (WMA)", "Duties of doctors in general, to the sick, and to each other"],
          ["1956", "**Szasz & Hollender models**", "Activity\u2013passivity, guidance\u2013cooperation, mutual participation"],
          ["1957", "***Bolam* v. Friern Hospital**", "Standard of care = a practice accepted by a responsible body of professional opinion"],
          ["1964", "**Declaration of Helsinki**", "Ethical principles for medical research on human subjects"],
          ["1965", "**Tuckman's stages**", "Forming, storming, norming, performing (**adjourning** added 1977)"],
          ["1971", "**MTP Act** (India)", "Lawful termination of pregnancy; **amended 2021** \u2014 20/24-week limits, Medical Board beyond 24 weeks"],
          ["1972", "**Lundberg \u2014 critical values**", "Introduced the concept of the panic/critical value"],
          ["1978", "**Declaration of Alma-Ata**", "'Health for All'; health as a fundamental human right; primary health care"],
          ["1979", "**Belmont Report**; **Beauchamp & Childress**", "Respect for persons, beneficence, justice; and the **four principles** of biomedical ethics"],
          ["1981", "**Declaration of Lisbon**", "Rights of the patient (WMA)"],
          ["1986", "**Consumer Protection Act** (India)", "Consumer redressal machinery \u2014 **replaced by the 2019 Act**"],
          ["1989", "***Parmanand Katara* v. Union of India**", "**Right to emergency medical care** \u2014 a doctor must treat first, formalities later"],
          ["1994", "**PC-PNDT Act**; **THOA**", "Prenatal sex determination and disclosure a criminal offence; organ transplantation and brain-death certification (**THOA amended 2011**)"],
          ["1995", "***IMA* v. *V.P. Shantha***", "**Medical service = 'service'** under consumer law; patient = 'consumer'"],
          ["1997", "***Bolitho***", "The accepted practice relied on must withstand **logical analysis**"],
          ["1998", "***Mr X* v. *Hospital Z***", "Disclosure of HIV status to a fianc\u00e9e justified \u2014 **third-party-risk exception** to confidentiality"],
          ["2002", "**IMC (Professional Conduct, Etiquette and Ethics) Regulations**", "The operative Indian code of medical conduct and misconduct"],
          ["2005", "***Jacob Mathew* v. State of Punjab**; **UNESCO Bioethics Declaration**", "Adopted the *Bolam* standard; required a credible independent medical opinion before prosecuting a professional; global bioethics principles"],
          ["2008", "***Samira Kohli* v. *Dr Prabha Manchanda***", "Consent must be **real, valid and procedure-specific**"],
          ["2010", "**Clinical Establishments Act**", "Registration and minimum standards for clinical laboratories"],
          ["2011", "***Aruna Shanbaug* v. Union of India**", "**Passive euthanasia** permitted in exceptional cases"],
          ["2012", "**POCSO Act**", "**Mandatory reporting** of sexual offences against children"],
          ["2013", "**POSH Act**", "Internal Complaints Committee for sexual harassment at the workplace"],
          ["2016", "**Bio-Medical Waste Management Rules**", "Colour-coded segregation: yellow, red, white translucent, blue"],
          ["2017", "***K.S. Puttaswamy* v. Union of India**; **HIV/AIDS Act**; **Mental Healthcare Act**", "**Privacy is a fundamental right** under Article 21; consent and non-disclosure for HIV; rights of persons with mental illness and decriminalisation of attempted suicide"],
          ["2018", "***Common Cause* v. Union of India**; **Charter of Patients' Rights**", "**Right to die with dignity** and the **living will**; 17 patient rights (NHRC/MoHFW)"],
          ["2019", "**Consumer Protection Act**; **New Drugs and Clinical Trials Rules**", "CCPA, product liability, mediation, e-filing; ethics-committee and trial regulation"],
          ["2020", "**Epidemic Diseases (Amendment) Act**", "Violence against health-care personnel \u2014 cognizable and non-bailable"],
          ["2021", "**National Commission for Allied and Healthcare Professions Act**; **ART & Surrogacy Acts**; **MTP Amendment**", "**Statutory regulation of MLT and other allied professions**; regulation of ART and surrogacy; revised MTP limits"],
          ["2023", "**Digital Personal Data Protection Act**; **Bharatiya Nyaya Sanhita**", "Protection of digital health data; the new penal code replacing the IPC (s. 304A \u2192 rash/negligent act provisions)"]],
         [1.4, 5.4, 10.4],
         "Complete legal and historical timeline for BMLT304")),

('h2', "A.3  Latin Maxims and Technical Terms \u2014 Quick Glossary"),
('tbl', (["Term", "Meaning"],
         [["***Primum non nocere***", "'First, do no harm' \u2014 the maxim of **non-maleficence**"],
          ["***Salus aegroti suprema lex***", "'The welfare of the patient is the supreme law' \u2014 **beneficence**"],
          ["***Voluntas aegroti suprema lex***", "'The will of the patient is the supreme law' \u2014 **autonomy**"],
          ["***Res ipsa loquitur***", "'The thing speaks for itself' \u2014 negligence presumed; **burden shifts to the defendant**"],
          ["***Respondeat superior***", "'Let the master answer' \u2014 **vicarious liability**"],
          ["***Qui facit per alium facit per se***", "'He who acts through another acts himself' \u2014 vicarious liability"],
          ["***Volenti non fit injuria***", "'To a willing person no injury is done' \u2014 consent to a known risk as a defence"],
          ["***Novus actus interveniens***", "A new intervening act that breaks the chain of causation"],
          ["***Causa causans***", "The immediate, effective cause of the damage"],
          ["***Uberrima fides***", "'Utmost good faith' \u2014 the governing principle of an insurance contract"],
          ["***In loco parentis***", "'In the place of a parent' \u2014 consent by a person temporarily standing in for a parent"],
          ["***Ethos / Mores / Professio***", "Character / customs / to declare publicly \u2014 roots of *ethics*, *morals*, *profession*"],
          ["**Fiduciary relationship**", "A relationship of trust in which the stronger party must act in the weaker party's interest"],
          ["**Prima facie duty**", "A duty binding unless overridden by a stronger competing duty in the particular case"],
          ["**Paternalism**", "Overriding a person's choices for what one believes to be his own good (hard = over a competent patient; soft = where capacity is impaired)"],
          ["**Therapeutic privilege**", "The narrow exception permitting non-disclosure where disclosure itself would gravely harm the patient"],
          ["**Therapeutic misadventure**", "Injury from treatment given in good faith with due care \u2014 **not** negligence"],
          ["**Medical futility**", "Treatment that cannot achieve its objective or merely prolongs dying \u2014 **no obligation to provide it**"],
          ["**Doctrine of double effect**", "A foreseen but unintended harm may be permissible if the act is good, the intention is good and there is proportionate reason"],
          ["**Privileged communication**", "Lawful disclosure in good faith, to the proper authority, to the extent necessary"],
          ["**Dry labbing**", "Reporting a test that was never performed \u2014 fraud and grave professional misconduct"],
          ["**Delta check**", "Comparison of a result with the same patient's previous result to detect error"],
          ["**Turnaround time (TAT)**", "Interval from test order (or collection) to the result being available and acted upon"],
          ["**Critical / panic value**", "A result so abnormal as to be life-threatening; must be communicated immediately"],
          ["**Read-back**", "The receiver repeating a verbal result or order to confirm accurate transmission"],
          ["**Autoverification**", "Automatic release of results meeting predefined rules, so that staff review only exceptions"],
          ["**Universal / standard precautions**", "Treating **every** specimen as potentially infectious \u2014 protects staff *and* protects confidentiality"],
          ["**Whistle-blowing**", "Reporting unsafe or unethical practice through proper channels"],
          ["**Psychological safety**", "The shared belief that one can speak up, question and admit error without humiliation"],
          ["**Just culture**", "A culture that examines the system rather than punishing the individual, while retaining accountability"],
          ["**Allostatic load**", "The cumulative physiological wear and tear caused by chronic stress"],
          ["**Moral distress**", "The distress of knowing the right course of action but being prevented from taking it"],
          ["**Groupthink**", "Suppression of dissent in a cohesive group, leading to poor decisions"],
          ["**Social loafing**", "Reduced individual effort when working in a group"]],
         [4.6, 12.6],
         "Glossary of maxims and technical terms")),

('h2', "A.4  One-Page Answer Skeletons for the Most Likely Long Questions"),
('tbl', (["Question", "Skeleton \u2014 write these headings, then expand"],
         [["**Principles of medical ethics (Ch. 3)**",
           "1. Introduction + definition \u2192 2. Beauchamp & Childress, 1979; *prima facie* duties \u2192 3. Table of the four principles \u2192 4. **Autonomy** (definition, C-D-U-V-A, applications, limitations) \u2192 5. **Beneficence** (positive duty, risk\u2013benefit, lab duties) \u2192 6. **Non-maleficence** (*primum non nocere*, types of harm in the lab) \u2192 7. **Justice** (types, lab obligations) \u2192 8. Supporting principles \u2014 veracity, fidelity, confidentiality, dignity \u2192 9. One conflict with its resolution \u2192 10. Conclusion"],
          ["**Negligence (Ch. 7)**",
           "1. Definition \u2192 2. **4 D's table** \u2192 3. Standard of care \u2014 *Bolam* / *Jacob Mathew*; what the law does not require \u2192 4. **Types** table \u2192 5. *Res ipsa loquitur* \u2192 6. **Vicarious liability** \u2192 7. Negligence vs malpractice vs misconduct \u2192 8. **Defences** (numbered) \u2192 9. Lab examples by phase (pre-/analytical/post-) \u2192 10. Prevention (S-C-Q-D-I) \u2192 11. Conclusion"],
          ["**Communication (Ch. 4)**",
           "1. Definition + importance \u2192 2. **Process diagram** (S-M-C-R-F + noise + feedback) \u2192 3. **Types** \u2192 4. Verbal skills \u2192 5. **Non-verbal** (+ SOLER) \u2192 6. Active listening; empathy vs sympathy \u2192 7. **Barriers table** with remedies \u2192 8. **7 C's** \u2192 9. With patients / clinicians (**SBAR**) / attendants \u2192 10. Consequences of failure \u2192 11. Conclusion"],
          ["**Confidentiality (Ch. 6)**",
           "1. Definition \u2192 2. Ethical basis (autonomy, privacy, non-maleficence, fidelity, utility, trust) \u2192 3. Legal basis (**Art. 21/Puttaswamy 2017**, HIV Act 2017, MHA 2017, DPDP 2023, CPA 2019) \u2192 4. Scope \u2014 covers everything, binds everyone, survives death \u2192 5. **Privileged communication** \u2192 6. **Exceptions table** \u2192 7. Four golden rules of disclosure \u2192 8. Common breaches in a lab \u2192 9. Safeguards (administrative/physical/technical/personal) \u2192 10. Consequences + ***Mr X v. Hospital Z*** \u2192 11. Conclusion"],
          ["**Consumer protection + insurance (Ch. 8)**",
           "**Part A:** 1. ***IMA v. V.P. Shantha*** \u2192 2. Definitions \u2014 consumer, service, deficiency \u2192 3. **Six rights (S-I-C-H-R-E)** \u2192 4. **Three-tier machinery** with limits \u2192 5. Procedure and limitation (2 years) \u2192 6. Reliefs \u2192 7. New features of the 2019 Act. **Part B:** 8. **Hazards (B-C-P-E-P-W)** with prevention \u2192 9. Needle-stick management \u2192 10. **Types of insurance (P-W-E-H-P-L)** \u2192 11. Professional indemnity \u2014 cover and exclusions \u2192 12. Statutory protections \u2192 13. Conclusion"],
          ["**Time management (Ch. 9)**",
           "1. Definition; self-management; efficiency vs effectiveness \u2192 2. Importance (patient safety, TAT) \u2192 3. Principles (**PLANNED**, SMART) \u2192 4. **Eisenhower matrix diagram** \u2192 5. Pareto 80/20 + Parkinson's Law \u2192 6. **Time wasters** (external/internal table) \u2192 7. Techniques table \u2192 8. Application \u2014 TAT and the model shift plan \u2192 9. Procrastination \u2192 10. Barriers \u2192 11. Conclusion"],
          ["**Stress management (Ch. 10)**",
           "1. Definition (Selye) \u2192 2. Stressor / coping / adaptation \u2192 3. Types \u2014 eustress vs distress; **Yerkes\u2013Dodson** \u2192 4. **GAS flow diagram** \u2192 5. Physiology (HPA axis, cortisol) \u2192 6. Occupational + personal stressors \u2192 7. Effects (physical/emotional/cognitive/behavioural) \u2192 8. **Burnout (E-D-R)** vs depression \u2192 9. Coping \u2014 problem- vs emotion-focused \u2192 10. Individual measures + **relaxation techniques** \u2192 11. **Organisational measures** \u2192 12. Patient-safety conclusion"],
          ["**Leadership & teamwork (Ch. 11)**",
           "1. Definition of leadership \u2192 2. Leader vs manager table \u2192 3. Sources of power \u2192 4. **Qualities (LEADERSHIP)** grouped \u2192 5. **Styles table** (Lewin + transformational, servant, situational) \u2192 6. 'No single best style' \u2192 7. Functions of a leader \u2192 8. Team vs group \u2192 9. **Tuckman diagram** \u2192 10. Characteristics of an effective team (**TEAMWORK**, psychological safety) \u2192 11. Barriers (groupthink, social loafing) \u2192 12. **Conflict resolution** (Thomas\u2013Kilmann) \u2192 13. Patient-safety conclusion"]],
         [4.0, 13.2],
         "Answer skeletons \u2014 revise these on the night before the exam")),

('h2', "A.5  Twenty Two-Mark Answers You Should Be Able to Write in Two Lines"),
('n', [
    "**Ethics** \u2014 the systematic study of right and wrong conduct and the standards by which human actions are judged.",
    "**Professionalism** \u2014 the habitual demonstration of competence, character, commitment and accountability in the service of patients.",
    "**Autonomy** \u2014 the competent patient's right to make informed, voluntary decisions about his own body and information.",
    "**Non-maleficence** \u2014 the duty not to inflict harm; *primum non nocere*.",
    "**Beneficence** \u2014 the positive duty to act for the patient's benefit and welfare.",
    "**Justice** \u2014 fairness and non-discrimination in the distribution of benefits, risks and resources.",
    "**Informed consent** \u2014 voluntary agreement by a competent person after adequate disclosure and understanding.",
    "**Confidentiality** \u2014 the duty not to disclose patient information obtained professionally, without consent or lawful justification.",
    "**Privileged communication** \u2014 disclosure made in good faith, to the proper authority, to the extent necessary.",
    "**Critical (panic) value** \u2014 a result so abnormal as to be life-threatening, requiring immediate communication.",
    "**Negligence** \u2014 breach of a duty of care causing damage; requires duty, dereliction, direct causation and damage.",
    "**Res ipsa loquitur** \u2014 'the thing speaks for itself'; negligence is presumed and the burden of proof shifts to the defendant.",
    "**Vicarious liability** \u2014 an employer's liability for his employee's negligence committed in the course of employment.",
    "**Malpractice** \u2014 improper, illegal or negligent professional conduct causing injury to a patient.",
    "**Professional misconduct** \u2014 conduct regarded as disgraceful or dishonourable by professional colleagues of good repute.",
    "**Consumer** \u2014 a person who avails of a service for a consideration paid or promised.",
    "**Deficiency in service** \u2014 any fault, imperfection, shortcoming or inadequacy in the quality or manner of performance of a service.",
    "**Stress** \u2014 the non-specific response of the body to any demand made upon it (Selye).",
    "**Burnout** \u2014 emotional exhaustion, depersonalisation and reduced personal accomplishment from chronic workplace stress.",
    "**Leadership** \u2014 the process of influencing and motivating people towards the achievement of a common goal.",
    "**Team** \u2014 a small group with complementary skills, a common goal and mutual accountability.",
    "**Time management** \u2014 planning, prioritising and controlling one's use of time to achieve goals with least waste and stress.",
    "**Human dignity** \u2014 the inherent, unconditional worth of every person, requiring that he never be treated merely as a means.",
    "**Euthanasia** \u2014 intentional termination of the life of a person with an incurable, painful disease to relieve suffering.",
    "**Brain death** \u2014 irreversible cessation of all functions of the entire brain including the brainstem."
]),

('h2', "A.6  Final Checklist Before You Enter the Examination Hall"),
('key', [
    "Can I write the **four principles** with a definition, a limitation and a laboratory example for each? *(Ch. 3)*",
    "Can I draw the **4 D's of negligence** and name three defences? *(Ch. 7)*",
    "Can I list **eight exceptions to confidentiality** and the four golden rules of disclosure? *(Ch. 6)*",
    "Can I reproduce the **barriers-to-communication table** and the **7 C's**? *(Ch. 4)*",
    "Can I draw the **Eisenhower matrix** with laboratory examples in all four quadrants? *(Ch. 9)*",
    "Can I draw **Selye's GAS** in three stages and name the burnout triad? *(Ch. 10)*",
    "Can I draw **Tuckman's five stages** and name Lewin's three leadership styles with one use for each? *(Ch. 11)*",
    "Can I state the **three-tier consumer machinery** with its monetary limits and the 2-year limitation? *(Ch. 8)*",
    "Can I recall **six hazards of a laboratory** and the needle-stick protocol with the PEP time window? *(Ch. 8)*",
    "Can I quote at least **six Indian statutes with the correct year** and **four case names**? *(Chs. 2, 6, 7, 8)*",
    "Have I written all the **mnemonics from A.1** on my rough sheet in the first two minutes?",
    "Do I remember the **universal answer template**: Definition \u2192 Classification \u2192 Explanation \u2192 Table/Diagram \u2192 Example \u2192 Conclusion?"
]),
('tip', [
    "**In the hall, in this order:**",
    "- **Minute 0\u20132:** write every mnemonic you remember on the rough sheet. You will not lose them later under pressure.",
    "- **Minute 2\u20135:** read all the questions; mark the ones you know best; decide your order (**attempt your strongest answer first** \u2014 it sets the examiner's impression of your whole script).",
    "- **Allot roughly 1.5 minutes per mark.** A 10-mark answer gets about 15 minutes and about 2 pages; a 5-mark answer about 7 minutes and about 1 page; a 2-mark answer 2\u20133 lines.",
    "- **Every long answer:** start with the definition in a box or underlined, use numbered headings, include **at least one table or diagram**, add **one example** and finish with a **2-line conclusion**.",
    "- **Underline every technical term and every case name and statute.** Examiners scan for keywords.",
    "- **Never leave anything blank.** Write the definition and whatever headings you remember \u2014 partial marks are real marks.",
    "- **Keep 10 minutes** at the end to complete question numbers, tidy headings and check that nothing is left unattempted.",
    "**You have the full content. Now write it in points, draw a table, and the marks will follow. All the best!**"
]),

('recap', [
    "Definition \u2192 Classification \u2192 Explanation \u2192 **Table/Diagram** \u2192 Example \u2192 Conclusion. Every single answer.",
    "Underline keywords, case names and statute years. Number every point.",
    "1.5 minutes per mark. Strongest answer first. Nothing left blank.",
    "Mnemonics on the rough sheet in the first two minutes.",
]),

]
