# -*- coding: utf-8 -*-
"""Chapter 1 - Introduction to Professionalism and Ethics
   Chapter 2 - Value and Dignity of Human Life"""

BLOCKS = [

# ===========================================================================
('ch', (1, "Introduction to Professionalism and Ethics",
        "Meaning \u2022 Characteristics \u2022 Attributes \u2022 Code of conduct \u2022 Ethics vs Law vs Etiquette \u2022 Professionalism in the laboratory")),
# ===========================================================================

('h2', "1.1  Introduction"),
('p', "Health care is not merely a technical occupation; it is a **moral enterprise**. A Medical Laboratory Technologist handles a patient's blood, tissue, body fluids and \u2014 most importantly \u2014 a patient's **secrets, fears and future**. A single wrongly reported HIV test, a mislabelled blood group, or one careless remark in a corridor can destroy a life. Technical competence alone therefore cannot make a good laboratory professional; competence must be married to **character**. The study of that character, of the rules that govern it, and of the duties that flow from it, is the subject of *professionalism and ethics*."),
('p', "The word **ethics** comes from the Greek *ethos*, meaning character, custom or habitual conduct. The word **moral** comes from the Latin *mores*, meaning customs or manners. **Profession** comes from the Latin *professio* \u2014 'to declare publicly', because historically a professional publicly *professed* an oath to serve society before being allowed to practise. This origin is important: from the very beginning, a profession was defined not by what it earned but by what it **promised**."),

('def', ("Ethics",
         "Ethics is the branch of philosophy (moral philosophy) that deals with the systematic study of what is **right and wrong, good and bad, just and unjust** in human conduct, and provides the standards or principles by which human actions and character are judged.",
         ["**Medical Ethics:** the branch of applied ethics that studies moral values, principles and rules governing the conduct of persons engaged in the practice of medicine and allied health sciences, and their relationship with patients, colleagues, society and the State.",
          "**Morals:** an individual's personal beliefs about right and wrong, usually derived from family, religion, culture and upbringing.",
          "**Values:** deeply held convictions about what is desirable and important, which act as the foundation of both morals and ethics."])),

('def', ("Profession",
         "A profession is an occupation that requires **prolonged specialised education and training**, is based on a **body of scientific knowledge**, involves **intellectual skill and judgement**, functions with a considerable degree of **autonomy**, is regulated by its own **code of ethics** and licensing body, and is practised primarily as a **service to society** rather than purely for personal gain.")),

('def', ("Professionalism",
         "Professionalism is the **habitual and judicious demonstration** of the knowledge, technical skills, communication, ethical values, attitudes, behaviour and accountability that are expected of a member of a profession in the service of the individual patient and the community.",
         ["In one exam-friendly line: *Professionalism = Competence + Character + Commitment + Accountability.*"])),

('quote', ("Ethics is knowing the difference between what you have a right to do and what is right to do.", "Potter Stewart")),

('h2', "1.2  Why Study Ethics? (Need and Importance)"),
('n', [
    "**To protect the patient.** The patient is in a vulnerable, dependent position and cannot judge technical quality; ethics is the patient's only real protection.",
    "**To guide decision-making in grey areas.** Textbooks tell you *how* to do a test; ethics tells you *whether* you should, and what to do with the result.",
    "**To maintain public trust in the health system.** Health care runs on trust; a single scandal (fake reports, organ racket, sex determination) damages the credibility of an entire hospital or profession.",
    "**To provide a uniform standard of conduct.** A code of ethics ensures that a patient receives the same minimum standard of respect and care from every technologist, everywhere.",
    "**To protect the professional.** A technologist who follows ethical protocol (consent, documentation, confidentiality, reporting through proper channels) is legally far safer.",
    "**To resolve conflicts of interest and conflicts of duty.** For example, loyalty to an employer versus honesty about a faulty analyser.",
    "**To act as a self-regulating mechanism.** A profession that disciplines itself avoids harsher regulation being imposed from outside.",
    "**To humanise technology.** As laboratories become automated, the risk of treating a patient as a barcode increases; ethics keeps the person visible behind the sample.",
    "**Legal necessity.** Many ethical duties (consent, confidentiality, non-abandonment, record keeping) are now enforceable in law; ignorance is not a defence.",
    "**Professional satisfaction.** Ethical practice reduces moral distress and burnout and increases pride in one's work."
]),

('h2', "1.3  Characteristics (Hallmarks) of a Profession"),
('p', "Sociologists list the following features which distinguish a **profession** from an ordinary **job** or **occupation**. Medical Laboratory Technology satisfies all of them, which is why an MLT is a professional and not merely a technician."),
('n', [
    "**A systematic body of theoretical knowledge** \u2014 haematology, microbiology, biochemistry, pathology, immunology.",
    "**Prolonged, specialised, formal education** in a recognised institution, ending in a degree or diploma.",
    "**Professional authority and expertise** \u2014 the professional, not the client, decides the technically correct course of action.",
    "**Autonomy of practice** \u2014 the freedom and responsibility to exercise independent judgement (for example, rejecting a haemolysed sample).",
    "**A code of ethics** which is binding on all members.",
    "**Registration / licensure** by a statutory council, and the power of that council to remove a name from the register.",
    "**A professional association or organisation** that sets standards and speaks for the members.",
    "**Service orientation / altruism** \u2014 the interest of the patient is placed above self-interest.",
    "**Accountability and responsibility** \u2014 answerable to the patient, employer, council, courts and society.",
    "**Continuing professional development** \u2014 an obligation to remain up to date lifelong.",
    "**Public recognition and social status**, with a corresponding expectation of higher standards of behaviour.",
    "**Distinct professional culture** \u2014 shared language, norms, symbols and dress."
]),

('mne', ("\u201CKASSA-CARD\u201D \u2014 characteristics of a profession",
         ["**K** \u2013 Knowledge base (theoretical)",
          "**A** \u2013 Autonomy",
          "**S** \u2013 Specialised prolonged education",
          "**S** \u2013 Service / altruism",
          "**A** \u2013 Accountability",
          "**C** \u2013 Code of ethics",
          "**A** \u2013 Association (professional body)",
          "**R** \u2013 Registration / licensure",
          "**D** \u2013 Development (continuing education)"])),

('tbl', (["Basis", "Job / Occupation", "Profession"],
         [["Entry requirement", "Little or no formal specialised training", "Prolonged, formal, recognised education"],
          ["Knowledge base", "Practical / manual skill", "Systematic scientific theory"],
          ["Regulation", "By the employer only", "By a statutory council + code of ethics"],
          ["Autonomy", "Follows instructions", "Exercises independent judgement"],
          ["Primary motive", "Earning a livelihood", "Service to society (livelihood follows)"],
          ["Accountability", "Mainly to the employer", "To patient, council, court and society"],
          ["Relationship with client", "Commercial / contractual", "**Fiduciary** \u2014 based on trust"],
          ["Continuing education", "Optional", "Obligatory"],
          ["Consequence of misconduct", "Loss of job", "Loss of job **plus** removal from register, criminal / civil liability"]],
         [2.6, 6.8, 7.8],
         "Job vs Profession \u2014 a favourite 5-mark comparison question")),

('h2', "1.4  Attributes / Elements of Professionalism"),
('p', "The following are the qualities that a patient, a clinician and an employer expect from a laboratory professional. In the examination this is usually asked as *'Enumerate the attributes of a health-care professional'* or *'Write short notes on professionalism'*."),

('h3', "A. Core Ethical Attributes"),
('b', [
    "**Altruism** \u2014 placing the patient's welfare above one's own convenience, profit or comfort; staying back to complete an urgent crossmatch is altruism.",
    "**Integrity and Honesty** \u2014 absolute truthfulness in reporting results; never fabricating, altering or 'adjusting' a value, never reporting a test that was not performed (a practice called **'dry labbing'**, which is a serious professional crime).",
    "**Accountability and Responsibility** \u2014 owning one's errors, reporting them, correcting them and accepting the consequences.",
    "**Respect for others** \u2014 for the patient, the attendant, the sweeper, the junior and the senior alike.",
    "**Compassion and Empathy** \u2014 the ability to sense and acknowledge the patient's fear, especially during painful procedures such as venepuncture or bone-marrow aspiration.",
    "**Confidentiality** \u2014 treating every result as a secret held in trust.",
    "**Justice and Fairness** \u2014 no discrimination on the basis of caste, religion, gender, sexual orientation, HIV status, ability to pay or 'VIP' status; no queue-jumping for favours.",
    "**Duty and Dutifulness** \u2014 completing the work assigned, and not abandoning the patient or the bench.",
]),

('h3', "B. Attributes of Competence"),
('b', [
    "**Technical competence** \u2014 knowing and correctly performing the procedure; knowing one's own limits.",
    "**Commitment to excellence and quality** \u2014 running controls, calibrating, participating in **internal quality control (IQC)** and **external quality assurance (EQAS)**.",
    "**Lifelong learning** \u2014 attending CMEs, reading journals, updating on new methods.",
    "**Scientific attitude** \u2014 evidence-based, objective, willing to be corrected.",
    "**Reliability and Punctuality** \u2014 turnaround time (TAT) is an ethical issue, not only a managerial one; a delayed troponin report can cost a life.",
]),

('h3', "C. Attributes of Conduct and Appearance"),
('b', [
    "**Professional appearance** \u2014 clean laboratory coat, identity badge worn visibly, tied hair, trimmed nails, appropriate footwear, no coat worn outside the laboratory or in the canteen.",
    "**Professional demeanour** \u2014 calm, courteous, controlled voice; no shouting, arguing, gossiping or use of mobile phones at the bench.",
    "**Effective communication** \u2014 clear, polite, jargon-free with patients; precise and structured with clinicians.",
    "**Teamwork and Collegiality** \u2014 respectful cooperation with nurses, clinicians, phlebotomists and housekeeping staff.",
    "**Respect for institutional rules**, biosafety norms and the chain of command.",
    "**Self-regulation** \u2014 willingness to report unsafe practice by oneself or by others (a duty sometimes called **whistle-blowing** when done through proper channels)."
]),

('mne', ("\u201CA-CHIEVER\u201D \u2014 attributes of professionalism",
         ["**A** \u2013 Altruism",
          "**C** \u2013 Competence & Compassion",
          "**H** \u2013 Honesty / Integrity",
          "**I** \u2013 Integrity of records & Confidentiality",
          "**E** \u2013 Excellence (quality, lifelong learning)",
          "**V** \u2013 Values & respect for persons",
          "**E** \u2013 Empathy",
          "**R** \u2013 Responsibility & Accountability"])),

('h2', "1.5  Unprofessional Conduct / Professional Misconduct"),
('p', "Professional misconduct (also called **infamous conduct in a professional respect**) means any act or omission by a registered practitioner which is regarded as disgraceful or dishonourable by his professional colleagues of good repute and competence. In India, misconduct by doctors is governed by Chapter 7 of the **Indian Medical Council (Professional Conduct, Etiquette and Ethics) Regulations, 2002**; the same principles are applied by analogy to paramedical staff through institutional and Clinical Establishments Act rules."),
('n', [
    "**Falsification of reports** \u2014 fabricating, altering, back-dating or issuing a report without performing the test.",
    "**Breach of confidentiality** \u2014 disclosing results to unauthorised persons, discussing patients on social media.",
    "**Working beyond one's competence** or performing procedures for which one is not authorised.",
    "**Negligence** \u2014 wrong labelling, sample mix-up, failing to inform a critical value.",
    "**Reporting for duty under the influence** of alcohol or drugs.",
    "**Accepting or giving 'cuts', commissions, kickbacks** for referring samples to a particular laboratory \u2014 explicitly prohibited (a form of **fee-splitting** or **dichotomy**).",
    "**Advertising and canvassing** for patients in an undignified manner; making exaggerated claims.",
    "**Sex determination of a foetus** and disclosure of foetal sex \u2014 a criminal offence under the **PC-PNDT Act, 1994**.",
    "**Issuing false certificates** (fitness, sickness, medico-legal).",
    "**Refusal to treat / discrimination**, especially against HIV-positive patients.",
    "**Sexual misconduct or harassment** of patients or colleagues.",
    "**Violation of biosafety and waste-disposal rules** endangering the public.",
    "**Rudeness, abusive behaviour or physical violence** at the workplace.",
    "**Covering up** \u2014 shielding an unqualified person or concealing another's serious error."
]),
('warn', ["**Malpractice vs Misconduct vs Negligence** \u2014 examiners love this distinction:",
          "- **Negligence** = failure to exercise reasonable care \u2192 leads to a *civil suit for damages*.",
          "- **Malpractice** = negligence or improper conduct *by a professional* in the course of professional duty \u2192 civil and sometimes criminal liability.",
          "- **Professional misconduct** = conduct disgraceful to the profession (may not harm any individual patient, e.g. advertising) \u2192 leads to *disciplinary action by the council*, i.e. warning, suspension or **erasure of name from the register**."]),

('h2', "1.6  Code of Ethics and Code of Conduct"),
('def', ("Code of Ethics",
         "A formal, written statement of the **values, principles and moral standards** adopted by a professional group, which guides the members in exercising their professional responsibilities and informs the public of the standard it may expect.")),
('tbl', (["Point", "Code of **Ethics**", "Code of **Conduct**"],
         [["Nature", "Value-based, aspirational, 'why'", "Rule-based, specific, 'what and how'"],
          ["Content", "Broad principles \u2014 e.g. 'respect patient autonomy'", "Concrete rules \u2014 e.g. 'obtain written consent before HIV testing'"],
          ["Flexibility", "Requires interpretation and judgement", "Little scope for interpretation"],
          ["Scope", "Governs attitude and character", "Governs observable behaviour"],
          ["Enforcement", "Moral / professional censure", "Disciplinary or legal action for breach"]],
         [2.0, 7.4, 7.8],
         "Code of Ethics vs Code of Conduct")),

('h3', "Historical Codes and Declarations \u2014 an examiner favourite"),
('tbl', (["Year", "Code / Declaration", "Core contribution"],
         [["c. 400 BC", "**Hippocratic Oath** (Greece)", "First codified oath \u2014 *primum non nocere* (first, do no harm), confidentiality, no abortion or euthanasia, no exploitation of patients."],
          ["c. 200 BC \u2013 200 AD", "**Charaka Samhita** \u2014 *Oath of the Physician* (India)", "Indian equivalent: purity of conduct, celibacy of speech, dedication to the patient, secrecy about the patient's household."],
          ["1803", "**Percival's Code of Medical Ethics**", "First modern written code of medical ethics; basis of later codes."],
          ["1847", "**AMA Code of Ethics** (USA)", "First national professional code."],
          ["1947", "**Nuremberg Code**", "Framed after the Nazi doctors' trial; established that **voluntary informed consent is absolutely essential** in human experimentation."],
          ["1948", "**Declaration of Geneva** (WMA)", "Modern restatement of the Hippocratic Oath for physicians."],
          ["1949", "**International Code of Medical Ethics** (WMA)", "Duties of doctors in general, to the sick, and to each other."],
          ["1964", "**Declaration of Helsinki** (WMA)", "Ethical principles for **medical research** on human subjects; requires ethics committee approval. Periodically revised."],
          ["1978", "**Declaration of Alma-Ata** (WHO)", "'Health for All' \u2014 health as a fundamental human right; primary health care."],
          ["1979", "**Belmont Report** (USA)", "Three principles of research ethics: **respect for persons, beneficence, justice**."],
          ["1981", "**Declaration of Lisbon** (WMA)", "Rights of the patient."],
          ["2002", "**IMC (Professional Conduct, Etiquette and Ethics) Regulations**, India", "The operative code for registered medical practitioners in India; duties, misconduct, punishment."],
          ["2005", "**UNESCO Universal Declaration on Bioethics and Human Rights**", "Global consensus on bioethical principles including human dignity."]],
         [1.5, 4.3, 11.4],
         "Landmark ethical codes and declarations")),

('h3', "Essential Duties Contained in a Typical Code for Laboratory Professionals"),
('b', [
    "Place the **welfare and safety of the patient** first.",
    "Perform tests only within the **scope of one's training and authorisation**.",
    "Maintain **accuracy, reliability and integrity** of every result; never suppress an inconvenient finding.",
    "Preserve **confidentiality** of all patient information.",
    "Obtain **consent** where required and respect the patient's dignity and privacy during specimen collection.",
    "Maintain **complete, legible, contemporaneous records**.",
    "Practise **biosafety** \u2014 protect self, colleagues, patients and the environment.",
    "Maintain and improve **professional competence**; accept supervision and constructive criticism.",
    "Avoid **conflicts of interest**, commissions and kickbacks.",
    "**Report** unsafe practice, errors and adverse events through proper channels.",
    "Behave with **courtesy and dignity** towards colleagues and other health professionals.",
    "Uphold the **honour and reputation of the profession** in public and on social media."
]),

('h2', "1.7  Ethics vs Law vs Etiquette vs Morals \u2014 The Four-Way Distinction"),
('tbl', (["Basis", "Ethics", "Law", "Etiquette", "Morals"],
         [["Meaning", "Standards of right conduct of a group/profession", "Rules enacted and enforced by the State", "Customary courtesies of a profession", "Personal beliefs of right and wrong"],
          ["Source", "Profession, philosophy, society", "Legislature, courts, statutes", "Professional tradition, convention", "Family, religion, culture, conscience"],
          ["Binding on", "Members of the profession", "All citizens", "Members of the profession (socially)", "The individual only"],
          ["Enforcement", "Professional body / conscience", "Police, courts, punishment", "Peer disapproval", "Guilt, conscience"],
          ["Penalty for breach", "Warning, suspension, erasure of name", "Fine, compensation, imprisonment", "Loss of respect among colleagues", "Inner guilt only"],
          ["Nature", "May exceed the law's demands", "Minimum enforceable standard", "Concerns manners, not morality", "Subjective, varies person to person"],
          ["Example", "Telling a patient the truth about an error", "Not disclosing foetal sex (PC-PNDT Act)", "Not criticising a colleague in front of a patient", "A technologist's personal objection to abortion"]],
         [1.8, 4.2, 4.0, 3.9, 3.9],
         "Ethics vs Law vs Etiquette vs Morals")),
('warn', ["**All that is legal is not ethical, and all that is ethical is not legal.**",
          "- *Legal but unethical:* charging a very high but legally permitted fee from a poor patient; refusing to see a patient after duty hours when no one else is available.",
          "- *Ethical but illegal (in a given jurisdiction):* active euthanasia to relieve unbearable suffering; disclosing a patient's confidential information to prevent a crime, where no statutory exception exists.",
          "- Therefore ethics generally sets a **higher standard** than the law. The law is the floor; ethics is the ceiling."]),
('def', ("Medical Etiquette",
         "The conventional code of **courtesy and good manners** to be observed by members of the medical profession in their dealings with one another and with patients \u2014 for example, standing up to greet a patient, not criticising a colleague in front of a patient, replying promptly to a referral, not poaching another's patients.")),

('h2', "1.8  Branches / Divisions of Ethics"),
('tbl', (["Branch", "What it studies", "Example question it asks"],
         [["**Meta-ethics**", "The nature and meaning of moral terms themselves", "What does the word 'good' actually mean?"],
          ["**Normative / Prescriptive ethics**", "Which standards or norms of conduct are correct", "Is it right to lie to a dying patient?"],
          ["**Descriptive ethics**", "Empirically describes what people actually believe and do", "What do laboratory staff in this hospital actually do about critical values?"],
          ["**Applied ethics**", "Application of ethical theory to specific fields", "Medical, nursing, laboratory, business, legal, environmental ethics"],
          ["**Bioethics**", "Ethical issues arising from biology, medicine and biotechnology", "Cloning, genetic testing, stem cells, surrogacy, organ transplant"],
          ["**Clinical ethics**", "Ethical problems at the bedside of an individual patient", "Should this patient be put on a ventilator?"],
          ["**Research ethics**", "Protection of human and animal research subjects", "Is this trial's consent form adequate?"],
          ["**Public-health ethics**", "Ethics of population-level interventions", "Can we quarantine a village compulsorily?"],
          ["**Professional ethics**", "Duties arising from membership of a profession", "May I accept a gift from a diagnostic-kit company?"]],
         [3.3, 6.6, 7.3],
         "Divisions of ethics")),

('h3', "Major Ethical Theories (the reasoning behind decisions)"),
('tbl', (["Theory", "Central idea", "Judges an act by", "Weakness"],
         [["**Deontology** (Kant) \u2014 duty-based", "Some acts are right or wrong in themselves; act only on rules you could will to be universal; treat persons as ends, never merely as means", "The **act / duty** itself", "Rigid; cannot resolve conflicts between two duties"],
          ["**Utilitarianism / Consequentialism** (Bentham, J.S. Mill)", "The right act is the one producing the greatest good (happiness) for the greatest number", "The **consequences**", "May justify sacrificing an individual for the majority"],
          ["**Virtue ethics** (Aristotle)", "Focus on the *character* of the agent \u2014 be a person of compassion, honesty, courage, prudence", "The **agent's character**", "Vague guidance in a specific dilemma"],
          ["**Principlism** (Beauchamp & Childress)", "Balance the four principles: autonomy, beneficence, non-maleficence, justice", "Balance of **principles**", "No fixed hierarchy when principles clash"],
          ["**Ethics of care** (Gilligan, Noddings)", "Morality grows out of relationships, responsiveness and caring", "The **relationship**", "Risk of partiality / favouritism"],
          ["**Casuistry**", "Reason from previous similar cases (like case law)", "**Precedent cases**", "Needs a good stock of agreed cases"],
          ["**Natural law / Theological ethics**", "Right conduct follows the natural or divinely ordained order", "Conformity to **nature / scripture**", "Pluralistic societies do not share one scripture"]],
         [3.4, 6.0, 2.6, 5.2],
         "Ethical theories \u2014 write any three in a 5-mark answer")),

('h2', "1.9  Professionalism in the Medical Laboratory \u2014 Practical Application"),
('p', "In the examination you will score extra marks if you connect abstract professionalism to your **own** field. The following table converts each attribute into a concrete laboratory behaviour."),
('tbl', (["Situation in the laboratory", "Unprofessional response", "Professional response"],
         [["Sample is haemolysed", "Run it anyway to avoid an argument", "Reject it, document the reason, inform the ward, request a fresh sample"],
          ["You realise you reported the wrong blood group", "Keep quiet and hope nobody notices", "Immediately inform the supervisor and the treating team, issue a corrected report, document, participate in root-cause analysis"],
          ["A neighbour asks for 'her sister's' HIV result", "Tell her, since she is family", "Politely refuse; explain confidentiality; direct her to the authorised channel"],
          ["A friend asks you to 'make' a normal report for a fitness certificate", "Oblige, since it is 'harmless'", "Refuse firmly \u2014 this is falsification and professional misconduct"],
          ["Critical potassium of 7.2 mmol/L at 2 a.m.", "Leave it in the printout for the morning", "Verify, repeat if protocol requires, phone the ward at once, read-back, log the call"],
          ["A representative offers a gift for preferring his kit", "Accept quietly", "Decline; declare the offer to the supervisor; base kit selection on validation data"],
          ["A collection is painful and the child is crying", "Scold the child to keep still", "Explain, reassure, involve the parent, use the smallest gauge, complete quickly and gently"],
          ["The analyser control is out of range", "Release results, controls are 'usually fine'", "Stop reporting, troubleshoot, recalibrate, re-run, document corrective action"],
          ["A colleague is not wearing gloves for phlebotomy", "Ignore it; not your business", "Remind politely; if repeated, report to the supervisor \u2014 safety is a shared duty"],
          ["A patient is HIV positive", "Warn other staff loudly to 'be careful'", "Maintain confidentiality and apply **universal (standard) precautions to every** sample"]],
         [4.6, 5.6, 7.0],
         "Professionalism at the bench \u2014 use one or two rows as examples in any answer")),

('h2', "1.10  Barriers to Professionalism"),
('b', [
    "**Work overload and staff shortage** \u2014 encourages shortcuts.",
    "**Commercialisation of health care** \u2014 targets, incentives and 'cut practice' pull against patient interest.",
    "**Poor role models** \u2014 juniors copy what seniors actually do, not what they say (the **hidden curriculum**).",
    "**Lack of ethics training** in technical courses.",
    "**Burnout, fatigue and stress** \u2014 erode empathy first.",
    "**Hierarchical culture** in which juniors cannot question unsafe practice.",
    "**Inadequate infrastructure** \u2014 no gloves, no space for privacy during sample collection.",
    "**Social media carelessness** \u2014 casual posts breaching confidentiality.",
    "**Weak accountability systems** \u2014 no consequence for repeated errors."
]),

('h2', "1.11  Professional Socialisation and How Professionalism Is Developed"),
('n', [
    "**Formal teaching** of ethics, law and communication in the curriculum.",
    "**Role modelling** by senior technologists and pathologists \u2014 the single most powerful influence.",
    "**Reflective practice** \u2014 keeping a log and discussing 'what I would do differently'.",
    "**Case discussion and ethics committee exposure.**",
    "**Feedback and appraisal**, including 360-degree feedback from nurses and patients.",
    "**Institutional culture and policy** \u2014 SOPs, incident-reporting systems that are blame-free.",
    "**White-coat / oath-taking ceremonies** which create a sense of identity and public promise.",
    "**Continuing professional development and re-certification.**"
]),

('key', [
    "**Ethics = *ethos* (character); Morals = *mores* (custom); Profession = *professio* (to declare publicly).**",
    "A profession has: specialised knowledge, prolonged education, autonomy, code of ethics, registration, association, altruism and accountability.",
    "**Professionalism = Competence + Character + Commitment + Accountability.**",
    "The relationship between a professional and a patient is a **fiduciary** relationship \u2014 based on trust, with unequal knowledge.",
    "The law is the **minimum** standard; ethics is a **higher** standard. Legal \u2260 ethical.",
    "**'Dry labbing'** (reporting a test not performed) and **falsification of reports** are the gravest forms of laboratory misconduct.",
    "The main Indian code is the **Indian Medical Council (Professional Conduct, Etiquette and Ethics) Regulations, 2002**.",
    "The punishment for professional misconduct ranges from **warning \u2192 suspension \u2192 erasure of name from the register (professional death)**."
]),

('tip', [
    "**Expected questions from this chapter:**",
    "- *Long (10 marks):* 'Define ethics and professionalism. Discuss the characteristics of a profession and the attributes of a health-care professional.'",
    "- *Long (10 marks):* 'What is professional misconduct? Enumerate the acts amounting to professional misconduct and the punishments provided.'",
    "- *Short (5 marks):* Code of ethics; Differences between ethics and law; Medical etiquette; Ethical theories; Barriers to professionalism; Hippocratic Oath.",
    "- *Very short (2 marks):* Define ethics / morals / values / profession / bioethics; expand PC-PNDT; year of Nuremberg Code; what is 'dry labbing'."
]),

('qa', ("QUESTION BANK \u2014 CHAPTER 1", [
    ("Define ethics, morals and values. How do they differ?",
     ["**Ethics** \u2014 the systematic study of right and wrong conduct, and the standards adopted by a group or profession. **Morals** \u2014 an individual's personal beliefs of right and wrong drawn from family, religion and culture. **Values** \u2014 deeply held convictions about what is desirable, which form the basis of both.",
      "Difference: ethics is **collective, reasoned and enforceable by a professional body**; morals are **personal and enforced only by conscience**; values are the **underlying beliefs** from which both arise."]),
    ("What is professionalism? Give its four components.",
     ["Professionalism is the habitual and judicious demonstration of knowledge, skills, values, attitudes and accountability expected of a member of a profession in the service of patients and society.",
      "Four components: **(i) Competence** (knowledge and technical skill), **(ii) Character** (honesty, altruism, respect), **(iii) Commitment** (to excellence, lifelong learning, the patient), **(iv) Accountability** (to patient, employer, council, society)."]),
    ("Enumerate any eight characteristics of a profession.",
     ["Specialised body of knowledge; prolonged formal education; professional authority; autonomy of practice; a code of ethics; statutory registration/licensure; a professional association; service/altruistic orientation; accountability; continuing education. *(Mnemonic: KASSA-CARD.)*"]),
    ("Differentiate between a job and a profession.",
     ["Draw the comparison table \u2014 basis: entry requirement, knowledge base, regulation, autonomy, motive, accountability, nature of client relationship, continuing education, consequence of misconduct."]),
    ("What is professional misconduct? Enumerate ten examples relevant to a laboratory professional.",
     ["Definition: infamous conduct in a professional respect \u2014 an act or omission regarded as disgraceful or dishonourable by professional colleagues of good repute and competence.",
      "Examples: falsification of reports/dry labbing; breach of confidentiality; practising beyond competence; negligence causing harm; duty under influence of alcohol; accepting commissions/cut practice; undignified advertising; foetal sex determination (PC-PNDT); false certificates; refusal to treat/discrimination; sexual misconduct; biosafety violations; covering up another's error."]),
    ("'All that is legal is not ethical.' Discuss with examples.",
     ["Law prescribes the **minimum enforceable** standard; ethics prescribes a **higher, aspirational** standard. Legal-but-unethical: exploiting a poor patient with legally permissible high charges; technically valid consent obtained without real explanation. Ethical-but-illegal: active euthanasia to end unbearable suffering; breaking confidentiality to prevent serious harm where no statutory exception exists. Conclusion: a professional must satisfy both, and where they conflict must choose the ethically higher course while accepting legal accountability."]),
    ("Write short notes on the Hippocratic Oath.",
     ["Attributed to Hippocrates of Kos (c. 460\u2013370 BC), the 'Father of Medicine'; the earliest codified oath of the medical profession. Core promises: benefit the sick and **do no harm or injustice** (*primum non nocere*); refuse to give a deadly drug or cause abortion; keep life and art pure; abstain from sexual relations with patients; **keep secret whatever is seen or heard** in the course of treatment. Modern successor: the WMA **Declaration of Geneva, 1948**."]),
    ("List the landmark declarations in medical ethics with their years.",
     ["Hippocratic Oath (c. 400 BC); Charaka Samhita oath (ancient India); Percival's Code (1803); AMA Code (1847); **Nuremberg Code (1947)**; Declaration of Geneva (1948); International Code of Medical Ethics (1949); **Declaration of Helsinki (1964)**; Declaration of Alma-Ata (1978); Belmont Report (1979); Declaration of Lisbon (1981); IMC Regulations, India (2002); UNESCO Declaration on Bioethics (2005)."]),
    ("What is medical etiquette? How does it differ from medical ethics?",
     ["Medical etiquette is the conventional code of courtesy and good manners among members of the profession and towards patients. Ethics concerns **right and wrong (morality)**; etiquette concerns **manners and convention**. Breach of ethics may attract legal or disciplinary action; breach of etiquette usually attracts only professional disapproval. Example of etiquette: not criticising a colleague before a patient, replying to a referral promptly."]),
    ("Explain briefly any four ethical theories.",
     ["**Deontology** \u2014 duty-based, an act is right in itself (Kant). **Utilitarianism** \u2014 greatest good of the greatest number, judged by consequences (Bentham, Mill). **Virtue ethics** \u2014 focuses on the character of the agent (Aristotle). **Principlism** \u2014 balancing autonomy, beneficence, non-maleficence and justice (Beauchamp & Childress). May also mention ethics of care and casuistry."]),
])),

('recap', [
    "Ethics = study of right and wrong; **Medical ethics** applies it to health care.",
    "Profession \u2192 knowledge + education + autonomy + code + registration + service + accountability.",
    "Professionalism \u2192 **C\u2074: Competence, Character, Commitment, Accountability.**",
    "Attributes: altruism, honesty, accountability, respect, empathy, confidentiality, justice, competence, excellence, appearance, teamwork.",
    "Misconduct \u2192 falsification, breach of confidentiality, negligence, cut practice, false certificates, PC-PNDT violation.",
    "Punishment ladder: **warning \u2192 suspension \u2192 erasure of name from the register.**",
    "Ethics > Law > Etiquette in terms of moral demand; law is the floor, ethics the ceiling."
]),


# ===========================================================================
('ch', (2, "Value and Dignity of Human Life",
        "Sanctity of life \u2022 Human dignity \u2022 Respect for persons \u2022 Quality of life \u2022 Beginning and end-of-life issues")),
# ===========================================================================

('h2', "2.1  Introduction"),
('p', "Every rule of medical ethics ultimately rests on one foundational belief: that **human life has value, and every human being has dignity that must be respected**. If a patient were merely a biological specimen, there would be no reason to seek consent, keep secrets, tell the truth, or treat the poor and the rich alike. It is precisely because the person on the other side of the collection counter possesses **intrinsic worth** that the technologist owes him or her respect. This chapter therefore forms the philosophical base of the whole subject."),
('p', "For a laboratory professional this is not abstract. The sample in your hand is not 'the 2 o'clock CBC' \u2014 it is a part of a frightened human being waiting outside. **Dignity is protected or destroyed in very small acts**: whether you draw the curtain, whether you use the patient's name, whether you discuss the case in the lift, whether you keep an elderly patient standing in a queue."),

('h2', "2.2  Value of Human Life"),
('def', ("Value of human life (Sanctity of life)",
         "The principle that human life possesses **intrinsic, inherent and immeasurable worth** \u2014 a worth that belongs to a person simply because he or she is human, and which does not depend on age, sex, caste, religion, wealth, social usefulness, intelligence, health status or physical or mental ability.",
         ["Because the value is *intrinsic*, human life is regarded as **priceless and non-negotiable** \u2014 it cannot be traded, purchased or ranked."])),

('h3', "Characteristics of the Value of Human Life"),
('n', [
    "**Intrinsic** \u2014 belongs to the person in himself, not conferred by others.",
    "**Inherent** \u2014 present from the very fact of being human; not earned.",
    "**Inalienable** \u2014 cannot be taken away, surrendered or forfeited, even by a criminal or a comatose patient.",
    "**Equal** \u2014 the life of a beggar and of a minister have identical value; this is the basis of the principle of **justice**.",
    "**Universal** \u2014 applies across all cultures, nations and religions.",
    "**Immeasurable / priceless** \u2014 cannot be expressed in money; the law awards 'compensation', never a 'price'.",
    "**Non-instrumental** \u2014 a human being must never be treated *merely* as a means to another's end (Kant's formula of humanity)."
]),

('h3', "Foundations of the Value of Human Life"),
('tbl', (["Basis", "Explanation"],
         [["**Philosophical**", "Kant: rational beings are 'ends in themselves' and possess *dignity*, not *price*; they must never be used merely as means."],
          ["**Religious / theological**", "Most faiths hold life to be a divine gift or trust \u2014 *sanctity of life*. Hindu thought speaks of the *atman* in every being; Christianity of man made in God's image; Islam of life as an *amanah* (trust); Jainism and Buddhism of *ahimsa*, non-injury to all life."],
          ["**Legal / Constitutional (India)**", "**Article 21** \u2014 'No person shall be deprived of his life or personal liberty except according to procedure established by law.' The Supreme Court has read into Article 21 the **right to live with human dignity**, the right to health and emergency medical care (*Parmanand Katara v. Union of India*, 1989), and the right to die with dignity (*Common Cause*, 2018)."],
          ["**Human-rights based**", "Universal Declaration of Human Rights, 1948, **Article 1**: 'All human beings are born free and equal in dignity and rights.' UNESCO Declaration on Bioethics, 2005, makes human dignity the first principle."],
          ["**Professional**", "Every health-care code obliges the professional to respect the life and dignity of the patient; the Declaration of Geneva states 'I will maintain the utmost respect for human life.'"]],
         [3.0, 14.2],
         "Why human life is regarded as valuable")),

('h2', "2.3  Human Dignity"),
('def', ("Human Dignity",
         "Human dignity is the **inherent, unconditional worth and status of a human being**, by virtue of which every person deserves to be treated with respect, never to be humiliated, degraded, exploited or used merely as an object or a means to another's ends.")),
('p', "Dignity is best understood in two complementary senses:"),
('b', [
    "**Intrinsic (inviolable) dignity** \u2014 possessed equally by all humans, cannot be lost or reduced; it is the basis of human rights. An unconscious patient in the ICU has exactly the same intrinsic dignity as the consultant treating him.",
    "**Attributed / experienced dignity** \u2014 the *feeling* of being valued and respected, which very much **can** be enhanced or destroyed by how others behave. Exposing a patient's body needlessly, shouting a diagnosis across the room, or referring to 'the diabetic in bed 4' assaults this experienced dignity."
]),

('h3', "Elements / Components of Human Dignity in Health Care"),
('n', [
    "**Respect** \u2014 addressing the patient by name, greeting, listening, not talking over them.",
    "**Privacy** \u2014 physical (curtains, screens, separate cubicle for collection), informational (records, results), and territorial (not intruding without permission).",
    "**Autonomy and choice** \u2014 the right to be informed and to decide, including the right to refuse.",
    "**Confidentiality** \u2014 secrecy of information given in trust.",
    "**Communication** \u2014 truthful, understandable, in the patient's own language.",
    "**Bodily integrity** \u2014 no procedure without consent; minimum necessary exposure; minimum necessary pain.",
    "**Identity and individuality** \u2014 the patient is a person with a name, a family and a story, not a bed number or barcode.",
    "**Equality and non-discrimination** \u2014 same standard for all, irrespective of status or diagnosis.",
    "**Cultural and religious sensitivity** \u2014 respect for modesty norms, dietary and ritual practices, same-gender attendants where required.",
    "**Comfort and freedom from unnecessary suffering** \u2014 including pain relief and gentle technique.",
    "**Dignity in dependence** \u2014 preserving the self-respect of those who need help with basic functions.",
    "**Dignity in death** \u2014 respectful handling of the dying and of the dead body, and of the bereaved family."
]),
('mne', ("\u201CDIGNITY\u201D \u2014 what a patient's dignity requires",
         ["**D** \u2013 Decision-making respected (autonomy, consent)",
          "**I** \u2013 Identity preserved (name, not 'the case')",
          "**G** \u2013 Gentleness (minimum pain, minimum exposure)",
          "**N** \u2013 No discrimination",
          "**I** \u2013 Information given honestly and understandably",
          "**T** \u2013 Trust and confidentiality maintained",
          "**Y** \u2013 Your privacy protected (physical and informational)"])),

('h2', "2.4  Respect for Persons"),
('p', "'Respect for persons' is the operational form of human dignity and is one of the three principles of the **Belmont Report (1979)**. It has two distinct requirements:"),
('n', [
    "**Respect the autonomy of those who are capable of it** \u2014 inform them, seek consent, allow refusal, keep their secrets.",
    "**Protect those with diminished autonomy** \u2014 children, the unconscious, the mentally ill, the intellectually disabled, prisoners, the very poor, and the illiterate must be given *additional* safeguards (surrogate consent, assent, ethics committee scrutiny), because they cannot protect themselves."
]),
('warn', ["A common exam trap: respect for persons is **not** the same as 'doing whatever the patient says'. It means respecting the person's *considered* choice **and** protecting them when they cannot choose. Abandoning a vulnerable patient to a 'free choice' he cannot understand is a failure of respect, not an example of it."]),

('h2', "2.5  Sanctity of Life vs Quality of Life"),
('tbl', (["Point", "Sanctity of Life doctrine", "Quality of Life approach"],
         [["Core claim", "Human life is intrinsically valuable and must always be preserved", "The **value to the person living it** matters; life burdened by unbearable suffering may not be worth prolonging"],
          ["Basis", "Religious and deontological", "Utilitarian / consequentialist"],
          ["View of treatment withdrawal", "Generally opposed; every life must be sustained", "Permits withholding/withdrawing futile or burdensome treatment"],
          ["View of euthanasia", "Opposes actively ending life", "May permit passive (and in some countries active) euthanasia"],
          ["Risk if taken to an extreme", "**Vitalism** \u2014 meaningless prolongation of dying by machines", "Devaluing the lives of the disabled, elderly or 'unproductive'"],
          ["Modern reconciliation", "Life is valuable, but there is no obligation to provide **futile** treatment; the aim shifts from cure to **comfort and dignity** (palliative care)", ""]],
         [2.2, 7.5, 7.5],
         "Sanctity of life vs Quality of life \u2014 the central tension in end-of-life ethics")),
('def', ("Quality of Life (QOL)",
         "The individual's own perception of his or her position in life, in the context of the culture and value systems in which he lives, and in relation to his goals, expectations, standards and concerns (WHO). It has **physical, psychological, social, spiritual and environmental** domains.")),
('def', ("Medical futility",
         "A treatment is *futile* when it cannot achieve its physiological objective, or when it merely prolongs the process of dying without producing any benefit that the patient can appreciate. **There is no ethical obligation to provide futile treatment**, and providing it may itself violate non-maleficence and dignity.")),

('h2', "2.6  Ethical Issues at the Beginning of Life"),
('tbl', (["Issue", "Key ethical points", "Indian legal position"],
         [["**Abortion / MTP**", "Conflict between the woman's autonomy and bodily integrity and the moral status of the foetus; the *personhood* debate", "**Medical Termination of Pregnancy Act, 1971**, amended **2021** \u2014 permitted up to 20 weeks on one doctor's opinion, up to 24 weeks for specified categories on two doctors' opinion, and beyond 24 weeks for substantial foetal abnormality on the opinion of a Medical Board"],
          ["**Prenatal sex determination**", "Violates the equal value of female life; leads to female foeticide and a skewed sex ratio", "**PC-PNDT Act, 1994** \u2014 determination *and disclosure* of foetal sex is a **criminal offence**; laboratories must display the mandatory notice"],
          ["**Prenatal / genetic testing**", "Right to know vs risk of eugenic selection and discrimination; needs genetic counselling and consent", "Regulated under PC-PNDT and ICMR guidelines"],
          ["**Assisted reproduction (IVF, ART), surrogacy**", "Commodification of gametes, embryos and women's bodies; status of surplus embryos; rights of the child", "**ART (Regulation) Act, 2021** and **Surrogacy (Regulation) Act, 2021** \u2014 commercial surrogacy prohibited, only altruistic surrogacy permitted"],
          ["**Stem-cell and embryo research**", "Moral status of the human embryo vs therapeutic promise", "**ICMR National Guidelines for Stem Cell Research**; institutional committee approval required"],
          ["**Severely malformed newborn**", "Sanctity vs quality of life; parental role in decision-making; best-interest standard", "Decisions taken in the child's best interest, with parental involvement; no active killing permitted"]],
         [3.2, 6.7, 7.3],
         "Beginning-of-life issues")),

('h2', "2.7  Ethical Issues at the End of Life"),
('def', ("Euthanasia",
         "Derived from Greek *eu* (good) + *thanatos* (death), literally 'good death'. It means the intentional termination of the life of a person suffering from an incurable and painful disease, at his request or in his interest, in order to relieve suffering. Also called **mercy killing**.")),
('h3', "Classification of Euthanasia"),
('tbl', (["Basis", "Type", "Meaning"],
         [["By **method**", "**Active** (positive)", "A deliberate act *causing* death, e.g. giving a lethal injection \u2014 a **commission**"],
          ["", "**Passive** (negative)", "Withholding or withdrawing life-sustaining treatment and allowing the patient to die of the underlying disease \u2014 an **omission**"],
          ["By **consent**", "**Voluntary**", "At the competent patient's own clear request"],
          ["", "**Non-voluntary**", "Patient is incapable of consenting (coma, infant); decision taken by others in his best interest"],
          ["", "**Involuntary**", "Against the patient's wishes \u2014 this is **murder**, never ethically defensible"],
          ["Related concept", "**Physician-assisted suicide**", "The doctor supplies the means, but the **patient himself** performs the final act"],
          ["Related concept", "**Palliative / terminal sedation**", "Sedation to relieve refractory suffering; death is not the intention (see doctrine of double effect)"]],
         [2.4, 4.0, 10.8],
         "Types of euthanasia")),
('eg', ["**Indian legal landmark \u2014 remember these three:**",
        "- **Aruna Shanbaug v. Union of India (2011)** \u2014 the Supreme Court permitted **passive euthanasia** in exceptional cases with High Court approval. Aruna Shanbaug, a nurse at KEM Hospital, Mumbai, had remained in a persistent vegetative state for 37 years after a brutal assault.",
        "- **Common Cause v. Union of India (2018)** \u2014 the Supreme Court held that the **right to die with dignity is part of the right to life under Article 21**, legalised passive euthanasia and recognised the **'living will' / advance medical directive**. Guidelines were simplified in **2023**.",
        "- **Active euthanasia and assisted suicide remain illegal in India.** Attempt to suicide has, however, been effectively decriminalised for the mentally ill by the **Mental Healthcare Act, 2017 (s. 115)**."]),
('def', ("Advance Directive / Living Will",
         "A written document by which a competent adult states in advance what medical treatment he does or does not wish to receive if he later becomes incompetent to decide, and may nominate a **surrogate decision-maker** (health-care proxy).")),
('def', ("Doctrine of Double Effect",
         "An act with two effects \u2014 one good and intended, one harmful and merely foreseen \u2014 may be permissible if: (i) the act itself is not wrong, (ii) the **intention** is to achieve the good effect, (iii) the bad effect is not the means to the good, and (iv) there is proportionate reason. *Example:* giving morphine in a dose needed to relieve intractable pain, foreseeing that it may shorten life \u2014 this is **not** euthanasia, because death is not intended.")),
('def', ("Brain Death",
         "Irreversible cessation of all functions of the **entire brain, including the brainstem**. In India, brain-stem death is recognised by the **Transplantation of Human Organs Act (THOA), 1994 (amended 2011)** and must be certified by a **board of four registered medical practitioners** \u2014 including the medical administrator in charge, an authorised specialist, a neurologist/neurosurgeon and the treating doctor \u2014 with **two examinations six hours apart**. Neither the transplant surgeon nor a member of the transplant team may be on this board.")),
('h3', "Other End-of-Life Concepts"),
('b', [
    "**Palliative care** \u2014 active total care of patients whose disease is not responsive to curative treatment, aiming at the best possible quality of life through control of pain and other symptoms, and psychological, social and spiritual support (WHO). It **affirms life and regards dying as a normal process**, and neither hastens nor postpones death.",
    "**Hospice care** \u2014 palliative care delivered in a dedicated setting for patients in the last phase of life.",
    "**DNR / DNAR (Do Not Attempt Resuscitation)** order \u2014 a documented decision not to attempt CPR when it would be futile; it does **not** mean withdrawal of other care.",
    "**Withholding vs withdrawing treatment** \u2014 ethically regarded as equivalent, though psychologically withdrawal feels harder.",
    "**Organ donation** \u2014 must be voluntary, altruistic and free of commerce; **commercial dealing in organs is a criminal offence** under THOA. 'Required request' and 'presumed consent' models are debated.",
    "**Care of the dead body** \u2014 respectful handling, correct identification, prevention of exposure, prompt release to relatives, and dignified disposal of tissue in the laboratory.",
    "**Truth-telling to the dying patient** \u2014 the patient has a right to know; disclosure should be gradual, compassionate and paced to what the patient wants to hear."
]),

('h2', "2.8  Threats to the Value and Dignity of Human Life"),
('b', [
    "**Commercialisation** \u2014 unnecessary tests, target-driven diagnostics, organ trade, cut practice: the patient becomes a source of revenue.",
    "**Dehumanisation and depersonalisation** \u2014 the patient reduced to a bed number, a barcode or a diagnosis.",
    "**Discrimination and stigma** \u2014 against HIV-positive, tuberculosis, leprosy, mentally ill, transgender, disabled and poor patients.",
    "**Female foeticide and infanticide** \u2014 the denial of equal value to female life.",
    "**Neglect of the elderly and of the terminally ill.**",
    "**Research without consent**, exploitation of poor and illiterate subjects as 'guinea pigs'.",
    "**Torture, custodial violence and violence against health workers.**",
    "**Breach of privacy and confidentiality**, including careless social-media posts.",
    "**Vitalism / over-medicalisation of dying** \u2014 prolonging death instead of allowing a peaceful end.",
    "**Poverty and inequitable access** \u2014 the most fundamental practical assault on dignity in health care."
]),

('h2', "2.9  How a Laboratory Professional Upholds the Dignity of a Patient"),
('n', [
    "Greet the patient, **introduce yourself**, and use his or her **name**.",
    "**Explain the procedure** before doing it \u2014 what will be done, why, how long, and what it will feel like.",
    "**Obtain consent**, and honour a refusal without displaying annoyance.",
    "**Ensure privacy** \u2014 curtain or screen for collection, especially for female patients and for any procedure requiring exposure; a separate, private counter for sensitive tests.",
    "**Minimise exposure and pain** \u2014 expose only the required part; use correct technique; do not make repeated blind attempts, call for help.",
    "**Never discuss** the patient, the diagnosis or the result in corridors, lifts, canteens or on social media.",
    "**Handle the sample with respect** \u2014 it is part of a person; label correctly, transport safely, dispose lawfully.",
    "**Do not react visibly** to a stigmatised diagnosis; apply **universal precautions to every** sample so no patient feels marked out.",
    "**Give equal courtesy and equal turn** to every patient irrespective of status \u2014 no VIP queue-jumping.",
    "**Be honest about delays and errors**, and apologise sincerely when the patient has been inconvenienced or harmed.",
    "**Be sensitive to culture, religion, language, gender and disability** \u2014 arrange a same-gender attendant or an interpreter where needed.",
    "**Show respect to the dead** and to the bereaved when handling post-mortem specimens or releasing reports after death."
]),

('key', [
    "Human life has **intrinsic, inherent, inalienable, equal and immeasurable** value.",
    "**Dignity** has two faces: *intrinsic* (cannot be lost) and *experienced/attributed* (very easily destroyed by our behaviour).",
    "**Respect for persons = respect the autonomous + protect the vulnerable.** (Belmont Report, 1979.)",
    "**Article 21** of the Indian Constitution \u2192 right to life **with dignity**, including emergency care and death with dignity.",
    "**UDHR 1948, Article 1** \u2192 'All human beings are born free and equal in dignity and rights.'",
    "**Sanctity of life vs quality of life** is the core tension in end-of-life ethics; the resolution is *no obligation to give futile treatment* + palliative care.",
    "In India: **passive euthanasia is legal** (Aruna Shanbaug 2011; Common Cause 2018, which also recognised the **living will**); **active euthanasia is not**.",
    "**Brain death** in India = brain-stem death certified by a **board of four doctors**, two examinations **six hours** apart (THOA 1994/2011).",
    "**PC-PNDT Act 1994** \u2014 foetal sex determination and disclosure is a criminal offence; **MTP Act 1971 (amd. 2021)** \u2014 20/24 weeks limits."
]),

('tip', [
    "**Expected questions from this chapter:**",
    "- *Long (10 marks):* 'Discuss the value and dignity of human life and the responsibility of a health-care professional in upholding it.'",
    "- *Long (10 marks):* 'What is euthanasia? Classify it and discuss the ethical and legal position in India.'",
    "- *Short (5 marks):* Human dignity; Sanctity vs quality of life; Respect for persons; Living will / advance directive; Brain death; Palliative care; Doctrine of double effect; PC-PNDT Act.",
    "- *Very short (2 marks):* Define euthanasia; two types of euthanasia; Article 21; expand THOA, MTP, PC-PNDT; year of the Aruna Shanbaug judgement.",
    "**Scoring tip:** in any 10-mark answer here, always include (i) the definition, (ii) the characteristics of the value of life, (iii) the components of dignity, (iv) at least three practical laboratory examples, and (v) one Indian legal reference. That combination is very hard to mark down."
]),

('qa', ("QUESTION BANK \u2014 CHAPTER 2", [
    ("Define human dignity. Enumerate its components in health care.",
     ["Human dignity is the inherent, unconditional worth of a human being by virtue of which he must be treated with respect and never humiliated, degraded, exploited or used merely as a means.",
      "Components: respect, privacy, autonomy and choice, confidentiality, honest communication, bodily integrity, identity/individuality, equality and non-discrimination, cultural sensitivity, freedom from unnecessary suffering, dignity in dependence, dignity in death. *(Mnemonic: DIGNITY.)*"]),
    ("What are the characteristics of the value of human life?",
     ["Intrinsic, inherent, inalienable, equal, universal, immeasurable/priceless, and non-instrumental (never a mere means). Add the foundations \u2014 philosophical (Kant), religious (sanctity of life), constitutional (Article 21), human rights (UDHR Art. 1) and professional (Declaration of Geneva)."]),
    ("Differentiate between sanctity of life and quality of life.",
     ["Draw the comparison table \u2014 core claim, philosophical basis, view on withdrawal of treatment, view on euthanasia, extreme risk (vitalism vs devaluing the disabled). Conclude with the modern reconciliation: no obligation to provide **futile** treatment; the goal shifts to comfort, palliation and dignity."]),
    ("Classify euthanasia and state the legal position in India.",
     ["By method: **active** (act causing death) and **passive** (withholding/withdrawing treatment). By consent: **voluntary, non-voluntary, involuntary** (the last is murder). Related: physician-assisted suicide; terminal sedation.",
      "India: **passive euthanasia is permitted** \u2014 *Aruna Shanbaug* (2011) and *Common Cause* (2018), the latter recognising the right to die with dignity under Article 21 and the validity of a **living will**; procedure simplified in 2023. **Active euthanasia and assisted suicide remain criminal offences.**"]),
    ("What is a living will? Why is it important?",
     ["A living will (advance medical directive) is a document by which a competent adult states in advance the treatment he would or would not want if he later becomes incompetent, and may appoint a surrogate. Importance: extends autonomy into the period of incapacity, prevents futile treatment, relieves the family and the treating team of an impossible burden of guesswork, and protects dignity in dying. Recognised in India by *Common Cause* (2018)."]),
    ("Write short notes on brain death.",
     ["Irreversible cessation of all functions of the entire brain including the brainstem. Legal basis in India: **THOA 1994 (amended 2011)**. Certified by a **board of four** \u2014 medical administrator in charge, authorised specialist, neurologist/neurosurgeon, treating doctor \u2014 by **two examinations six hours apart**; the transplant team must not be involved. Significance: permits lawful withdrawal of ventilation and cadaveric organ donation; distinguishes brain death from persistent vegetative state and coma."]),
    ("Explain the doctrine of double effect with an example.",
     ["An act producing both a good intended effect and a foreseen bad effect is permissible if the act is not intrinsically wrong, the intention is the good effect, the bad effect is not the means to the good, and there is proportionate reason. Example: morphine given in the dose necessary to relieve intractable cancer pain, foreseeing possible respiratory depression. This is **not** euthanasia because death is foreseen, not intended."]),
    ("How can a laboratory technologist protect the dignity of patients? Give ten practical measures.",
     ["Introduce yourself and use the patient's name; explain the procedure; take consent and respect refusal; ensure physical privacy with a curtain/screen; minimise exposure and pain; never discuss cases in public spaces or on social media; label and handle specimens correctly and respectfully; do not react to a stigmatised diagnosis and use universal precautions for all; give equal courtesy and equal turn to all; be honest about delays and errors; respect culture, language, gender and disability; treat the dead and the bereaved with respect."]),
    ("What are the main threats to human dignity in modern health care?",
     ["Commercialisation and unnecessary testing; dehumanisation and depersonalisation; discrimination and stigma; female foeticide; neglect of the elderly and dying; research without valid consent; violence and custodial torture; breaches of privacy including social media; over-medicalisation of dying (vitalism); and inequitable access due to poverty."]),
    ("What is palliative care? State its principles.",
     ["WHO: active total care of patients whose disease is not responsive to curative treatment, aiming at the best quality of life through control of pain and other symptoms and psychological, social and spiritual support. Principles: affirms life and regards dying as a normal process; **neither hastens nor postpones death**; relieves pain and distressing symptoms; integrates psychological and spiritual care; supports the family, including bereavement care; uses a team approach; applicable early in the course of illness alongside disease-modifying treatment."]),
])),

('recap', [
    "Human life = **intrinsic, inalienable, equal, priceless**; dignity = never a mere means (Kant).",
    "Dignity in practice = **privacy + name + explanation + consent + confidentiality + gentleness + no discrimination**.",
    "Respect for persons = respect autonomy **and** protect the vulnerable (Belmont, 1979).",
    "**Article 21** \u2192 life with dignity, emergency care, death with dignity.",
    "Euthanasia: active vs passive; voluntary / non-voluntary / involuntary. **India: passive yes, active no.**",
    "Cases: **Aruna Shanbaug 2011** (passive euthanasia), **Common Cause 2018** (living will, death with dignity).",
    "Brain death \u2192 **4-doctor board, 2 tests, 6 hours apart (THOA)**.",
    "Futile treatment \u2192 no ethical obligation to provide; switch to **palliative care**."
]),

]
