# -*- coding: utf-8 -*-
"""Chapter 3 - Principles of Medical Ethics"""

BLOCKS = [

('ch', (3, "Principles of Medical Ethics",
        "Autonomy \u2022 Beneficence \u2022 Non-maleficence \u2022 Justice \u2022 Veracity \u2022 Fidelity \u2022 Confidentiality \u2022 Conflicts")),

('h2', "3.1  Introduction"),
('p', "In 1979 two American philosophers, **Tom Beauchamp** and **James Childress**, published *Principles of Biomedical Ethics*, in which they proposed that almost every ethical problem in health care can be analysed using four basic principles. This framework, known as **Principlism** or the **'Four Principles' approach** (sometimes called the **Georgetown Mantra**), has become the standard language of medical ethics worldwide and is the single most important topic in this syllabus."),
('p', "The four principles are not a mechanical formula. They are **prima facie** duties \u2014 meaning each is binding *unless* it conflicts with an equal or stronger duty in a particular case. The skill of ethics lies in **balancing and specifying** them when they pull in opposite directions."),

('def', ("Principles of Medical Ethics",
         "The fundamental, universally accepted moral norms \u2014 **autonomy, beneficence, non-maleficence and justice** \u2014 that guide health-care professionals in making decisions and resolving conflicts in patient care, research and public health.")),

('mne', ("\u201CA-B-N-J\u201D or the Georgetown Mantra",
         ["**A** \u2013 **Autonomy** \u2192 *Respect the patient's choice* (\u201CYour body, your decision\u201D)",
          "**B** \u2013 **Beneficence** \u2192 *Do good* (\u201CHelp the patient\u201D)",
          "**N** \u2013 **Non-maleficence** \u2192 *Do no harm* (\u201C**Primum non nocere**\u201D)",
          "**J** \u2013 **Justice** \u2192 *Be fair to all* (\u201CTreat equals equally\u201D)",
          "Extended set to write for a 10-mark answer: add **V**eracity, **F**idelity, **C**onfidentiality, **D**ignity \u2192 *\u201CABNJ + VFCD\u201D*"])),

('tbl', (["#", "Principle", "Latin / core phrase", "One-line meaning", "Classic laboratory example"],
         [["1", "**Autonomy**", "*Voluntas aegroti suprema lex*", "Respect the competent patient's right to decide for himself", "Taking informed consent before HIV testing; honouring a refusal of venepuncture"],
          ["2", "**Beneficence**", "*Salus aegroti suprema lex*", "Act positively for the patient's benefit and welfare", "Phoning a critical potassium result to the ward immediately"],
          ["3", "**Non-maleficence**", "*Primum non nocere*", "Above all, do not inflict harm", "Rejecting a haemolysed sample rather than issuing a falsely high potassium"],
          ["4", "**Justice**", "*Suum cuique tribuere*", "Distribute benefits, risks and costs fairly; treat like cases alike", "Same turnaround time and courtesy for a free-ward patient as for a private patient"]],
         [0.7, 2.6, 3.2, 5.0, 5.7],
         "The four principles at a glance \u2014 memorise this table")),

('h2', "3.2  Principle I \u2014 Autonomy (Respect for Autonomy)"),
('def', ("Autonomy",
         "From Greek *autos* (self) + *nomos* (rule/law) \u2014 literally 'self-rule'. Autonomy is the capacity of a competent individual to make **informed, voluntary, deliberate and uncoerced decisions** about his or her own body, treatment and personal information. The principle of respect for autonomy requires the professional to **acknowledge and facilitate** that right.")),
('h3', "Conditions Necessary for a Valid Autonomous Decision"),
('n', [
    "**Competence / Capacity** \u2014 the patient must be able to *understand* the information, *retain* it, *weigh* it and *communicate* a choice. Capacity is decision-specific and can fluctuate.",
    "**Disclosure of adequate information** \u2014 diagnosis, nature and purpose of the proposed procedure, risks and benefits, alternatives, and consequences of refusal.",
    "**Understanding** \u2014 in the patient's own language, free of jargon; verified by asking the patient to repeat back.",
    "**Voluntariness** \u2014 free from coercion, undue influence, manipulation, threats or inducement.",
    "**Authorisation** \u2014 an actual, explicit decision by the patient (signature, thumb impression, or clearly documented verbal consent)."
]),
('mne', ("\u201CC-D-U-V-A\u201D \u2014 elements of a valid autonomous consent",
         ["**C** \u2013 Competence", "**D** \u2013 Disclosure", "**U** \u2013 Understanding",
          "**V** \u2013 Voluntariness", "**A** \u2013 Authorisation"])),
('h3', "What Respect for Autonomy Requires in Practice"),
('b', [
    "**Informed consent** before every procedure, test and research participation.",
    "**Truth-telling** \u2014 the patient cannot decide autonomously if he is deceived.",
    "**The right to refuse** \u2014 a competent adult may refuse even life-saving treatment; refusal must be documented (a 'refusal of treatment' / LAMA form) after re-explaining the consequences.",
    "**The right to a second opinion** and the right to choose or change one's practitioner or laboratory.",
    "**Confidentiality and privacy** \u2014 control over one's own information is an expression of autonomy.",
    "**The right to information** \u2014 access to one's own records and results.",
    "**Respect for advance directives** and for previously expressed wishes.",
    "**Shared decision-making** rather than the professional deciding alone.",
    "**Cultural respect** \u2014 including the choice of some patients to delegate decisions to the family (a legitimate exercise of autonomy, not a denial of it)."
]),
('h3', "Limitations / Exceptions to Autonomy"),
('n', [
    "**Incompetence** \u2014 minors, the unconscious, severe intellectual disability, delirium, severe mental illness \u2192 decision by a **surrogate** (parent/guardian/next of kin) using the **best-interest standard** or **substituted judgement**.",
    "**Emergency** \u2014 immediate treatment to save life when consent cannot be obtained; the law implies consent (**doctrine of implied/presumed consent** or *emergency privilege*).",
    "**Risk to public health** \u2014 compulsory notification of notifiable diseases, isolation and quarantine (e.g. under the **Epidemic Diseases Act, 1897** and the Disaster Management Act, 2005).",
    "**Risk of serious harm to an identifiable third party** \u2014 e.g. an HIV-positive person refusing to inform a spouse (*Mr X v. Hospital Z*, 1998).",
    "**Court orders and statutory duties** \u2014 e.g. testing under court direction.",
    "**Therapeutic privilege** \u2014 a very narrow and now heavily criticised exception where disclosure itself would gravely harm the patient; must never be used as an excuse for routine concealment.",
    "**Waiver** \u2014 the patient may validly choose *not* to be told; this too must be respected and documented.",
    "**Patient cannot demand harmful or futile treatment** \u2014 autonomy is a right to refuse, not a right to compel any treatment one wishes."
]),
('warn', ["**Autonomy \u2260 abandonment.** Respecting a refusal does not mean walking away. You must re-explain, offer alternatives, document, and continue all other care. Similarly, **paternalism** \u2014 deciding *for* the patient 'for his own good' \u2014 is the opposite error. Distinguish:",
          "- **Hard/strong paternalism:** overriding a *competent* patient's informed choice \u2014 ethically unacceptable.",
          "- **Soft/weak paternalism:** acting protectively for a patient whose decision-making is *impaired* \u2014 ethically acceptable and often obligatory."]),

('h2', "3.3  Informed Consent \u2014 The Operational Form of Autonomy"),
('def', ("Informed Consent",
         "The voluntary agreement given by a competent person, or by an authorised surrogate, to a proposed diagnostic or therapeutic procedure or research participation, **after** he has been given and has understood adequate information about its nature, purpose, benefits, risks, alternatives and consequences of refusal, and while remaining free to withdraw at any time.")),
('h3', "Types of Consent"),
('tbl', (["Type", "Meaning / When used", "Example"],
         [["**Implied consent**", "Inferred from the patient's conduct; sufficient for routine, low-risk, non-invasive acts", "The patient rolls up his sleeve and extends the arm for venepuncture"],
          ["**Expressed \u2013 oral**", "Stated verbally; should be documented and preferably witnessed", "Consent for a routine blood sugar test"],
          ["**Expressed \u2013 written**", "Signed document; mandatory for invasive, risky or sensitive procedures, and for research", "Bone-marrow aspiration, HIV testing, blood transfusion, biopsy, participation in a trial"],
          ["**Informed consent**", "Written consent preceded by full disclosure and verified understanding", "Any procedure with material risk"],
          ["**Blanket / open consent**", "A general form signed at admission covering routine care \u2014 legally weak, **not** a substitute for procedure-specific consent", "The 'consent for treatment' form at the registration counter"],
          ["**Proxy / surrogate consent**", "Given by a legally authorised person for an incompetent patient", "Parent for a child; guardian for a person with severe intellectual disability"],
          ["**Assent**", "The willing agreement of a child or partly competent person, in addition to parental consent", "A 12-year-old agreeing to a blood draw"],
          ["**Implied by law / presumed**", "In a life-threatening emergency where the patient cannot consent and no surrogate is available", "Unconscious road-accident victim needing urgent crossmatch and transfusion"],
          ["**Loco parentis**", "Consent by a person temporarily standing in a parent's place", "A school teacher for a child injured on a school trip"]],
         [3.2, 8.0, 6.0],
         "Types of consent \u2014 a very frequently asked 5-mark question")),
('h3', "Essential Contents of a Consent Form / Elements of Disclosure"),
('n', [
    "The patient's **identity** and the date and time.",
    "The **diagnosis** or provisional diagnosis and the patient's condition.",
    "The **nature and purpose** of the proposed procedure, explained in simple language.",
    "The **expected benefits**.",
    "The **material risks, complications and side-effects**, including the rare but serious ones.",
    "The **alternatives available**, including their risks and benefits.",
    "The **consequences of refusing** the procedure.",
    "A statement that the patient may **withdraw consent at any time** without prejudice to further care.",
    "An **opportunity to ask questions**, and confirmation that they were answered.",
    "For research: purpose, duration, procedures, compensation, confidentiality safeguards, contact details of the investigator and ethics committee, and that participation is voluntary.",
    "**Signature / thumb impression** of the patient (or surrogate, with relationship stated), of the person obtaining consent, and of a **witness**, especially if the patient is illiterate.",
    "Documented in the **language the patient understands**; if an interpreter was used, record his name."
]),
('h3', "Legal Points on Consent in India"),
('b', [
    "**Age of consent for medical examination and treatment is 18 years** (Indian Majority Act, 1875 read with Indian Contract Act, 1872). Below 18, consent of a parent or guardian is required.",
    "For **general physical examination**, a child of **12 years** and above can give valid consent (Indian Penal Code, s. 89 / BNS equivalent); for anything invasive, guardian consent is needed.",
    "**Consent must be free** \u2014 obtained without misrepresentation, fraud, coercion or undue influence, otherwise it is void.",
    "Consent obtained for one procedure does **not** authorise a different procedure (except an unforeseen emergency arising during the procedure).",
    "**Two-doctor / special consents** are required in specific situations (e.g. MTP beyond 20 weeks, sterilisation, organ donation).",
    "**HIV testing** requires **specific informed consent and pre- and post-test counselling** \u2014 the **HIV/AIDS (Prevention and Control) Act, 2017** prohibits testing without consent and prohibits disclosure without consent.",
    "**Absence of consent** can convert a lawful act into **assault/battery**; inadequate disclosure gives rise to an action in **negligence**.",
    "*Samira Kohli v. Dr Prabha Manchanda* **(2008)** \u2014 the Supreme Court held that consent must be **real and valid**, for the *specific* procedure, and that a doctor must disclose what a *prudent patient* in the circumstances would want to know; consent for a diagnostic procedure does not authorise radical surgery."
]),
('eg', ["**Laboratory reality check \u2014 consent situations you will meet:**",
        "- *Routine phlebotomy* \u2192 implied consent is enough, but you must still **explain** what you are doing.",
        "- *HIV / hepatitis / genetic testing* \u2192 **written, specific, counselled consent**; never add such a test to a panel silently.",
        "- *Using left-over samples for research or method validation* \u2192 requires **consent and ethics committee approval**, or valid anonymisation as per ICMR guidelines.",
        "- *Photographing a slide, culture plate or patient for teaching* \u2192 consent needed; remove all identifiers.",
        "- *A patient refuses a repeat sample* \u2192 explain the risk of an unreliable result, document the refusal, inform the clinician \u2014 do **not** report the unreliable sample as though it were valid."]),

('h2', "3.4  Principle II \u2014 Beneficence"),
('def', ("Beneficence",
         "From Latin *bene* (good) + *facere* (to do) \u2014 'to do good'. Beneficence is the **positive obligation** to act for the benefit and welfare of the patient: to prevent harm, to remove harm, and to promote good, weighing the benefits against the risks and costs.")),
('h3', "Forms of Beneficence"),
('b', [
    "**Positive beneficence** \u2014 the duty to provide actual benefit (treat the disease, relieve pain, report the result accurately and quickly).",
    "**Utility / proportionality** \u2014 the duty to weigh benefits against burdens, risks and costs so that the *net* balance favours the patient (this is the **risk\u2013benefit analysis**)."
]),
('h3', "Practical Duties Flowing from Beneficence"),
('n', [
    "**Provide competent care** and keep one's knowledge and skills up to date.",
    "**Prevent harm** \u2014 anticipate and eliminate hazards (correct labelling, pre-analytical checks, biosafety).",
    "**Remove existing harm** \u2014 correct an erroneous report at once; recall a wrong report actively.",
    "**Promote the patient's welfare** even beyond the strict job description \u2014 explaining fasting instructions, guiding a confused patient to the right counter.",
    "**Act promptly in emergencies** \u2014 STAT samples, critical values, blood for a bleeding patient.",
    "**Advocate for the patient** \u2014 pointing out to a clinician that a test ordered is inappropriate or that a sample must be repeated.",
    "**Ensure quality** \u2014 IQC, EQAS, calibration, method validation, accreditation (NABL): quality assurance is an *ethical* duty, not merely technical.",
    "**Provide relief of suffering** \u2014 gentle technique, minimum number of pricks, warmth and reassurance."
]),
('warn', ["**Beneficence vs Non-maleficence \u2014 do not mix them up.**",
          "- Non-maleficence is a **negative duty** (an *omission*): *do not* harm. It is generally the **stronger** duty and applies to everyone, always.",
          "- Beneficence is a **positive duty** (an *action*): *do* good. It is limited by practicality, resources and the professional relationship.",
          "- Illustration: I have a duty not to harm every person on earth; I do not have a duty to actively benefit every person on earth. But towards **my patient** I have both."]),
('warn', ["**Beneficence vs Paternalism.** When beneficence is pursued *at the cost of* the patient's informed choice, it degenerates into **paternalism**. Modern ethics resolves this in favour of autonomy for competent patients: the professional's view of the patient's good does not override the patient's own considered decision."]),

('h2', "3.5  Principle III \u2014 Non-maleficence"),
('def', ("Non-maleficence",
         "The obligation **not to inflict harm intentionally**, and not to expose the patient to unnecessary or disproportionate risk of harm \u2014 expressed in the maxim ***primum non nocere***, 'first, do no harm'. Harm includes death, disability, pain, distress, disease, deprivation of liberty, financial loss and loss of reputation.")),
('h3', "What Counts as 'Harm' in Laboratory Practice?"),
('tbl', (["Category of harm", "Examples in the laboratory"],
         [["**Physical harm**", "Repeated painful punctures; nerve or arterial injury; haematoma; excessive blood volume drawn from a neonate; needle-stick injury to staff; infection from a contaminated device"],
          ["**Harm from a wrong result**", "Wrong blood group \u2192 fatal haemolytic transfusion reaction; false-negative culture \u2192 untreated sepsis; false-positive HIV \u2192 devastating psychological and social consequences; wrong value \u2192 wrong drug dose"],
          ["**Harm from delay**", "Delayed troponin, potassium, CSF or crossmatch report \u2192 preventable death"],
          ["**Psychological harm**", "Careless disclosure of a serious diagnosis; a frightening remark ('this looks like cancer'); rudeness; loss of dignity"],
          ["**Social harm**", "Breach of confidentiality \u2192 stigma, divorce, loss of job, ostracism (HIV, TB, psychiatric illness, pregnancy)"],
          ["**Financial harm**", "Unnecessary or duplicated tests; repeat tests due to laboratory error charged to the patient"],
          ["**Harm to third parties and the environment**", "Improper biomedical waste disposal; failure to report a notifiable disease; unsafe transport of infectious samples"]],
         [3.6, 13.6],
         "Types of harm a laboratory can cause \u2014 excellent material for a long answer")),
('h3', "Duties Flowing from Non-maleficence"),
('b', [
    "**Do not act beyond your competence**; call for help rather than risk the patient.",
    "**Do not perform unnecessary tests or procedures.**",
    "**Do not report a result you do not trust** \u2014 an unreliable result is worse than no result.",
    "**Follow SOPs, universal precautions and biosafety levels**; use PPE; dispose of sharps correctly.",
    "**Avoid pre-analytical errors** \u2014 correct patient identification (two identifiers), correct tube, correct order of draw, correct volume, correct mixing, correct transport and storage.",
    "**Maintain instruments and controls**; do not release results when QC has failed.",
    "**Do not gossip** \u2014 words cause real harm.",
    "**Report adverse events and near-misses** so that systemic harm is prevented.",
    "**Do not work when impaired** by illness, sleep deprivation, alcohol or drugs."
]),
('def', ("Doctrine of Double Effect (applied here)",
         "A harmful effect may be ethically tolerable if it is a foreseen but unintended side-effect of an action whose intended effect is good, the harm is not the means to the good, and there is proportionate reason. *Example:* drawing blood inevitably causes pain (harm) in order to obtain a diagnosis (good) \u2014 justified because the harm is minimal, unavoidable and proportionate.")),

('h2', "3.6  Principle IV \u2014 Justice"),
('def', ("Justice",
         "Justice means **fairness, equity and impartiality** in the treatment of persons: giving each person what is due to him, distributing benefits and burdens fairly, treating like cases alike, and not discriminating on morally irrelevant grounds such as caste, religion, sex, race, language, disability, sexual orientation, social status, ability to pay or the nature of the illness.")),
('h3', "Types of Justice"),
('tbl', (["Type", "Meaning", "Health-care example"],
         [["**Distributive justice**", "Fair allocation of scarce resources, benefits and burdens across a population", "Allocation of ICU beds, ventilators or vaccines during a pandemic; the organ allocation waiting list; deciding how many analysers a district hospital gets"],
          ["**Rights-based justice**", "Respecting people's legitimate rights and entitlements", "Right to emergency care under Article 21; right to information and to one's own records"],
          ["**Legal justice**", "Respecting morally acceptable laws", "Complying with PC-PNDT, THOA, the HIV Act, biomedical waste rules"],
          ["**Procedural justice**", "Fair, transparent, consistent procedures for deciding", "First-come-first-served queue; documented, published criteria for transplant priority"],
          ["**Retributive / corrective justice**", "Fair punishment and fair compensation for wrongs", "Compensation awarded by a consumer forum for a negligent report"],
          ["**Social justice**", "Correcting structural disadvantage", "Free tests for BPL patients; outreach camps in tribal areas; subsidised dialysis"]],
         [3.4, 6.0, 7.8],
         "Types of justice")),
('h3', "Criteria (Theories) for Distributing Scarce Resources"),
('b', [
    "**To each an equal share** \u2014 strict equality or a lottery.",
    "**To each according to need** \u2014 the sickest first (triage); the usual medical default.",
    "**To each according to effort / merit.**",
    "**To each according to contribution to society** \u2014 controversial, risks devaluing the disabled and the elderly.",
    "**To each according to ability to pay** \u2014 the free market; widely regarded as unjust in health care.",
    "**Maximising total benefit** \u2014 utilitarian: save the most lives, or the most life-years (QALYs).",
    "**Priority to the worst off** \u2014 egalitarian / Rawlsian; also 'fair innings' arguments.",
    "In practice a **combination** is used: medical need + likelihood of benefit + urgency + waiting time, applied through a transparent published policy."
]),
('h3', "Justice in the Laboratory \u2014 Concrete Obligations"),
('n', [
    "**Equal quality of testing** for every patient \u2014 no 'better' reagents or faster machine for private patients.",
    "**Equal turnaround time** on clinical priority alone, not on social status; a genuine emergency, not a VIP, jumps the queue.",
    "**No discrimination** against HIV, hepatitis, TB, leprosy, psychiatric, transgender or disabled patients \u2014 including no refusal to collect samples and no extra 'infection charges'.",
    "**Rational test utilisation** \u2014 not wasting scarce reagents on unnecessary tests, since waste in one place is denial elsewhere.",
    "**Transparent, published charges**; no overcharging and no hidden costs; free or subsidised testing honoured without humiliation.",
    "**Fair access** \u2014 collection timings, ramps and assistance for the elderly and disabled, reports in a language the patient can read.",
    "**Fairness to colleagues too** \u2014 equitable duty rosters, night shifts and leave; justice is owed within the team as well.",
    "**Whistle-blowing** where resources are being diverted or patients exploited."
]),

('h2', "3.7  The Supporting (Secondary) Principles"),
('p', "For a 10-mark answer, after the four main principles, add these. They are sometimes called *derivative* or *secondary* principles because each can be traced back to the main four, but examiners expect them to be named separately."),
('tbl', (["Principle", "Meaning", "Application"],
         [["**Veracity** (truthfulness)", "The duty to tell the truth, not to lie or deceive, and not to withhold material information", "Reporting the true value even when it is embarrassing; disclosing an error to the patient; honest turnaround-time information"],
          ["**Fidelity** (faithfulness)", "The duty to keep promises, honour commitments and remain loyal to the patient's interest", "Doing what you told the ward you would do; not abandoning duty; loyalty to the patient over the employer's commercial interest"],
          ["**Confidentiality**", "The duty to keep secret the information disclosed in the professional relationship", "Not revealing results to relatives, employers or insurers without authorisation"],
          ["**Privacy**", "The duty to respect the patient's physical and informational private sphere", "Curtains for collection; secure LIS passwords; no unattended reports on the counter"],
          ["**Autonomy-related: Informed consent**", "See section 3.3", "Written consent for HIV and genetic tests"],
          ["**Dignity**", "Treating the person as a person, never as a mere object", "Using the patient's name; respectful handling of specimens and of the dead"],
          ["**Accountability / Responsibility**", "Being answerable for one's acts and omissions", "Signing the report; incident reporting; root-cause analysis"],
          ["**Non-abandonment**", "The duty not to withdraw care unilaterally once a professional relationship has begun", "Not walking away from a difficult or non-paying patient"],
          ["**Vulnerability & protection of the weak**", "Additional safeguards for those with diminished autonomy", "Extra care with children, the unconscious, prisoners, illiterate patients"],
          ["**Solidarity / Professional cooperation**", "Duty to work with, and not undermine, other health professionals", "Respectful communication with nurses and clinicians"],
          ["**Stewardship**", "Responsible use of shared resources", "Avoiding reagent wastage; energy and biosafety compliance"],
          ["**Sanctity / respect for life**", "See Chapter 2", "Respect for the value of every patient's life"]],
         [3.5, 6.2, 7.5],
         "Supporting principles of medical ethics")),

('h2', "3.8  Conflicts Between Principles and How to Resolve Them"),
('p', "Because the four principles are **prima facie** duties of equal standing, real cases often set them against each other. The examiner's favourite question is exactly this. Learn at least four standard conflicts."),
('tbl', (["Conflict", "Typical situation", "How it is resolved"],
         [["**Autonomy vs Beneficence**", "A competent adult with severe anaemia refuses a blood transfusion on religious grounds (Jehovah's Witness)", "**Autonomy prevails** for a competent, informed adult. Re-explain, offer alternatives (iron, erythropoietin, cell salvage), document refusal, continue all other care. For a **minor**, the court may override the parents in the child's best interest."],
          ["**Autonomy vs Non-maleficence**", "A patient demands a test or treatment that is useless or harmful", "Autonomy is a right to **refuse**, not a right to **demand**. Non-maleficence prevails; explain and decline politely."],
          ["**Confidentiality (autonomy) vs Prevention of harm to others**", "An HIV-positive patient refuses to disclose his status to his spouse", "Counsel first and give time; if he still refuses, disclosure to the identified partner at risk may be justified \u2014 *Mr X v. Hospital Z* (1998). Under the **HIV/AIDS Act 2017**, disclosure requires informed consent or a **court order**, so the correct practical route is intensive counselling and referral to the designated authority."],
          ["**Beneficence vs Justice**", "Spending an entire month's reagent budget on one very ill patient", "Individual benefit must be balanced against the needs of all other patients; apply a transparent, published allocation policy."],
          ["**Veracity vs Non-maleficence**", "A family insists the patient must not be told he has cancer", "The patient's right to know prevails, but disclosure is **paced and compassionate**; ask the patient how much he wishes to know (his **right to waive** must also be respected). Collusion with the family to deceive a patient who wants the truth is unethical."],
          ["**Fidelity to patient vs loyalty to employer**", "The laboratory owner instructs you to release results despite failed QC", "The patient's safety prevails. Refuse, escalate in writing, document; if necessary, blow the whistle through proper channels."],
          ["**Autonomy vs Public health (justice)**", "A patient with infectious multi-drug-resistant TB refuses isolation", "Public interest can override individual autonomy; statutory notification and, if necessary, legally authorised isolation."]],
         [3.4, 6.0, 7.8],
         "Standard conflicts \u2014 learn at least four with their resolutions")),

('h3', "A Step-by-Step Method for Solving an Ethical Dilemma (write this if asked)"),
('flow', [
    "**Step 1 \u2014 Gather the facts:** clinical, personal, family, social, legal and institutional facts. Most 'dilemmas' dissolve once the facts are clear.",
    "**Step 2 \u2014 Identify the ethical problem** and all the stakeholders (patient, family, staff, other patients, society).",
    "**Step 3 \u2014 Identify which principles are in conflict** (autonomy? non-maleficence? justice?).",
    "**Step 4 \u2014 Consider the patient's own wishes, values and capacity** (or the surrogate's / advance directive).",
    "**Step 5 \u2014 List all realistic options** with their consequences \u2014 never assume there are only two.",
    "**Step 6 \u2014 Check the legal and professional rules** and institutional policy.",
    "**Step 7 \u2014 Consult** \u2014 senior colleague, pathologist, clinical ethics committee, professional body.",
    "**Step 8 \u2014 Decide, act, and be able to justify the decision publicly** (the 'newspaper test').",
    "**Step 9 \u2014 Document** the reasoning, the discussion and the decision.",
    "**Step 10 \u2014 Review and reflect** on the outcome; feed it back into policy."
]),
('mne', ("\u201CFOUR-BOX METHOD\u201D (Jonsen, Siegler & Winslade) \u2014 an alternative framework worth quoting",
         ["**Box 1 \u2013 Medical indications:** diagnosis, prognosis, goals of treatment, is it futile?",
          "**Box 2 \u2013 Patient preferences:** is the patient competent? informed? what does he want? advance directive?",
          "**Box 3 \u2013 Quality of life:** what will life be like with and without treatment, judged by the patient's own values?",
          "**Box 4 \u2013 Contextual features:** family, cost, resources, law, religion, institutional policy, conflicts of interest.",
          "Mapping: Box 1 \u2192 beneficence/non-maleficence; Box 2 \u2192 autonomy; Box 3 \u2192 beneficence + autonomy; Box 4 \u2192 justice."])),

('h2', "3.9  Ethics Committees"),
('tbl', (["Committee", "Full form / Purpose", "Composition (typical)"],
         [["**IEC / IRB**", "Institutional Ethics Committee / Institutional Review Board \u2014 reviews and approves **research** on human participants; monitors ongoing studies", "Chairperson (external), Member Secretary, basic medical scientist, clinician(s), legal expert, social scientist/philosopher/theologian, and a **lay person** from the community; minimum 7 members with both genders represented (ICMR/NDCT Rules 2019)"],
          ["**Clinical / Hospital Ethics Committee**", "Advises on **individual patient** dilemmas (end-of-life, consent, conflicts), frames policy, and provides education", "Clinicians, nurses, administrator, social worker, legal adviser, ethicist, community representative"],
          ["**IAEC**", "Institutional Animal Ethics Committee \u2014 approves animal experimentation (CPCSEA)", "Includes a CPCSEA nominee, scientists, veterinarian, socially aware member"],
          ["**Hospital Infection Control / Biosafety Committee**", "Protects patients and staff from infection and biohazard \u2014 an application of non-maleficence", "Microbiologist, infection-control nurse, clinicians, administrator, laboratory in-charge"]],
         [3.0, 7.2, 7.0],
         "Ethics committees")),

('key', [
    "The four principles (**Beauchamp & Childress, 1979** \u2014 *Principlism* / the *Georgetown Mantra*): **Autonomy, Beneficence, Non-maleficence, Justice.**",
    "They are **prima facie** duties \u2014 none is absolute; each must be balanced against the others in the specific case.",
    "**Autonomy** \u2192 informed consent; its five elements are **Competence, Disclosure, Understanding, Voluntariness, Authorisation**.",
    "**Beneficence = do good (positive duty). Non-maleficence = do no harm (negative duty, generally stronger).** *Primum non nocere.*",
    "**Justice** \u2192 distributive, rights-based, legal, procedural, retributive and social; in the lab it means equal quality, equal courtesy and priority by clinical need alone.",
    "Supporting principles: **veracity, fidelity, confidentiality, privacy, dignity, accountability, non-abandonment, stewardship**.",
    "**Age of consent for treatment in India = 18 years**; HIV testing needs **specific written consent with pre- and post-test counselling** (HIV/AIDS Act, 2017).",
    "Key Indian cases: **Samira Kohli v. Dr Prabha Manchanda (2008)** \u2014 real and valid, procedure-specific consent; **Mr X v. Hospital Z (1998)** \u2014 confidentiality may yield to a partner's right to be protected.",
    "For dilemmas, quote the **Four-Box Method** (medical indications, patient preferences, quality of life, contextual features)."
]),

('tip', [
    "**This is the highest-yield chapter in the paper. Expect a full 10-mark question almost every year.**",
    "- *Long:* 'Enumerate and explain the principles of medical ethics with suitable examples.' \u2192 Write all four in detail + the supporting principles + one conflict + a conclusion.",
    "- *Long:* 'Define informed consent. Describe its types, essential elements and legal aspects.'",
    "- *Long:* 'What is autonomy? Discuss its elements, applications and limitations.'",
    "- *Short (5 marks):* Non-maleficence; Beneficence vs non-maleficence; Types of justice; Types of consent; Paternalism; Veracity and fidelity; Ethics committee; Four-box method.",
    "- *Very short (2 marks):* Expand *primum non nocere*; who proposed the four principles; two types of consent; age of consent in India; full form of IEC.",
    "**Presentation tip:** draw the four-principle table first, then expand each principle under sub-headings *(definition \u2192 requirements \u2192 laboratory example \u2192 limitation)*. This structure alone reads like a topper's answer."
]),

('qa', ("QUESTION BANK \u2014 CHAPTER 3", [
    ("Enumerate and explain the four principles of medical ethics with laboratory examples.",
     ["**Autonomy** \u2014 respect the competent patient's self-determination; requires competence, disclosure, understanding, voluntariness and authorisation; *e.g.* written consent with counselling before HIV testing, and honouring a refusal of venepuncture.",
      "**Beneficence** \u2014 the positive duty to act for the patient's benefit; includes competence, quality assurance and prompt action; *e.g.* immediately telephoning a critical potassium of 7.2 mmol/L to the ward.",
      "**Non-maleficence** \u2014 *primum non nocere*, the duty not to inflict harm; *e.g.* rejecting a haemolysed sample instead of issuing a falsely raised potassium, and refusing to release results when QC has failed.",
      "**Justice** \u2014 fairness and non-discrimination; *e.g.* the same quality and turnaround time for a free-ward patient as for a private patient, and no refusal to collect a sample from an HIV-positive patient.",
      "Conclude: all four are *prima facie* duties, to be balanced; add veracity, fidelity, confidentiality and dignity as supporting principles."]),
    ("Define informed consent and state its essential elements.",
     ["Definition as given in section 3.3. Elements of validity: **competence, disclosure, understanding, voluntariness, authorisation (C-D-U-V-A)**. Contents of disclosure: diagnosis; nature and purpose of the procedure; benefits; material risks; alternatives; consequences of refusal; right to withdraw; opportunity to ask questions; signature of patient, person taking consent and a witness; in the patient's own language."]),
    ("Describe the types of consent.",
     ["Implied; expressed oral; expressed written; informed; blanket/open (legally weak); proxy/surrogate; assent (of a child); consent implied by law in an emergency; loco parentis. Give one example of each and note which situations legally require **written** consent \u2014 invasive procedures, transfusion, HIV testing, MTP, sterilisation, organ donation, research."]),
    ("Differentiate between beneficence and non-maleficence.",
     ["Beneficence is a **positive** duty to do good, limited by feasibility, resources and the professional relationship. Non-maleficence is a **negative** duty to refrain from harming, owed universally and generally regarded as the **stronger** obligation. Beneficence example: phoning a critical value. Non-maleficence example: not releasing an unreliable result. Note that in practice they operate together as a **risk\u2013benefit analysis**."]),
    ("What is paternalism? Distinguish hard and soft paternalism.",
     ["Paternalism is overriding a person's choices or actions for what the professional believes to be that person's own good. **Hard (strong) paternalism** overrides the informed choice of a **competent** patient \u2014 ethically unacceptable. **Soft (weak) paternalism** acts protectively where the patient's decision-making is **impaired** (unconscious, delirious, a young child) \u2014 ethically acceptable and often obligatory. Modern ethics has shifted decisively from paternalism to **shared decision-making**."]),
    ("Discuss the types of justice with examples.",
     ["Distributive (ICU beds, vaccines, organ allocation); rights-based (right to emergency care under Article 21); legal (compliance with PC-PNDT, THOA, HIV Act); procedural (transparent published criteria, first-come-first-served); retributive/corrective (compensation for a negligent report); social (free tests for BPL patients, outreach camps). Add the criteria for allocating scarce resources: equal share, need, merit, contribution, ability to pay, maximum benefit, priority to the worst-off."]),
    ("How would you resolve a conflict between autonomy and beneficence? Give an example.",
     ["State that both are *prima facie* duties. For a **competent, informed adult, autonomy prevails** \u2014 e.g. a Jehovah's Witness refusing transfusion: re-explain, explore alternatives (iron, erythropoietin, cell salvage), document the refusal, and continue all other care without abandonment. Where the patient is **incompetent** or is a **minor**, beneficence and the best-interest standard prevail, and a court may authorise treatment. Mention the Four-Box Method as the analytical tool."]),
    ("List the limitations/exceptions to the principle of autonomy.",
     ["Incompetence (minors, unconscious, severe mental illness) \u2192 surrogate decision on the best-interest standard; emergency (implied consent); risk to public health (notifiable disease, quarantine \u2014 Epidemic Diseases Act 1897); serious risk to an identifiable third party (*Mr X v. Hospital Z*); court order or statutory duty; therapeutic privilege (very narrow); the patient's own waiver of information; and the fact that autonomy does not entitle a patient to demand futile or harmful treatment."]),
    ("Write short notes on the Institutional Ethics Committee.",
     ["Purpose: to protect the rights, safety and well-being of human research participants by reviewing, approving and monitoring research protocols; also reviews serious adverse events and consent documents. Composition (ICMR / New Drugs and Clinical Trials Rules, 2019): chairperson (preferably external), member secretary, basic medical scientist, clinicians, legal expert, social scientist/philosopher/theologian and a **lay person** from the community; minimum seven members with representation of both genders. Functions: initial review, continuing review, expedited review, site monitoring, record keeping for a prescribed period, and registration with the national authority."]),
    ("Explain veracity and fidelity with examples.",
     ["**Veracity** \u2014 the duty of truthfulness: reporting the true value even when it reveals an error, disclosing a mistake to the patient, giving honest information about delay. **Fidelity** \u2014 the duty to keep promises and remain loyal to the patient's interest: doing what you told the ward you would do, not abandoning duty, placing patient safety above the employer's commercial pressure. Both derive from respect for autonomy and from the **fiduciary** nature of the professional relationship."]),
])),

('recap', [
    "**A-B-N-J:** Autonomy, Beneficence, Non-maleficence, Justice \u2014 Beauchamp & Childress, 1979.",
    "Consent validity = **C-D-U-V-A** (Competence, Disclosure, Understanding, Voluntariness, Authorisation).",
    "*Primum non nocere* = non-maleficence = the strongest duty.",
    "Autonomy = right to **refuse**, not the right to **demand**.",
    "Competent adult's refusal **must** be honoured \u2014 re-explain, document, do not abandon.",
    "Justice in the lab = equal quality + equal courtesy + priority by clinical need only.",
    "Add **veracity, fidelity, confidentiality, dignity, accountability** for extra marks.",
    "Dilemma tool = **Four-Box Method**: indications, preferences, quality of life, context.",
]),

]
