# -*- coding: utf-8 -*-
"""Chapter 4 - Introduction to Communication Skills"""

BLOCKS = [

('ch', (4, "Communication Skills for Interacting with Colleagues, Clinicians, Patients and Attendants",
        "Process \u2022 Types \u2022 Verbal & non-verbal \u2022 Listening \u2022 Barriers \u2022 SBAR \u2022 Empathy \u2022 Interpersonal skills")),

('h2', "4.1  Introduction"),
('p', "Communication is the **most frequently performed 'procedure'** in health care. A technologist may perform fifty tests a day but will communicate several hundred times \u2014 with patients, attendants, nurses, clinicians, couriers and colleagues. Studies consistently show that the majority of medical errors and the overwhelming majority of patient complaints and negligence suits arise not from lack of technical skill but from **communication failure**. In the laboratory, the classic communication failures are: a critical value not conveyed, a verbal order misheard, a wrong patient identified, a sample mislabelled, a report handed to the wrong person, or a diagnosis blurted out insensitively."),
('quote', ("The single biggest problem in communication is the illusion that it has taken place.", "attributed to George Bernard Shaw")),

('def', ("Communication",
         "Communication is the **two-way process of exchanging information, ideas, thoughts, feelings and emotions** between two or more persons through a common system of verbal or non-verbal symbols, signs or behaviour, resulting in **shared understanding** and, usually, in some action or response.",
         ["Derived from the Latin *communicare* \u2014 'to share, to make common'.",
          "**Key idea:** communication is complete only when the receiver has understood the message as the sender intended \u2014 proved by **feedback**. Mere talking is not communication."])),

('h2', "4.2  Purposes / Importance of Communication in Health Care"),
('n', [
    "**To obtain accurate information** \u2014 correct patient identity, history, fasting status, drug intake, sample type and site.",
    "**To give information and instructions** \u2014 preparation for a test, timing, sample collection, when and how to collect the report.",
    "**To obtain valid informed consent** \u2014 impossible without effective communication.",
    "**To ensure patient safety** \u2014 correct identification, correct labelling, correct handover, timely reporting of critical values.",
    "**To reduce fear and anxiety** and build trust and cooperation.",
    "**To ensure compliance** \u2014 the patient who understands the instruction comes fasting and brings the right specimen.",
    "**To coordinate the team** \u2014 doctors, nurses, technologists, phlebotomists and support staff working from the same information.",
    "**To document** \u2014 written communication forms the legal record and the defence in a lawsuit.",
    "**To provide psychological support**, especially when the news is bad.",
    "**To prevent and resolve conflicts and complaints** with attendants.",
    "**To teach and learn** \u2014 training juniors, presenting at meetings, participating in CMEs.",
    "**To promote health** \u2014 counselling and public education."
]),

('h2', "4.3  Process / Elements of Communication"),
('p', "The classical model (Shannon\u2013Weaver, adapted for health care) has the following elements. Draw this as a diagram \u2014 it earns marks quickly."),
('tbl', (["Element", "Meaning", "Laboratory example"],
         [["**1. Sender / Source (encoder)**", "The person who originates the message", "The technologist who has a critical result"],
          ["**2. Message**", "The information, idea or feeling to be conveyed", "'Serum potassium is 7.2 mmol/L'"],
          ["**3. Encoding**", "Converting the idea into words, symbols, figures or gestures", "Choosing clear words and the exact numeric value with units"],
          ["**4. Channel / Medium**", "The route through which the message travels", "Telephone, LIS/computer, printed report, face-to-face, WhatsApp (**avoid for confidential data**)"],
          ["**5. Receiver (decoder)**", "The person for whom the message is intended", "The duty doctor or staff nurse"],
          ["**6. Decoding**", "Interpretation of the message by the receiver", "The nurse understands that this is a life-threatening hyperkalaemia"],
          ["**7. Feedback**", "The receiver's response confirming understanding \u2014 **the element that completes communication**", "**Read-back:** 'Potassium seven point two, patient Ram Lal, bed 12' "],
          ["**8. Noise / Barrier**", "Anything that distorts or blocks the message", "Poor telephone line, ward noise, language difference, distraction, jargon"],
          ["**9. Context / Environment**", "Physical, social, cultural and emotional setting", "A crowded, noisy collection room versus a quiet counselling cubicle"]],
         [3.4, 6.3, 7.5],
         "Elements of the communication process")),
('flow', ["**SENDER** (has an idea)", "**ENCODES** into words / symbols",
          "**MESSAGE** travels through a **CHANNEL** (with possible **NOISE**)",
          "**RECEIVER** receives and **DECODES**",
          "**UNDERSTANDING** achieved", "**FEEDBACK** returned to the sender \u2192 loop is closed"]),
('mne', ("\u201CS-M-C-R-F\u201D \u2014 the core of any communication model",
         ["**S** \u2013 Sender", "**M** \u2013 Message", "**C** \u2013 Channel",
          "**R** \u2013 Receiver", "**F** \u2013 Feedback",
          "(Add **N** for Noise and **E** for Environment for a fuller answer.)"])),

('h2', "4.4  Types of Communication"),
('h3', "A. On the Basis of the Medium Used"),
('tbl', (["Type", "Description", "Advantages", "Disadvantages"],
         [["**Verbal \u2013 Oral**", "Spoken words: face-to-face, telephone, meetings, presentations", "Fast; allows immediate feedback and clarification; personal and warm", "No permanent record; easily forgotten or distorted; risk of mishearing"],
          ["**Verbal \u2013 Written**", "Reports, requisition forms, SOPs, registers, emails, LIS entries", "Permanent legal record; precise; can be circulated and re-read", "Slow; no immediate feedback; useless if illegible or if the reader is illiterate"],
          ["**Non-verbal**", "Body language, facial expression, gestures, posture, eye contact, touch, tone, appearance, silence", "Conveys emotion and attitude powerfully; universal; hard to fake", "Easily misinterpreted; culturally variable; often unconscious"],
          ["**Visual**", "Diagrams, charts, colour codes, posters, biohazard symbols, graphs, videos", "Instantly understood; overcomes literacy and language barriers", "Can oversimplify; needs to be designed carefully"]],
         [2.4, 5.4, 4.7, 4.7],
         "Types of communication by medium")),
('h3', "B. On the Basis of Organisational Flow"),
('b', [
    "**Formal communication** \u2014 through the official hierarchy and prescribed channels (a signed report, an official memo, a requisition form). Reliable, documented, but slower.",
    "**Informal communication ('grapevine')** \u2014 unofficial, person-to-person (canteen conversation). Very fast, useful for morale, but **prone to rumour and to breach of confidentiality**.",
    "**Downward** \u2014 from senior to junior: orders, SOPs, instructions.",
    "**Upward** \u2014 from junior to senior: reports, complaints, suggestions, incident reports, **whistle-blowing**. A healthy laboratory must actively protect upward communication, because patient safety depends on a junior's freedom to say 'this looks wrong'.",
    "**Horizontal / Lateral** \u2014 between equals: technologist to technologist, ward nurse to laboratory.",
    "**Diagonal / Crosswise** \u2014 across levels and departments: technologist directly to a consultant in an emergency.",
    "**Intrapersonal** \u2014 within oneself (thinking, self-talk, reflection).",
    "**Interpersonal** \u2014 between two persons; the commonest and most important in clinical work.",
    "**Group / Small-group** \u2014 team meetings, quality-circle meetings, CME discussions.",
    "**Mass communication** \u2014 to the public: health education, notices, media, blood-donation campaigns.",
    "**Therapeutic communication** \u2014 purposeful, patient-centred interaction intended to help the patient psychologically, using techniques such as open questions, reflection, clarification, summarising and silence."
]),
('h3', "C. Special Types"),
('b', [
    "**One-way** (a notice board) vs **Two-way** (a conversation) \u2014 two-way is always more effective because it permits feedback.",
    "**Assertive communication** \u2014 expressing one's needs and views honestly and firmly while respecting others. Contrast with **passive** (bottling up, giving in) and **aggressive** (attacking, blaming). Assertiveness is the professional ideal, and is essential for a technologist who must say 'no' to an inappropriate request.",
    "**Electronic communication** \u2014 LIS, HIS, email, SMS, WhatsApp, tele-reporting. Fast and efficient, but raises serious **confidentiality, authentication and data-security** issues; patient-identifiable data should never be sent on personal messaging apps."
]),
('tbl', (["Style", "Behaviour", "Typical sentence", "Result"],
         [["**Passive**", "Avoids conflict, does not express needs, apologises excessively", "'It's all right, never mind, I'll manage somehow.'", "Frustration, stress, errors go unreported"],
          ["**Aggressive**", "Attacks, blames, shouts, humiliates", "'You people in the ward never label anything properly!'", "Conflict, resentment, breakdown of cooperation"],
          ["**Passive-aggressive**", "Indirect resistance, sarcasm, sulking, deliberate delay", "'Oh, of course, *your* sample is always the urgent one.'", "Mistrust, poor teamwork"],
          ["**Assertive** \u2713", "States facts and needs clearly, respectfully, using 'I' statements", "'I cannot process this sample because it is unlabelled. Please send a fresh, labelled sample; I will run it on priority.'", "Problem solved, relationship preserved, patient protected"]],
         [2.6, 4.6, 6.2, 3.8],
         "Communication styles \u2014 always recommend the assertive style")),

('h2', "4.5  Verbal Communication Skills"),
('b', [
    "**Clarity** \u2014 simple, short sentences; one idea at a time.",
    "**Avoid jargon and abbreviations** with patients: say 'blood count' rather than 'CBC', 'sugar test' rather than 'glycosylated haemoglobin'. Abbreviations are also a well-recognised cause of error *between* professionals \u2014 avoid ambiguous ones.",
    "**Correct language and vocabulary** \u2014 use the patient's own language or an interpreter.",
    "**Appropriate pace and volume** \u2014 slower and slightly louder for elderly or anxious patients, but never shouting.",
    "**Tone and pitch** \u2014 warm, calm, respectful. The *same* words spoken harshly become an insult.",
    "**Correct pronunciation of names**, and use of the appropriate honorific.",
    "**Sequencing** \u2014 most important information first, then details; summarise at the end.",
    "**Repetition and reinforcement** of critical instructions ('Nothing to eat or drink after 10 p.m., water is allowed').",
    "**Check understanding** \u2014 use the **'teach-back'** method: 'Could you tell me in your own words what you will do tomorrow morning?'",
    "**Avoid false reassurance** ('Don't worry, everything is definitely normal') and avoid speculation about diagnosis.",
    "**Never interrupt** unnecessarily; allow the patient to complete a sentence.",
    "**Use 'I' statements** rather than accusatory 'you' statements when raising a problem."
]),

('h2', "4.6  Non-verbal Communication"),
('p', "Non-verbal communication, also called **body language** or **kinesics**, often carries more weight than words, particularly when words and behaviour contradict each other. It is said that in emotionally charged interactions the greater part of the message is conveyed by **tone and body language** rather than by the words themselves (Mehrabian's much-quoted 7 % words / 38 % tone / 55 % body-language observation). Patients continuously 'read' the technologist's face and hands to judge whether the news is good."),
('tbl', (["Component", "What it conveys", "Do", "Avoid"],
         [["**Facial expression**", "The most powerful single channel of emotion", "Calm, pleasant, attentive face; a genuine smile at greeting", "Frowning at a result; grimacing; visible disgust or alarm"],
          ["**Eye contact (oculesics)**", "Attention, honesty, interest", "Comfortable, intermittent eye contact at the patient's level", "Staring; or never looking up from the screen/register"],
          ["**Posture**", "Interest and respect", "Upright, open, slightly forward-leaning; sit if the patient is sitting", "Slouching, arms crossed, turning away, standing over a lying patient"],
          ["**Gestures (kinesics)**", "Emphasis and explanation", "Open palms; simple demonstrative gestures", "Pointing a finger; snapping fingers; impatient hand-waving"],
          ["**Touch (haptics)**", "Comfort and reassurance; also necessary for procedures", "Explain before touching; gentle, purposeful, professional contact; ensure a chaperone where appropriate", "Sudden or rough handling; culturally inappropriate touch"],
          ["**Proximity / space (proxemics)**", "Intimacy vs respect for personal space", "Arm's length for conversation; closer only for the procedure, with permission", "Crowding the patient; or shouting from across the room"],
          ["**Tone, pitch, volume, pauses (paralanguage)**", "Emotional colouring of the words", "Warm, steady, unhurried; pause after important information", "Sarcasm, sighing, hurried monotone"],
          ["**Silence**", "Space to absorb and respond", "Deliberate pause after giving serious news; wait for the patient", "Filling every silence with talk"],
          ["**Appearance / attire**", "Competence and hygiene", "Clean coat, visible ID badge, tied hair, trimmed nails", "Stained coat, no ID, coat worn in the canteen, strong perfume"],
          ["**Chronemics (use of time)**", "Respect for the patient", "Punctuality; telling patients the realistic waiting time", "Keeping patients waiting without information"],
          ["**Written / documentary appearance**", "Professionalism of the laboratory", "Legible, neat, complete, signed reports", "Overwriting, whitener, unsigned or illegible entries"]],
         [3.2, 3.6, 5.2, 5.2],
         "Components of non-verbal communication")),
('mne', ("\u201CSOLER\u201D \u2014 the attentive, non-verbal listening posture (Egan)",
         ["**S** \u2013 **S**it (or stand) **squarely** facing the person",
          "**O** \u2013 **O**pen posture (do not fold arms or cross legs defensively)",
          "**L** \u2013 **L**ean slightly forward to show interest",
          "**E** \u2013 **E**ye contact, comfortable and intermittent",
          "**R** \u2013 **R**elax \u2014 appear unhurried and at ease"])),

('h2', "4.7  Listening and Active Listening"),
('def', ("Active Listening",
         "A deliberate, disciplined process of **hearing, attending to, interpreting, evaluating and responding** to the complete message of the speaker \u2014 including its emotional content \u2014 and visibly demonstrating that attention, so that the speaker feels heard and understood.")),
('h3', "Levels of Listening"),
('n', [
    "**Ignoring** \u2014 not listening at all.",
    "**Pretend listening** \u2014 nodding while thinking of something else.",
    "**Selective listening** \u2014 hearing only what interests you (a common cause of missed critical information).",
    "**Attentive listening** \u2014 paying full attention to the words.",
    "**Empathic / active listening** \u2014 listening with the intent to understand the speaker's feelings and frame of reference. **This is the professional standard.**"
]),
('h3', "Techniques of Active Listening"),
('b', [
    "**Give full attention** \u2014 stop typing, put down the pipette, face the speaker.",
    "**Use minimal encouragers** \u2014 'Yes...', 'I see', 'Go on', with nodding.",
    "**Ask open-ended questions** first ('Tell me what happened'), then closed ones to confirm details ('Did you eat anything after 10 p.m.?').",
    "**Paraphrase / restate** \u2014 'So you had the sample taken yesterday and were told to come back today.'",
    "**Reflect feelings** \u2014 'It sounds as though you are worried about the needle.'",
    "**Clarify** \u2014 'When you say a \u2018sugar test\u2019, do you mean fasting sugar or HbA1c?'",
    "**Summarise** periodically and at the end.",
    "**Allow silences**; do not rush to fill them.",
    "**Do not interrupt, argue or finish the speaker's sentences.**",
    "**Note-taking** for details such as dosage, timing and identifiers.",
    "**Read-back / repeat-back** for all verbal orders and critical values \u2014 a mandatory patient-safety practice.",
    "**Suspend judgement** and avoid premature advice."
]),
('mne', ("\u201CRESPECT\u201D \u2014 elements of active listening",
         ["**R** \u2013 Reflect feelings", "**E** \u2013 Eye contact and encouragers",
          "**S** \u2013 Summarise", "**P** \u2013 Paraphrase",
          "**E** \u2013 Empathise", "**C** \u2013 Clarify",
          "**T** \u2013 Take notes / repeat back"])),
('h3', "Empathy vs Sympathy \u2014 an examiner favourite"),
('tbl', (["Point", "Empathy \u2713 (professional)", "Sympathy (limited value)"],
         [["Meaning", "Understanding and accurately perceiving the patient's feelings **as if** they were your own, while retaining objectivity", "Feeling pity or sorrow **for** the patient; sharing the emotion"],
          ["Position", "Standing *in* the patient's shoes but keeping your own feet", "Getting *into* the patient's emotional hole with him"],
          ["Effect on the professional", "Preserves objectivity and clinical judgement", "May cause emotional exhaustion and impaired judgement"],
          ["Effect on the patient", "Feels understood, respected and supported", "May feel pitied, patronised or more helpless"],
          ["Typical sentence", "'I can understand that waiting for this report is very worrying for you. Let me tell you exactly when it will be ready.'", "'Oh, you poor thing, how terrible, I feel so sorry for you.'"],
          ["Also distinguish", "**Compassion** = empathy **plus** the wish and action to relieve the suffering. **Apathy** = absence of feeling; **Antipathy** = hostility.", ""]],
         [2.2, 7.6, 7.4],
         "Empathy vs Sympathy")),

('h2', "4.8  Barriers to Communication"),
('p', "This is one of the most frequently asked questions in the paper. Classify the barriers \u2014 do not give a random list."),
('tbl', (["Category", "Barriers", "Remedies"],
         [["**Physical / Environmental**", "Noise in the collection room; crowding; poor lighting; distance; faulty telephone; interruptions; poor network or LIS downtime; uncomfortable temperature", "Quiet, private counselling space; maintained equipment; a dedicated telephone line for critical results; 'do not disturb' during counselling; downtime SOP"],
          ["**Physiological**", "Deafness or hearing impairment; visual impairment; speech defect; pain; fatigue; drowsiness; illness; hunger; effect of drugs or anaesthesia", "Speak into the better ear or use a hearing aid; write it down; large print; treat pain first; postpone non-urgent discussion; involve a family member"],
          ["**Psychological / Emotional**", "Anxiety, fear, anger, grief, depression, denial, shock, stress, prejudice, mistrust, low self-esteem, defensiveness, information overload, selective perception", "Acknowledge the emotion first; reassure; allow ventilation; give information in small portions; repeat later; build rapport before information"],
          ["**Semantic / Linguistic**", "Different language or dialect; **medical jargon and abbreviations**; technical terms; ambiguous words; poor handwriting; illiteracy; faulty translation", "Use the patient's language or a trained interpreter; plain words; pictures; legible writing; **teach-back** to confirm understanding"],
          ["**Cultural / Social**", "Differences of religion, caste, gender norms, modesty taboos, beliefs about illness; the taboo on discussing death or sexual health; stigma", "Cultural sensitivity; same-gender staff and chaperones; respect for beliefs; non-judgemental language"],
          ["**Organisational / Structural**", "Steep hierarchy; fear of the senior; overwork and time pressure; understaffing; too many links in the chain; no defined channel for critical results; departmental rivalry; poor documentation", "Flat, blame-free reporting culture; clear SOPs and escalation policy; adequate staffing; structured handover tools such as **SBAR**; incident-reporting system"],
          ["**Personal / Attitudinal**", "Rudeness; arrogance; indifference; not listening; assuming the patient will not understand; prejudice against certain patients; poor eye contact; use of a mobile phone while talking", "Training in communication; feedback and appraisal; role modelling; self-awareness and reflection"],
          ["**Perceptual**", "Different frames of reference; premature judgement; stereotyping; halo effect", "Clarify assumptions; ask rather than assume; summarise back"]],
         [2.8, 7.0, 7.4],
         "Barriers to communication and their remedies")),
('mne', ("\u201CP-P-P-S-C-O-P\u201D \u2014 the seven groups of barriers",
         ["**P** \u2013 Physical / environmental", "**P** \u2013 Physiological",
          "**P** \u2013 Psychological", "**S** \u2013 Semantic / linguistic",
          "**C** \u2013 Cultural / social", "**O** \u2013 Organisational",
          "**P** \u2013 Personal / attitudinal"])),

('h2', "4.9  Characteristics of Effective Communication \u2014 The 7 C's"),
('tbl', (["The 7 C's", "Meaning", "Laboratory application"],
         [["**1. Clear**", "One idea at a time, simple and unambiguous", "'Do not eat or drink anything except water after 10 p.m.'"],
          ["**2. Concise**", "Brief, no unnecessary words", "A critical-value call gives identity, test, value, units \u2014 nothing else"],
          ["**3. Concrete**", "Specific facts and figures, not vague statements", "'Potassium 7.2 mmol/L' \u2014 not 'potassium is high'"],
          ["**4. Correct**", "Accurate facts, correct grammar, correct units and reference range", "Correct patient identifiers and correct units on every report"],
          ["**5. Coherent**", "Logically organised and consistent", "Report format: identity \u2192 specimen \u2192 result \u2192 reference range \u2192 comment \u2192 signature"],
          ["**6. Complete**", "All information the receiver needs to act", "Include specimen type, collection time, method and any interference comment"],
          ["**7. Courteous**", "Polite, respectful, considerate of the receiver's feelings", "Greeting the patient; apologising for a delay; polite tone even at 3 a.m."]],
         [2.2, 6.4, 8.6],
         "The 7 C's of effective communication \u2014 memorise; frequently asked")),
('p', "Some authors add **Credibility** (the source must be trustworthy), **Consideration** (see it from the receiver's point of view \u2014 the 'you-attitude'), **Continuity** and **Consistency**. Mention these as 'additional C's' to show depth."),

('h2', "4.10  Communicating with Patients"),
('h3', "Before, During and After Sample Collection"),
('tbl', (["Stage", "What to communicate"],
         [["**Greeting**", "Greet by name; introduce yourself and your role; 'Good morning, are you Mrs Sunita Devi? I am Ramesh, the laboratory technologist.'"],
          ["**Identification**", "Verify with **two identifiers** (full name and date of birth / hospital number) \u2014 **never** simply call out 'Sunita?' and accept a nod; ask the patient to state her own name"],
          ["**Explanation**", "What test, why, which sample, how it will be taken, how long it will take, how much it will hurt, and when the report will be ready"],
          ["**Consent**", "Ask permission; for special tests obtain written, counselled consent"],
          ["**Pre-test instructions**", "Fasting, medication, timing, posture, urine collection technique, container to be used \u2014 given both **verbally and in writing**"],
          ["**During the procedure**", "Warn before the prick; keep talking calmly; do not discuss other patients; do not comment on the appearance of the sample"],
          ["**After the procedure**", "Post-procedure care (press, do not bend the arm, watch for bleeding), what to do if there is a haematoma, when and where to collect the report, whom to contact"],
          ["**Closing**", "Ask if there are any questions; thank the patient; confirm understanding by teach-back"]],
         [2.6, 14.6],
         "A model patient interaction in the laboratory")),
('h3', "Special Groups \u2014 Adapting Your Communication"),
('tbl', (["Group", "Key adaptations"],
         [["**Children**", "Get down to the child's eye level; simple honest words; never lie ('it won't hurt at all'); allow a parent to stay and hold the child; use distraction, praise and a small reward; be quick and skilful; obtain the child's **assent** along with parental consent"],
          ["**Elderly**", "Speak slowly, clearly, facing the person; sit down; allow extra time; check hearing aids and spectacles; use written instructions in large print; address respectfully; do not talk to the accompanying relative *instead of* the patient; watch for cognitive impairment"],
          ["**Anxious or frightened patient**", "Acknowledge the fear; explain step by step; allow ventilation; do not hurry; consider lying position for a needle-phobic patient"],
          ["**Angry patient / attendant**", "Stay calm and lower your own voice; listen fully without interrupting; do not argue or take it personally; acknowledge the grievance ('I can see this delay has been very frustrating'); apologise for the inconvenience; state exactly what you will do and by when; escalate to the supervisor if needed; never respond with sarcasm or threat; ensure your own safety"],
          ["**Unconscious patient**", "Continue to speak \u2014 hearing may be preserved; explain to the attendant; take surrogate consent; maintain dignity and cover the body"],
          ["**Hearing-impaired**", "Face the person in good light so lips are visible; speak normally, do not exaggerate; write key points; use gestures; use a sign-language interpreter if available"],
          ["**Visually impaired**", "Announce your presence and identify yourself; explain by touch and sound; describe what you are about to do; do not move his belongings; offer your arm for guidance; provide the report in an accessible format"],
          ["**Patient with a language barrier**", "Use a **trained interpreter** rather than a random bystander; speak to the patient, not to the interpreter; use short sentences; use pictorial instruction cards"],
          ["**Illiterate patient**", "Verbal explanation plus pictorial instructions; consent by thumb impression **with an independent witness**; teach-back is essential"],
          ["**Mentally ill / cognitively impaired**", "Simple short sentences, one instruction at a time; calm environment; assess capacity; involve the guardian; avoid confrontation"],
          ["**Terminally ill / bad news**", "Private setting, sit down, warning shot, small chunks, silence, empathy, plan \u2014 see the **SPIKES** protocol in Chapter 6"],
          ["**Bereaved relatives**", "Private room; simple direct words ('has died'); allow grief and silence; do not offer platitudes; offer practical help with formalities"]],
         [3.0, 14.2],
         "Communicating with special groups")),

('h2', "4.11  Communicating with Clinicians"),
('p', "Communication with a clinician has a different purpose: it must be **precise, structured, brief and complete**. The internationally recommended tool for clinical hand-off is **SBAR**, and it is examinable."),
('mne', ("\u201CSBAR\u201D \u2014 structured clinical communication (originally from the US Navy, now standard in health care)",
         ["**S \u2013 Situation:** who you are, who the patient is, and what the problem is in one sentence. *'This is Ramesh from Biochemistry. Regarding Mr Ram Lal, bed 12, ward 5 \u2014 I have a critical potassium result.'*",
          "**B \u2013 Background:** the relevant context. *'Sample received at 2.10 a.m. for renal profile; the patient is a known chronic kidney disease case.'*",
          "**A \u2013 Assessment:** the finding and its significance. *'Serum potassium is 7.2 mmol/L, confirmed on repeat; the sample was not haemolysed. This is in the critical range.'*",
          "**R \u2013 Recommendation / Request:** what you want to happen. *'Please review the patient urgently. Shall I keep the sample for a repeat, and may I have the name of the person receiving this result?'*",
          "Then close with a **read-back** and **document** the call: date, time, result, name of the person informed, and your own name."])),
('h3', "Rules for Communication with Clinicians and Colleagues"),
('b', [
    "**Be prepared** before you telephone: have the report, the identifiers and the previous value in front of you.",
    "**Identify yourself and your department** first; ask for and record the name and designation of the person you speak to.",
    "**Use exact figures with units** and state the reference range and the critical threshold.",
    "**Never use ambiguous abbreviations** or 'trailing zeros' in dosages when repeating verbal information.",
    "**Insist on a read-back** for every verbal or telephonic result and every verbal order.",
    "**Report analytical limitations honestly** \u2014 haemolysis, lipaemia, clot, insufficient volume, delay in transport, interference, dilution.",
    "**Escalate appropriately** \u2014 if the duty doctor cannot be reached, follow the written escalation ladder (senior resident \u2192 consultant \u2192 nursing supervisor \u2192 medical officer on call). **Never stop at one failed attempt.**",
    "**Do not offer a clinical diagnosis or treatment advice** beyond your role, but do offer the technical interpretation you are qualified to give.",
    "**Do not criticise a clinician in front of a patient**; raise disagreements privately and professionally.",
    "**Document everything** \u2014 in the critical-value register / LIS: date, time, result, informed to whom, read-back done, your signature.",
    "**Respect the chain of command** but never let hierarchy stop you from voicing a safety concern \u2014 use the **'CUS' words**: 'I am **C**oncerned \u2026 I am **U**ncomfortable \u2026 this is a **S**afety issue.'",
    "**Give feedback to the ward** on repeated pre-analytical errors, politely and with data, not with blame."
]),
('eg', ["**A model critical-value telephone call (learn this \u2014 it can be reproduced verbatim in the exam):**",
        "*'Good morning, this is Ramesh, laboratory technologist, Central Clinical Laboratory. May I know your name and designation, please? \u2026 Thank you, Sister Meena. I am calling about a critical result. Patient: Mr Ram Lal, UHID 45231, bed 12, male, 62 years. Serum potassium is seven point two millimoles per litre \u2014 that is seven, point, two. It has been confirmed on a repeat run and the sample was not haemolysed. This is above our critical limit of six point zero. Please inform the duty doctor immediately. Could you read the value back to me, please? \u2026 Yes, that is correct, seven point two. Thank you. I am recording this call at 2.35 a.m. and will retain the sample.'*"]),

('h2', "4.12  Communicating with Attendants and Relatives"),
('b', [
    "**Confirm identity and relationship** before disclosing anything; the patient's information belongs to the **patient**, not the family.",
    "**Take the patient's permission** (ideally recorded in advance) about who may be given information.",
    "**Talk in a private place**, never in the corridor or at the counter within earshot of others.",
    "**Address the senior-most responsible attendant** but include the person who will actually give care.",
    "**Use simple language**, avoid jargon, avoid numbers without explanation.",
    "**Do not give a diagnosis or prognosis** \u2014 that is the treating clinician's role. Say clearly: 'The report will be given to your doctor, who will explain what it means.' This single sentence prevents most conflicts.",
    "**Explain the process and the realistic time**: why the test takes six hours, why culture takes 48\u201372 hours.",
    "**Answer questions about charges and procedures** honestly.",
    "**Manage expectations proactively** \u2014 an attendant told 'it will take three hours' does not become an angry attendant at hour two.",
    "**Handle aggression safely** \u2014 stay calm, keep a safe distance and an exit available, call security when needed, and never argue with a group.",
    "**Show empathy for their anxiety** \u2014 they are frightened, not hostile by nature."
]),

('h2', "4.13  Documentation and Written Communication"),
('b', [
    "**Legible, in ink, no pencil**; no overwriting, no whitener \u2014 strike through a single line, write the correct entry, initial and date it.",
    "**Contemporaneous** \u2014 recorded at the time of the event, never back-dated.",
    "**Complete** \u2014 two patient identifiers, specimen type, collection date and time, receipt time, method, result with units and reference range, comments, and the signature and designation of the person releasing the report.",
    "**Accurate and objective** \u2014 record facts, not opinions about the patient ('patient was abusive' \u2192 better: 'patient declined the procedure and left at 10.15 a.m.').",
    "**Confidential** \u2014 records locked, screens locked, individual passwords never shared, reports not left on open counters.",
    "**Retained** for the period prescribed by law and by NABL/institutional policy.",
    "**Amendments** to an issued report must be made as a clearly marked **corrected report**, with the reason, and the original must not be destroyed; the clinician must be actively informed.",
    "**Remember the legal maxim:** *'Not documented, not done.'* In court, a good record is the professional's best defence."
]),

('h2', "4.14  Consequences of Poor Communication"),
('b', [
    "**Patient harm** \u2014 wrong patient, wrong test, wrong or delayed result acted upon.",
    "**Diagnostic and therapeutic delay.**",
    "**Non-compliance** \u2014 the patient arrives non-fasting; the wrong specimen is collected; the test must be repeated.",
    "**Loss of trust**, dissatisfaction and complaints.",
    "**Litigation** \u2014 poor communication is the single largest driver of complaints and negligence suits.",
    "**Conflict, aggression and violence** against health-care workers.",
    "**Team dysfunction** and duplication or omission of work.",
    "**Wastage of resources** \u2014 repeat samples, repeat tests, wasted reagents.",
    "**Staff stress, moral distress and burnout.**",
    "**Damage to the reputation** of the laboratory and the institution."
]),

('key', [
    "Communication = a **two-way** process; it is complete only with **feedback**. *Communicare* = 'to share'.",
    "Elements: **Sender \u2192 encoding \u2192 message \u2192 channel \u2192 receiver \u2192 decoding \u2192 feedback**, with **noise** and **context** acting throughout.",
    "Types: verbal (oral, written), non-verbal, visual; formal/informal; downward/upward/horizontal/diagonal; intrapersonal/interpersonal/group/mass; therapeutic.",
    "**Non-verbal communication often outweighs words** \u2014 face, eyes, posture, gesture, touch, space, tone, silence, appearance.",
    "**SOLER** = the attentive listening posture; **active/empathic listening** is the professional standard.",
    "**Empathy \u2260 sympathy.** Empathy understands and retains objectivity; sympathy pities and risks exhaustion.",
    "Barriers = **physical, physiological, psychological, semantic, cultural, organisational, personal, perceptual.**",
    "Effective communication = the **7 C's**: Clear, Concise, Concrete, Correct, Coherent, Complete, Courteous.",
    "**SBAR** (Situation, Background, Assessment, Recommendation) is the structured tool for talking to clinicians; always finish with a **read-back** and **documentation**.",
    "The **assertive** style is the professional ideal \u2014 not passive, not aggressive.",
    "Legal maxim: **'Not documented, not done.'**"
]),

('tip', [
    "**Expected questions from this chapter:**",
    "- *Long (10 marks):* 'Define communication. Describe the process, types and barriers to effective communication in a hospital laboratory.'",
    "- *Long (10 marks):* 'Discuss the communication skills required by a laboratory technologist while interacting with patients, attendants, colleagues and clinicians.'",
    "- *Short (5 marks):* 7 C's of communication; Non-verbal communication; Active listening / SOLER; Empathy vs sympathy; Barriers to communication; SBAR; Assertive communication; Therapeutic communication.",
    "- *Very short (2 marks):* Define communication; expand SBAR and SOLER; two types of non-verbal communication; what is feedback; what is 'noise'.",
    "**Presentation tip:** draw the **SMCRF flow diagram** and the **barriers table** \u2014 these two visuals alone can carry a 10-mark answer."
]),

('qa', ("QUESTION BANK \u2014 CHAPTER 4", [
    ("Define communication and describe its process with a diagram.",
     ["Definition as in section 4.1. Process/elements: sender \u2192 encoding \u2192 message \u2192 channel \u2192 receiver \u2192 decoding \u2192 **feedback**, operating within a **context** and subject to **noise/barriers**. Draw the loop diagram. Emphasise that communication is complete only when the receiver's understanding matches the sender's intention, which is proved by feedback (in the laboratory, the **read-back**)."]),
    ("What are the barriers to effective communication? How can they be overcome?",
     ["Classify into physical/environmental, physiological, psychological/emotional, semantic/linguistic, cultural/social, organisational/structural, personal/attitudinal and perceptual. Give two examples and one remedy for each \u2014 reproduce the table. *(Mnemonic: P-P-P-S-C-O-P.)*"]),
    ("Explain the 7 C's of effective communication.",
     ["Clear, Concise, Concrete, Correct, Coherent, Complete, Courteous \u2014 define each in one line and add a laboratory example. Mention the additional C's: Credibility, Consideration, Continuity, Consistency."]),
    ("Write short notes on non-verbal communication.",
     ["Definition: transmission of messages without words, through body language and paralanguage. Components: facial expression, eye contact (oculesics), posture, gestures (kinesics), touch (haptics), personal space (proxemics), tone/pitch/volume (paralanguage), silence, appearance, use of time (chronemics). Importance: conveys emotion more powerfully than words; when words and body language conflict, the patient believes the body language. Add **SOLER** and two laboratory do's and don'ts."]),
    ("What is active listening? Describe its techniques.",
     ["Definition as in section 4.7. Levels: ignoring \u2192 pretend \u2192 selective \u2192 attentive \u2192 empathic. Techniques: full attention, minimal encouragers, open then closed questions, paraphrasing, reflecting feelings, clarifying, summarising, allowing silence, not interrupting, note-taking, **read-back**, suspending judgement. Add SOLER and the value of active listening in preventing error and complaints."]),
    ("Differentiate between empathy and sympathy.",
     ["Reproduce the comparison table \u2014 meaning, position, effect on the professional, effect on the patient, typical sentence. Add: compassion = empathy + action to relieve suffering; apathy = absence of feeling; antipathy = hostility. Conclude that empathy is the professional ideal because it supports the patient while preserving objectivity and protecting the professional from burnout."]),
    ("Describe the SBAR technique with an example.",
     ["**S**ituation \u2013 who you are, who the patient is, what the problem is; **B**ackground \u2013 relevant context; **A**ssessment \u2013 the finding and its significance; **R**ecommendation/Request \u2013 what you want done. Give the critical potassium example. Close with read-back and documentation. Advantages: structured, brief, complete, reduces omission, works across hierarchy, improves patient safety."]),
    ("How will you communicate with an angry attendant whose report has been delayed?",
     ["Take him to a quiet place; stay calm and lower your own voice; listen fully without interrupting; do not argue or become defensive; acknowledge and validate the grievance; apologise for the inconvenience (an apology for delay is not an admission of negligence); explain the actual reason honestly and briefly; state exactly what you will do and by when; give a realistic time; offer to involve the supervisor; document the complaint; ensure your own safety and call security if there is any threat; follow up as promised."]),
    ("Distinguish between passive, aggressive and assertive communication.",
     ["Reproduce the styles table with the typical sentence for each and its result. Conclude that **assertiveness** \u2014 stating facts and needs clearly and respectfully using 'I' statements \u2014 is the professional standard, because it protects the patient (the technologist can refuse an unsafe request) while preserving the working relationship."]),
    ("List the special communication needs of children and the elderly.",
     ["**Children:** eye-level, simple honest words, never lie about pain, parent present, distraction and praise, quick skilful technique, take the child's assent with parental consent. **Elderly:** slow clear speech facing the person, sit down, extra time, check hearing aid and spectacles, large-print written instructions, respectful address, speak *to* the patient and not only to the relative, watch for cognitive impairment and for fear of dependence."]),
    ("What are the consequences of poor communication in a laboratory?",
     ["Patient harm from wrong identification or a mis-conveyed result; diagnostic and therapeutic delay; non-compliance and repeat sampling; loss of trust and complaints; litigation; conflict and violence against staff; team dysfunction; wastage of reagents and time; staff stress and burnout; loss of reputation and accreditation."]),
])),

('recap', [
    "**S-M-C-R-F** + Noise + Context = communication process; **feedback closes the loop**.",
    "Verbal / non-verbal / written / visual; formal vs informal; up, down, horizontal, diagonal.",
    "**SOLER** = Squarely, Open, Lean, Eye contact, Relax.",
    "**7 C's** = Clear, Concise, Concrete, Correct, Coherent, Complete, Courteous.",
    "Barriers = **P-P-P-S-C-O-P** (physical, physiological, psychological, semantic, cultural, organisational, personal).",
    "**Empathy** understands; **sympathy** pities. Choose empathy.",
    "**SBAR** for clinicians; **read-back** for every verbal/critical result; then **document**.",
    "Be **assertive**, never passive or aggressive. *'Not documented, not done.'*",
]),

]
