# -*- coding: utf-8 -*-
"""Chapter 5 - Relationship of Paramedics and Patient"""

BLOCKS = [

('ch', (5, "Relationship of Paramedics and Patient",
        "Nature \u2022 Models \u2022 Rights and duties \u2022 Trust and fiduciary duty \u2022 Boundaries \u2022 Difficult situations")),

('h2', "5.1  Introduction and Meaning of 'Paramedic'"),
('def', ("Paramedic / Paramedical Personnel",
         "Paramedical (or allied health) personnel are **trained health-care workers who assist and support the physician** in the diagnosis, treatment, rehabilitation and prevention of disease, but who do not themselves independently practise medicine. The group includes medical laboratory technologists, radiographers, physiotherapists, occupational therapists, optometrists, dialysis and OT technicians, emergency medical technicians, dietitians, and others.",
         ["The prefix *para-* means 'alongside'. A paramedic works **alongside** the doctor \u2014 not below him in dignity, but distinct in role and scope.",
          "In India these professions are being brought under statutory regulation through the **National Commission for Allied and Healthcare Professions Act, 2021**, which provides for central and state councils, registers of practitioners, and enforceable standards of professional conduct and ethics."])),
('def', ("Paramedic\u2013Patient Relationship",
         "The professional, **fiduciary** (trust-based) association that arises the moment a paramedical professional undertakes to render a service to a patient, and by virtue of which the professional owes the patient duties of competence, care, honesty, confidentiality, respect and non-abandonment, while the patient acquires corresponding rights.")),
('p', "The paramedic\u2013patient relationship is often the patient's **first and last** contact with the diagnostic process. In practice the phlebotomist or technologist frequently spends more physical time with the patient than the consultant does. The patient forms his judgement of the entire hospital from that encounter. It is therefore not a peripheral relationship \u2014 it is central."),

('h2', "5.2  Nature and Characteristics of the Relationship"),
('n', [
    "**Fiduciary** \u2014 founded on trust. The patient must trust because he cannot verify: he cannot check whether the analyser was calibrated or whether the sample was labelled correctly.",
    "**Asymmetric / unequal** \u2014 there is an imbalance of knowledge, skill and power. The professional holds the expertise; the patient is vulnerable, often frightened, sometimes undressed, in pain and dependent. This asymmetry is precisely why ethical duties are imposed on the stronger party.",
    "**Contractual as well as ethical** \u2014 in law, a paid diagnostic service is a 'service' under the **Consumer Protection Act, 2019**, giving rise to contractual liability *and* to the tort of negligence, over and above ethical duties.",
    "**Voluntary in initiation, but not freely terminable** \u2014 once undertaken, the professional cannot abandon the patient midway (**duty of non-abandonment**).",
    "**Professional, not personal** \u2014 warm but bounded; there must be no exploitation, no romantic or sexual involvement, no borrowing of money, no business dealings with patients.",
    "**Confidential** \u2014 information flows to the professional on the implied condition of secrecy.",
    "**Purposeful and time-limited** \u2014 directed towards a defined clinical purpose, not open-ended friendship.",
    "**Therapeutic** \u2014 the relationship itself has healing value; a reassuring, respectful encounter reduces anxiety and improves cooperation.",
    "**Culturally embedded** \u2014 shaped by family structure, gender norms, religion and social hierarchy, which in India frequently means the family, not the individual, comes to the counter.",
    "**Legally accountable** \u2014 breach can give rise to civil liability (compensation), criminal liability (in gross cases), and disciplinary action."
]),
('mne', ("\u201CT-R-U-S-T\u201D \u2014 the foundation of the relationship",
         ["**T** \u2013 **Truthfulness** (veracity, honest reporting)",
          "**R** \u2013 **Respect** (dignity, privacy, courtesy)",
          "**U** \u2013 **Understanding** (empathy, communication, listening)",
          "**S** \u2013 **Secrecy** (confidentiality)",
          "**T** \u2013 **Technical competence** (accuracy, quality, safety)"])),

('h2', "5.3  Models of the Professional\u2013Patient Relationship"),
('p', "Several classifications exist. Learn **both** the Szasz\u2013Hollender model and the Emanuel & Emanuel model \u2014 examiners accept either, and quoting both is impressive."),
('h3', "A. Szasz and Hollender's Three Models (1956)"),
('tbl', (["Model", "Description", "Patient's role", "Best suited to", "Analogy"],
         [["**1. Activity\u2013Passivity**", "The professional acts *upon* the patient, who is entirely passive and contributes nothing", "Completely passive; consent is impossible", "Unconscious patient, general anaesthesia, cardiac arrest, delirium, neonate", "Parent \u2013 infant"],
          ["**2. Guidance\u2013Cooperation**", "The professional guides and instructs; the patient is conscious, cooperates and obeys", "Obedient cooperator; limited participation", "Acute illness \u2014 an acutely febrile patient told to give a blood sample", "Parent \u2013 adolescent child"],
          ["**3. Mutual Participation**", "Both are partners with roughly equal power; the professional helps the patient to help himself", "Active partner in decision-making and self-care", "Chronic disease \u2014 diabetes, hypertension, CKD, HIV; long-term monitoring", "Adult \u2013 adult"]],
         [3.1, 6.0, 2.9, 3.4, 1.8],
         "Szasz & Hollender's models \u2014 the classic answer")),
('h3', "B. Emanuel & Emanuel's Four Models (1992)"),
('tbl', (["Model", "Professional's role", "Patient's values", "Comment"],
         [["**Paternalistic** (parental / priestly)", "Guardian \u2014 decides what is best and presents it as the only option", "Assumed to be shared and objective", "The traditional model; now generally unacceptable except in emergencies"],
          ["**Informative** (scientific / consumer / engineering)", "Technical expert who supplies facts, all options and probabilities", "Fixed, known to the patient", "Risk: the professional becomes a mere technician, emotionally detached"],
          ["**Interpretive**", "Counsellor / adviser who helps the patient clarify and articulate his own values", "Inchoate, need elucidation", "Requires time and skill; risk of the professional imposing his own interpretation"],
          ["**Deliberative**", "Friend / teacher who engages in dialogue about which values are most worth pursuing", "Open to development through discussion", "**Regarded by the authors as the ideal**; closest to modern shared decision-making"]],
         [3.4, 5.4, 3.4, 5.0],
         "Emanuel & Emanuel's four models")),
('h3', "C. Other Descriptive Models"),
('b', [
    "**Priestly model** \u2014 'Doctor knows best'; strongly paternalistic.",
    "**Engineering model** \u2014 the professional supplies facts only and makes no value judgement; the patient decides everything alone.",
    "**Collegial model** \u2014 professional and patient as colleagues pursuing a shared goal; idealistic, ignores real power differences.",
    "**Contractual model** \u2014 an agreement with mutual obligations and benefits, respecting both parties' values; considered a realistic and workable model.",
    "**Covenantal model** \u2014 goes beyond contract to a bond of mutual commitment and trust.",
    "**Consumerist model** \u2014 the patient as a purchaser of services with enforceable rights; the model reflected in the **Consumer Protection Act**.",
    "**Patient-centred / shared decision-making model** \u2014 the currently accepted ideal in all health-care systems."
]),
('warn', ["A frequent exam trap: **there is no single 'correct' model for all situations.** The appropriate model depends on the patient's condition and capacity \u2014 activity\u2013passivity is right for an unconscious trauma victim, mutual participation is right for a stable diabetic. A good answer says exactly this in the conclusion."]),

('h2', "5.4  Rights of the Patient"),
('p', "The National Human Rights Commission and the Ministry of Health & Family Welfare have issued a **Charter of Patients' Rights (2018)** for India, which States are adopting. Learn the list \u2014 it is directly examinable."),
('n', [
    "**Right to information** \u2014 about the illness, proposed investigations, their cost, expected results and the identity and qualification of the persons treating him.",
    "**Right to records and reports** \u2014 to receive copies of case papers, investigation reports and discharge summary; ordinarily within 24 hours to 72 hours of a request.",
    "**Right to emergency medical care** \u2014 immediate, without insisting on advance payment (Article 21; *Parmanand Katara v. Union of India*, 1989).",
    "**Right to informed consent** before any invasive investigation or treatment.",
    "**Right to confidentiality, human dignity and privacy** \u2014 including the presence of a **chaperone** during physical examination of a female patient.",
    "**Right to a second opinion** and to have the records made available for it.",
    "**Right to transparency in rates**, and the right to be charged according to the displayed rate schedule.",
    "**Right to choose** the source of medicines or the diagnostic laboratory \u2014 the hospital cannot compel purchase from its own pharmacy or laboratory.",
    "**Right to non-discrimination** on grounds of illness, condition, HIV status, gender, sexual orientation, religion, caste, ethnicity or social origin.",
    "**Right to safety and quality care** according to standards.",
    "**Right to be treated by a qualified person**, and to know who is treating him.",
    "**Right to protection for participants in clinical trials** (as per NDCT Rules, 2019 and ICMR guidelines).",
    "**Right to protection of participants in biomedical and health research.**",
    "**Right to take discharge**, and \u2014 for the next of kin \u2014 the **right to receive the body** of a deceased patient from the hospital (the body must not be detained for want of payment).",
    "**Right to patient education** \u2014 about his condition, healthy living, available insurance and social schemes, and the redressal mechanism.",
    "**Right to be heard and to seek redressal** \u2014 to complain and to have the complaint addressed.",
    "**Right to refuse treatment** and to leave against medical advice, after being informed of the consequences."
]),
('mne', ("\u201CI-C-C-R-E-D-S\u201D \u2014 core patient rights",
         ["**I** \u2013 **I**nformation (and Records)",
          "**C** \u2013 **C**onsent (informed)",
          "**C** \u2013 **C**onfidentiality (and privacy, dignity)",
          "**R** \u2013 **R**efusal, and **R**edressal",
          "**E** \u2013 **E**mergency care",
          "**D** \u2013 **D**iscrimination-free, **D**ignity",
          "**S** \u2013 **S**econd opinion, **S**afety, and transparency of **S**cale of charges"])),

('h2', "5.5  Responsibilities / Duties of the Patient"),
('p', "A balanced answer must mention that the relationship carries obligations on **both** sides. Do not forget this section \u2014 it is often a separate 5-mark question."),
('n', [
    "**Provide accurate and complete information** \u2014 history, current medication, allergies, fasting status, previous reports.",
    "**Cooperate with the procedure** and follow instructions (fasting, timed samples, correct urine collection technique).",
    "**Follow the prescribed treatment** and keep appointments; inform if unable to attend.",
    "**Respect the staff** \u2014 not abusing, threatening or assaulting health-care workers (now an offence under various State Medicare Service Persons Acts and the Epidemic Diseases (Amendment) Act, 2020).",
    "**Respect other patients** \u2014 maintain the queue, keep silence, do not crowd, restrict the number of attendants.",
    "**Respect hospital property and rules** \u2014 no smoking, no spitting, no tampering with equipment.",
    "**Pay the agreed charges** promptly.",
    "**Not demand false certificates, false reports, or preferential treatment.**",
    "**Not offer bribes or gratification** to jump the queue or obtain a favour.",
    "**Take responsibility for his own decisions**, including a decision to refuse treatment.",
    "**Provide valid consent** and ask questions if anything is unclear.",
    "**Maintain confidentiality of other patients** whose information he may accidentally see or hear."
]),

('h2', "5.6  Duties of the Paramedic Towards the Patient"),
('h3', "A. Duties of Competence and Care"),
('b', [
    "**Duty of care** \u2014 to exercise a reasonable degree of skill, knowledge and care; the standard is that of an ordinary competent member of the profession (the *Bolam* standard).",
    "**Duty to practise within one's scope** and to refuse tasks beyond one's competence or authorisation.",
    "**Duty of accuracy** \u2014 correct identification, correct pre-analytical handling, correct analysis, correct transcription, correct reporting.",
    "**Duty of quality** \u2014 internal quality control, EQAS participation, calibration, method validation, maintenance.",
    "**Duty of timeliness** \u2014 defined turnaround times; immediate communication of critical values.",
    "**Duty to update knowledge** \u2014 continuing professional development.",
    "**Duty of safety** \u2014 biosafety, universal precautions, correct waste segregation and disposal, prevention of needle-stick injury."
]),
('h3', "B. Duties of Respect and Communication"),
('b', [
    "**Duty to obtain consent** and to respect refusal.",
    "**Duty of confidentiality and privacy.**",
    "**Duty of veracity** \u2014 honest reporting, honest disclosure of error and of delay.",
    "**Duty to explain** \u2014 procedure, preparation, timing, and where to collect the report.",
    "**Duty of courtesy and dignity** \u2014 greeting, using the name, screening for privacy, minimal exposure, gentleness.",
    "**Duty of non-discrimination** \u2014 equal service to all.",
    "**Duty of non-abandonment** \u2014 not leaving a procedure or a duty half-done.",
    "**Duty to refer / escalate** \u2014 to a senior, to another laboratory, or to the clinician when the matter is beyond one's role.",
    "**Duty of documentation** \u2014 complete, legible, contemporaneous records.",
    "**Duty to report** \u2014 notifiable diseases to the authority, adverse events to the institution, unsafe practice through proper channels."
]),
('h3', "C. Duties Towards the Employer, Colleagues and Society"),
('b', [
    "Loyal and honest service to the institution; care of equipment; no misuse of resources; no unauthorised private work using the institution's facilities.",
    "Respect and cooperation towards colleagues, nurses, clinicians and support staff; no criticism of a colleague before a patient.",
    "Supervision and fair teaching of juniors and students; no exploitation of trainees.",
    "Participation in quality, safety and infection-control programmes.",
    "Honest participation in public-health duties \u2014 disease notification, surveillance, outbreak investigation, blood-donation drives.",
    "Upholding the reputation of the profession in public and on social media.",
    "**Whistle-blowing** through proper channels where patients are being endangered or defrauded."
]),

('h2', "5.7  Building and Maintaining Trust and Rapport"),
('n', [
    "**First impression** \u2014 clean coat, visible identity badge, a greeting and a smile.",
    "**Introduce yourself by name and role** \u2014 the 'Hello, my name is\u2026' practice.",
    "**Use the patient's name** and correct honorific; pronounce it correctly.",
    "**Explain before you act** \u2014 no surprises, no unexplained needles.",
    "**Demonstrate competence** \u2014 confident, skilful, first-attempt technique; visible attention to labelling and to hand hygiene.",
    "**Be truthful** \u2014 about pain ('you will feel a sharp prick for about two seconds'), about delay, and about your own mistakes.",
    "**Keep promises** \u2014 if you say the report will be ready at 4 p.m., ensure it is, or inform the patient before 4 p.m. that it will not be.",
    "**Listen actively** \u2014 let the patient finish; acknowledge anxiety.",
    "**Protect privacy visibly** \u2014 draw the curtain, lower your voice, cover the screen; the patient must *see* that you protect secrets.",
    "**Show consistency and reliability** across every encounter and every patient.",
    "**Follow up** \u2014 if you promised to check something, come back and tell the patient the outcome.",
    "**Apologise sincerely** when something has gone wrong; an early, honest apology defuses far more complaints than any argument."
]),

('h2', "5.8  Professional Boundaries"),
('def', ("Professional boundary",
         "The limits that define the safe, therapeutic and professional space within which the professional\u2013patient relationship operates, and which protect the vulnerable party from exploitation of the power differential.")),
('tbl', (["Boundary issue", "Why it is a problem", "Correct practice"],
         [["**Romantic or sexual involvement with a patient**", "Gross exploitation of the power imbalance; a serious form of professional misconduct in every code", "Absolutely prohibited. Transfer care if a mutual personal attraction arises"],
          ["**Treating one's own family or close friends**", "Objectivity, confidentiality and the ability to ask sensitive questions are all compromised", "Best avoided for anything beyond the routine; refer to a colleague"],
          ["**Accepting gifts** from patients", "Creates obligation and the appearance of preferential treatment", "Politely decline anything of value; a small token of gratitude may be accepted where refusal would offend, and should be declared"],
          ["**Accepting commissions / 'cuts'** for referrals", "Corrupts clinical judgement; the patient pays for the kickback", "Absolutely prohibited (fee-splitting / dichotomy)"],
          ["**Lending or borrowing money**", "Creates dependence and conflict", "Never"],
          ["**Social-media friendship with patients**", "Blurs roles; endangers confidentiality", "Keep professional and personal accounts separate; do not accept patient requests on personal accounts"],
          ["**Self-disclosure**", "Excessive personal disclosure shifts focus to the professional", "Brief, purposeful disclosure only if it helps the patient"],
          ["**Religious or political proselytising**", "Exploits a captive, vulnerable audience", "Never; respect and never attempt to change a patient's beliefs"],
          ["**Giving medical advice or a diagnosis beyond one's role**", "Practising beyond competence; may cause harm and is legally indefensible", "Explain only the technical aspects; direct clinical questions to the treating doctor"]],
         [3.4, 6.6, 7.2],
         "Professional boundary violations \u2014 and the correct practice")),

('h2', "5.9  Difficult Situations and How to Handle Them"),
('tbl', (["Situation", "Professional approach"],
         [["**Patient refuses venepuncture**", "Explore the reason (fear, previous bad experience, religious objection); re-explain the necessity and the consequence of not testing; offer choices (position, site, a smaller needle, a different technologist, a later time); if the refusal persists, respect it, **document** it on the requisition and in the register, and **inform the clinician**"],
          ["**Difficult venous access**", "Do not make repeated blind attempts \u2014 a maximum of two attempts, then hand over to a more experienced colleague. Apologise for the discomfort. Repeated painful attempts are a breach of non-maleficence"],
          ["**Patient demands his report directly, but the clinician has asked to see it first**", "Legally the report belongs to the patient and he has a right to it; the humane course is to release it as per institutional policy while strongly encouraging him to have the doctor interpret it, and to inform the clinician. Never interpret a serious abnormal result yourself"],
          ["**Patient asks 'Is it cancer?' while looking at the slide**", "Do not speculate and do not deny. 'I can see the sample has been examined and the pathologist is preparing the report. Your doctor will explain exactly what it means \u2014 he will have it by this evening.' Then actually ensure it reaches the clinician"],
          ["**Relative demands another patient's result**", "Politely and firmly refuse; explain confidentiality; direct to the authorised channel; do not be pressured by seniority or influence"],
          ["**A VIP or a colleague asks to jump the queue**", "Explain the queue politely; genuine clinical urgency \u2014 not status \u2014 is the only basis for priority. Justice requires the same treatment for all"],
          ["**Patient offers money or a gift to hurry the report**", "Decline politely and firmly; explain the process; report persistent offers to the supervisor"],
          ["**Aggressive or intoxicated patient**", "Remain calm, keep a safe distance and a clear exit, do not argue or touch him, summon help and security, document the incident; your own safety comes first"],
          ["**Patient reveals something confidential and dangerous** (e.g. suicidal intent)", "Take it seriously; do not promise absolute secrecy; stay with the patient; inform the treating doctor and a senior immediately \u2014 the duty to prevent serious harm outweighs strict confidentiality"],
          ["**You have made an error affecting the patient**", "Inform the supervisor at once; correct the record; ensure the clinician and patient are told; apologise honestly; participate in root-cause analysis. **Never conceal.** Concealment converts an error into misconduct"],
          ["**Non-paying or very poor patient**", "Never let the ability to pay affect the quality or urgency of the service; guide him to the free-ward, welfare-fund or scheme counter"],
          ["**Language barrier**", "Use a trained interpreter, pictorial instruction cards or a bilingual colleague; do not rely on a random bystander for consent-related communication"]],
         [3.6, 13.6],
         "Difficult situations at the counter \u2014 rich material for any long answer")),

('h2', "5.10  Factors Affecting the Paramedic\u2013Patient Relationship"),
('tbl', (["Favourable factors \u2713", "Unfavourable factors \u2717"],
         [["Courtesy, warmth and a greeting", "Rudeness, indifference, not looking up"],
          ["Clear explanation and honest information", "Jargon, evasiveness, false reassurance"],
          ["Technical competence and confidence", "Repeated painful attempts, visible uncertainty, errors"],
          ["Privacy and confidentiality visibly protected", "Discussion of cases in public; open counters; loose talk"],
          ["Punctuality and reliable turnaround time", "Unexplained delays and broken promises"],
          ["Adequate time and unhurried manner", "Overwork, understaffing, assembly-line handling"],
          ["Cleanliness and professional appearance", "Untidy premises, stained coats, no identity badges"],
          ["Equity \u2014 same treatment for all", "VIP culture, queue-jumping, discrimination"],
          ["Transparent charges", "Hidden charges, overcharging, commissions"],
          ["Grievance mechanism that works", "No one to complain to; complaints ignored"],
          ["Cultural and gender sensitivity", "Insensitivity to modesty, religion or language"],
          ["Continuity \u2014 the same familiar staff", "Constant change of personnel; no accountability"]],
         [8.6, 8.6],
         "What builds and what destroys the relationship")),

('h2', "5.11  Termination of the Relationship"),
('b', [
    "The relationship normally ends when the **purpose is fulfilled** \u2014 the report has been issued and received.",
    "It may end by **mutual agreement**, by the **patient's own withdrawal**, on **referral** to another professional or institution, on **discharge**, or on **death**.",
    "A professional may withdraw **only** after giving the patient reasonable notice and reasonable opportunity to obtain the services of another professional, and after handing over adequate information \u2014 otherwise it is **abandonment**, which is both negligence and misconduct.",
    "Even after termination, the duties of **confidentiality** and of **record retention** continue \u2014 confidentiality survives the relationship and survives the patient's death.",
    "Grounds on which withdrawal may be legitimate: the patient's persistent non-cooperation, threats or violence, a request for something illegal or unethical, or a conflict of interest \u2014 but there must always be a **safe handover**, never an abrupt refusal in an emergency."
]),

('key', [
    "The relationship is **fiduciary** (trust-based) and **asymmetric** (unequal knowledge and power) \u2014 this is why the ethical burden falls on the professional.",
    "**Szasz & Hollender:** Activity\u2013Passivity (unconscious), Guidance\u2013Cooperation (acute illness), Mutual Participation (chronic illness).",
    "**Emanuel & Emanuel:** Paternalistic, Informative, Interpretive, **Deliberative (ideal)**.",
    "No single model fits every case \u2014 the model must match the patient's condition and capacity.",
    "India has a **Charter of Patients' Rights (NHRC / MoHFW, 2018)** \u2014 17 rights including information, records, emergency care, consent, confidentiality, second opinion, non-discrimination, transparency of rates, and redressal.",
    "The patient also has **duties**: accurate information, cooperation, respect for staff and other patients, payment, no demand for false reports.",
    "**Duty of non-abandonment:** once undertaken, care cannot be withdrawn without reasonable notice and a safe handover.",
    "**Professional boundaries** must be maintained \u2014 no sexual involvement, no gifts of value, no commissions, no money dealings, no treating one's own family for serious matters.",
    "Trust is built by **competence + honesty + respect + reliability + visible protection of privacy**.",
    "Regulation of paramedics in India: **National Commission for Allied and Healthcare Professions Act, 2021**."
]),

('tip', [
    "**Expected questions from this chapter:**",
    "- *Long (10 marks):* 'Describe the relationship between a paramedic and a patient. Discuss its nature, models, and the rights and duties of both parties.'",
    "- *Long (10 marks):* 'Enumerate the rights of a patient. What are the duties of a laboratory professional towards the patient?'",
    "- *Short (5 marks):* Models of the professional\u2013patient relationship; Patients' rights; Duties of a patient; Fiduciary relationship; Professional boundaries; Non-abandonment; How to build rapport.",
    "- *Very short (2 marks):* Meaning of 'paramedic'; what is a fiduciary relationship; name Szasz & Hollender's three models; two rights of a patient; which Act regulates allied health professionals in India.",
    "**Scoring tip:** the strongest answer here contains *four* elements \u2014 (i) the definition and fiduciary/asymmetric nature, (ii) the models table, (iii) rights **and** duties of both sides, (iv) two or three difficult-situation examples from the laboratory."
]),

('qa', ("QUESTION BANK \u2014 CHAPTER 5", [
    ("Define the paramedic\u2013patient relationship and describe its characteristics.",
     ["Definition as in section 5.1. Characteristics: fiduciary (trust-based); asymmetric/unequal in knowledge and power; contractual as well as ethical (a 'service' under the Consumer Protection Act, 2019); voluntary to begin but not freely terminable (non-abandonment); professional and not personal (boundaries); confidential; purposeful and time-limited; therapeutic in itself; culturally embedded; and legally accountable. *(Mnemonic: TRUST \u2014 Truthfulness, Respect, Understanding, Secrecy, Technical competence.)*"]),
    ("Describe the models of the professional\u2013patient relationship.",
     ["**Szasz & Hollender (1956):** Activity\u2013Passivity (professional acts on a wholly passive patient \u2014 unconscious, anaesthetised; analogy parent\u2013infant); Guidance\u2013Cooperation (professional guides, patient obeys \u2014 acute illness; parent\u2013adolescent); Mutual Participation (partnership \u2014 chronic disease; adult\u2013adult).",
      "**Emanuel & Emanuel (1992):** Paternalistic, Informative, Interpretive and Deliberative (the last regarded as ideal).",
      "Also mention priestly, engineering, collegial, contractual, covenantal and consumerist models. Conclude that the appropriate model depends on the patient's clinical condition and decision-making capacity."]),
    ("Enumerate the rights of a patient as per the Charter of Patients' Rights.",
     ["Information; records and reports; emergency medical care without advance payment; informed consent; confidentiality, dignity and privacy (including a chaperone); second opinion; transparency of rates and charging as per the displayed schedule; choice of pharmacy and diagnostic laboratory; non-discrimination; safety and quality care; treatment by a qualified person; protection in clinical trials and in biomedical research; discharge and the right of the next of kin to receive the body; patient education; and the right to be heard and to seek redressal; right to refuse treatment. *(Mnemonic: I-C-C-R-E-D-S.)*"]),
    ("What are the duties/responsibilities of a patient?",
     ["Give accurate and complete information; cooperate and follow instructions (fasting, timed samples, correct collection technique); keep appointments and follow treatment; respect the staff and refrain from abuse or violence; respect other patients and the queue; respect hospital property and rules; pay agreed charges; not demand false certificates or reports; not offer bribes; accept responsibility for his own decisions; give valid consent and ask questions when unclear; respect other patients' confidentiality."]),
    ("What is a fiduciary relationship? Why is the paramedic\u2013patient relationship fiduciary?",
     ["A fiduciary relationship is one in which one party places trust and confidence in another who has superior knowledge or power, and the latter is legally and ethically bound to act in the former's best interest rather than his own. The paramedic\u2013patient relationship is fiduciary because the patient cannot verify the quality of the service (whether the analyser was calibrated, whether the sample was correctly labelled) and must simply trust; he is also vulnerable, dependent, often frightened and must disclose intimate information. This trust generates the duties of competence, confidentiality, veracity and loyalty, and forbids exploitation of the relationship for personal gain."]),
    ("Write short notes on professional boundaries.",
     ["Definition as in section 5.8. Boundary violations: sexual or romantic involvement with a patient; treating one's own family for serious matters; accepting valuable gifts; accepting commissions or 'cuts'; lending or borrowing money; social-media friendship with patients; excessive self-disclosure; religious or political proselytising; giving clinical advice beyond one's role. Rationale: boundaries protect the vulnerable party from exploitation of the power differential and preserve objectivity. Consequence of violation: professional misconduct, loss of registration, civil and criminal liability."]),
    ("How will you handle a patient who refuses to give a blood sample?",
     ["Remain calm and do not show irritation; explore the reason (fear of needles, previous painful experience, religious objection, mistrust, misunderstanding about the volume of blood); re-explain the purpose of the test, what will be done and the consequence of not doing it; offer realistic choices \u2014 position, site, smaller-gauge needle, another technologist, a later time, presence of a relative; if the patient is competent and still refuses, **respect the refusal** \u2014 autonomy prevails; document the refusal on the requisition form and in the register with date, time and signature; **inform the treating clinician**; do not abandon the patient or become hostile; offer to help again if he changes his mind."]),
    ("What is abandonment? When may a professional lawfully withdraw from a case?",
     ["Abandonment is the unilateral termination of the professional relationship without the patient's consent and without reasonable notice or a safe handover, at a time when continuing care is still required. It amounts to negligence and professional misconduct. Lawful withdrawal requires: reasonable advance notice; a reasonable opportunity for the patient to obtain another professional; adequate transfer of information; and never withdrawal in an emergency. Legitimate grounds include persistent non-cooperation, threats or violence, a demand for something illegal or unethical, or a conflict of interest."]),
    ("List the factors that build and those that destroy the paramedic\u2013patient relationship.",
     ["Reproduce the two-column table \u2014 courtesy vs rudeness; clear explanation vs jargon and evasiveness; competence vs repeated painful attempts; visible privacy vs public discussion of cases; punctuality vs unexplained delay; adequate time vs assembly-line handling; cleanliness vs untidiness; equity vs VIP culture; transparent charges vs hidden costs; working grievance mechanism vs ignored complaints; cultural sensitivity vs insensitivity; continuity of staff vs constant change."]),
    ("A relative insists that you tell him another patient's HIV report. How will you respond?",
     ["Politely and firmly refuse. Explain that laboratory results are confidential and belong to the patient, that you are legally and ethically barred from disclosing them, and that this rule protects him and his family too. Do not disclose even partially and do not be influenced by his insistence, seniority or influence. Direct him to the treating doctor or to the authorised channel, i.e. the patient himself giving written authorisation. Note additionally that the **HIV/AIDS (Prevention and Control) Act, 2017** specifically prohibits disclosure of HIV status without the person's informed consent or a court order. Record the incident if the pressure is persistent, and inform the supervisor."]),
])),

('recap', [
    "Relationship = **fiduciary + asymmetric + contractual + confidential + non-abandonable**.",
    "**Szasz\u2013Hollender:** Activity\u2013Passivity | Guidance\u2013Cooperation | Mutual Participation.",
    "**Emanuel\u00b2:** Paternalistic | Informative | Interpretive | **Deliberative (best)**.",
    "Patient rights \u2192 **I-C-C-R-E-D-S**; patients have **duties** too.",
    "Trust = **TRUST** \u2014 Truthfulness, Respect, Understanding, Secrecy, Technical competence.",
    "Boundaries: no romance, no gifts of value, no cuts, no money, no family cases.",
    "Refusal \u2192 explore \u2192 re-explain \u2192 offer options \u2192 respect \u2192 **document** \u2192 inform clinician.",
    "Error \u2192 disclose, correct, apologise, analyse. **Never conceal.**",
]),

]
