# -*- coding: utf-8 -*-
"""Chapter 6 - How to Communicate Diagnostic Results and Confidentiality"""

BLOCKS = [

('ch', (6, "How to Communicate Diagnostic Results and Confidentiality",
        "Reporting \u2022 Critical values \u2022 Breaking bad news (SPIKES) \u2022 Confidentiality \u2022 Privileged communication \u2022 Exceptions")),

('h2', "6.1  Introduction"),
('p', "A laboratory report is not merely a number on paper \u2014 it is a **clinical intervention**. The moment a value is released it triggers decisions: a drug is given, a transfusion is started, an operation is cancelled, a marriage is called off, a job application is rejected. Therefore **how, to whom, when and in what form** a result is communicated is as ethically significant as the accuracy of the analysis itself. The two halves of this chapter are inseparable: results must reach the **right person quickly** (communication) and **nobody else, ever** (confidentiality)."),
('quote', ("The right result, on the right patient, at the right time, to the right person, with the right interpretation.", "the 'Five Rights' of laboratory reporting")),

('h2', "6.2  Principles of Communicating Diagnostic Results"),
('n', [
    "**Accuracy first** \u2014 never communicate a result you do not trust. Verify identity, check the QC status, look for pre-analytical problems (haemolysis, clot, wrong tube, insufficient volume, delay), and consider a repeat or a delta check against the previous value.",
    "**Right recipient** \u2014 results go to the **patient** and to the **authorised treating clinician**, and to nobody else without the patient's authorisation.",
    "**Right time** \u2014 within the defined turnaround time; **immediately** if the value is critical.",
    "**Right form** \u2014 preferably in **writing**, with all required elements; verbal or telephonic reporting only when urgency demands, and always with a **read-back** and documentation, followed by the written report.",
    "**Complete and interpretable** \u2014 with units, biological reference interval, method, specimen type, collection time and any comment on interference or limitation.",
    "**Confidential channel** \u2014 sealed envelope, password-protected portal, secure LIS. Never a public counter, never a personal WhatsApp number, never through the courier's hand to a neighbour.",
    "**Comprehensible** \u2014 to the intended recipient; a patient-facing report should avoid unnecessary jargon; a clinician-facing report may be technical.",
    "**Traceable** \u2014 who authorised, who released, who received, at what time; every communication must be documented.",
    "**Honest about limitations** \u2014 if the specimen was suboptimal, say so on the report; do not silently issue a doubtful result.",
    "**Sensitive** \u2014 the manner of communication must fit the seriousness of the news; grave results are conveyed by the treating clinician in a private setting, not read out at a counter.",
    "**Never interpret beyond your competence** \u2014 the technologist reports and flags; the clinician diagnoses.",
    "**Corrected reports** \u2014 if an error is discovered, actively recall the report, issue a clearly marked corrected report stating the reason, inform the clinician **personally**, retain the original in the record, and document the whole sequence."
]),
('mne', ("\u201CFive R's\u201D of reporting a result",
         ["**R**ight **result** (verified, QC-passed)",
          "**R**ight **patient** (two identifiers)",
          "**R**ight **time** (TAT / immediately for critical values)",
          "**R**ight **person** (patient or authorised clinician only)",
          "**R**ight **route** (written, secure, documented; verbal only with read-back)"])),

('h2', "6.3  Essential Contents of a Laboratory Report"),
('n', [
    "**Name and address of the laboratory**, and its accreditation status/number if applicable.",
    "**Unique report number** and page numbering ('Page 1 of 2').",
    "**Patient identification** \u2014 full name, age, sex, unique hospital/UHID number; ward and bed for inpatients.",
    "**Name of the referring clinician** and the referring institution.",
    "**Specimen type and site**, and any relevant condition (fasting/random, timed, first-void urine, left arm, etc.).",
    "**Date and time of collection**, of receipt in the laboratory, and of reporting.",
    "**Name of the test** in unambiguous full form.",
    "**Result with correct units** (SI units, with conventional units where locally used).",
    "**Biological reference interval** appropriate to the patient's age and sex, with any interpretive comment.",
    "**Method / technology used** where it affects interpretation (e.g. immunoassay platform, culture medium, PCR target).",
    "**Comments on specimen quality or interference** \u2014 haemolysed, lipaemic, icteric, clotted, insufficient, diluted, delayed transport.",
    "**Flags** for abnormal and for critical values.",
    "**Notes on limitations** and, for screening tests, the need for confirmation (e.g. 'reactive screening test \u2014 requires confirmation by a supplemental assay').",
    "**Name, qualification, designation and signature** of the person who verified and authorised the report.",
    "**Date and time of authorisation**; and, if amended, a clear statement that it is a **corrected/amended report** with the reason.",
    "A statement that the report relates only to the specimen received, and (where appropriate) that it is not valid for medico-legal purposes unless specified."
]),
('warn', ["**Reports that require special handling \u2014 do not treat these as routine:**",
          "- **HIV, hepatitis B/C, other STIs** \u2014 confidential handling; specific consent; pre- and post-test counselling; a *screening reactive* result must never be reported or spoken of as 'HIV positive'; it goes for confirmation as per the national testing algorithm.",
          "- **Genetic and prenatal tests** \u2014 counselling before and after; implications for family members; strict PC-PNDT compliance (**foetal sex must never be disclosed, even to the parents**).",
          "- **Malignancy on histopathology or cytology** \u2014 conveyed to the treating clinician, who breaks the news.",
          "- **Psychiatric and drug-abuse test results** \u2014 high stigma; strictest confidentiality.",
          "- **Pregnancy test in an unmarried or adolescent patient** \u2014 belongs to her alone; the technologist must not disclose it to family.",
          "- **Medico-legal and forensic samples** \u2014 chain of custody, sealed, released only to the authorised authority or on court direction.",
          "- **Notifiable diseases** \u2014 must be reported to the public-health authority; this is a lawful exception to confidentiality, not a breach of it."]),

('h2', "6.4  Critical Values (Panic Values / Alert Values)"),
('def', ("Critical value (Panic value)",
         "A laboratory result which represents a **pathophysiological state so far from normal that it is life-threatening** unless corrective action is taken quickly, and which therefore must be communicated to the responsible clinician **immediately, by telephone or in person**, irrespective of the hour, even before the written report is issued. The concept was introduced by **George D. Lundberg** in 1972.")),
('tbl', (["Analyte / Finding", "Typical critical limit (illustrative \u2014 each lab must define its own)"],
         [["Serum **potassium**", "< 2.8 or > 6.0\u20136.5 mmol/L"],
          ["Serum **sodium**", "< 120 or > 160 mmol/L"],
          ["Blood **glucose**", "< 40\u201345 or > 450\u2013500 mg/dL"],
          ["Serum **calcium**", "< 6.0 or > 13.0 mg/dL"],
          ["**Haemoglobin**", "< 6.0\u20137.0 g/dL (or a large unexplained fall)"],
          ["**Platelet count**", "< 20 \u00d7 10\u2079/L or > 1000 \u00d7 10\u2079/L"],
          ["**Total leucocyte count**", "< 1.0\u20132.0 \u00d7 10\u2079/L (neutropenia) or a blast crisis on the smear"],
          ["**INR / PT**", "INR > 5.0 (on anticoagulant)"],
          ["**Troponin**", "Any positive/raised value in a suspected acute coronary syndrome"],
          ["**Blood culture**", "Any **positive** blood culture, or a positive Gram stain"],
          ["**CSF findings**", "Any positive Gram stain, culture, or a raised cell count suggesting meningitis"],
          ["**Acid-fast bacilli**", "Newly detected AFB in sputum or CSF"],
          ["**Blood gas**", "pH < 7.2 or > 7.6; pO\u2082 < 40 mmHg"],
          ["**Malarial parasite**", "Detection of *P. falciparum*, especially with high parasitaemia"],
          ["**Crossmatch / blood bank**", "Incompatible crossmatch; a suspected transfusion reaction; positive antibody screen in pregnancy"],
          ["**Histopathology**", "Unexpected malignancy; frozen-section result during surgery"]],
         [4.6, 12.6],
         "Commonly designated critical values \u2014 quote three or four examples, not the whole list")),
('h3', "Protocol for Communicating a Critical Value \u2014 write this as a numbered protocol"),
('n', [
    "**Recognise** the value against the laboratory's approved critical-limit list (usually flagged by the LIS).",
    "**Verify** \u2014 confirm patient identity, check specimen integrity (haemolysis for potassium, drip-arm dilution for sodium, clot for platelets), check QC status, review the previous value (**delta check**), and **repeat the assay** if the SOP requires.",
    "**Notify immediately** \u2014 telephone the responsible clinician or the ward nurse in charge, without waiting for the printed report and without regard to the time of day. Target: usually **within 15\u201330 minutes** of the result being available.",
    "**Use a structured format** \u2014 SBAR; state patient name and identifier, the test, the value with units, and that it is a critical value.",
    "**Obtain a read-back** \u2014 ask the receiver to repeat the patient's name and the value back to you; correct any error.",
    "**Record the receiver's name and designation.**",
    "**Escalate if unsuccessful** \u2014 follow the written escalation ladder (duty doctor \u2192 senior resident \u2192 consultant \u2192 nursing supervisor \u2192 medical officer on call \u2192 hospital administrator on duty). Do not simply stop after one unanswered call.",
    "**Document fully** in the critical-value register or LIS: date, time the result was available, time of notification, value, name of the caller and of the receiver, read-back confirmation, and any action advised.",
    "**Retain the specimen** for possible repeat testing.",
    "**Issue the written report** promptly thereafter, with the critical flag.",
    "**Audit** \u2014 the laboratory should monitor the percentage of critical values notified within the target time as a **quality indicator** (NABL requirement)."
]),
('eg', ["**Why this matters \u2014 a real-world scenario for your answer:** A potassium of 7.4 mmol/L is reported into the LIS at 2.05 a.m. The technologist decides the printed report can wait for the morning round. The patient develops ventricular fibrillation at 3.40 a.m. and dies. On investigation, the laboratory had produced a **technically perfect result** which was **ethically and legally worthless** because it was never communicated. This is negligence by omission \u2014 and it is entirely preventable by a critical-value protocol."]),

('h2', "6.5  Verbal and Telephonic Reporting"),
('b', [
    "Permitted **only** for urgent/critical results, or when the LIS is down \u2014 never as the routine channel.",
    "**Identify yourself** (name, designation, laboratory) and **record** the name and designation of the receiver.",
    "Release verbal results **only to authorised health-care personnel** \u2014 never to a patient's relative, employer, insurer or an unidentified caller.",
    "**Never give results to an unverified telephone caller** claiming to be the patient; identity cannot be confirmed by telephone. Direct them to collect the report with proof of identity or through the secure portal.",
    "**Spell out numbers** to avoid error: 'seven point two \u2014 that is, seven, point, two'; avoid trailing zeros; state the units.",
    "**Read-back is mandatory** \u2014 the receiver repeats it; you confirm.",
    "**Document** the call immediately in the register/LIS.",
    "**Follow up with the written report** in every case.",
    "Never allow a **verbal report to substitute** for the written one in the case file."
]),

('h2', "6.6  Breaking Bad News"),
('def', ("Bad news",
         "Any information that seriously and adversely alters a person's view of his or her future \u2014 for example a diagnosis of cancer, HIV, chronic kidney failure, a genetic disorder, infertility, or the death of a relative.")),
('p', "Primary responsibility for breaking bad news rests with the **treating clinician**, not the laboratory. However, the technologist must (a) know the protocol, because it is examinable and because he may be present; and (b) know **what not to do** \u2014 never blurt out a serious result at the counter, never speculate, never let a patient read a distressing report unaccompanied in a corridor."),
('mne', ("\u201CSPIKES\u201D \u2014 the six-step protocol for breaking bad news (Baile & Buckman, 2000)",
         ["**S \u2013 SETTING up:** private room, sit down, no interruptions, switch off the phone, tissues available, allow the patient to have a relative present, arrange for enough time.",
          "**P \u2013 PERCEPTION:** find out what the patient already knows and believes \u2014 *'Before I tell you the report, may I ask what you understand about your illness so far?'* (\u2018ask before you tell\u2019).",
          "**I \u2013 INVITATION:** find out how much he wants to know \u2014 *'Would you like me to explain the full details of the report, or would you prefer that I explain the broad picture and the plan?'* (respects the **right to waive** information).",
          "**K \u2013 KNOWLEDGE:** give a **warning shot** (*'I am afraid the news is not what we had hoped for'*), pause, then deliver the information in **small chunks**, in plain language, avoiding jargon and bluntness; check understanding after each chunk.",
          "**E \u2013 EMOTIONS / EMPATHY:** respond to the reaction with **empathic statements** \u2014 observe the emotion, name it, identify its cause, and connect: *'I can see this is a great shock to you \u2014 anyone would feel that way.'* Allow **silence** and tears; do not rush to reassure falsely.",
          "**S \u2013 STRATEGY & SUMMARY:** summarise, present a clear plan (further tests, treatment options, referral, palliative support), check understanding, offer written information and a contact point, and arrange a follow-up meeting. **Never leave the patient without hope and without a plan.**"])),
('b', [
    "**Do:** be truthful; be gentle; use the words 'cancer' or 'died' clearly when necessary (euphemisms cause confusion); allow questions; offer a second appointment because little is retained after the first shock; involve the family with the patient's consent.",
    "**Don't:** break bad news on the telephone or in a corridor; give a prognosis in exact months; say 'there is nothing more we can do' (there is always symptom control and support); argue with denial; deceive the patient at the family's request when he has asked for the truth; use professional jargon.",
    "**Collusion:** the family's demand that 'do not tell him' must be handled by exploring their fears and by asking **the patient himself** how much he wants to know. The patient's right to information prevails over the family's wish, though the pace of disclosure may be adjusted compassionately."
]),

('h2', "6.7  Confidentiality \u2014 Meaning and Basis"),
('def', ("Confidentiality",
         "The **ethical and legal duty of a health-care professional not to disclose to any third party** the information about a patient which has come to his knowledge in the course of the professional relationship, **without the patient's valid consent** or a legally recognised justification. It also includes the duty to store, transmit and dispose of such information securely.")),
('def', ("Privileged Communication",
         "A communication made by a professional **in good faith, in discharge of a legal, social or moral duty, to the proper authority**, disclosing information which he would otherwise be bound to keep secret. It is a **valid, protected exception** to confidentiality \u2014 not a breach \u2014 provided it is made (i) in good faith, (ii) only to the *right authority*, and (iii) only to the *extent necessary*. *Example:* a laboratory notifying a case of cholera to the district health officer; informing the police of a suspected homicidal poisoning.")),
('h3', "Why Confidentiality Matters \u2014 Its Basis"),
('n', [
    "**Respect for autonomy** \u2014 the patient, not the professional, owns the information about his body.",
    "**Respect for privacy and dignity** \u2014 medical information is among the most intimate information a person has.",
    "**Non-maleficence** \u2014 disclosure causes real, severe and often irreversible harm: divorce, loss of employment, denial of insurance, social ostracism, violence, suicide.",
    "**Fidelity / implied promise** \u2014 the patient discloses on the understanding that it will be kept secret.",
    "**Utility / public health** \u2014 if confidentiality is not guaranteed, people will not come forward for testing (HIV, TB, mental illness), which harms the whole community. Confidentiality is therefore a **public-health tool**, not just a private courtesy.",
    "**Trust** \u2014 the entire fiduciary relationship collapses without it.",
    "**Legal obligation** \u2014 in India, privacy is a **fundamental right** under Article 21 (*K.S. Puttaswamy v. Union of India*, 2017); further protected by the HIV/AIDS Act 2017, the Mental Healthcare Act 2017, the Clinical Establishments Act 2010, the IT Act 2000 (s. 43A/72A) and the **Digital Personal Data Protection Act, 2023**; breach can also be a tort and professional misconduct."
]),
('h3', "What Is Covered by Confidentiality?"),
('b', [
    "**All** information: the diagnosis, all test results, the fact that the patient attended at all, his address and telephone number, his photograph, his images and slides, his genetic data, and even his death.",
    "Information **learned incidentally** \u2014 something overheard, something seen on another patient's file.",
    "Information about the patient's **family** learnt from him.",
    "It applies to **verbal, written, electronic, photographic and specimen-based** information.",
    "It binds **every** member of staff \u2014 technologists, phlebotomists, receptionists, data-entry operators, housekeeping, security, students and trainees.",
    "It **continues after** the professional relationship ends, and **survives the patient's death**.",
    "It applies **within** the hospital too \u2014 the fact that you work in the same institution does not entitle you to look up a colleague's or a celebrity's results. Access must be on a **need-to-know** basis only."
]),

('h2', "6.8  Exceptions to Confidentiality \u2014 When Disclosure Is Permitted"),
('p', "**This is the single most frequently asked question of the chapter.** Classify the exceptions \u2014 do not give a random list."),
('tbl', (["Category", "Exception", "Example"],
         [["**1. With consent**", "The patient's own valid, informed, preferably written authorisation", "Releasing a report to an employer, insurer or another hospital on the patient's written request"],
          ["**2. Within the care team**", "Sharing on a strict **need-to-know** basis with those actually involved in the patient's care", "Technologist \u2192 treating clinician; laboratory \u2192 blood bank for a crossmatch"],
          ["**3. Statutory duty \u2014 notification**", "**Notifiable diseases** must be reported to the public-health authority", "Cholera, plague, yellow fever, TB, measles, dengue, COVID-19 \u2014 as notified; also birth and death registration"],
          ["**4. Court order / legal process**", "Disclosure directed by a **court of law** or under a subpoena; evidence given in court", "Producing records in a consumer forum or criminal trial. *Note:* in India there is **no doctor\u2013patient testimonial privilege** \u2014 a professional **must** answer when directed by the court"],
          ["**5. Statutory reporting to police**", "Certain injuries and offences must be reported", "Suspected homicide or poisoning; custodial injury; a child-abuse case (**POCSO Act, 2012** \u2014 mandatory reporting); gunshot or acid-attack injury"],
          ["**6. Protection of an identifiable third party**", "Serious, imminent risk of harm to a specific person", "*Mr X v. Hospital Z* (1998) \u2014 disclosure of HIV status to a fianc\u00e9e held justified; an epileptic or visually impaired commercial driver; *Tarasoff* principle (USA) \u2014 duty to warn a threatened person"],
          ["**7. Public interest / public safety**", "Where the wider public interest clearly outweighs the individual's privacy", "An infectious food handler; an airline pilot with uncontrolled epilepsy; a serious communicable-disease outbreak"],
          ["**8. Statutory bodies and inspections**", "Disclosure to a statutory regulator exercising lawful powers", "Records produced before a Medical Council enquiry, drug inspector, or NABL assessor (identifiers minimised)"],
          ["**9. Incompetent patient / minor**", "Disclosure to the parent, guardian or lawful surrogate in the patient's best interest", "Informing the parent of a young child's blood report"],
          ["**10. Research, audit, teaching**", "Permitted only with ethics-committee approval and after **anonymisation**, or with consent", "Using archived data for a study; a case presentation with all identifiers removed"],
          ["**11. Employer-mandated examinations**", "Where the patient has agreed in advance to a report going to the employer \u2014 disclose only fitness/unfitness, not the full clinical detail", "Pre-employment medical examination"],
          ["**12. Insurance / statutory claims**", "On the insured's written authorisation, and limited to what is relevant", "Processing a mediclaim"],
          ["**13. To prevent a serious crime**", "Disclosure to the police where necessary to prevent or detect a grave offence", "Information about a planned act of violence"]],
         [2.9, 6.0, 8.3],
         "Exceptions to confidentiality \u2014 memorise the categories")),
('mne', ("\u201CC-O-U-R-T-S P-L-E-A-S-E\u201D \u2014 exceptions to confidentiality",
         ["**C** \u2013 **C**onsent of the patient",
          "**O** \u2013 **O**wn care team (need-to-know)",
          "**U** \u2013 **U**nder statute (notifiable diseases, POCSO, PC-PNDT records, births/deaths)",
          "**R** \u2013 **R**isk to an identifiable third party (*Mr X v. Hospital Z*; *Tarasoff*)",
          "**T** \u2013 **T**hird-party payers / insurers, with written authorisation",
          "**S** \u2013 **S**uspected crime \u2192 police reporting",
          "**P** \u2013 **P**ublic interest / public health",
          "**L** \u2013 **L**egal process \u2014 court order, subpoena, testimony",
          "**E** \u2013 **E**mployer-mandated examination (fitness only)",
          "**A** \u2013 **A**udit, research and teaching \u2014 anonymised, with ethics approval",
          "**S** \u2013 **S**tatutory bodies / regulators / inspectors",
          "**E** \u2013 **E**mergency, and incompetent patients (surrogate)"])),
('warn', ["**The golden rules of any lawful disclosure \u2014 apply all four:**",
          "- **1. Minimum necessary** \u2014 disclose only what is required for the purpose, to the smallest number of people.",
          "- **2. Right authority only** \u2014 to the person legally entitled, and to nobody else.",
          "- **3. Tell the patient** \u2014 wherever practicable, inform the patient that disclosure is being made and why (unless doing so would defeat the legal purpose).",
          "- **4. Document** \u2014 record what was disclosed, to whom, when, and under which authority.",
          "Additionally, remember the special statutory position of **HIV**: under the **HIV/AIDS (Prevention and Control) Act, 2017**, disclosure of a person's HIV status requires his **informed consent** or a **court order**; testing without informed consent and counselling is prohibited; and the Act creates a duty of **non-discrimination**. Do not answer an HIV confidentiality question without citing this Act."]),

('h2', "6.9  Common Breaches of Confidentiality in the Laboratory"),
('n', [
    "**Talking about a case** in the corridor, canteen, lift, bus or at home; discussing a 'funny' or 'interesting' case with friends.",
    "**Reports left lying** on an open counter, in an unsealed envelope, or given to whoever collects them without verifying identity.",
    "**Displaying results** on a public notice board or handing them out in a queue by calling out the diagnosis.",
    "**Shared or written-down LIS passwords**; an unlocked, unattended computer screen showing a result.",
    "**Sending results on personal WhatsApp** or to an unverified mobile number; photographing a report on a personal phone.",
    "**Posting on social media** \u2014 a photograph of a slide, a culture plate, a report, an unusual specimen, or a 'guess this diagnosis' post; even without a name, indirect identifiers can identify a patient.",
    "**Registers and requisition forms** left open to public view at the collection counter.",
    "**Discussing a patient in front of another patient** at the collection counter.",
    "**Curiosity browsing** \u2014 looking up the results of a celebrity, a colleague, a neighbour or a relative in the LIS without any care role.",
    "**Improper disposal** \u2014 discarded printouts and requisition slips in an open bin, or used as scrap paper.",
    "**Telling the family** a result the patient has not authorised them to receive, or 'helpfully' informing a spouse.",
    "**Loose talk about the fact of attendance** \u2014 even saying 'yes, she came for a test yesterday' is a breach.",
    "**Careless verbal handover** within earshot of visitors."
]),

('h2', "6.10  Measures to Maintain Confidentiality"),
('h3', "A. Administrative Measures"),
('b', [
    "A **written confidentiality policy** and a signed **confidentiality undertaking** by every employee, student and trainee at induction.",
    "**Training and periodic refreshers** for all staff, including housekeeping and security.",
    "**Access control on a need-to-know basis**, with defined authorisation levels.",
    "**Defined SOP for report release** \u2014 who may collect a report, with what proof of identity, and how results are given by telephone (i.e., not at all, to unverified callers).",
    "**Audit of access logs** and disciplinary action for unauthorised browsing.",
    "**Record-retention and secure-destruction policy** \u2014 shredding, not scrap paper.",
    "A **breach-response protocol** \u2014 report, contain, inform the patient, investigate, correct the system."
]),
('h3', "B. Physical Measures"),
('b', [
    "A **private cubicle or curtained area** for sample collection and for any discussion.",
    "**Sealed envelopes** for reports; separate, discreet handling of sensitive reports.",
    "**Locked cabinets** for registers and records; restricted entry to the reporting area.",
    "Registers and monitors **turned away from public view**; privacy screens on monitors.",
    "**Shredders** and covered, secure bins for confidential waste.",
    "**Anonymised labelling** where appropriate (barcodes rather than diagnoses written on the tube). **Never** write 'HIV +ve' or a biohazard warning naming the disease on the specimen container or the request form \u2014 use universal precautions for all specimens instead."
]),
('h3', "C. Technical / Electronic Measures"),
('b', [
    "**Unique individual login and strong passwords**, never shared; automatic screen lock and session timeout.",
    "**Role-based access rights** in the LIS/HIS, with a full **audit trail** of who viewed and modified what.",
    "**Encryption** of stored and transmitted data; secure patient portals rather than email or messaging apps.",
    "**Regular backups** held securely, and controlled data-transfer policies.",
    "**No patient-identifiable data on personal devices**, personal email or personal cloud storage.",
    "**Anonymisation or pseudonymisation** of data used for audit, research and teaching.",
    "Compliance with the **Digital Personal Data Protection Act, 2023** and the IT Act \u2014 health data is sensitive personal data requiring heightened protection."
]),
('h3', "D. Personal / Behavioural Measures"),
('b', [
    "**Never discuss patients outside the workplace**, and never within earshot of anyone who does not need to know.",
    "**Lower your voice** at the counter and on the telephone.",
    "**Verify identity** before handing over any report.",
    "**Refuse politely but firmly** \u2014 practise a standard sentence: *'I am sorry, I am not permitted to give results to anyone except the patient or the treating doctor. Please ask the patient to collect it or authorise you in writing.'*",
    "**Zero social-media posting** about work, patients, specimens or reports.",
    "**Log out** every time you leave the terminal.",
    "**Treat every specimen as infectious and every result as secret** \u2014 then no patient is singled out."
]),

('h2', "6.11  Consequences of Breach of Confidentiality"),
('tbl', (["Type of consequence", "Details"],
         [["**Harm to the patient**", "Stigma, ostracism, divorce or broken engagement, loss of employment, denial of insurance, violence, depression and suicide"],
          ["**Loss of trust**", "The individual patient and the community stop coming forward for testing \u2014 a public-health harm"],
          ["**Civil liability**", "Suit for damages for breach of confidence and for violation of the right to privacy; compensation before a consumer forum"],
          ["**Criminal / statutory liability**", "Penalties under the HIV/AIDS Act 2017, the Mental Healthcare Act 2017, PC-PNDT (for disclosing foetal sex), IT Act s. 72A, and the Digital Personal Data Protection Act 2023"],
          ["**Professional / disciplinary action**", "Warning, suspension, termination of employment, and removal of the name from the professional register"],
          ["**Institutional consequences**", "Loss of NABL/NABH accreditation, loss of reputation, adverse publicity, financial loss"],
          ["**Constitutional dimension**", "Privacy is a fundamental right under Article 21 (*K.S. Puttaswamy*, 2017); breach is a violation of that right"]],
         [4.0, 13.2],
         "Consequences of breaching confidentiality")),
('eg', ["**Landmark case to quote \u2014 *Mr X v. Hospital Z* (Supreme Court of India, 1998):** A hospital disclosed a patient's HIV-positive status, as a result of which his proposed marriage was called off. The Supreme Court held that although the duty of confidentiality exists, **the fianc\u00e9e's right to be informed of a life-threatening risk outweighed the patient's right to secrecy in this instance**, so the disclosure was not actionable. The case is the standard Indian authority for the **'risk to an identifiable third party'** exception. *Note for a complete answer:* the position must now be read together with the **HIV/AIDS (Prevention and Control) Act, 2017**, which requires informed consent or a court order for disclosure of HIV status, so the practical route today is intensive counselling of the patient to disclose voluntarily, and recourse to the statutory mechanism where he refuses."]),

('key', [
    "The **Five R's of reporting:** right result, right patient, right time, right person, right route.",
    "A report must contain patient identifiers, specimen type, collection/receipt/report times, result **with units and reference interval**, method, comments on interference, and the **signature of the authorising person**.",
    "**Critical (panic) value** = a result so abnormal as to be life-threatening; must be telephoned **immediately** with a **read-back** and full documentation; concept introduced by **Lundberg (1972)**.",
    "Critical-value protocol: recognise \u2192 verify \u2192 notify at once \u2192 SBAR \u2192 **read-back** \u2192 record the receiver \u2192 escalate if unreachable \u2192 document \u2192 retain specimen \u2192 issue written report \u2192 audit.",
    "**Breaking bad news = SPIKES** \u2014 Setting, Perception, Invitation, Knowledge, Emotions/Empathy, Strategy & Summary. Give a **warning shot**, use small chunks, allow silence, always end with a plan.",
    "**Confidentiality** covers *everything*, including the mere fact of attendance; it binds **all** staff; it **survives death**; access is strictly **need-to-know**.",
    "**Privileged communication** = disclosure in good faith, to the proper authority, to the extent necessary \u2014 a lawful exception, not a breach.",
    "Exceptions: **consent, care team, statute/notification, court order, police reporting, risk to a third party, public interest, statutory bodies, surrogate for the incompetent, anonymised research, employer examination, insurance.**",
    "Any lawful disclosure must be: **minimum necessary + right authority + patient informed + documented.**",
    "Indian law: **Article 21 / *K.S. Puttaswamy* (2017)** \u2014 privacy is a fundamental right; **HIV/AIDS Act 2017**; **Mental Healthcare Act 2017**; **POCSO 2012** (mandatory reporting); **DPDP Act 2023**; **PC-PNDT 1994**.",
    "Key case: ***Mr X v. Hospital Z* (1998)** \u2014 third-party risk can justify disclosure of HIV status."
]),

('tip', [
    "**Expected questions from this chapter:**",
    "- *Long (10 marks):* 'What is confidentiality? Discuss its importance, the exceptions to it, and the measures to maintain it in a clinical laboratory.'",
    "- *Long (10 marks):* 'How should diagnostic results be communicated? Describe the protocol for reporting a critical value and the SPIKES protocol for breaking bad news.'",
    "- *Short (5 marks):* Critical/panic values; Privileged communication; SPIKES; Exceptions to confidentiality; Contents of a laboratory report; Breaches of confidentiality in a laboratory; *Mr X v. Hospital Z*.",
    "- *Very short (2 marks):* Define critical value; expand SPIKES; two exceptions to confidentiality; who introduced the concept of critical values; what is a read-back; does confidentiality end with death (answer: **no**).",
    "**Scoring tip:** in the confidentiality answer, always (i) define it, (ii) give the ethical **and** legal basis, (iii) classify the exceptions in a table, (iv) list the four golden rules of lawful disclosure, (v) cite **Article 21/Puttaswamy, the HIV Act 2017 and *Mr X v. Hospital Z***, and (vi) list the administrative/physical/technical/personal safeguards. That is a guaranteed full-marks structure."
]),

('qa', ("QUESTION BANK \u2014 CHAPTER 6", [
    ("Define confidentiality. Discuss its ethical and legal basis.",
     ["Definition as in section 6.7. Ethical basis: respect for autonomy (the information belongs to the patient); privacy and dignity; non-maleficence (disclosure causes stigma, divorce, job loss, violence, suicide); fidelity and the implied promise of secrecy; utility \u2014 without a guarantee of secrecy people avoid testing, which harms public health; and trust, without which the fiduciary relationship collapses.",
      "Legal basis in India: **Article 21** \u2014 privacy is a fundamental right (*K.S. Puttaswamy v. Union of India*, 2017); **HIV/AIDS (Prevention and Control) Act, 2017**; **Mental Healthcare Act, 2017**; **Clinical Establishments Act, 2010**; **IT Act, 2000** (ss. 43A, 72A); **Digital Personal Data Protection Act, 2023**; and the IMC Regulations, 2002. Breach may give rise to civil damages, statutory penalty and professional disciplinary action."]),
    ("Enumerate the exceptions to confidentiality with examples.",
     ["Reproduce the classified table: consent of the patient; sharing within the care team on a need-to-know basis; statutory notification (notifiable diseases, births and deaths); court order, subpoena and testimony (note: **no doctor\u2013patient privilege in Indian evidence law**); mandatory police/statutory reporting (suspected homicide or poisoning, POCSO child abuse); serious risk to an identifiable third party (*Mr X v. Hospital Z*, 1998; the *Tarasoff* duty to warn); public interest and public safety (infectious food handler, unfit pilot or driver); statutory bodies and inspectors; surrogate disclosure for minors and incompetent patients; anonymised use for audit, research and teaching with ethics approval; employer-mandated examinations (fitness only); insurance claims on written authorisation; prevention of a serious crime.",
      "Conclude with the four golden rules: **minimum necessary, right authority only, inform the patient where practicable, document the disclosure.**"]),
    ("What is a critical value? Describe the protocol for its communication.",
     ["Definition as in section 6.4 (Lundberg, 1972), with three or four examples \u2014 potassium > 6.5 mmol/L, glucose < 40 mg/dL, platelets < 20 \u00d7 10\u2079/L, a positive blood culture, an incompatible crossmatch.",
      "Protocol: recognise against the approved list \u2192 verify identity, specimen integrity, QC and delta check, repeat if the SOP requires \u2192 telephone the responsible clinician **immediately**, irrespective of the hour, target 15\u201330 minutes \u2192 use **SBAR** \u2192 obtain a **read-back** \u2192 record the receiver's name and designation \u2192 **escalate** if unreachable, following the written ladder \u2192 document date, time, value, caller, receiver and read-back \u2192 retain the specimen \u2192 issue the written report \u2192 audit the notification time as a quality indicator."]),
    ("Explain the SPIKES protocol for breaking bad news.",
     ["**S \u2013 Setting:** private, seated, uninterrupted, adequate time, relative present if the patient wishes. **P \u2013 Perception:** ask what the patient already knows. **I \u2013 Invitation:** ask how much he wants to be told (respect a waiver). **K \u2013 Knowledge:** give a **warning shot**, then information in small chunks, in plain language, checking understanding. **E \u2013 Emotions/Empathy:** name and acknowledge the emotion, allow silence and tears, avoid false reassurance. **S \u2013 Strategy and Summary:** summarise, give a clear plan, offer written information and a contact, arrange follow-up. Add the do's and don'ts and the handling of family 'collusion'."]),
    ("What is privileged communication? Give two examples.",
     ["Definition as in section 6.7. Requirements: made in **good faith**, to the **proper authority**, and only to the **extent necessary**. Examples: notifying a case of cholera or tuberculosis to the district health authority; informing the police of a suspected homicidal poisoning or a case of child sexual abuse under POCSO; informing a spouse at real risk of HIV infection after counselling has failed; informing the transport authority about a driver with uncontrolled epilepsy. It is a **lawful exception** and therefore not a breach of confidentiality."]),
    ("List the essential contents of a laboratory report.",
     ["Laboratory name and accreditation details; unique report number and page numbering; patient identification (name, age, sex, UHID, ward/bed); referring clinician; specimen type, site and condition; date and time of collection, receipt and reporting; full name of the test; result with correct units; biological reference interval; method where relevant; comments on specimen quality and interference; flags for abnormal and critical values; limitations and the need for confirmation where applicable; name, qualification, designation and signature of the authorising person with date and time; and a clear marking if it is a corrected or amended report."]),
    ("Enumerate the common breaches of confidentiality in a laboratory and the measures to prevent them.",
     ["Breaches: corridor and canteen discussion; reports left on an open counter or handed to an unverified person; results announced in a queue; shared passwords and unlocked screens; sending results on personal WhatsApp; **social-media posts** of slides, plates or reports; open registers at the counter; curiosity browsing of a celebrity's or colleague's results; improper disposal of printouts; informing the family without authorisation; even confirming that the patient attended.",
      "Measures, classified as **administrative** (written policy, signed undertaking, training, need-to-know access, report-release SOP, access audit, retention and destruction policy, breach-response protocol); **physical** (private collection cubicle, sealed envelopes, locked cabinets, monitors turned away, shredders, no disease names on tubes); **technical** (unique logins, role-based access, audit trails, encryption, secure portals, no data on personal devices, anonymisation, DPDP Act compliance); and **personal** (no discussion outside work, lowered voice, identity verification, a firm refusal sentence, no social-media posting, log out every time)."]),
    ("Discuss the case of Mr X v. Hospital Z and its significance.",
     ["Facts and holding as in the box in section 6.10: the Supreme Court of India held in 1998 that disclosure of the patient's HIV-positive status to his fianc\u00e9e was justified because her right to be informed of a life-threatening risk outweighed his right to confidentiality. Significance: it is the leading Indian authority for the **third-party-risk exception** to confidentiality and for the 'duty to warn'. Qualification: it must now be read with the **HIV/AIDS (Prevention and Control) Act, 2017**, under which disclosure of HIV status requires informed consent or a court order; the correct present-day approach is intensive counselling to secure voluntary disclosure, with recourse to the statutory mechanism if the patient refuses."]),
    ("A telephone caller says he is the patient and asks for his HIV result. What will you do?",
     ["Do **not** disclose. Identity cannot be verified on the telephone, and an HIV result requires face-to-face post-test counselling. Explain politely that results of this test are given only in person; ask him to come with photo identity, or to use the secure patient portal if the laboratory has one; offer an appointment time and, if he is anxious, offer to arrange counselling. Record the call. Note that under the HIV/AIDS Act, 2017 disclosure requires the person's informed consent and that a screening-reactive result must never be reported as 'HIV positive' before confirmation as per the national testing algorithm."]),
    ("Why must a screening-reactive HIV test never be reported as 'positive'?",
     ["Because a single screening assay has high sensitivity but lower specificity, so false-reactive results occur (pregnancy, autoimmune disease, recent vaccination, technical error). The national testing algorithm requires **confirmation with additional assays of different antigen/principle** before a diagnosis is made. Reporting a screening reactive as 'HIV positive' can cause catastrophic, irreversible social harm \u2014 a breach of non-maleficence \u2014 and may amount to negligence. The correct report reads 'reactive on screening \u2014 requires confirmation', with post-test counselling and referral to the designated confirmatory centre."]),
])),

('recap', [
    "**Five R's:** right result, patient, time, person, route.",
    "**Critical value** \u2192 phone **immediately** \u2192 SBAR \u2192 **read-back** \u2192 record receiver \u2192 escalate \u2192 document. (Lundberg, 1972.)",
    "**SPIKES** = Setting, Perception, Invitation, Knowledge, Emotions, Strategy. Warning shot + small chunks + silence + a plan.",
    "Confidentiality covers **everything, binds everyone, survives death**; access is **need-to-know**.",
    "Exceptions \u2192 consent, care team, statute/notification, court, police, third-party risk, public interest, regulators, surrogate, anonymised research, employer, insurer.",
    "Every disclosure \u2192 **minimum + right authority + tell the patient + document**.",
    "Law: **Article 21 / Puttaswamy 2017**; **HIV Act 2017**; **POCSO 2012**; **DPDP Act 2023**; ***Mr X v. Hospital Z* 1998**.",
    "Never: corridor talk, open counters, shared passwords, WhatsApp results, social-media posts.",
]),

]
