# -*- coding: utf-8 -*-
"""Chapter 7 - Negligence, Malpractice, Legal Implications and Law Suits"""

BLOCKS = [

('ch', (7, "Negligence, Malpractice, Legal Implications and Law Suits in Medical Practice",
        "Negligence \u2022 4 D's \u2022 Types \u2022 Res ipsa loquitur \u2022 Vicarious liability \u2022 Defences \u2022 Consent \u2022 Documentation")),

('h2', "7.1  Introduction"),
('p', "Health care is one of the most heavily litigated fields in the world. In India, the number of complaints against hospitals and diagnostic laboratories has risen sharply since the **Supreme Court held in *Indian Medical Association v. V.P. Shantha* (1995)** that medical services fall within the definition of 'service' under the Consumer Protection Act, making doctors and laboratories answerable before consumer forums. A laboratory professional must therefore understand not only what is *ethically* wrong but what is *legally actionable*."),
('p', "The reassuring point, which you should state in your conclusion, is that **the law does not demand perfection \u2014 it demands reasonable care**. A professional who follows the SOP, documents properly, communicates honestly and stays within his competence is very well protected, even if an unfortunate outcome occurs."),

('h2', "7.2  Basic Legal Vocabulary"),
('tbl', (["Term", "Meaning"],
         [["**Law**", "A body of rules made or recognised by the State and enforced by its authority"],
          ["**Civil law**", "Governs disputes between private parties; the remedy is **compensation (damages)** or an injunction; standard of proof: **preponderance of probability**"],
          ["**Criminal law**", "Governs offences against the State/society; the remedy is **punishment** (fine, imprisonment); standard of proof: **beyond reasonable doubt**"],
          ["**Tort**", "A civil wrong (other than breach of contract) for which the remedy is an action for unliquidated damages \u2014 negligence is a tort"],
          ["**Liability**", "Legal responsibility for one's acts or omissions"],
          ["**Damages**", "Monetary compensation awarded to the injured party"],
          ["**Plaintiff / Complainant**", "The person who brings the action"],
          ["**Defendant / Respondent**", "The person against whom the action is brought"],
          ["**Burden of proof**", "The obligation to prove one's allegation \u2014 normally on the complainant"],
          ["**Vicarious liability**", "Liability of an employer for the wrongful acts of his employee committed in the course of employment"],
          ["**Limitation period**", "The time within which a suit must be filed \u2014 **2 years** for a consumer complaint from the date the cause of action arose (condonable for sufficient cause)"],
          ["**Medical jurisprudence**", "The application of law to medical practice \u2014 the legal duties and rights of medical practitioners"],
          ["**Medical ethics vs medical law**", "Ethics = what one *ought* to do; law = what one *must* do"]],
         [3.6, 13.6],
         "Legal terms you must be able to define")),

('h2', "7.3  Negligence"),
('def', ("Negligence",
         "Negligence is the **omission to do something which a reasonable man, guided by those ordinary considerations which ordinarily regulate human affairs, would do, or the doing of something which a reasonable and prudent man would not do**. In law it is the **breach of a duty of care** which results in damage to the person to whom that duty is owed.")),
('def', ("Medical / Professional Negligence",
         "The failure of a medical or paramedical professional to exercise the **reasonable degree of skill, knowledge and care** ordinarily expected of an average member of that profession in the circumstances, resulting in **injury or damage** to the patient.")),
('h3', "The Four Essential Elements \u2014 The '4 D's' of Negligence"),
('p', "**The complainant must prove all four.** If even one fails, the claim fails. This is the single most important thing to write in any negligence answer."),
('tbl', (["#", "Element", "What must be proved", "Laboratory illustration"],
         [["**1**", "**Duty** \u2014 a duty of care was owed", "That a professional relationship existed and the defendant owed the patient a duty to exercise reasonable care", "The laboratory accepted the sample and the fee \u2014 a duty of care arose"],
          ["**2**", "**Dereliction / Deviation** \u2014 breach of that duty", "That the defendant fell below the standard of an ordinary competent professional (deviation from the accepted standard of practice/SOP)", "The tube was not labelled at the bedside; samples of two patients were interchanged"],
          ["**3**", "**Direct causation** \u2014 the breach caused the damage", "A direct and proximate causal link between the breach and the injury (*causa causans*); the 'but-for' test", "Because of the interchange, the patient received a transfusion of the wrong blood group"],
          ["**4**", "**Damage** \u2014 actual harm resulted", "Actual legally recognisable damage \u2014 physical, mental, or financial. **No damage, no negligence** in tort", "The patient suffered an acute haemolytic transfusion reaction and renal failure"]],
         [0.7, 3.0, 7.0, 6.5],
         "The 4 D's of negligence \u2014 draw this table in every negligence answer")),
('mne', ("\u201C4 D's\u201D and their alternative names",
         ["**D**uty \u2014 duty of care owed",
          "**D**ereliction \u2014 breach / deviation from the standard of care",
          "**D**irect causation \u2014 proximate cause; the 'but-for' test",
          "**D**amage \u2014 actual injury suffered",
          "*(Some textbooks state them as: **Duty, Breach, Causation, Damages** \u2014 the same four elements.)*"])),

('h3', "The Standard of Care \u2014 The *Bolam* Test"),
('def', ("Bolam Test (Bolam v. Friern Hospital Management Committee, 1957)",
         "A professional is **not negligent if he has acted in accordance with a practice accepted as proper by a responsible body of professional opinion skilled in that particular art**, even if other professionals would have acted differently. The standard is that of the **ordinary competent practitioner**, not of the most eminent expert.",
         ["Applied in India in ***Jacob Mathew v. State of Punjab* (2005)**, which laid down that a professional may be held liable for negligence only if (i) he did not possess the requisite skill which he professed to have, **or** (ii) he did not exercise, with reasonable competence, the skill which he did possess.",
          "***Bolitho* qualification (1997):** the accepted practice relied upon must itself withstand **logical analysis** \u2014 a common practice that is indefensible cannot excuse negligence."])),
('warn', ["**Things the law does NOT require \u2014 state these to show understanding:**",
          "- The law does **not** require the **highest** or most expert level of skill \u2014 only reasonable, average competence.",
          "- The law does **not** guarantee a **cure or a successful outcome**. A bad outcome is not proof of negligence.",
          "- A mere **error of judgement** is not necessarily negligence \u2014 provided reasonable care and skill were exercised in reaching the judgement.",
          "- A difference of professional opinion is not negligence.",
          "- **But:** ignorance of a basic, elementary procedure, failure to follow the SOP, or acting beyond one's competence **is** negligence."]),

('h2', "7.4  Types / Classification of Negligence"),
('tbl', (["Type", "Meaning", "Example"],
         [["**Civil negligence**", "Ordinary negligence giving rise to a claim for **compensation**; proof on the balance of probabilities", "A wrongly reported blood sugar leading to an unnecessary hospital admission"],
          ["**Criminal negligence**", "Negligence so **gross, reckless and of such a high degree** as to show disregard for human life or safety; punishable under the **Bharatiya Nyaya Sanhita, 2023 (earlier IPC s. 304A)** \u2014 causing death by a rash or negligent act", "Transfusing blood without any crossmatch, causing death; reporting a fabricated HIV result on which a transfusion was based"],
          ["**Contributory negligence**", "Negligence **on the part of the patient himself** which contributes to his own injury \u2014 it reduces (or in some jurisdictions defeats) the compensation", "The patient did not fast despite clear written instructions; concealed his medication; failed to return for a repeat test or to collect the report"],
          ["**Composite negligence**", "Two or more persons are jointly negligent towards the patient; each is fully liable", "The ward nurse mislabels the tube **and** the laboratory releases the result without verifying identity"],
          ["**Corporate / institutional negligence**", "Negligence of the institution itself \u2014 in employing unqualified staff, providing defective equipment, inadequate staffing or absent protocols", "A hospital employing an untrained person as a technologist; a laboratory running an uncalibrated analyser with no QC programme"],
          ["**Vicarious liability**", "The employer is held liable for the negligent act of the employee committed **in the course of employment** \u2014 *qui facit per alium facit per se* ('he who acts through another acts himself'); also called the doctrine of ***respondeat superior***", "The hospital is liable for a mislabelled sample by its technologist; the pathologist/laboratory owner is liable for his technician's error"],
          ["**Negligence per se**", "Breach of a statutory duty which itself establishes negligence", "Performing a prenatal sex-determination test in breach of the PC-PNDT Act"],
          ["**Therapeutic misadventure**", "Injury caused by treatment given in good faith and with due care \u2014 **not** negligence", "An unforeseeable anaphylactic reaction to a contrast agent despite proper history-taking and precautions"],
          ["**Novus actus interveniens**", "A new, independent intervening act breaks the chain of causation and relieves the original actor of liability", "A correct report is issued, but the ward transcribes it wrongly into the chart"]],
         [3.2, 6.8, 7.2],
         "Types of negligence \u2014 a very common 5-mark or 10-mark question")),

('h2', "7.5  Malpractice"),
('def', ("Malpractice (Malpraxis)",
         "**Improper, illegal, unethical or negligent professional activity or treatment** by a person holding himself out as a professional, resulting in injury, loss or damage to the patient. Malpractice is a broader term than negligence: it includes negligence **and also** intentional wrongdoing, dishonesty, and practice outside one's competence or licence.")),
('tbl', (["Basis", "Negligence", "Malpractice", "Professional Misconduct"],
         [["Meaning", "Failure to exercise reasonable care", "Improper, illegal or unethical professional conduct causing harm \u2014 includes negligence", "Conduct disgraceful or dishonourable to the profession"],
          ["Intention", "**Unintentional** \u2014 carelessness", "May be **intentional or unintentional**", "Usually intentional"],
          ["Who can commit it", "Anyone", "Only a **professional**, in his professional capacity", "Only a registered professional"],
          ["Harm to patient", "Essential \u2014 no damage, no claim", "Usually present", "**Not essential** (e.g. advertising, false certificate)"],
          ["Forum / consequence", "Civil suit or consumer complaint \u2192 compensation", "Civil, criminal and disciplinary action", "Council enquiry \u2192 warning, suspension, **erasure of name**"],
          ["Example", "A sample mix-up due to carelessness", "Performing a test one is not qualified to perform; 'dry labbing' a result", "Advertising, cut practice, breach of confidentiality, false certificate"]],
         [2.4, 4.8, 5.2, 4.8],
         "Negligence vs Malpractice vs Misconduct \u2014 the most commonly confused triad")),
('h3', "Common Examples of Malpractice in a Diagnostic Laboratory"),
('n', [
    "**Dry labbing** \u2014 issuing a report for a test that was never performed. Fraud plus malpractice.",
    "**Falsifying, altering or back-dating** results or records.",
    "**Reporting without QC** \u2014 releasing results when internal quality control has failed.",
    "**Sample mix-up / wrong labelling** \u2014 the classic cause of a fatal transfusion reaction.",
    "**Using expired or improperly stored reagents and kits.**",
    "**Using uncalibrated, unmaintained or unvalidated equipment.**",
    "**Performing tests without the required qualification, licence or accreditation** \u2014 or allowing an unqualified person to sign reports.",
    "**Signing a report one has not verified** (rubber-stamp reporting; the 'absentee pathologist').",
    "**Failure to communicate a critical value.**",
    "**Failure to inform of a suboptimal specimen** and reporting a doubtful result as valid.",
    "**Breach of confidentiality.**",
    "**Performing a test without valid consent** \u2014 notably HIV testing.",
    "**Prenatal sex determination or disclosure** \u2014 criminal under PC-PNDT.",
    "**Cut practice / fee-splitting** \u2014 paying or receiving commissions for referrals.",
    "**Unnecessary or duplicated tests** ordered or encouraged for profit; overcharging.",
    "**Improper biomedical waste disposal**, endangering the public.",
    "**Failure to maintain records**, or destruction of records.",
    "**Abandonment** \u2014 leaving a procedure or duty incomplete."
]),

('h2', "7.6  Res Ipsa Loquitur"),
('def', ("Res ipsa loquitur",
         "A Latin maxim meaning **'the thing speaks for itself'**. Where the accident or injury is of such a nature that it could not ordinarily have happened without negligence, and the thing that caused it was under the exclusive control and management of the defendant, negligence is **presumed** and the **burden of proof shifts to the defendant** to show that he was not negligent. The complainant is then relieved of the need to lead expert evidence.")),
('h3', "Conditions for Applying the Maxim"),
('n', [
    "The occurrence must be one that **does not ordinarily happen** in the absence of negligence.",
    "The instrumentality or the situation must have been within the **exclusive control** of the defendant.",
    "The injury must **not** have been due to any voluntary act or contributory negligence of the patient.",
    "The cause of the accident must be **unexplained** by the defendant."
]),
('eg', ["**Classic examples where *res ipsa loquitur* applies:**",
        "- A **swab, sponge or artery forceps left inside** the abdomen after surgery.",
        "- **Operation on the wrong patient**, wrong side or wrong limb.",
        "- **Transfusion of the wrong blood group** to the wrong patient.",
        "- **Burns from a hot-water bottle or diathermy** in an anaesthetised patient.",
        "- **Amputation of the wrong finger.**",
        "- **Fracture caused during handling** of an unconscious patient.",
        "- **A report issued in the name of a patient who never attended the laboratory** \u2014 the negligence speaks for itself."]),

('h2', "7.7  Vicarious Liability"),
('def', ("Vicarious liability",
         "The liability imposed on a **master/employer for the negligent acts or omissions of his servant/employee** committed **in the course of employment**, based on the maxims ***qui facit per alium facit per se*** ('he who does an act through another does it himself') and ***respondeat superior*** ('let the master answer').")),
('b', [
    "**Three conditions:** (i) there must be a master\u2013servant relationship, (ii) the servant must have been negligent, and (iii) the negligent act must have been committed **in the course of employment**.",
    "**The employee remains personally liable as well** \u2014 vicarious liability is *additional*, not a substitute. The injured party may sue either or both.",
    "The hospital or laboratory owner is therefore liable for a **technologist's mislabelling**, a **phlebotomist's nerve injury**, or a **data-entry operator's transcription error**.",
    "**Independent contractors:** traditionally an employer was not liable for the acts of a truly independent contractor (e.g. a visiting consultant), but Indian courts increasingly hold the hospital liable on the basis of **holding out** \u2014 if the hospital presented the person as part of its team, the patient was entitled to rely on that.",
    "**'Borrowed servant' / *captain of the ship* doctrine:** the person in charge (e.g. the surgeon in the operation theatre, the pathologist in the laboratory) may be liable for those temporarily under his direction and control.",
    "**Corporate negligence** is different: there the institution is liable for **its own** failures \u2014 employing unqualified staff, defective equipment, inadequate staffing, absent protocols \u2014 not for someone else's act.",
    "**Practical consequence:** this is why hospitals insist on qualified staff, SOPs, training records and **professional indemnity insurance** (see Chapter 8)."
]),

('h2', "7.8  Consent and the Law \u2014 Assault, Battery and Negligence"),
('tbl', (["Situation", "Legal consequence"],
         [["**No consent at all** \u2014 procedure done without any authorisation", "**Assault and battery** (an intentional tort, and possibly a criminal offence) \u2014 harm need not be proved"],
          ["**Consent obtained by fraud or misrepresentation**", "Consent is **void**; treated as no consent"],
          ["**Consent for procedure A, procedure B performed**", "Battery in respect of B \u2014 *Samira Kohli v. Dr Prabha Manchanda* (2008)"],
          ["**Consent given, but inadequate disclosure of material risks**", "Not battery, but **negligence** in the duty to inform"],
          ["**Consent of a minor (below 18) for treatment**", "Invalid \u2014 guardian's consent required"],
          ["**Consent obtained under coercion or undue influence**", "Invalid \u2014 the requirement of **voluntariness** fails"],
          ["**Emergency, patient unconscious, no surrogate available**", "Treatment is lawful \u2014 **implied/presumed consent** ('emergency privilege'); document the circumstances"],
          ["**HIV test performed without specific informed consent**", "Violation of the **HIV/AIDS (Prevention and Control) Act, 2017** \u2014 statutory liability in addition to tort"]],
         [6.4, 10.8],
         "Consent failures and their legal consequences")),

('h2', "7.9  Legal Implications for a Laboratory Professional"),
('h3', "A. The Forums Before Which You Can Be Called"),
('tbl', (["Forum", "Nature of proceeding", "Outcome"],
         [["**Consumer Commission** (District / State / National)", "Complaint of 'deficiency in service' under the **Consumer Protection Act, 2019**; quick, cheap, no court fee complexity", "**Compensation**, refund, correction, and costs"],
          ["**Civil Court**", "Suit in tort for negligence or for breach of contract", "**Damages / injunction**"],
          ["**Criminal Court**", "Prosecution for causing death or hurt by a rash or negligent act (BNS 2023, formerly IPC ss. 304A, 336\u2013338), or under a special statute (PC-PNDT, HIV Act, Drugs & Cosmetics Act)", "**Fine and/or imprisonment**"],
          ["**Professional Council** (Medical Council / State Allied & Healthcare Council)", "Disciplinary enquiry into professional misconduct", "Warning, suspension, **erasure of name from the register**"],
          ["**Employer / Departmental enquiry**", "Internal disciplinary proceeding", "Warning, withholding of increment, transfer, **termination**"],
          ["**Human Rights Commission**", "Complaint of violation of human rights", "Recommendation, compensation"],
          ["**Writ jurisdiction of High Court / Supreme Court**", "Violation of a fundamental right (Art. 21) by a State institution", "Directions, compensation"],
          ["**Consumer/consumer-like redressal under Clinical Establishments Act, 2010**", "Non-compliance with minimum standards", "Penalty, cancellation of registration"]],
         [4.0, 8.0, 5.2],
         "Where a laboratory professional may be held answerable")),
('h3', "B. Statutes a Laboratory Professional Must Know"),
('tbl', (["Statute", "Key relevance to the laboratory"],
         [["**Consumer Protection Act, 2019** (replaced the 1986 Act)", "Diagnostic services are a 'service'; a patient is a 'consumer'; deficiency in service \u2192 compensation. Three-tier commissions; limitation **2 years**"],
          ["**Clinical Establishments (Registration and Regulation) Act, 2010**", "Compulsory registration of clinical laboratories; minimum standards of facilities and personnel; display of rates; maintenance of records"],
          ["**Bharatiya Nyaya Sanhita, 2023** (replacing the IPC, 1860)", "Causing death by a rash/negligent act (earlier s. 304A IPC); causing hurt by a rash act; s. 89/consent provisions; criminal breach of trust and forgery for falsified reports"],
          ["**Bio-Medical Waste Management Rules, 2016** (as amended)", "Colour-coded segregation, storage, transport and disposal; authorisation; annual reporting. Non-compliance \u2192 penalty under the Environment (Protection) Act, 1986"],
          ["**PC-PNDT Act, 1994**", "Prohibits prenatal sex determination and its disclosure; registration of genetic laboratories; mandatory records (Form F) and display of the prohibition notice; imprisonment and fine on conviction"],
          ["**HIV/AIDS (Prevention and Control) Act, 2017**", "Informed consent and counselling before HIV testing; prohibition of disclosure without consent or court order; prohibition of discrimination"],
          ["**Transplantation of Human Organs Act, 1994 (amd. 2011)**", "Brain-death certification by a board of four; prohibition of commercial dealings in organs"],
          ["**MTP Act, 1971 (amd. 2021)**", "Lawful termination of pregnancy \u2014 gestational limits and authorised providers; strict confidentiality of the woman's identity"],
          ["**Mental Healthcare Act, 2017**", "Rights of persons with mental illness, including confidentiality; advance directives; decriminalisation of attempted suicide"],
          ["**POCSO Act, 2012**", "**Mandatory reporting** of known or suspected sexual offences against children \u2014 failure to report is itself an offence"],
          ["**Drugs and Cosmetics Act, 1940 & Rules**", "Regulation of diagnostic kits and reagents; blood banks are licensed under Schedule F Part XII-B"],
          ["**Atomic Energy (Radiation Protection) Rules, 2004 / AERB**", "Licensing and safety for radioisotope work (RIA laboratories)"],
          ["**Information Technology Act, 2000** and **Digital Personal Data Protection Act, 2023**", "Security and privacy of electronic health data; penalties for negligent handling or wrongful disclosure of sensitive personal data"],
          ["**Epidemic Diseases Act, 1897 (amd. 2020)**", "Powers during an epidemic; **enhanced punishment for violence against health-care personnel**"],
          ["**National Commission for Allied and Healthcare Professions Act, 2021**", "Statutory regulation, registration and professional conduct of medical laboratory technologists and other allied professionals"],
          ["**Indian Evidence Act, 1872 / Bharatiya Sakshya Adhiniyam, 2023**", "Laboratory records and reports as evidence; expert evidence; **no doctor\u2013patient testimonial privilege in India**"]],
         [5.6, 11.6],
         "Statutes governing laboratory practice in India")),

('h2', "7.10  Defences Available Against a Charge of Negligence"),
('p', "This is a high-scoring sub-question. Learn the list."),
('n', [
    "**No duty of care existed** \u2014 there was no professional relationship with the complainant.",
    "**No breach of duty** \u2014 the accepted standard of care was met; the **Bolam** defence: the practice followed is accepted as proper by a responsible body of professional opinion (*Jacob Mathew*, 2005).",
    "**No causation** \u2014 the injury was not caused by the alleged breach; or **novus actus interveniens** broke the chain of causation.",
    "**No damage** \u2014 no legally recognisable injury was suffered.",
    "**Error of judgement, not negligence** \u2014 a reasonable decision that turned out to be wrong is not negligence.",
    "**Therapeutic misadventure / unforeseeable complication** \u2014 an inherent risk that materialised despite due care.",
    "**Contributory negligence of the patient** \u2014 he did not fast, concealed medication, did not return for the repeat test or did not collect the report.",
    "**Volenti non fit injuria / informed consent to a known risk** \u2014 the patient was informed of and accepted the risk (this does not excuse negligent performance).",
    "**Res judicata / limitation** \u2014 the claim is time-barred (2 years for a consumer complaint) or already decided.",
    "**Act of God / inevitable accident**, or a genuine, documented emergency in which resources were unavailable.",
    "**Good Samaritan / emergency assistance** rendered gratuitously and in good faith.",
    "**Compliance with a statutory duty** \u2014 e.g. a lawful disclosure under notification rules.",
    "**Documentary evidence of due care** \u2014 SOPs followed, QC records, calibration logs, training records, consent form, critical-value register. *In practice this is the single most effective defence.*"
]),
('mne', ("The five practical shields of a laboratory professional \u2014 \u201CS-C-Q-D-I\u201D",
         ["**S** \u2013 **SOPs** followed and documented",
          "**C** \u2013 **Consent** obtained and recorded",
          "**Q** \u2013 **Quality control** records (IQC, EQAS, calibration, maintenance)",
          "**D** \u2013 **Documentation** \u2014 complete, legible, contemporaneous ('not documented, not done')",
          "**I** \u2013 **Insurance** \u2014 professional indemnity cover, plus **communication** (honest, empathic \u2014 which prevents most suits from ever being filed)"])),

('h2', "7.11  Common Sources of Litigation in the Laboratory"),
('tbl', (["Phase", "Error", "Potential consequence"],
         [["**Pre-analytical** (the commonest source \u2014 up to about 60\u201370 % of laboratory errors)", "Wrong patient identification; unlabelled or mislabelled tube; wrong tube/anticoagulant; wrong order of draw; insufficient volume; haemolysis; clotted sample; delay or wrong temperature in transport; wrong or missing patient preparation; drip-arm sampling", "Wrong result on the wrong patient \u2192 wrong treatment; wrong transfusion; repeat sampling and delay"],
          ["**Analytical**", "Uncalibrated instrument; failed or ignored QC; expired reagent; carry-over; interference not recognised; dilution error; test performed by an untrained person", "False high or low result \u2192 wrong drug dose, unnecessary treatment or missed diagnosis"],
          ["**Post-analytical**", "Transcription error; result entered against the wrong patient; report not delivered; **critical value not communicated**; wrong reference interval quoted; report released without authorisation; unreadable report", "Delay in treatment, death, litigation"],
          ["**Confidentiality**", "Disclosure to a relative, employer or on social media", "Suit for breach of privacy; statutory penalty; social catastrophe for the patient"],
          ["**Consent**", "HIV or genetic test done without specific consent; procedure without explanation", "Battery / statutory offence"],
          ["**Safety**", "Needle-stick injury to staff or patient; infection from a reused device; improper waste disposal", "Compensation, statutory penalty, criminal liability"],
          ["**Documentation**", "Missing, illegible or altered records", "Loss of the defence \u2014 'not documented, not done'"],
          ["**Behaviour**", "Rudeness, refusal to answer, arrogance after an error", "Converts a minor complaint into a lawsuit"]],
         [4.2, 7.0, 6.0],
         "Where laboratory litigation actually comes from")),

('h2', "7.12  Prevention of Negligence and Litigation \u2014 Risk Management"),
('n', [
    "**Follow SOPs** for every step; never improvise; know where the SOP manual is.",
    "**Two-identifier patient identification** \u2014 ask the patient to state his own name and date of birth/UHID; label the tube **at the bedside, in the patient's presence, immediately after collection** \u2014 never in advance and never at the workstation.",
    "**Work within your competence** and licence; decline politely and escalate what is beyond you.",
    "**Obtain and document consent**, and document any refusal.",
    "**Maintain a full quality-assurance programme** \u2014 IQC every run, EQAS participation, calibration, method validation, equipment maintenance logs, temperature charts.",
    "**Never release results when QC has failed**; investigate, correct, re-run.",
    "**Verify improbable results** \u2014 delta checks, repeat, check for interference, correlate with the clinical picture; a potassium of 9 mmol/L in a walking, talking patient is usually haemolysis.",
    "**Communicate critical values immediately**, with read-back and documentation.",
    "**Document everything, contemporaneously and legibly**; never alter a record improperly \u2014 strike through, initial and date any correction.",
    "**Maintain confidentiality** rigorously.",
    "**Practise strict biosafety** \u2014 universal precautions, PPE, sharps containers, correct waste segregation, immunisation of staff, post-exposure prophylaxis protocol.",
    "**Communicate well and empathically** \u2014 explain, be courteous, be honest about delays. *The overwhelming majority of complaints arise from poor communication rather than technical error.*",
    "**Disclose and apologise** promptly when an error occurs; open disclosure demonstrably reduces litigation.",
    "**Report incidents and near-misses** in a blame-free system; do root-cause analysis; change the system, not just the person.",
    "**Continuing education and competency assessment** for all staff, with records.",
    "**Obtain professional indemnity insurance**, and ensure the institution's cover extends to you.",
    "**Seek accreditation (NABL / ISO 15189)** \u2014 accreditation is strong evidence of due care.",
    "**Handle complaints promptly and courteously** through a defined grievance mechanism, before they become suits."
]),

('h2', "7.13  What To Do If You Are Involved in an Incident or Sued"),
('n', [
    "**Attend to the patient first** \u2014 mitigate the harm, inform the treating clinician, and take corrective clinical action.",
    "**Inform your supervisor and the institution immediately**; never attempt to handle it alone or quietly.",
    "**Preserve all records, samples and evidence** \u2014 the specimen, the requisition form, QC data, instrument printouts, maintenance logs. **Do not alter, add to, back-date or destroy any record** \u2014 this converts a defensible case into an indefensible one and may itself be a criminal offence.",
    "**Make a factual, contemporaneous written account** of what happened, and keep a copy.",
    "**Be honest and open with the patient and family**; express regret for the harm; do not argue, do not blame others, and do not make legal admissions about liability \u2014 an expression of **sympathy is not an admission of negligence**.",
    "**Notify the insurer** promptly, as the policy requires.",
    "**Take legal advice** through the institution or your professional association; do not respond to legal notices yourself.",
    "**Cooperate fully** with the internal enquiry and with root-cause analysis.",
    "**Do not discuss the case** with the media, on social media, or with colleagues who are not involved.",
    "**Attend the forum** when summoned; be courteous, factual and consistent; take the records with you.",
    "**Learn from it** \u2014 implement the system change so that the same error cannot recur; document that change (it also demonstrates good faith)."
]),
('warn', ["**The three fatal mistakes after an error \u2014 avoid all three:**",
          "- **1. Concealment or alteration of records** \u2014 turns negligence into fraud and destroys all credibility.",
          "- **2. Arrogance or rudeness** to the patient and family \u2014 the commonest trigger that converts a complaint into a lawsuit.",
          "- **3. Blaming others** publicly \u2014 destroys team defence and looks like evasion."]),

('key', [
    "**Negligence = Duty + Dereliction (breach) + Direct causation + Damage.** All four must be proved (the **4 D's**).",
    "The standard is that of the **ordinary competent professional** (*Bolam*, 1957; *Jacob Mathew v. State of Punjab*, 2005), tested for logic (*Bolitho*).",
    "The law does **not** require the highest skill or a cure; a bad outcome or a mere error of judgement is **not** negligence.",
    "Types: **civil, criminal (gross \u2014 BNS 2023, earlier IPC s. 304A), contributory, composite, corporate, vicarious, negligence per se**; and **therapeutic misadventure**, which is *not* negligence.",
    "***Res ipsa loquitur*** = 'the thing speaks for itself' \u2192 negligence presumed, **burden shifts to the defendant** (swab left inside, wrong blood transfused, wrong-side surgery).",
    "**Vicarious liability** \u2014 *qui facit per alium facit per se* / *respondeat superior*: the employer answers for the employee's negligence in the course of employment; the employee remains liable too.",
    "**Malpractice** is wider than negligence (includes intentional wrongdoing); **misconduct** needs no patient harm at all.",
    "**No consent = battery; inadequate disclosure = negligence** (*Samira Kohli*, 2008).",
    "***IMA v. V.P. Shantha* (1995)** \u2014 medical services are a 'service' under consumer law; **Consumer Protection Act, 2019**; limitation **2 years**.",
    "Best defences: **SOP compliance + consent + QC records + documentation + indemnity insurance + good communication.**",
    "**Pre-analytical errors are the largest single source** of laboratory litigation \u2014 above all, **patient identification and labelling**.",
    "**'Not documented, not done.'** Never alter or destroy a record after an incident."
]),

('tip', [
    "**This chapter, along with Chapter 3, is the most likely source of a full 10-mark question.**",
    "- *Long (10 marks):* 'Define negligence. Discuss its essential elements, types, and the defences available to a health-care professional.'",
    "- *Long (10 marks):* 'What is malpractice? Describe the legal implications of laboratory errors and the measures to prevent litigation.'",
    "- *Short (5 marks):* 4 D's of negligence; *Res ipsa loquitur*; Vicarious liability; Criminal vs civil negligence; Contributory negligence; Bolam test / *Jacob Mathew*; Defences against negligence; Malpractice vs misconduct; Therapeutic misadventure.",
    "- *Very short (2 marks):* Expand *res ipsa loquitur*, *respondeat superior*, *qui facit per alium facit per se*; limitation period for a consumer complaint; which case brought medical services under consumer law; two types of negligence.",
    "**Presentation tip:** open with the definition, immediately draw the **4 D's table**, then the **types table**, then *res ipsa loquitur* and vicarious liability as separate sub-headings, then the **defences** as a numbered list, then two laboratory examples, and close with the preventive measures. This is a textbook 10/10 structure."
]),

('qa', ("QUESTION BANK \u2014 CHAPTER 7", [
    ("Define negligence and explain its essential elements.",
     ["Definition as in section 7.3. The four essential elements (**4 D's**), all of which must be proved by the complainant: **Duty** of care owed; **Dereliction** \u2014 breach of that duty by falling below the standard of the ordinary competent professional; **Direct causation** \u2014 a proximate causal link between the breach and the injury; and **Damage** \u2014 actual legally recognisable harm. Illustrate with the sample-mix-up \u2192 wrong transfusion \u2192 haemolytic reaction example. Add the *Bolam*/*Jacob Mathew* standard and note that a bad outcome alone does not prove negligence."]),
    ("Classify negligence with examples.",
     ["Civil; criminal (gross \u2014 BNS 2023, earlier IPC s. 304A); contributory (by the patient); composite (two or more wrongdoers); corporate/institutional; vicarious; negligence per se (breach of statute). Distinguish **therapeutic misadventure** (injury despite due care \u2014 not negligence) and **novus actus interveniens** (an intervening act breaking causation). Give one laboratory example for each \u2014 reproduce the table."]),
    ("Write short notes on res ipsa loquitur.",
     ["Meaning: 'the thing speaks for itself'. Effect: negligence is presumed and the **burden of proof shifts to the defendant**; the complainant need not lead expert evidence. Conditions: the event does not ordinarily occur without negligence; the thing was under the defendant's exclusive control; no contributory act by the patient; the defendant offers no explanation. Examples: swab or forceps left in the abdomen, wrong-side or wrong-patient surgery, transfusion of the wrong blood group, burns in an anaesthetised patient, a report issued for a patient who never attended."]),
    ("Explain vicarious liability with its conditions.",
     ["Definition and the maxims *qui facit per alium facit per se* and *respondeat superior*. Conditions: (i) a master\u2013servant relationship; (ii) negligence by the servant; (iii) the act committed **in the course of employment**. The employee remains personally liable in addition. Application: the hospital or laboratory owner is liable for the technologist's mislabelling or the phlebotomist's nerve injury. Mention 'holding out' for independent contractors, the 'borrowed servant'/captain-of-the-ship doctrine, and the distinction from **corporate negligence** (the institution's own failures \u2014 unqualified staff, defective equipment, no protocols)."]),
    ("Differentiate between civil and criminal negligence.",
     ["**Civil negligence** \u2014 ordinary want of care; proceeding before a civil court or consumer commission; standard of proof: **preponderance of probability**; remedy: **compensation**. **Criminal negligence** \u2014 gross, reckless negligence showing disregard for human life or safety; prosecution under the BNS 2023 (earlier IPC s. 304A); standard of proof: **beyond reasonable doubt**; punishment: **fine and/or imprisonment**; and (per *Jacob Mathew*, 2005) prosecution of a professional requires a **credible independent medical opinion** before proceeding. Give one example of each."]),
    ("What defences are available against a charge of negligence?",
     ["No duty of care; no breach of duty (the **Bolam** defence \u2014 a practice accepted by a responsible body of professional opinion, per *Jacob Mathew*); no causation, or *novus actus interveniens*; no damage; error of judgement rather than negligence; therapeutic misadventure/unforeseeable complication; contributory negligence of the patient; *volenti non fit injuria*/informed consent to a known risk; limitation (2 years) and *res judicata*; act of God or inevitable accident; Good Samaritan assistance; compliance with a statutory duty; and above all **documentary proof of due care** \u2014 SOPs, QC and calibration records, consent forms, training records and the critical-value register."]),
    ("Differentiate between negligence, malpractice and professional misconduct.",
     ["Reproduce the three-column table \u2014 meaning, intention, who can commit it, whether harm to the patient is essential, forum and consequence, and an example of each. Key points: negligence is **unintentional** carelessness; malpractice is **wider** and may be intentional; misconduct requires **no patient harm** at all and is dealt with by the professional council, whose ultimate sanction is **erasure of the name from the register**."]),
    ("Enumerate the common errors in a laboratory that may lead to litigation.",
     ["Classify by phase. **Pre-analytical (the largest group, roughly 60\u201370 %):** misidentification, unlabelled or mislabelled tubes, wrong anticoagulant, insufficient volume, haemolysis, clotting, delayed or wrongly stored transport, wrong patient preparation, drip-arm sampling. **Analytical:** uncalibrated equipment, failed or ignored QC, expired reagents, carry-over, unrecognised interference, dilution error, untrained operator. **Post-analytical:** transcription error, result attached to the wrong patient, report not delivered, **critical value not communicated**, wrong reference interval, unauthorised release. Add breaches of confidentiality and consent, biosafety failures, poor documentation, and rude behaviour after an error."]),
    ("How can a laboratory professional prevent negligence and litigation?",
     ["Follow SOPs; two-identifier patient identification with bedside labelling; work within competence; obtain and document consent and refusals; maintain a full quality-assurance programme (IQC, EQAS, calibration, maintenance, temperature logs); never release results on failed QC; verify improbable results with delta checks and repeats; communicate critical values immediately with read-back; document everything contemporaneously and legibly; maintain confidentiality; practise strict biosafety; communicate empathically and honestly; disclose and apologise for errors; report incidents in a blame-free system and do root-cause analysis; undertake continuing education with competency records; hold professional indemnity insurance; seek NABL/ISO 15189 accreditation; and resolve complaints promptly through a grievance mechanism. *(Mnemonic: S-C-Q-D-I.)*"]),
    ("What is the legal significance of medical records?",
     ["Records are the primary evidence of what was done and of the standard of care exercised; the maxim is **'not documented, not done.'** Requirements: legible, in ink, contemporaneous, complete, objective, signed and dated, with corrections made by a single strike-through, initialled and dated \u2014 never by erasure, overwriting or whitener. Records must be retained for the period prescribed by law and institutional/NABL policy, and produced when the patient requests a copy (a patient's right) or when a court so directs. Tampering, back-dating or destruction destroys the defence and may itself be a criminal offence (forgery, fabrication of evidence). Good records are simultaneously the patient's right and the professional's strongest shield."]),
    ("Write short notes on the Bolam test and Jacob Mathew's case.",
     ["**Bolam v. Friern Hospital Management Committee (1957):** a professional is not negligent if he acted in accordance with a practice accepted as proper by a responsible body of professional opinion skilled in that art, even if others would have acted differently; the standard is that of the ordinary competent practitioner. **Bolitho (1997)** added that the practice relied upon must withstand logical analysis. ***Jacob Mathew v. State of Punjab* (2005):** the Supreme Court of India adopted the *Bolam* standard, holding a professional liable only if he did not possess the requisite skill he professed, or did not exercise with reasonable competence the skill he possessed; it further directed that a doctor should not be prosecuted for criminal negligence without a **credible independent medical opinion**, to protect professionals from frivolous prosecution."]),
])),

('recap', [
    "**4 D's:** Duty \u2192 Dereliction \u2192 Direct causation \u2192 Damage. All four, or no case.",
    "Standard = **ordinary competent professional** (*Bolam* / *Jacob Mathew* 2005), not the best expert.",
    "Bad outcome \u2260 negligence. Error of judgement \u2260 negligence.",
    "***Res ipsa loquitur*** \u2192 negligence presumed, **burden shifts** to the defendant.",
    "**Vicarious liability** \u2192 employer answers for the employee (*respondeat superior*).",
    "Negligence (careless) < Malpractice (wider, may be intentional); Misconduct needs **no harm**.",
    "**No consent = battery; poor disclosure = negligence** (*Samira Kohli* 2008).",
    "**Pre-analytical errors dominate** \u2014 identification and labelling above all.",
    "Shields: **SOP + Consent + QC + Documentation + Insurance + Communication**.",
    "***IMA v. V.P. Shantha* (1995)** \u2192 medical service = 'service'; **CPA 2019**; limitation **2 years**.",
]),

]
