# -*- coding: utf-8 -*-
"""Chapter 8 - Consumer Protection and Insurance for Professional Health Hazard"""

BLOCKS = [

('ch', (8, "Consumer Protection and Insurance for Professional Health Hazard",
        "CPA 1986 / 2019 \u2022 Consumer rights \u2022 Redressal machinery \u2022 Occupational hazards \u2022 Indemnity & health insurance")),

('h2', "8.1  Introduction"),
('p', "This chapter has **two distinct halves**, and a common exam mistake is to answer only one. The first half deals with the patient as a **consumer** who can sue the laboratory for deficient service. The second half deals with the professional as a **worker exposed to occupational hazards**, who needs insurance and statutory protection for himself. Read the question carefully and answer whichever half \u2014 or both \u2014 is asked."),

('h2', "PART A \u2014 CONSUMER PROTECTION"),

('h2', "8.2  Background and the Landmark Case"),
('p', "The **Consumer Protection Act, 1986** was enacted to provide simple, speedy and inexpensive redressal to consumers. It was initially unclear whether medical services fell within it. The question was settled decisively by the Supreme Court."),
('eg', ["**Indian Medical Association v. V.P. Shantha (1995) \u2014 the single most important case in this chapter:** The Supreme Court held that **medical services rendered for a fee fall within the definition of 'service'** under the Consumer Protection Act, and that a patient who pays for such service is a **'consumer'**. Therefore a patient may complain of **'deficiency in service'** before a consumer forum, which is a far cheaper and faster remedy than a civil suit.",
        "**Important refinements laid down in the same case:**",
        "- Service rendered **free of charge to everybody** is **not** 'service' under the Act \u2014 so a wholly free government hospital or charitable dispensary was outside it.",
        "- **But** where a hospital charges some patients and treats poor patients free, even the **free patient is a consumer**, because the service is not free 'to all'.",
        "- Where the charges are paid by an **insurer or employer** on the patient's behalf, the patient is still a consumer.",
        "- A **medical officer employed in a hospital** is not personally in a consumer relationship with the patient, but the hospital is (see vicarious liability, Chapter 7)."]),
('p', "The 1986 Act has now been **repealed and replaced by the Consumer Protection Act, 2019** (in force from 20 July 2020), which modernised and strengthened the framework. **Quote the 2019 Act as the current law** and mention 1986 as the predecessor \u2014 many textbooks still say 1986, and stating both shows you are up to date."),

('h2', "8.3  Key Definitions Under the Consumer Protection Act, 2019"),
('def', ("Consumer",
         "Any person who **buys any goods or hires or avails of any service for a consideration** which has been paid or promised or partly paid and partly promised, or under any system of deferred payment. It includes a user of such goods or a beneficiary of such service **other than the person who paid**, when used with the approval of the buyer. It **excludes** a person who obtains goods or services for **resale or for any commercial purpose**.",
         ["The 2019 Act expressly includes transactions made **online, through electronic means, teleshopping, direct selling or multi-level marketing** \u2014 relevant to online report delivery and home-collection services."])),
('def', ("Service",
         "Service of any description made available to potential users, including **health care**, banking, insurance, transport, supply of electrical energy, housing construction, entertainment and amusement, but **excluding** services rendered **free of charge** or under a **contract of personal service**.")),
('def', ("Deficiency",
         "Any **fault, imperfection, shortcoming or inadequacy in the quality, nature and manner of performance** which is required to be maintained by or under any law, or has been undertaken to be performed under a contract or otherwise. The 2019 Act expressly adds (i) any **act of negligence, omission or commission** which causes loss or injury to the consumer, and (ii) **deliberate withholding of relevant information** from the consumer.")),
('def', ("Complaint",
         "Any allegation in writing made by a complainant regarding an unfair or restrictive trade practice, defective goods, **deficient services**, excess pricing, or the offering of hazardous goods or services.")),
('def', ("Unfair trade practice",
         "A trade practice adopting deceptive methods to promote a sale \u2014 including **false or misleading representation about the standard, quality or usefulness** of a service, misleading advertisement, refusal to issue a bill or receipt, and (added in 2019) **disclosure of personal information given in confidence, unless required by law or in the public interest**.")),
('warn', ["Note that last point carefully \u2014 under the **Consumer Protection Act, 2019, disclosure of a consumer's personal information given in confidence is itself an 'unfair trade practice'.** This means a **breach of patient confidentiality by a laboratory is actionable before a consumer commission**, quite apart from any other law. This is an excellent, high-level point to include in a confidentiality answer as well."]),

('h2', "8.4  The Six Consumer Rights"),
('tbl', (["#", "Right", "Meaning", "Application to a diagnostic laboratory"],
         [["1", "**Right to Safety**", "Protection against goods and services hazardous to life and property", "Sterile, single-use needles; safe phlebotomy; safe premises; correct biomedical waste disposal"],
          ["2", "**Right to be Informed**", "The right to know the quality, quantity, potency, purity, standard and price", "Displayed rate list; information about the test, the sample required, the preparation needed and the reporting time; a proper bill"],
          ["3", "**Right to Choose**", "Access to a variety of goods and services at competitive prices", "The patient may choose any laboratory; a hospital cannot compel him to use its own laboratory"],
          ["4", "**Right to be Heard**", "The right to have one's interests receive due consideration at appropriate forums", "A working complaint/grievance mechanism; a complaint register; a designated grievance officer"],
          ["5", "**Right to Seek Redressal**", "The right to redressal against unfair trade practices or exploitation", "Complaint before the District/State/National Commission for a wrong or delayed report"],
          ["6", "**Right to Consumer Education**", "The right to acquire the knowledge and skill to be an informed consumer", "Patient information leaflets; explanation of test preparation; display of patients' rights"]],
         [0.7, 3.2, 5.6, 7.7],
         "The six consumer rights recognised by the Act")),
('mne', ("\u201CS-I-C-H-R-E\u201D \u2014 the six consumer rights",
         ["**S** \u2013 **S**afety", "**I** \u2013 **I**nformation", "**C** \u2013 **C**hoice",
          "**H** \u2013 **H**earing (right to be heard)", "**R** \u2013 **R**edressal",
          "**E** \u2013 **E**ducation"])),

('h2', "8.5  Consumer Dispute Redressal Machinery (Three-Tier)"),
('tbl', (["Level", "Name", "Pecuniary jurisdiction (CPA 2019, as amended 2021)", "Composition", "Appeal lies to"],
         [["**District**", "District Consumer Disputes Redressal **Commission** (DCDRC)", "Up to **\u20b9 50 lakh**", "President (District Judge rank) + at least 2 members", "State Commission, within **45 days**"],
          ["**State**", "State Consumer Disputes Redressal **Commission** (SCDRC)", "Above \u20b9 50 lakh and up to **\u20b9 2 crore**", "President (High Court Judge rank) + at least 4 members", "National Commission, within **30 days**"],
          ["**National**", "National Consumer Disputes Redressal **Commission** (NCDRC), New Delhi", "Above **\u20b9 2 crore**", "President (Supreme Court Judge rank) + at least 4 members", "**Supreme Court**, within **30 days**"]],
         [1.5, 4.2, 4.0, 4.0, 3.5],
         "The three-tier redressal machinery \u2014 learn the monetary limits")),
('warn', ["**Examiner trap on jurisdiction:** the 1986 Act's limits were \u20b9 20 lakh / \u20b9 1 crore / above \u20b9 1 crore, and the 2019 Act originally set \u20b9 1 crore / \u20b9 10 crore / above \u20b9 10 crore. These were **revised in 2021 to \u20b9 50 lakh / \u20b9 2 crore / above \u20b9 2 crore**, based on the **value of the goods or services paid as consideration** (not on the compensation claimed). If you are unsure of the exact figure, write the structure (District \u2192 State \u2192 National \u2192 Supreme Court) and state the current limits as \u20b9 50 lakh and \u20b9 2 crore \u2014 the three-tier structure itself carries most of the marks."]),
('h3', "Procedure for Filing a Complaint"),
('n', [
    "**Who may complain:** the consumer himself; any recognised consumer association; the Central or State Government; the Central Consumer Protection Authority; one or more consumers with the same interest; or, if the consumer has died, his legal heir or representative; and a parent or legal guardian for a minor.",
    "**Limitation period: 2 years** from the date on which the cause of action arose. A delay may be condoned if sufficient cause is shown.",
    "**Where to file:** the 2019 Act permits filing where the complainant **resides or works**, in addition to where the opposite party carries on business \u2014 a major convenience for patients.",
    "**How to file:** a **written complaint** (no lawyer necessary), with a **nominal fee**; **e-filing is permitted** under the 2019 Act.",
    "**Contents:** particulars of both parties, the facts, the deficiency alleged, supporting documents (bill/receipt, prescription, the report complained of, correspondence) and the relief claimed.",
    "**Procedure:** notice to the opposite party \u2192 written version/reply \u2192 evidence by affidavit \u2192 hearing (summary procedure, not a full civil trial) \u2192 order. The Act aims at disposal within **3 months** (or 5 months where laboratory analysis is required).",
    "**Mediation:** the 2019 Act introduced **court-annexed mediation**; at the first hearing the Commission may refer the dispute to mediation with the parties' consent.",
    "**Appeal:** District \u2192 State within 45 days; State \u2192 National within 30 days; National \u2192 Supreme Court within 30 days. An appellant against an order to pay must deposit **50 %** of the amount awarded.",
    "**Execution:** an order of a Commission is enforceable as a decree; non-compliance is punishable with imprisonment (1 month to 3 years) and/or fine (\u20b9 25,000 to \u20b9 1 lakh)."
]),
('h3', "Reliefs the Commission Can Grant"),
('b', [
    "**Compensation** for loss or injury, including for mental agony and harassment.",
    "**Refund** of the price or charges paid.",
    "**Removal of the defect or deficiency** in the service.",
    "**Replacement** of the goods, or **re-performance** of the service.",
    "**Discontinuation of an unfair or restrictive trade practice**, and a direction not to repeat it.",
    "**Withdrawal of hazardous goods** from sale; a direction to cease manufacture of hazardous goods.",
    "**Punitive damages** in appropriate cases.",
    "**Corrective advertisement** to neutralise a misleading advertisement.",
    "**Costs** of the proceedings to the complainant.",
    "**Product liability** action (new in 2019) against a manufacturer, service provider or seller for a defective product causing harm."
]),
('h3', "New Features Introduced by the Consumer Protection Act, 2019"),
('n', [
    "Establishment of the **Central Consumer Protection Authority (CCPA)** with powers to investigate, recall goods, order reimbursement, and impose penalties for misleading advertisements.",
    "**Product liability** provisions \u2014 covering the manufacturer, the service provider and the seller.",
    "**E-commerce and direct selling** brought expressly within the Act.",
    "**Mediation** as an alternative dispute-resolution mechanism annexed to the Commissions.",
    "**Filing at the complainant's place of residence or work**, and **e-filing** with electronic hearings.",
    "**Enhanced penalties** for misleading advertisements and for adulterated or spurious goods.",
    "Expanded definition of **'deficiency'** to expressly include negligence and the **deliberate withholding of information**.",
    "**Disclosure of personal information given in confidence** treated as an **unfair trade practice**.",
    "Revised, simplified **pecuniary jurisdiction** based on the value of the consideration paid."
]),

('h2', "8.6  Implications of the Consumer Protection Act for a Laboratory"),
('tbl', (["Common allegation before a consumer commission", "How the laboratory protects itself"],
         [["**Wrong report** \u2014 wrong blood group, false positive/negative, wrong value", "Two-identifier identification; bedside labelling; IQC/EQAS records; delta checks; repeat and confirm; documented method validation"],
          ["**Delayed report** causing loss or delayed treatment", "Defined and displayed turnaround times; honest communication of any delay; documented reasons for delay"],
          ["**Critical value not communicated**", "Written critical-value list, SOP, register with read-back documentation, escalation ladder"],
          ["**Overcharging / hidden charges**", "Displayed rate list; itemised computer-generated bill; no charge for a repeat necessitated by laboratory error"],
          ["**Rude behaviour / refusal of service / discrimination**", "Staff training; grievance register; a designated grievance officer; documented action on complaints"],
          ["**Breach of confidentiality**", "Confidentiality policy and undertaking; access control; sealed reports; secure LIS (note: breach is itself an **unfair trade practice** under the 2019 Act)"],
          ["**Test performed without consent** (e.g. HIV)", "Specific written consent with pre- and post-test counselling (HIV/AIDS Act, 2017)"],
          ["**Injury during sample collection** \u2014 nerve injury, haematoma, syncope, infection", "Trained phlebotomists; correct technique; maximum two attempts; single-use sterile devices; post-procedure instructions; incident register"],
          ["**Report by an unqualified person**", "Only qualified, registered personnel to perform and authorise; maintain qualification and training records"],
          ["**Misleading advertisement** \u2014 'most accurate lab', '100 % accurate'", "No exaggerated claims; advertise only factual information as permitted by the professional code"],
          ["**Loss of a sample or a report**", "Sample-tracking system; barcoding; acknowledgement of receipt; retention policy; prompt honest disclosure and free repeat"]],
         [7.6, 9.6],
         "Consumer complaints against laboratories and how to prevent them")),
('key', [
    "***IMA v. V.P. Shantha* (1995)** \u2014 medical service for a fee is a **'service'**; the patient is a **'consumer'**; wholly free service to all is excluded, but a free patient in a hospital that charges others **is** a consumer.",
    "Current law: **Consumer Protection Act, 2019** (replaced the 1986 Act; effective 20 July 2020).",
    "Six consumer rights: **Safety, Information, Choice, Hearing, Redressal, Education (S-I-C-H-R-E).**",
    "Three-tier machinery: **District (up to \u20b9 50 lakh) \u2192 State (up to \u20b9 2 crore) \u2192 National (above \u20b9 2 crore) \u2192 Supreme Court.**",
    "**Limitation: 2 years**; written complaint; nominal fee; **no lawyer necessary**; e-filing allowed; filing possible where the complainant resides or works.",
    "New in 2019: **CCPA, product liability, e-commerce coverage, mediation, e-filing**, and **disclosure of confidential personal information as an unfair trade practice**."
]),

('h2', "PART B \u2014 OCCUPATIONAL HEALTH HAZARDS AND INSURANCE"),

('h2', "8.7  Occupational Hazards of a Laboratory Professional"),
('p', "A medical laboratory is one of the most hazardous workplaces in a hospital. Classify the hazards \u2014 a classified answer scores far higher than a list."),
('tbl', (["Category", "Specific hazards", "Preventive measures"],
         [["**1. Biological**", "Needle-stick and sharps injury; **HIV, hepatitis B, hepatitis C**; tuberculosis; brucellosis; typhoid; meningococcus; COVID-19 and other respiratory viruses; aerosols from centrifuges and uncapping; spills; bites in animal houses; cuts from broken glass", "**Universal (standard) precautions for every specimen**; PPE \u2014 gloves, gown, mask, face shield; **hepatitis B vaccination** of all staff; no recapping of needles; **puncture-proof sharps containers**; never mouth-pipetting; biosafety cabinets for aerosol-generating work; correct biosafety level; hand hygiene; **post-exposure prophylaxis (PEP)** protocol; needle-stick injury register; safety-engineered devices"],
          ["**2. Chemical**", "Acids and alkalis; **formaldehyde/formalin** (carcinogen); xylene, toluene, benzene; **phenol**; methanol; **mercury**; azide; carcinogenic dyes (benzidine); cyanide in reagents; sensitisers causing dermatitis and asthma", "Fume hood for volatile chemicals; correct labelling and **material safety data sheets (MSDS)**; segregated, ventilated storage; spill kits; eye-wash station and emergency shower; chemical-resistant gloves and aprons; substitution with safer chemicals; no eating, drinking or cosmetics in the laboratory"],
          ["**3. Physical**", "Electrical shock; burns from flames, autoclaves and hot plates; **fire and explosion**; cuts from glassware; **radiation** (radioisotope/RIA laboratories, X-ray); UV light from transilluminators and safety cabinets; **noise**; extremes of temperature; liquid nitrogen cold burns; compressed-gas cylinders", "Earthed equipment and periodic electrical audit; fire extinguishers, fire drills and marked exits; autoclave maintenance and validation; **film badges/TLD dosimeters and lead shielding** for radiation, with AERB compliance; UV shields and interlocks; cryogenic gloves and face shields; secured cylinders; noise control"],
          ["**4. Ergonomic / Mechanical**", "Prolonged standing; repetitive pipetting \u2192 **repetitive strain injury, carpal tunnel syndrome**, tenosynovitis of the thumb; awkward microscope posture \u2192 neck and back pain; heavy lifting; **eye strain** from microscopy and screens; slips, trips and falls on wet floors", "Adjustable chairs and bench heights; electronic or ergonomic multichannel pipettes; scheduled micro-breaks and task rotation; correct microscope height and eyepiece adjustment; anti-fatigue mats; proper lifting technique and trolleys; dry, uncluttered floors; the 20-20-20 rule for screen work"],
          ["**5. Psychosocial**", "**Work overload** and long shifts; **night and rotating shift work** with circadian disruption; time pressure and fear of error; **burnout**; **violence and abuse from attendants**; harassment and bullying; hierarchical stress; poor recognition and pay; **moral distress** at being pressured to release doubtful results", "Adequate staffing and rational rosters with rest between shifts; realistic workload norms; a **blame-free incident-reporting culture**; training and support; security arrangements and a violence-response protocol; an **Internal Complaints Committee** under the **POSH Act, 2013**; counselling and employee-assistance programmes; recognition and career progression"],
          ["**6. Waste-related / Environmental**", "Sharps injuries during waste handling; infectious waste; **mercury and chemical waste**; cytotoxic waste; effluent discharge", "**Bio-Medical Waste Management Rules, 2016** \u2014 colour-coded segregation at the point of generation (yellow/red/white translucent/blue), authorised disposal through a common facility, effluent treatment, training of housekeeping staff, annual reports"],
          ["**7. Latex / Allergic**", "Latex allergy; glutaraldehyde and formaldehyde sensitisation; laboratory-animal allergy", "Powder-free, non-latex (nitrile) gloves; ventilation; pre-placement and periodic screening"]],
         [2.6, 7.0, 7.6],
         "Occupational hazards in a medical laboratory and their prevention")),
('mne', ("\u201CB-C-P-E-P-W\u201D \u2014 the six groups of laboratory hazards",
         ["**B** \u2013 **B**iological (needle-stick, HIV, HBV, HCV, TB, aerosols)",
          "**C** \u2013 **C**hemical (formalin, xylene, acids, mercury)",
          "**P** \u2013 **P**hysical (electrical, fire, radiation, UV, noise, burns)",
          "**E** \u2013 **E**rgonomic (RSI, back and neck pain, eye strain, falls)",
          "**P** \u2013 **P**sychosocial (overload, shift work, burnout, violence, harassment)",
          "**W** \u2013 **W**aste and environmental (BMW Rules, 2016)"])),
('h3', "Needle-Stick Injury \u2014 Immediate Management (a favourite short question)"),
('flow', ["**1.** Do **not** panic; do **not** squeeze or suck the wound",
          "**2.** Wash the site immediately with **soap and running water** for several minutes (mucosa/eyes: irrigate copiously with water or saline; do not use antiseptic in the eye)",
          "**3.** Do **not** apply strong caustic antiseptics; do not scrub or use bleach on the wound",
          "**4.** **Report immediately** to the supervisor and the designated PEP officer/casualty \u2014 the clock matters",
          "**5.** **Assess the exposure and the source** \u2014 type of injury, device, volume, and the source patient's HIV/HBV/HCV status (with consent as required)",
          "**6.** **Baseline testing** of the exposed worker for HIV, HBsAg and anti-HCV",
          "**7.** **HIV PEP** to be started as early as possible, ideally within **2 hours**, and not beyond **72 hours**; continued for **28 days** as per the national protocol",
          "**8.** **Hepatitis B:** if unvaccinated or non-responder, give **HBIG + vaccine**; if vaccinated with documented adequate anti-HBs, no action is usually needed",
          "**9.** **Hepatitis C:** no PEP available \u2014 arrange follow-up testing so that early treatment can be given if infection occurs",
          "**10.** **Document** in the needle-stick injury register; **follow up** at 6 weeks, 3 months and 6 months; counsel on safe practices in the interim; do root-cause analysis and correct the system"]),

('h2', "8.8  Insurance \u2014 Meaning and Principles"),
('def', ("Insurance",
         "A contract (evidenced by a **policy**) by which one party (the **insurer**) undertakes, in return for a consideration called the **premium**, to indemnify the other party (the **insured**) against loss, damage or liability arising from a specified uncertain event, or to pay a specified sum on the happening of such an event. Its essence is the **pooling and transfer of risk** from an individual to a large group.")),
('h3', "Basic Principles of Insurance"),
('b', [
    "**Insurable interest** \u2014 the insured must stand to suffer a real loss from the event.",
    "**Utmost good faith (*uberrima fides*)** \u2014 full and honest disclosure of all material facts by both parties; non-disclosure can void the policy.",
    "**Indemnity** \u2014 the insured is restored to the position he was in before the loss, not better; he cannot profit from insurance.",
    "**Contribution** \u2014 where more than one policy covers the same loss, insurers share it proportionately.",
    "**Subrogation** \u2014 after paying, the insurer acquires the insured's rights to recover from the party at fault.",
    "**Proximate cause** \u2014 the nearest effective cause of the loss determines liability.",
    "**Mitigation of loss** \u2014 the insured must take reasonable steps to minimise the loss.",
    "**Law of large numbers** \u2014 the actuarial basis: risk becomes predictable across a large pool."
]),

('h2', "8.9  Types of Insurance Relevant to a Health-Care Professional"),
('tbl', (["Type of policy", "What it covers", "Why a laboratory professional needs it"],
         [["**Professional Indemnity Insurance** (also called **Errors and Omissions** or **medical malpractice** insurance)", "The professional's **legal liability** to third parties \u2014 compensation awarded against him and the **legal defence costs** \u2014 arising from an act of professional negligence, error or omission in the course of his professional duty", "**The single most important policy for a professional.** It protects against a consumer or civil award for a wrong or delayed report, a mislabelled sample or an injury during phlebotomy. Should be taken by the individual and by the laboratory"],
          ["**Public Liability Insurance**", "Liability for injury to third parties or damage to their property on the premises", "A visitor slips on a wet laboratory floor; a chemical spill injures a bystander"],
          ["**Workmen's / Employees' Compensation Insurance** (Employee's Compensation Act, 1923)", "Statutory compensation payable by the **employer** to an employee for death, disablement or occupational disease **arising out of and in the course of employment**", "Covers a technologist who contracts hepatitis B from a needle-stick, or is injured by an autoclave burst"],
          ["**Employees' State Insurance (ESI Act, 1948)**", "Contributory social security \u2014 **medical, sickness, maternity, disablement and dependants' benefits**; funded by employer and employee contributions", "Provides medical care and cash benefits to eligible laboratory employees and their families"],
          ["**Health / Mediclaim Insurance**", "Hospitalisation and treatment expenses of the insured and family (cashless or reimbursement)", "Covers the professional's own illness \u2014 including illness acquired at work; group cover is commonly provided by hospitals"],
          ["**Personal Accident Insurance**", "Death, permanent total/partial disablement and temporary disablement due to accident, with medical expenses", "Covers commuting and on-duty accidents; often includes needle-stick-related consequences"],
          ["**Life Insurance**", "Payment of the sum assured on death (and on maturity in endowment plans)", "Financial security for the family; a term policy is the most cost-effective protection"],
          ["**Fire and Special Perils / Property Insurance**", "Damage to the building, equipment and stock by fire, explosion, flood, riot, etc.", "Analysers and reagent stock represent a very large capital exposure"],
          ["**Equipment Breakdown / Electronic Equipment Insurance**", "Repair or replacement of analysers and electronic equipment, and sometimes loss of reagents due to breakdown", "A refrigerator or analyser failure can destroy an entire reagent inventory"],
          ["**Group Personal Accident & Group Health Cover**", "Cover for all employees under one institutional policy", "Standard practice in accredited laboratories and hospitals"],
          ["**Clinical Trial / Research Liability Insurance**", "Injury to research participants; compensation as required by the NDCT Rules, 2019", "Mandatory if the laboratory participates in clinical research"],
          ["**Cyber Liability Insurance**", "Loss from a data breach, ransomware or hacking of the LIS, including notification and legal costs", "Increasingly relevant with electronic records and the DPDP Act, 2023"]],
         [4.8, 6.6, 5.8],
         "Types of insurance for a laboratory professional and a laboratory")),
('mne', ("\u201CP-W-E-H-P-L\u201D \u2014 the six policies every health professional should know",
         ["**P** \u2013 **P**rofessional indemnity (negligence liability) \u2014 the most important",
          "**W** \u2013 **W**orkmen's/Employee's compensation (Act of 1923)",
          "**E** \u2013 **E**SI (Employees' State Insurance Act, 1948)",
          "**H** \u2013 **H**ealth / mediclaim",
          "**P** \u2013 **P**ersonal accident",
          "**L** \u2013 **L**ife insurance (+ property, equipment and cyber cover for the laboratory)"])),

('h2', "8.10  Professional Indemnity Insurance in Detail"),
('h3', "What It Covers"),
('b', [
    "**Damages/compensation** awarded by a court, consumer commission or tribunal against the insured for professional negligence.",
    "**Legal defence costs and expenses** incurred with the insurer's consent \u2014 often the largest practical benefit, since defending even a baseless claim is expensive.",
    "Claims arising from **error, omission or negligence** in the rendering of professional services.",
    "Usually available on a **'claims made'** basis \u2014 the policy must be in force when the **claim is made**, not merely when the incident occurred. Hence the importance of **continuous renewal** and of a **retroactive date**."
]),
('h3', "Common Exclusions \u2014 important, because these are what students get wrong"),
('b', [
    "**Criminal acts, deliberate or intentional wrongdoing, fraud and dishonesty** \u2014 indemnity covers *negligence*, never crime.",
    "Services rendered **while under the influence of alcohol or drugs**.",
    "Services performed **outside the insured's qualification, licence or scope of practice**.",
    "**Punitive or exemplary damages** (in many policies), and fines and statutory penalties.",
    "Liability arising from **breach of confidentiality where deliberate**, from defamation, or from a **third-party data breach** (needs separate cyber cover).",
    "**Weight-reduction, cosmetic and certain specified procedures**, and unproven or experimental treatment, in many policies.",
    "Claims arising from **war, nuclear risk, and pre-existing known claims** or circumstances not disclosed at inception.",
    "Liability assumed under a **contract** beyond common-law liability."
]),
('h3', "Practical Points"),
('n', [
    "**Choose an adequate sum insured** \u2014 awards against laboratories have risen substantially; also check the **'any one accident' (AOA)** and **'any one year' (AOY)** limits.",
    "**Renew without any break** \u2014 a lapse can destroy cover for past incidents on a claims-made policy.",
    "**Disclose all material facts** at inception and at renewal \u2014 non-disclosure voids the policy (*uberrima fides*).",
    "**Notify the insurer immediately** of any incident or legal notice, as the policy requires; delayed notification is a common ground for repudiation.",
    "**Do not admit liability or settle** a claim without the insurer's written consent \u2014 doing so may void the cover.",
    "**Cooperate fully** in the defence and preserve all records.",
    "Verify whether the **employer's institutional policy actually names or covers you**; if it does not, take individual cover \u2014 employed technologists are frequently left uninsured.",
    "Remember that insurance covers the **money**, not the **reputation or the disciplinary consequence** \u2014 it is no substitute for good practice."
]),

('h2', "8.11  Statutory Protection for the Health Worker"),
('tbl', (["Statute / Mechanism", "Protection it gives"],
         [["**Employee's Compensation Act, 1923**", "Employer's liability to pay compensation for death, disablement or **occupational disease** arising out of and in the course of employment"],
          ["**Employees' State Insurance Act, 1948**", "Medical, sickness, maternity, disablement and dependants' benefits for insured employees"],
          ["**Factories Act, 1948** (and State shops/establishment laws)", "Working hours, rest intervals, welfare and safety provisions; notification of occupational diseases"],
          ["**Bio-Medical Waste Management Rules, 2016**", "Mandatory training, immunisation of handlers and safe-handling systems \u2014 protects staff as well as the public"],
          ["**Sexual Harassment of Women at Workplace (POSH) Act, 2013**", "**Internal Complaints Committee** in every workplace with 10 or more employees; enquiry and redressal"],
          ["**Epidemic Diseases (Amendment) Act, 2020**", "Made **violence against health-care personnel** a cognizable, non-bailable offence with enhanced punishment and compensation for damage to property"],
          ["**State Medicare Service Persons and Medicare Service Institutions (Prevention of Violence) Acts**", "State-level protection against assault on health-care staff and damage to hospital property"],
          ["**AERB / Atomic Energy (Radiation Protection) Rules, 2004**", "Dose limits, personnel monitoring (TLD badges), licensing and medical surveillance for radiation workers"],
          ["**National Commission for Allied and Healthcare Professions Act, 2021**", "Statutory recognition, registration and defined scope of practice \u2014 which itself protects the professional from being made to work beyond his competence"],
          ["**Maternity Benefit Act, 1961 (amd. 2017)**", "Paid maternity leave of 26 weeks and related protections"]],
         [5.6, 11.6],
         "Statutory protections for laboratory personnel")),

('key', [
    "**Two halves:** (A) the patient as a **consumer** who can sue you; (B) you as a **worker** who needs protection and insurance.",
    "***IMA v. V.P. Shantha* (1995)** \u2014 paid medical service = 'service'; patient = 'consumer'; deficiency \u2192 compensation.",
    "**Consumer Protection Act, 2019** replaced the 1986 Act; six rights = **S-I-C-H-R-E**; three tiers = **District (\u2264 \u20b9 50 lakh) \u2192 State (\u2264 \u20b9 2 crore) \u2192 National (> \u20b9 2 crore) \u2192 Supreme Court**; limitation **2 years**; no lawyer needed; e-filing and mediation available.",
    "Under the 2019 Act, **disclosure of confidential personal information is an unfair trade practice** \u2014 so a confidentiality breach is actionable before a consumer commission.",
    "Laboratory hazards = **B-C-P-E-P-W** (biological, chemical, physical, ergonomic, psychosocial, waste).",
    "Needle-stick injury: wash with soap and water \u2192 do **not** squeeze \u2192 report at once \u2192 baseline tests \u2192 **HIV PEP within 2 hours, not beyond 72 hours, for 28 days** \u2192 HBIG + vaccine if unprotected \u2192 document and follow up at 6 weeks, 3 and 6 months.",
    "**Professional indemnity insurance** covers compensation **and legal costs** for negligence; it does **not** cover criminal acts, fraud, intoxication or practice beyond one's qualification; it is usually **'claims made'**, so continuous renewal is essential.",
    "Statutory protection: **Employee's Compensation Act 1923; ESI Act 1948; POSH Act 2013; Epidemic Diseases (Amendment) Act 2020** (violence against health workers); **BMW Rules 2016**; **AERB rules**."
]),

('tip', [
    "**Expected questions from this chapter:**",
    "- *Long (10 marks):* 'Discuss the Consumer Protection Act with reference to medical practice. Describe the consumer rights and the redressal machinery.'",
    "- *Long (10 marks):* 'Enumerate the occupational hazards of a laboratory professional and discuss the preventive measures and the types of insurance available.'",
    "- *Short (5 marks):* Consumer rights; Redressal machinery; Deficiency in service; *IMA v. V.P. Shantha*; Professional indemnity insurance; Occupational hazards of a laboratory; Needle-stick injury management; Universal precautions; Biomedical waste segregation.",
    "- *Very short (2 marks):* Who is a 'consumer'; limitation period under the CPA; three tiers of the redressal machinery; expand ESI and POSH; two biological hazards; the time window for HIV PEP.",
    "**Read the question carefully:** if it says 'consumer protection **and** insurance for professional health hazard', you must write **both** halves \u2014 roughly half the answer each. Many students lose 4\u20135 marks by writing only Part A."
]),

('qa', ("QUESTION BANK \u2014 CHAPTER 8", [
    ("Discuss the applicability of the Consumer Protection Act to medical and diagnostic services.",
     ["State the position established in ***IMA v. V.P. Shantha* (1995)**: medical services rendered for a fee are 'service' under the Act and the patient is a 'consumer', so deficiency in service is actionable before a consumer commission. Refinements: service rendered free **to everybody** is excluded; a patient treated free in a hospital that charges others **is** a consumer; payment by an insurer or employer does not affect consumer status. Add that the current law is the **Consumer Protection Act, 2019**, whose definition of 'deficiency' expressly includes **negligence** and the **deliberate withholding of information**, and which treats **disclosure of confidential personal information as an unfair trade practice**. Conclude with the practical implications for a laboratory \u2014 displayed rates, proper bills, defined turnaround times, quality systems and a grievance mechanism."]),
    ("Enumerate the rights of a consumer.",
     ["Right to safety; right to be informed; right to choose; right to be heard; right to seek redressal; right to consumer education. Explain each in one or two lines and add a diagnostic-laboratory application for each (as in the table). *(Mnemonic: S-I-C-H-R-E.)*"]),
    ("Describe the consumer dispute redressal machinery and the procedure for filing a complaint.",
     ["Three tiers: **District Commission** \u2014 value of consideration up to \u20b9 50 lakh; **State Commission** \u2014 above \u20b9 50 lakh up to \u20b9 2 crore; **National Commission** \u2014 above \u20b9 2 crore; further appeal to the **Supreme Court**. Appeals: District \u2192 State within 45 days; State \u2192 National and National \u2192 Supreme Court within 30 days.",
      "Procedure: who may complain (consumer, recognised association, Government, CCPA, legal heir); **limitation 2 years**; written complaint with nominal fee, **no lawyer required**, e-filing permitted, may be filed where the complainant resides or works; notice and reply; evidence on affidavit; summary hearing; target disposal in 3\u20135 months; **mediation** available. Reliefs: compensation (including for mental agony), refund, removal of the deficiency, re-performance of the service, discontinuation of unfair practice, punitive damages, corrective advertisement and costs. Non-compliance with an order is punishable with imprisonment and fine."]),
    ("Enumerate the occupational hazards of a medical laboratory technologist.",
     ["Classify as **biological** (needle-stick, HIV, HBV, HCV, TB, aerosols, spills), **chemical** (formalin, xylene, acids, mercury, sensitisers), **physical** (electrical, fire, burns, radiation, UV, noise, cryogenic, compressed gas), **ergonomic** (repetitive strain injury, carpal tunnel, back and neck pain from microscopy, eye strain, falls), **psychosocial** (overload, shift work, burnout, violence, harassment, moral distress) and **waste-related/environmental**. Add the preventive measures for each. *(Mnemonic: B-C-P-E-P-W.)*"]),
    ("Describe the immediate management of a needle-stick injury.",
     ["Do not panic and do **not** squeeze or suck the wound; wash with soap and running water (irrigate mucosa/eyes copiously with water or saline); avoid caustic antiseptics and scrubbing; report immediately to the supervisor and PEP officer; assess the exposure and the source patient's HIV/HBV/HCV status; baseline testing of the exposed worker; start **HIV post-exposure prophylaxis as early as possible, ideally within 2 hours and not later than 72 hours, continued for 28 days**; give **HBIG plus hepatitis B vaccine** if unvaccinated or a non-responder; no PEP exists for hepatitis C, so arrange follow-up for early detection and treatment; document in the injury register; follow up at 6 weeks, 3 months and 6 months with counselling; and perform root-cause analysis to correct the system."]),
    ("What is professional indemnity insurance? State what it covers and excludes.",
     ["Definition: a policy indemnifying a professional against his legal liability to third parties for compensation and legal defence costs arising from negligence, error or omission in the course of professional practice. **Covers:** damages awarded by a court, consumer commission or tribunal; legal defence costs; claims from error, omission or negligence; usually on a **'claims made'** basis with a retroactive date. **Excludes:** criminal acts, deliberate wrongdoing, fraud and dishonesty; services rendered under the influence of alcohol or drugs; practice beyond one's qualification or licence; fines, penalties and (often) punitive damages; deliberate breach of confidentiality and defamation; cyber/data-breach liability; war and nuclear risk; undisclosed pre-existing claims. Practical points: adequate sum insured with AOA/AOY limits, uninterrupted renewal, full disclosure, prompt notification, and no admission of liability without the insurer's consent."]),
    ("Differentiate between professional indemnity insurance and workmen's compensation insurance.",
     ["**Professional indemnity** protects the **professional against liability to a third party (the patient)** for negligence, and pays compensation and legal costs to that third party. **Workmen's/Employee's compensation insurance** covers the **employer's statutory liability to his own employee** under the Employee's Compensation Act, 1923, for death, disablement or occupational disease arising out of and in the course of employment. In short: indemnity looks **outward** to the patient's claim; workmen's compensation looks **inward** to the employee's own injury \u2014 for example a technologist who contracts hepatitis B from a needle-stick injury."]),
    ("What are universal precautions? Why are they important?",
     ["Universal (standard) precautions are a set of infection-control measures applied to **every patient and every specimen**, on the assumption that all blood and body fluids are potentially infectious, regardless of the known or presumed diagnosis. Components: hand hygiene; gloves, gown, mask and eye protection as indicated; safe injection and sharps practice with no recapping and immediate disposal into puncture-proof containers; no mouth-pipetting; safe handling and transport of specimens in leak-proof containers; disinfection of spills; safe waste segregation; hepatitis B immunisation of staff; and a PEP protocol. Importance: they protect staff, patients and the community; they remove the need to 'label' or single out infectious patients, thereby also **protecting confidentiality and preventing discrimination**; and they cover the large number of infected patients whose status is unknown."]),
    ("Write short notes on biomedical waste segregation.",
     ["Governed by the **Bio-Medical Waste Management Rules, 2016** (as amended). Segregation must occur **at the point of generation** into colour-coded containers: **yellow** \u2014 human anatomical waste, soiled waste, discarded medicines, chemical and laboratory waste, microbiological cultures (incineration or deep burial); **red** \u2014 contaminated recyclable plastic such as tubings, bottles, catheters, syringes without needles, gloves (autoclave/microwave then recycle through an authorised recycler); **white translucent puncture-proof** \u2014 sharps including needles and scalpels (autoclave/dry heat, then shred and dispose); **blue** \u2014 broken or discarded glassware and metallic implants (disinfect, then dispose). Other requirements: authorisation from the State Pollution Control Board, pre-treatment of laboratory cultures, barcoding and record keeping, staff training and immunisation, annual reports, and disposal through a Common Bio-medical Waste Treatment Facility. Non-compliance attracts penalty under the Environment (Protection) Act, 1986."]),
    ("What statutory protections are available to a health-care worker in India?",
     ["Employee's Compensation Act, 1923 (compensation for injury and occupational disease); ESI Act, 1948 (medical, sickness, maternity, disablement and dependants' benefits); Factories Act, 1948 and State establishment laws (hours, rest, welfare, safety, notification of occupational disease); Bio-Medical Waste Management Rules, 2016 (training and immunisation of handlers); **POSH Act, 2013** (Internal Complaints Committee for sexual harassment); **Epidemic Diseases (Amendment) Act, 2020** and State Medicare Service Persons (Prevention of Violence) Acts (violence against health workers made a cognizable, non-bailable offence); AERB radiation-protection rules (dose limits, TLD monitoring, medical surveillance); Maternity Benefit Act, 1961 (amended 2017); and the **National Commission for Allied and Healthcare Professions Act, 2021**, which defines scope of practice and thereby protects the professional."]),
])),

('recap', [
    "***IMA v. V.P. Shantha* (1995)** \u2192 medical service = 'service'; patient = 'consumer'.",
    "**CPA 2019** (replaced 1986). Rights = **S-I-C-H-R-E**. Limitation = **2 years**.",
    "Tiers: **District \u2264 \u20b9 50 lakh | State \u2264 \u20b9 2 crore | National > \u20b9 2 crore \u2192 Supreme Court**.",
    "2019 additions: **CCPA, product liability, e-commerce, mediation, e-filing**; confidentiality breach = unfair trade practice.",
    "Hazards = **B-C-P-E-P-W**: Biological, Chemical, Physical, Ergonomic, Psychosocial, Waste.",
    "Needle-stick \u2192 wash, don't squeeze, report, baseline test, **PEP \u2264 2 h (max 72 h) \u00d7 28 days**, HBIG if unprotected, follow up 6 wk/3 mo/6 mo.",
    "**Professional indemnity** = negligence liability + legal costs; **excludes** crime, fraud, intoxication, practice beyond qualification.",
    "Worker protection: **EC Act 1923, ESI 1948, POSH 2013, Epidemic Diseases (Amd) 2020, BMW Rules 2016**.",
]),

]
