# -*- coding: utf-8 -*-
"""Chapter 9 - Time Management"""

BLOCKS = [

('ch', (9, "Time Management",
        "Principles \u2022 Eisenhower matrix \u2022 Pareto principle \u2022 Time wasters \u2022 Techniques \u2022 Application in the laboratory")),

('h2', "9.1  Introduction"),
('p', "Time is the only resource that is **absolutely equal for everyone and absolutely non-renewable**. Every professional gets 24 hours; the difference between an efficient laboratory and a chaotic one is entirely a matter of how those hours are used. In a clinical laboratory, time is not merely a matter of personal efficiency \u2014 it is a matter of **patient safety and of ethics**. A troponin report delayed by two hours, a crossmatch delayed by twenty minutes, or a critical potassium left in the printer overnight can kill a patient. **Turnaround time is an ethical parameter.**"),
('def', ("Time Management",
         "Time management is the process of **planning, organising, prioritising and controlling** the way one spends one's time in order to accomplish specific goals and tasks **effectively and efficiently**, with the least waste of effort and the least avoidable stress.",
         ["Strictly speaking, time cannot be managed \u2014 it passes at a fixed rate. What is actually managed is **oneself in relation to time**; hence time management is really **self-management**.",
          "**Efficiency** = doing the task with the least waste of resources (*doing things right*). **Effectiveness** = doing the *right* task, the one that actually matters (*doing the right things*). A good professional needs both, but **effectiveness comes first** \u2014 there is no value in performing an unnecessary task very efficiently."])),
('quote', ("Until we can manage time, we can manage nothing else.", "Peter Drucker")),

('h2', "9.2  Importance / Benefits of Time Management"),
('n', [
    "**Improved patient safety and outcomes** \u2014 timely results permit timely treatment; delay causes harm.",
    "**Reduced turnaround time (TAT)** \u2014 the principal quality indicator of any diagnostic laboratory.",
    "**Higher productivity** \u2014 more work of better quality in the same hours.",
    "**Better quality and fewer errors** \u2014 hurry is the commonest cause of mislabelling and transcription error; good planning removes hurry.",
    "**Reduced stress, anxiety and burnout** \u2014 the strongest personal benefit; poor time management is a major *cause* of stress (see Chapter 10).",
    "**Meeting deadlines and commitments** reliably \u2014 which builds professional credibility.",
    "**Better patient and clinician satisfaction** \u2014 and consequently fewer complaints and lawsuits.",
    "**Time for professional development** \u2014 reading, CMEs, teaching, research.",
    "**Better work\u2013life balance**, adequate sleep, family time and health.",
    "**Greater job satisfaction and a sense of control** \u2014 the feeling of being on top of one's work rather than buried under it.",
    "**Economy** \u2014 time saved is money saved; idle instruments and idle staff are wasted capital.",
    "**Improved teamwork** \u2014 one person's delay is the whole team's delay; punctuality is a form of respect for colleagues.",
    "**Better decision-making** \u2014 decisions taken under time pressure are demonstrably worse."
]),

('h2', "9.3  Principles of Time Management"),
('n', [
    "**Set clear goals** \u2014 write them down. Use the **SMART** framework: **S**pecific, **M**easurable, **A**chievable, **R**elevant, **T**ime-bound.",
    "**Plan in advance** \u2014 a daily plan made the previous evening or first thing in the morning; a weekly and monthly plan for larger tasks. *Every minute spent planning saves several minutes in execution.*",
    "**Prioritise** \u2014 distinguish the **important** from the merely **urgent** (Eisenhower matrix); apply the **80/20 rule**.",
    "**Make a to-do list**, keep it in one place only, and review and tick items off; carry forward what is undone.",
    "**Do one thing at a time** \u2014 single-tasking. **Multitasking is a myth**: the brain switches rather than parallel-processes, and every switch costs time and increases error. In a laboratory, multitasking during labelling or pipetting is a direct cause of patient harm.",
    "**Do the most important/difficult task first**, at your peak-energy time (**'eat the frog'**).",
    "**Batch similar tasks** \u2014 group all calls, all data entry, all quality-control runs; batching reduces set-up time and mental switching.",
    "**Break large tasks into small steps** \u2014 'chunking' makes a daunting task startable.",
    "**Set deadlines for yourself**, including internal deadlines ahead of the real one.",
    "**Learn to say 'no'** \u2014 politely and assertively, to requests that are not yours to accept.",
    "**Delegate** \u2014 assign what can be done by others, with clear instructions and follow-up; delegation multiplies your time but never transfers your accountability.",
    "**Avoid procrastination** \u2014 use the **two-minute rule** (anything taking under two minutes, do it now) and the **five-minute start** (just begin for five minutes).",
    "**Control interruptions** \u2014 designated 'quiet' periods, silenced phone during critical procedures, a policy that visitors are seen at defined times.",
    "**Use the right tools** \u2014 LIS, barcoding, autoanalysers, checklists, standard forms, calendar reminders. Automation is time management embedded in technology.",
    "**Standardise with SOPs and checklists** \u2014 a standardised process is a fast process.",
    "**Avoid perfectionism** on low-value tasks \u2014 apply the effort proportionate to the importance.",
    "**Build in buffer time** \u2014 never plan at 100 % capacity; emergencies are certain to arrive.",
    "**Schedule rest and recreation deliberately** \u2014 fatigue destroys speed and accuracy; breaks are an investment, not a loss.",
    "**Review and monitor** \u2014 keep a time log for a few days, analyse where the time actually went, and correct.",
    "**Handle paper and email once** \u2014 the '**touch it once**' or **4 D's** rule: **D**o it, **D**elegate it, **D**efer it (with a date), or **D**elete/**D**ump it."
]),
('mne', ("\u201CP-L-A-N-N-E-D\u201D \u2014 principles of time management",
         ["**P** \u2013 **P**rioritise (urgent vs important)",
          "**L** \u2013 **L**ist (to-do list, written)",
          "**A** \u2013 **A**void procrastination and time wasters",
          "**N** \u2013 **N**o \u2014 learn to say it assertively",
          "**N** \u2013 **N**ote and review (time log, audit)",
          "**E** \u2013 **E**liminate interruptions; **E**at the frog first",
          "**D** \u2013 **D**elegate, and **D**eadline everything"])),

('h2', "9.4  The Eisenhower Matrix (Urgent\u2013Important Matrix / Time Management Matrix)"),
('p', "This is **the** most examinable tool in the chapter. Draw the 2 \u00d7 2 box \u2014 a diagram is worth several marks. It was popularised by **Stephen Covey** in *The 7 Habits of Highly Effective People*, based on a distinction attributed to President Dwight D. Eisenhower."),
('tbl', (["", "**URGENT**", "**NOT URGENT**"],
         [["**IMPORTANT**",
           "**QUADRANT I \u2014 'DO IT NOW' (Crisis / Necessity)**\n- Critical value to be telephoned\n- STAT sample from casualty or ICU\n- Emergency crossmatch for a bleeding patient\n- Analyser breakdown during a busy run\n- Frozen section during ongoing surgery\n*Action:* **Do it immediately, personally.**\n*Danger:* living permanently here \u2192 stress and burnout",
           "**QUADRANT II \u2014 'PLAN IT' (Quality / Prevention)**\n- Preventive maintenance and calibration\n- Writing and updating SOPs\n- Training, CME, reading, teaching\n- Planning, audit, EQAS participation\n- Building relationships; health and exercise\n*Action:* **Schedule it \u2014 protect this time.**\n**This is the quadrant of effectiveness. Investing here shrinks Quadrant I.**"],
          ["**NOT IMPORTANT**",
           "**QUADRANT III \u2014 'DELEGATE / MINIMISE' (Deception)**\n- Most ringing telephones and 'quick' queries\n- Unnecessary meetings\n- Routine data entry and dispatch\n- Other people's minor requests and interruptions\n*Action:* **Delegate, or handle briefly; learn to say no.**\n*Danger:* feels productive but achieves little",
           "**QUADRANT IV \u2014 'ELIMINATE' (Waste)**\n- Idle gossip and chatting at the bench\n- Aimless social media and phone scrolling\n- Trivial paperwork of no value\n- Excessive tea breaks\n*Action:* **Eliminate ruthlessly.**"]],
         [2.4, 7.4, 7.4],
         "The Eisenhower / Covey Time Management Matrix \u2014 draw this diagram")),
('key', [
    "**Urgent** = demands immediate attention; **Important** = contributes to your goals and results. They are **not** the same thing.",
    "Most people spend their day in **Quadrant I and III** (reacting) and feel exhausted with little achieved.",
    "**Effective professionals live in Quadrant II** \u2014 planning, prevention, maintenance, training. Time invested in Quadrant II **prevents** Quadrant I crises.",
    "In laboratory terms: doing preventive maintenance and QC on schedule (Q-II) prevents the mid-run analyser breakdown (Q-I). Writing a critical-value SOP (Q-II) prevents the 3 a.m. panic (Q-I)."
]),

('h2', "9.5  The Pareto Principle (80/20 Rule)"),
('def', ("Pareto Principle",
         "Formulated from the observation of the Italian economist **Vilfredo Pareto**, it states that roughly **80 % of the results come from 20 % of the causes or efforts**, and conversely that 80 % of the effort produces only 20 % of the results. The managerial lesson is to **identify and concentrate on the vital 20 %**.")),
('b', [
    "About **20 % of the tests** performed in a laboratory account for about **80 % of the workload** \u2014 so automating or streamlining those few tests yields the greatest gain.",
    "About **20 % of the causes** account for about **80 % of the errors** \u2014 hence root-cause analysis targets the vital few (typically patient identification and labelling).",
    "About **20 % of the tasks** on your to-do list will produce **80 % of the value** \u2014 identify them and do them first.",
    "About **20 % of clients/wards** generate **80 % of the queries or complaints** \u2014 address those wards specifically.",
    "Related idea \u2014 **Parkinson's Law**: *'Work expands so as to fill the time available for its completion.'* Therefore set **tight, realistic deadlines**; a task given a whole day will take a whole day.",
    "Related idea \u2014 **Murphy's Law**: 'If anything can go wrong, it will.' Hence always build **buffer time**."
]),

('h2', "9.6  Time Wasters"),
('tbl', (["External time wasters (from others / the system)", "Internal time wasters (from oneself)"],
         [["Frequent **telephone calls** and 'just one quick question' interruptions", "**Procrastination** \u2014 postponing what should be done now"],
          ["**Unannounced visitors** and chatty colleagues at the bench", "**Lack of goals, planning and priorities** \u2014 working without a plan"],
          ["**Long, unstructured, unnecessary meetings**", "**Disorganisation** \u2014 cluttered bench, misplaced registers, time spent searching"],
          ["**Waiting** \u2014 for samples, for reagents, for a doctor to answer, for the analyser to finish", "**Inability to say 'no'** \u2014 accepting every request"],
          ["**Poor systems and duplicated paperwork**; no SOPs; unclear responsibilities", "**Failure to delegate**, or reluctance to trust others"],
          ["**Equipment breakdown**, LIS downtime, power failure", "**Multitasking** and constant task-switching"],
          ["**Understaffing and constant crises**", "**Perfectionism** on unimportant tasks"],
          ["**Rework** \u2014 repeat samples, corrected reports, re-runs caused by earlier error", "**Poor decision-making** and indecision; revisiting decisions repeatedly"],
          ["**Unclear or shifting instructions from superiors**", "**Social media, mobile phone and idle browsing**"],
          ["**Commuting and physical layout** \u2014 badly arranged workspace forcing extra movement", "**Fatigue, poor health and inadequate sleep** \u2014 which slow everything"],
          ["**Attendants demanding information** repeatedly because they were not properly informed the first time", "**Gossip and non-work conversation**"],
          ["**Unnecessary or duplicate test requests** from wards", "**Inability to concentrate**; daydreaming; stress and worry"]],
         [8.6, 8.6],
         "Time wasters \u2014 classify into external and internal")),

('h2', "9.7  Techniques and Tools of Time Management"),
('tbl', (["Technique", "How it works", "Where to use it in the laboratory"],
         [["**To-do list / Daily task list**", "Write every task in one place; prioritise A/B/C; tick off as completed; carry forward the rest", "Start-of-shift list: QC, pending re-runs, calls to make, maintenance due"],
          ["**ABC analysis**", "**A** = must do today (high value); **B** = should do (medium); **C** = nice to do (low). Do all A's before any B", "A = critical values and STAT samples; B = routine reports; C = filing old registers"],
          ["**Eisenhower matrix**", "Classify by urgency \u00d7 importance into four quadrants", "See section 9.4"],
          ["**Pareto / 80-20 analysis**", "Identify the vital few tasks or causes producing most of the result", "Streamline the 20 % of tests that make up most of the workload"],
          ["**Time log / Time audit**", "Record activity in 15\u201330 minute blocks for 3\u20135 days, then analyse the pattern", "Reveals how much time is actually lost to interruptions and searching"],
          ["**Pomodoro technique**", "Work in focused blocks of about **25 minutes** with a 5-minute break; a longer break after four blocks", "Data entry, report verification, study and revision"],
          ["**Time boxing / Time blocking**", "Allocate a fixed block in the calendar to a specific activity and protect it", "'2\u20133 p.m. \u2014 maintenance and calibration, no calls'"],
          ["**'Eat the frog'**", "Do the most difficult or most unpleasant important task first thing", "Complete the pending EQAS submission before the day's rush"],
          ["**Two-minute rule**", "If it takes less than two minutes, do it immediately rather than listing it", "Signing a register, sending a short reply, restocking a rack"],
          ["**Batching**", "Group similar tasks and do them together", "All telephone calls at one time; all slides stained in one batch; all reports verified together"],
          ["**Delegation**", "Assign the task with clear instruction, authority and a deadline; then follow up", "Assign dispatch and filing to an attendant; assign stock indenting to a junior"],
          ["**Standardisation \u2014 SOPs and checklists**", "A written standard removes decision time and prevents rework", "Pre-analytical checklist; start-of-day instrument checklist"],
          ["**Automation and IT**", "Machines and software absorb repetitive work", "Barcoding, autoverification rules, LIS interfacing, auto-dilution"],
          ["**Lean / 5S workplace organisation**", "**Sort, Set in order, Shine, Standardise, Sustain** \u2014 a place for everything and everything in its place", "Reagent and consumable storage; workstation layout to minimise movement"],
          ["**Workflow mapping / process mapping**", "Draw the actual path of a sample and remove every unnecessary step, wait and movement", "Reduce TAT by re-siting the centrifuge next to the receiving counter"],
          ["**Prime time / peak-energy scheduling**", "Do demanding work at your personal peak alertness", "Microscopy and result verification early in the shift, not at the end of a night duty"],
          ["**Saying 'no' assertively**", "Decline politely with a reason and, where possible, an alternative", "'I cannot run this now without valid labelling; send a labelled sample and I will prioritise it.'"],
          ["**Buffer / contingency time**", "Leave 15\u201325 % of the schedule unallocated", "Protects against the inevitable emergency sample"],
          ["**Meeting discipline**", "Fixed agenda, fixed start and end time, action points with owners and dates", "Weekly quality meeting kept to 30 minutes"]],
         [3.4, 6.8, 7.0],
         "Techniques and tools of time management")),

('h2', "9.8  Time Management in the Clinical Laboratory \u2014 Practical Application"),
('def', ("Turnaround Time (TAT)",
         "The time interval between a defined start point and a defined end point in the testing process \u2014 most usefully measured from the **time the test is ordered (or the sample collected) to the time the result is available to and acted upon by the clinician**. TAT is the most visible quality indicator of a laboratory and the commonest source of clinician dissatisfaction.",
         ["**Total (therapeutic) TAT** \u2014 order to clinical action; what the patient actually experiences.",
          "**Laboratory (intra-laboratory) TAT** \u2014 sample receipt to result release; the part the laboratory fully controls.",
          "Phases: **pre-pre-analytical** (order, collection, transport), **pre-analytical** (receipt, accessioning, centrifugation, aliquoting), **analytical** (the run itself), **post-analytical** (verification, release, reporting) and **post-post-analytical** (receipt and action by the clinician)."])),
('h3', "Where Time Is Actually Lost in a Laboratory \u2014 and How to Save It"),
('tbl', (["Phase", "Common time loss", "Time-saving action"],
         [["**Ordering & collection**", "Illegible or incomplete requisition; waiting for the phlebotomist; repeated punctures; wrong tube collected", "Electronic order entry; scheduled phlebotomy rounds; trained phlebotomists; a printed tube-selection chart at the collection counter"],
          ["**Transport**", "Batch transport once every few hours; samples waiting for a runner; wrong temperature causing rejection", "Fixed frequent transport slots; pneumatic tube system; dedicated STAT transport; validated transport boxes"],
          ["**Receipt & accessioning**", "Manual register entry; searching for the requisition; queue at the receiving counter", "**Barcoding** and LIS interfacing; separate STAT receiving window; single-piece flow rather than batching"],
          ["**Centrifugation & preparation**", "Waiting to fill the centrifuge; repeated re-spins; manual aliquoting", "Smaller, more frequent spins; gel tubes; automated aliquoting; site the centrifuge next to receiving"],
          ["**Analysis**", "Batching until the analyser is full; frequent breakdowns; repeated recalibration; reagent not available", "Random-access analysers; **preventive maintenance schedule**; reagent inventory with reorder levels; back-up method for critical tests"],
          ["**Verification & release**", "All reports waiting for one person's signature; manual transcription", "**Autoverification** rules for normal results; delegated authorisation levels; exception-based review; electronic signature"],
          ["**Reporting**", "Printed reports waiting for dispatch; report not reaching the ward", "LIS/portal delivery; SMS/e-mail alerts (secure); defined critical-value calling protocol"],
          ["**Rework (the biggest hidden loss)**", "Repeat sampling for haemolysis, clots, wrong tube, insufficient volume, mislabelling", "Get it right first time: training, checklists, bedside labelling, correct order of draw. **Prevention is the greatest time-saver of all**"]],
         [3.2, 6.8, 7.2],
         "Reducing turnaround time \u2014 phase by phase")),
('h3', "A Model Shift Plan for a Laboratory Technologist"),
('n', [
    "**First 15 minutes:** hand-over from the previous shift; read the communication register; note pending and re-run samples; check the critical-value register.",
    "**Next 20 minutes:** start-of-day checks \u2014 instrument start-up, temperature records of refrigerators and water baths, reagent levels, **run internal quality control** and verify it is acceptable **before** any patient sample.",
    "**Then:** attend to **STAT and emergency samples first**, always \u2014 these are Quadrant I.",
    "**Main run:** process routine samples in the planned batch sequence; label and verify identity at every transfer.",
    "**Throughout:** telephone any critical value **immediately** as it arises, with read-back and documentation \u2014 never postpone it to the end of the shift.",
    "**Mid-shift:** a short planned break \u2014 fatigue causes errors; step away from the bench.",
    "**Quiet period (a scheduled Quadrant II block):** preventive maintenance, calibration, stock indenting, SOP review, EQAS samples, documentation, training.",
    "**Before the shift ends:** complete all documentation and registers; verify and release pending reports; segregate and dispose of waste; clean and disinfect the workstation.",
    "**Last 10 minutes:** a clear, structured **hand-over** \u2014 pending work, unresolved problems, instrument status, and anything the next shift must watch for. A good hand-over saves the next shift an hour.",
    "**Weekly:** review the TAT data and the rejection log; identify the vital few causes (Pareto) and act on them."
]),

('h2', "9.9  Procrastination"),
('def', ("Procrastination",
         "The voluntary and irrational **postponement of an intended course of action** despite the expectation of being worse off for the delay \u2014 'putting off until tomorrow what should be done today'.")),
('tbl', (["Cause", "Remedy"],
         [["The task feels **too large or overwhelming**", "**Break it into small steps** ('chunking'); do only the first step"],
          ["**Fear of failure or of criticism**; perfectionism", "Aim for 'good enough' on a first draft; remember that a completed imperfect task beats a perfect unstarted one"],
          ["The task is **unpleasant or boring**", "**'Eat the frog'** \u2014 do it first; pair it with a reward; batch it with something pleasant"],
          ["**No clear deadline**", "Set a self-imposed deadline and tell someone about it (**accountability**)"],
          ["**Unclear about how to start**", "Define the very next physical action in concrete terms; ask for guidance"],
          ["**Distractions available**", "Remove the phone; block the time; change location"],
          ["**Low energy / fatigue**", "Schedule the task at peak-energy time; sleep and exercise adequately"],
          ["**Task is genuinely not important**", "Then **decide consciously to drop it** \u2014 that is a decision, not procrastination"]],
         [7.6, 9.6],
         "Causes of procrastination and their remedies")),
('b', [
    "Useful anti-procrastination devices: the **two-minute rule**; the **five-minute start** (commit to only five minutes); the **Pomodoro** timer; **'do the worst first'**; **public commitment**; and **breaking the task into a checklist** so progress is visible."
]),

('h2', "9.10  Barriers to Effective Time Management"),
('b', [
    "**Understaffing and genuine work overload** \u2014 the commonest real barrier in Indian laboratories; no technique can substitute for adequate staff.",
    "**Unpredictable emergency workload** in a hospital setting.",
    "**Poor systems** \u2014 no SOPs, no barcoding, manual registers, duplicated paperwork.",
    "**Frequent equipment breakdown** and reagent stock-outs.",
    "**Poor physical layout** forcing unnecessary movement.",
    "**Hierarchical culture** \u2014 inability to say no to a senior's non-urgent request.",
    "**Constant interruptions** by telephone and attendants; no protected time.",
    "**Lack of training** in prioritisation and in the use of the LIS.",
    "**Poor delegation** \u2014 either no one to delegate to, or unwillingness to let go.",
    "**Personal factors** \u2014 procrastination, disorganisation, perfectionism, fatigue, stress, health problems, family responsibilities, long commuting.",
    "**Absence of measurement** \u2014 if TAT is not measured, it cannot be improved."
]),

('key', [
    "Time management is really **self-management**; time itself cannot be managed.",
    "**Efficiency = doing things right; Effectiveness = doing the right things.** Effectiveness first.",
    "**SMART goals**: Specific, Measurable, Achievable, Relevant, Time-bound.",
    "**Eisenhower matrix:** Q-I urgent+important = **do now**; Q-II important, not urgent = **plan/schedule (the key to effectiveness)**; Q-III urgent, not important = **delegate**; Q-IV neither = **eliminate**.",
    "**Pareto 80/20** \u2014 concentrate on the vital 20 %. **Parkinson's Law** \u2014 work expands to fill the time available, so set tight deadlines.",
    "**Multitasking is a myth** and is a direct cause of laboratory error \u2014 single-task, especially while labelling and pipetting.",
    "Time wasters are **external** (calls, visitors, meetings, waiting, breakdowns, rework) and **internal** (procrastination, no plan, disorganisation, inability to say no, perfectionism, multitasking).",
    "Techniques: to-do list, ABC analysis, Eisenhower matrix, time log, **Pomodoro**, time blocking, eat-the-frog, two-minute rule, batching, delegation, SOPs, automation, **5S**, workflow mapping, buffer time.",
    "**TAT (turnaround time)** is the laboratory's key time indicator; **rework is the biggest hidden time loss**, so prevention (correct identification and labelling) is the greatest time-saver.",
    "Anti-procrastination: chunking, five-minute start, deadlines with accountability, eat the frog."
]),

('tip', [
    "**Do not underestimate this chapter \u2014 examiners frequently set a full 10-mark question on it precisely because it looks 'easy'.**",
    "- *Long (10 marks):* 'Define time management. Discuss its importance, principles and techniques with special reference to a clinical laboratory.'",
    "- *Long (10 marks):* 'What are time wasters? Explain the Eisenhower matrix and the techniques available to improve time management.'",
    "- *Short (5 marks):* Eisenhower/time-management matrix; Pareto principle; Time wasters; Procrastination; SMART goals; Turnaround time; Delegation; Pomodoro technique.",
    "- *Very short (2 marks):* Expand SMART; state Parkinson's Law; define TAT; two internal time wasters; what is the 80/20 rule.",
    "**Presentation tip:** **draw the Eisenhower 2 \u00d7 2 matrix** with laboratory examples in each quadrant. It is the fastest way to make this answer look like a topper's answer. Then add the two-column time-waster table."
]),

('qa', ("QUESTION BANK \u2014 CHAPTER 9", [
    ("Define time management and state its importance for a laboratory professional.",
     ["Definition as in section 9.1, with the point that it is really **self-management**, and the distinction between **efficiency** (doing things right) and **effectiveness** (doing the right things).",
      "Importance: patient safety through timely results; reduced turnaround time; higher productivity; fewer errors, because hurry causes mislabelling; reduced stress and burnout; reliable deadlines and professional credibility; patient and clinician satisfaction with fewer complaints and lawsuits; time for professional development; work\u2013life balance; job satisfaction and a sense of control; economy of resources; better teamwork; and better decisions. Conclude that in a laboratory **turnaround time is an ethical parameter**, not merely a managerial one."]),
    ("Explain the Eisenhower time-management matrix with laboratory examples.",
     ["Draw the 2 \u00d7 2 matrix (urgency \u00d7 importance). **Q-I urgent + important \u2192 do now:** critical value to be telephoned, STAT sample from casualty, emergency crossmatch, analyser breakdown mid-run. **Q-II important, not urgent \u2192 schedule:** preventive maintenance, calibration, SOP writing, training and CME, audit, EQAS, health. **Q-III urgent, not important \u2192 delegate/minimise:** most telephone interruptions, unnecessary meetings, routine dispatch. **Q-IV neither \u2192 eliminate:** gossip, aimless social media, trivial paperwork. Key conclusion: effective professionals live in **Quadrant II**, and investment there shrinks Quadrant I crises; those trapped in Q-I and Q-III burn out while achieving little."]),
    ("What are time wasters? Classify them with examples.",
     ["Time wasters are activities that consume time without producing proportionate value. **External:** telephone interruptions, unannounced visitors, long unnecessary meetings, waiting for samples/reagents/doctors, poor systems and duplicated paperwork, equipment breakdown and LIS downtime, understaffing, **rework** caused by earlier error, unclear instructions, poor layout, repeated queries from uninformed attendants, unnecessary test requests. **Internal:** procrastination, lack of goals and planning, disorganisation, inability to say no, failure to delegate, multitasking, perfectionism, indecision, social media and mobile phone, fatigue and poor health, gossip, inability to concentrate. Add the remedies briefly."]),
    ("Describe any six techniques of time management.",
     ["Choose six from: to-do list with ABC prioritisation; Eisenhower matrix; Pareto 80/20 analysis; time log/audit; **Pomodoro** (25-minute focused blocks); time blocking; 'eat the frog'; two-minute rule; batching similar tasks; delegation; SOPs and checklists; automation and barcoding; **5S** workplace organisation; workflow mapping to cut TAT; peak-energy scheduling; assertive refusal; buffer time; meeting discipline. Explain each in two or three lines with a laboratory application."]),
    ("What is procrastination? State its causes and remedies.",
     ["Definition as in section 9.9. Causes: the task feels overwhelming; fear of failure and perfectionism; the task is unpleasant or boring; no clear deadline; not knowing how to start; available distractions; low energy and fatigue; and the task genuinely not being important. Remedies: chunk the task into small steps; aim for 'good enough'; **eat the frog** \u2014 do it first; set self-imposed deadlines with public accountability; define the very next physical action; remove distractions; schedule at peak energy; the **two-minute rule** and the **five-minute start**; and consciously decide to drop truly unimportant tasks."]),
    ("Write short notes on the Pareto principle and Parkinson's Law.",
     ["**Pareto principle (80/20 rule):** roughly 80 % of results come from 20 % of causes or efforts; therefore identify and concentrate on the vital few. Laboratory applications: 20 % of tests generate 80 % of the workload; 20 % of causes produce 80 % of errors (chiefly identification and labelling); 20 % of tasks yield 80 % of value. **Parkinson's Law:** 'work expands so as to fill the time available for its completion' \u2014 hence set tight, realistic deadlines, because a task allotted a whole day will consume a whole day. Mention **Murphy's Law** as the reason for building buffer time."]),
    ("What is turnaround time? How can it be reduced?",
     ["Definition and phases as in section 9.8, distinguishing **total/therapeutic TAT** (order to clinical action) from **laboratory TAT** (receipt to release). Reduction, phase by phase: electronic order entry and trained phlebotomy; frequent scheduled transport or a pneumatic tube; **barcoding** and LIS interfacing with a separate STAT window; smaller frequent centrifuge runs sited near receiving; random-access analysers with **preventive maintenance** and reagent inventory control; **autoverification** with exception-based review and delegated authorisation; electronic report delivery with a critical-value calling protocol; and above all **elimination of rework** by getting identification, labelling, tube selection and volume right the first time. Add that TAT must be **measured and audited** as a quality indicator."]),
    ("Enumerate the principles of time management.",
     ["Set SMART goals; plan in advance; prioritise urgent versus important; keep a single written to-do list; single-task rather than multitask; do the most important task first at peak energy; batch similar tasks; break large tasks into steps; set self-deadlines; learn to say no; delegate with clear instructions; avoid procrastination using the two-minute rule; control interruptions; use tools and automation; standardise with SOPs and checklists; avoid perfectionism on low-value work; build buffer time; schedule rest deliberately; review with a time log; and handle each item once using the 4 D's \u2014 **Do, Delegate, Defer, Dump**. *(Mnemonic: PLANNED.)*"]),
    ("How would you organise your shift as a laboratory technologist to manage time effectively?",
     ["Reproduce the model shift plan: structured hand-over and review of the communication and critical-value registers; start-of-day instrument, temperature and reagent checks with **QC verified before any patient sample**; STAT and emergency samples first; planned batch processing of routine work with identity verified at every transfer; critical values telephoned immediately with read-back and documentation; a planned mid-shift break to prevent fatigue-related error; a protected quiet block for Quadrant II work \u2014 maintenance, calibration, indenting, SOP review, EQAS, training; completion of documentation, report release, waste segregation and workstation disinfection before the end of the shift; a clear structured hand-over in the last ten minutes; and a weekly review of TAT and rejection data using Pareto analysis."]),
    ("What are the barriers to effective time management in a hospital laboratory?",
     ["Understaffing and genuine overload; unpredictable emergency workload; poor systems with no SOPs or barcoding; frequent equipment breakdown and reagent stock-outs; poor physical layout; hierarchical culture preventing assertive refusal; constant interruptions with no protected time; lack of training in prioritisation and in LIS use; poor or impossible delegation; personal factors such as procrastination, disorganisation, perfectionism, fatigue, ill health, family responsibility and long commuting; and the absence of measurement \u2014 unmeasured TAT cannot be improved. Conclude that individual technique must be supported by **system and management change**."]),
])),

('recap', [
    "Time management = **self-management**. Effectiveness before efficiency.",
    "**SMART** goals; **PLANNED** principles; write **one** to-do list.",
    "**Eisenhower:** Q-I do now | **Q-II schedule (the key)** | Q-III delegate | Q-IV eliminate.",
    "**Pareto 80/20** \u2192 vital few. **Parkinson** \u2192 tight deadlines. **Murphy** \u2192 buffer time.",
    "**Multitasking causes errors.** Single-task while labelling and pipetting.",
    "Tools: ABC, time log, **Pomodoro (25 min)**, time blocking, eat the frog, 2-minute rule, batching, delegation, SOPs, automation, **5S**.",
    "**TAT** is the key indicator; **rework is the biggest time thief** \u2014 so prevention saves the most time.",
    "Procrastination \u2192 chunk it, start for five minutes, deadline it, eat the frog.",
]),

]
