# -*- coding: utf-8 -*-
"""Chapter 10 - Stress Management"""

BLOCKS = [

('ch', (10, "Stress Management",
        "Stress \u2022 GAS \u2022 Eustress vs distress \u2022 Causes \u2022 Effects \u2022 Burnout \u2022 Coping \u2022 Relaxation techniques")),

('h2', "10.1  Introduction"),
('p', "Health care is consistently ranked among the most stressful occupations in the world. A laboratory professional works with **infectious material, expensive equipment, unforgiving deadlines, life-and-death results, night duties and demanding attendants** \u2014 often with inadequate staff and little recognition. Stress in this setting is not a personal weakness; it is an **occupational hazard** (see Chapter 8, psychosocial hazards). Unmanaged, it produces error, illness, absenteeism, burnout and the loss of good professionals from the field. **Stress management is therefore both a personal survival skill and a patient-safety measure.**"),

('h2', "10.2  Definitions and Basic Concepts"),
('def', ("Stress",
         "Stress is the **non-specific response of the body to any demand made upon it** (**Hans Selye**, 1936 \u2014 the 'Father of Stress Research'). In psychological terms, it is the state of **physical, mental and emotional tension** that arises when the **demands placed on a person exceed his perceived ability or resources to cope** with them.",
         ["The word derives from the Latin *stringere*, 'to draw tight'.",
          "**Key insight \u2014 stress is a function of *perception*.** The same night duty is exciting for one technologist and terrifying for another. Stress = (perceived demand) \u2212 (perceived ability to cope). This is why *cognitive* strategies work."])),
('def', ("Stressor",
         "Any **stimulus, event, situation, person or demand \u2014 internal or external, physical or psychological \u2014 that produces stress** in an individual. Stressors may be acute (a single needle-stick injury) or chronic (perpetual understaffing).")),
('def', ("Stress response / Strain",
         "The **physiological, psychological and behavioural reaction** of the individual to a stressor \u2014 tachycardia, sweating, anxiety, irritability, insomnia, and so on.")),
('def', ("Coping",
         "The **constantly changing cognitive and behavioural efforts** made by a person to manage specific external or internal demands that are appraised as taxing or exceeding his resources (**Lazarus & Folkman**).")),
('def', ("Adaptation",
         "The process by which an individual adjusts successfully to a stressor and restores equilibrium (**homeostasis**).")),
('def', ("Stress Management",
         "The **set of techniques, strategies and skills** used to identify stressors, to control the level of stress, and to cope with stress in a way that preserves physical health, mental well-being, professional performance and quality of life.")),

('h2', "10.3  Types of Stress"),
('tbl', (["Type", "Meaning", "Example", "Effect"],
         [["**Eustress** ('good stress')", "Positive, motivating, energising stress that is within the person's coping capacity", "Preparing for an examination; taking charge of a new analyser; a challenging but achievable target", "**Improves** performance, motivation, learning and satisfaction"],
          ["**Distress** ('bad stress')", "Negative, excessive or prolonged stress that exceeds coping capacity", "Chronic understaffing; fear of a lawsuit; abuse by attendants; a night duty after a sleepless day", "**Impairs** performance, health, judgement and relationships"],
          ["**Hyperstress**", "Overload \u2014 too much demand in too little time", "Twelve STAT samples arriving together during a single-handed night shift", "Panic, error, exhaustion"],
          ["**Hypostress**", "Understimulation \u2014 boredom and monotony", "Weeks of repetitive routine work with no challenge or learning", "Apathy, disengagement, carelessness"],
          ["**Acute stress**", "Short-term, from an immediate threat; resolves quickly", "A needle-stick injury; a sudden analyser failure mid-run", "Intense but usually reversible"],
          ["**Episodic acute stress**", "Repeated bouts of acute stress in a person who lives in crisis", "The colleague who is always late and always in a crisis", "Hypertension, migraine, cardiac risk"],
          ["**Chronic stress**", "Prolonged, unrelenting stress", "Years of overwork, financial strain, or a hostile supervisor", "**The most damaging type** \u2014 leads to illness and burnout"],
          ["**Traumatic stress**", "Following exposure to a life-threatening or horrifying event", "A mass-casualty incident; assault by an attendant", "May lead to acute stress reaction or **PTSD**"]],
         [2.9, 4.7, 5.0, 4.6],
         "Types of stress \u2014 the eustress/distress distinction is essential")),
('warn', ["**A crucial concept: stress is not inherently bad.** The **Yerkes\u2013Dodson law** states that performance improves as arousal (stress) increases, but only **up to an optimum point**, beyond which further stress causes performance to deteriorate sharply \u2014 an **inverted-U curve**. Too little stress (hypostress) causes boredom and carelessness; the optimum produces peak performance; excess causes error and collapse. **The aim of stress management is therefore not to abolish stress but to keep it at the optimum level.** State this in every answer \u2014 it distinguishes a good answer from an average one."]),

('h2', "10.4  General Adaptation Syndrome (GAS) \u2014 Hans Selye, 1936"),
('p', "**This is the single most examinable item in the chapter.** Selye described a triphasic, non-specific bodily response to any prolonged stressor. Draw the three stages as a flow diagram."),
('flow', ["**STAGE 1 \u2014 ALARM REACTION (\u2018fight-or-flight\u2019)**\nImmediate recognition of the stressor. **Sympatho-adrenal activation:** adrenaline and noradrenaline released; HPA axis activated \u2192 CRH \u2192 ACTH \u2192 **cortisol**. Tachycardia, rise in blood pressure, rapid breathing, pupillary dilatation, sweating, dry mouth, raised blood glucose, blood diverted to muscle, digestion inhibited, alertness heightened. **Resistance is temporarily *below* normal, then rises.**",
          "**STAGE 2 \u2014 STAGE OF RESISTANCE (ADAPTATION)**\nThe body attempts to adapt and cope. Cortisol remains elevated; outward symptoms subside and the person appears to be functioning normally. Resistance is **above** normal, but at the cost of continuous consumption of physiological reserves. If the stressor is removed here, **full recovery occurs**. If it persists, reserves are steadily depleted.",
          "**STAGE 3 \u2014 STAGE OF EXHAUSTION**\nAdaptive reserves are depleted. Resistance falls **below** normal. Sustained high cortisol causes immunosuppression, hypertension, hyperglycaemia, peptic ulceration, muscle wasting and impaired healing. Clinically: fatigue, burnout, depression, anxiety, frequent infections, and the '**diseases of adaptation**' \u2014 hypertension, coronary artery disease, peptic ulcer, diabetes, asthma, autoimmune disease. Ultimately collapse, illness or (in extremis) death."]),
('key', [
    "**Selye's GAS = Alarm \u2192 Resistance \u2192 Exhaustion.** Learn the sequence and the resistance-level change in each stage (below normal \u2192 above normal \u2192 below normal).",
    "Key hormones: **adrenaline and noradrenaline** (immediate, sympathetic) and **cortisol** (sustained, via the **HPA axis**: hypothalamus \u2192 CRH \u2192 pituitary \u2192 ACTH \u2192 adrenal cortex \u2192 cortisol).",
    "Selye called the resulting disorders the **'diseases of adaptation'**.",
    "**Fight-or-flight** was described by **Walter Cannon**; **homeostasis** is also his term. **Allostasis** = achieving stability through change; **allostatic load** = the cumulative wear and tear of chronic stress.",
    "**Yerkes\u2013Dodson law** \u2192 the inverted-U relationship between arousal and performance."
]),
('h3', "Physiology in Brief \u2014 What Actually Happens"),
('tbl', (["System", "Acute stress response", "Consequence of chronic stress"],
         [["**Neuroendocrine**", "Sympathetic discharge; adrenaline/noradrenaline; HPA axis \u2192 cortisol", "Sustained hypercortisolaemia; HPA dysregulation; disturbed circadian rhythm"],
          ["**Cardiovascular**", "Tachycardia, raised blood pressure, increased cardiac output, vasoconstriction", "**Hypertension, coronary artery disease, arrhythmia, stroke**"],
          ["**Respiratory**", "Tachypnoea, bronchodilatation", "Hyperventilation, aggravation of **asthma**"],
          ["**Gastrointestinal**", "Digestion inhibited, dry mouth, nausea", "**Peptic ulcer, gastritis, irritable bowel syndrome**, appetite change, obesity"],
          ["**Metabolic**", "Hyperglycaemia, lipolysis, glycogenolysis", "**Type 2 diabetes**, dyslipidaemia, central obesity, metabolic syndrome"],
          ["**Immune**", "Transient enhancement, then suppression", "**Immunosuppression** \u2192 frequent infections, delayed wound healing, reactivation of latent infection; autoimmune flare"],
          ["**Musculoskeletal**", "Muscle tension, tremor", "**Tension headache**, neck and back pain, bruxism, fibromyalgia-like pain"],
          ["**Reproductive**", "Suppression of gonadal axis", "Menstrual irregularity, reduced libido, subfertility, aggravated premenstrual symptoms"],
          ["**Central nervous / psychological**", "Heightened alertness, anxiety", "**Insomnia, anxiety disorder, depression, memory and concentration impairment, burnout**; hippocampal effects of chronic cortisol"],
          ["**Skin**", "Sweating, pallor or flushing", "Aggravation of **eczema, psoriasis, acne, alopecia**, urticaria"]],
         [3.2, 6.4, 7.6],
         "Physiological and pathological effects of stress \u2014 system by system")),

('h2', "10.5  Causes of Stress (Stressors)"),
('h3', "A. Occupational Stressors of a Laboratory Professional"),
('n', [
    "**Work overload** \u2014 excessive sample load, understaffing, unrealistic turnaround-time expectations.",
    "**Time pressure and constant urgency** \u2014 STAT samples, emergency crossmatches, simultaneous demands.",
    "**Fear of error and of its consequences** \u2014 a single mislabelled tube can kill; fear of litigation and disciplinary action is a powerful chronic stressor.",
    "**Shift work and night duty** \u2014 circadian disruption, sleep deprivation, disturbed meals and family life.",
    "**Exposure to biological and chemical hazards** \u2014 the constant, low-grade fear after a needle-stick injury, and the wait for follow-up serology, is intensely stressful.",
    "**Violence, abuse and aggression from patients and attendants**; verbal abuse over a delayed report.",
    "**Role ambiguity and role conflict** \u2014 unclear responsibilities, or being asked to do work outside one's competence.",
    "**Moral distress** \u2014 knowing the right thing to do but being prevented from doing it: being pressed to release results despite failed QC, or to backdate a report.",
    "**Poor interpersonal relations** \u2014 a hostile supervisor, bullying, an uncooperative ward, inter-departmental friction.",
    "**Lack of recognition, autonomy and career progression**; poor pay relative to responsibility; being treated as 'only a technician'.",
    "**Equipment breakdown and resource shortage** \u2014 responsibility without the means to discharge it.",
    "**Repetitive, monotonous work** in some sections (hypostress).",
    "**Physical environment** \u2014 noise, heat, crowding, poor ergonomics, standing for long hours.",
    "**Exposure to human suffering and death** \u2014 handling paediatric oncology samples, post-mortem specimens, positive HIV reports on young patients.",
    "**Organisational change** \u2014 new LIS, new accreditation requirements, restructuring.",
    "**Job insecurity** \u2014 contractual employment, outsourcing."
]),
('h3', "B. Personal, Social and Environmental Stressors"),
('b', [
    "**Life events** \u2014 the *Holmes\u2013Rahe Social Readjustment Rating Scale* ranks life events by the 'life change units' they impose: death of a spouse (100), divorce (73), marital separation (65), imprisonment, death of a close family member, personal injury or illness, marriage (50), loss of job, retirement, pregnancy, financial change, change of residence, and so on. A high cumulative score in one year predicts an increased risk of illness.",
    "**Family and interpersonal** \u2014 marital discord, care of children or elderly parents, illness in the family, conflict with in-laws.",
    "**Financial** \u2014 debt, loans, insufficient income, medical expenses.",
    "**Academic** \u2014 examinations, results, competition, fear of failure.",
    "**Health** \u2014 personal illness, chronic pain, disability, sleep disorder.",
    "**Social** \u2014 discrimination, isolation, loss of social support, migration, urban living.",
    "**Environmental** \u2014 noise, pollution, traffic and long commuting, overcrowding, extreme weather.",
    "**Daily hassles** \u2014 the cumulative effect of small everyday irritations is now recognised to be as damaging as major life events.",
    "**Internal / personality stressors** \u2014 perfectionism, unrealistic expectations, pessimistic thinking, low self-esteem, inability to say no, poor time management, negative self-talk.",
    "**Type A personality** \u2014 competitive, impatient, hostile, time-urgent; described by **Friedman and Rosenman** and associated with a higher risk of coronary artery disease. **Type B** is relaxed and easy-going; **Type D** ('distressed') is characterised by negative affectivity and social inhibition, also linked to cardiac risk."
]),

('h2', "10.6  Signs and Symptoms of Stress"),
('tbl', (["Domain", "Manifestations"],
         [["**Physical**", "Headache; neck, shoulder and back pain; palpitations; chest discomfort; breathlessness; dry mouth; sweating; tremor; dizziness; fatigue and exhaustion; indigestion, acidity, nausea, altered bowel habit; loss or increase of appetite; weight change; **insomnia** or excessive sleep; frequent minor infections such as colds; menstrual irregularity; teeth grinding; skin flare-ups; reduced libido"],
          ["**Emotional**", "Anxiety, worry, tension, restlessness; **irritability, anger, short temper**; mood swings; sadness and depression; feeling overwhelmed; helplessness and hopelessness; loss of confidence; emotional numbness; crying easily; guilt; loss of a sense of humour"],
          ["**Cognitive**", "Poor concentration; **forgetfulness and memory lapses** (a direct cause of laboratory error); indecisiveness; racing thoughts; negative thinking and catastrophising; reduced creativity; impaired judgement; constant worry; mental 'fog'"],
          ["**Behavioural**", "**Increased errors and near-misses**; procrastination or, conversely, frantic overwork; **absenteeism and lateness**; presenteeism (present but unproductive); withdrawal from colleagues; increased **smoking, alcohol, caffeine or drug use**; overeating or skipping meals; nail-biting, fidgeting, pacing; aggressive or rude behaviour; neglect of appearance; accidents and injuries; **short-cutting of safety procedures**"],
          ["**Interpersonal / occupational**", "Conflict with colleagues, patients and family; loss of empathy and a cynical, detached attitude to patients; blaming others; deteriorating teamwork; falling productivity and quality; thoughts of leaving the job"]],
         [3.2, 14.0],
         "Manifestations of stress \u2014 present under these five headings")),

('h2', "10.7  Burnout"),
('def', ("Burnout",
         "A **syndrome of emotional exhaustion, depersonalisation (cynicism) and reduced personal accomplishment**, resulting from chronic, unmanaged **workplace** stress (**Christina Maslach**). The WHO's ICD-11 classifies burnout as an **occupational phenomenon** \u2014 not a medical condition \u2014 arising specifically from chronic workplace stress that has not been successfully managed.")),
('h3', "The Three Dimensions of Burnout (Maslach Burnout Inventory)"),
('n', [
    "**Emotional exhaustion** \u2014 feeling drained, depleted, unable to face another shift; the core dimension. 'I have nothing left to give.'",
    "**Depersonalisation / Cynicism** \u2014 a detached, callous, negative attitude towards patients and colleagues; patients become 'the specimens', 'the cases'; loss of empathy; dark humour at patients' expense.",
    "**Reduced personal accomplishment / Inefficacy** \u2014 a sense of incompetence, futility and lack of achievement. 'Nothing I do makes any difference.'"
]),
('mne', ("\u201CE-D-R\u201D \u2014 the triad of burnout",
         ["**E** \u2013 **E**motional exhaustion (drained)",
          "**D** \u2013 **D**epersonalisation / cynicism (detached, callous)",
          "**R** \u2013 **R**educed personal accomplishment (ineffective, futile)"])),
('h3', "Stages, Consequences and Prevention"),
('b', [
    "**Stages:** the honeymoon (enthusiasm) \u2192 onset of stress \u2192 chronic stress \u2192 burnout \u2192 habitual burnout (entrenched, requiring intervention).",
    "**Consequences for the patient:** increased medical errors, reduced quality, longer turnaround times, poor communication, loss of empathy, reduced professionalism \u2014 burnout is therefore a **patient-safety problem**.",
    "**Consequences for the professional:** depression, anxiety, substance misuse, physical illness, relationship breakdown, absenteeism, and departure from the profession.",
    "**Consequences for the organisation:** high turnover, absenteeism, low morale, litigation, cost of replacement.",
    "**Individual prevention:** boundary-setting, adequate sleep, exercise, hobbies, social support, reflective practice, peer support groups, professional counselling when needed, mindfulness.",
    "**Organisational prevention (more important, and often omitted in exam answers):** adequate staffing; rational rosters with recovery time after nights; realistic workloads; **blame-free error reporting**; recognition and fair reward; autonomy and participation in decisions; clear roles; career pathways; training; a functional grievance mechanism; **zero tolerance of violence and harassment**; and access to occupational health and counselling services.",
    "Distinguish also **compassion fatigue** \u2014 the emotional exhaustion arising specifically from repeated empathic engagement with suffering; and **moral injury/moral distress** \u2014 the damage caused by being prevented from doing what one knows to be right."
]),
('warn', ["**Burnout vs Depression vs Compassion fatigue \u2014 do not confuse them:**",
          "- **Burnout** is **work-specific**; the person typically feels better away from work; the core features are exhaustion, cynicism and inefficacy.",
          "- **Depression** is **pervasive** \u2014 it affects all domains of life, with persistent low mood, anhedonia, guilt, disturbed sleep and appetite, and possibly suicidal ideation. It is a **medical diagnosis requiring treatment**.",
          "- **Compassion fatigue** arises from repeated empathic exposure to others' trauma and suffering, with features overlapping secondary traumatic stress.",
          "Burnout untreated can **progress to depression**; if there is any suicidal ideation, immediate professional help is essential."]),

('h2', "10.8  Stress Management \u2014 Coping Strategies"),
('h3', "A. Classification of Coping"),
('tbl', (["Type of coping", "Meaning", "Example", "Best used when"],
         [["**Problem-focused (task-oriented)**", "Acting on the **stressor itself** to change or remove it", "Requesting extra staff; getting the analyser repaired; learning the new LIS; making a roster change; obtaining PEP after a needle-stick", "The stressor **is controllable** \u2014 this is the most effective form of coping"],
          ["**Emotion-focused**", "Managing the **emotional response** when the stressor cannot be changed", "Relaxation, exercise, talking to a friend, reframing, acceptance, prayer, humour", "The stressor is **uncontrollable** (a bereavement, an incurable illness in the family)"],
          ["**Meaning-focused / Appraisal-focused**", "Changing the **way one thinks** about the stressor", "Cognitive restructuring: 'This night duty is a chance to learn independent decision-making'", "Always useful as an adjunct"],
          ["**Social-support seeking**", "Drawing on others for practical help, information and emotional support", "Debriefing with a colleague after a difficult incident; a peer-support group", "Almost always beneficial"],
          ["**Maladaptive / Avoidant coping \u2717**", "Escaping rather than dealing with the stressor", "**Alcohol, smoking, drugs, overeating, denial, aggression, absenteeism, self-blame, withdrawal**", "**Never** \u2014 gives short-term relief and long-term damage. Must be identified and replaced"]],
         [3.4, 4.2, 5.4, 4.2],
         "Types of coping \u2014 problem-focused for what you can change, emotion-focused for what you cannot")),
('h3', "B. Individual Strategies \u2014 Physical"),
('b', [
    "**Regular physical exercise** \u2014 at least 30 minutes of moderate activity on most days (about 150 minutes a week); the single most effective and best-evidenced stress-reducer. It metabolises stress hormones, releases endorphins, improves sleep and improves mood.",
    "**Adequate sleep** \u2014 7\u20138 hours, with **sleep hygiene**: a fixed schedule, a dark quiet cool room, no screens or caffeine before bed, and (for night workers) blackout curtains and a protected daytime sleep period. Sleep deprivation both causes stress and is caused by it.",
    "**Balanced nutrition** \u2014 regular meals, no meal-skipping during shifts, adequate hydration; limit caffeine (especially after mid-afternoon), and avoid using sugar or junk food as a coping device.",
    "**Avoid alcohol, tobacco and other drugs** as coping devices \u2014 they worsen sleep, anxiety and health.",
    "**Regular medical check-ups**; treat hypertension, diabetes and thyroid disease; complete hepatitis B vaccination.",
    "**Ergonomic care and micro-breaks** \u2014 stretch, look away from the microscope, change posture; the 20-20-20 rule for screens.",
    "**Yoga and pranayama** \u2014 well-evidenced for reducing anxiety and blood pressure."
]),
('h3', "C. Individual Strategies \u2014 Psychological / Cognitive"),
('b', [
    "**Identify your own stressors** \u2014 keep a brief **stress diary** for two weeks noting the situation, your reaction and what helped.",
    "**Cognitive restructuring** \u2014 identify and challenge distorted automatic thoughts: catastrophising ('I will be sued'), all-or-nothing thinking, over-generalisation, mind-reading, 'should' statements. Replace them with realistic appraisals.",
    "**Positive self-talk** and realistic optimism.",
    "**Accept what cannot be changed**; distinguish clearly between what is within your control and what is not, and invest effort only in the former.",
    "**Set realistic expectations** and abandon perfectionism \u2014 aim for excellence in what matters, not flawlessness in everything.",
    "**Assertiveness training** \u2014 learn to say 'no' and to state your needs (see Chapter 4); much stress is simply unexpressed grievance.",
    "**Time management** \u2014 Chapter 9 is a stress-management chapter in disguise; poor prioritisation is a major generator of stress.",
    "**Problem-solving skills** \u2014 define the problem, list options, evaluate, choose, act, review.",
    "**Ventilation** \u2014 talk about it; write about it (expressive writing has measurable benefit).",
    "**Humour** \u2014 a well-recognised adaptive coping mechanism (but never at a patient's expense).",
    "**Mindfulness** \u2014 non-judgemental awareness of the present moment; **Mindfulness-Based Stress Reduction (MBSR)** has strong evidence in health-care workers.",
    "**Spirituality, prayer and meditation** \u2014 significant sources of resilience for many people.",
    "**Professional help** \u2014 counselling, cognitive behavioural therapy (CBT), and psychiatric treatment when there is depression, an anxiety disorder or substance dependence. **Seeking help is a strength, not a weakness.**"
]),
('h3', "D. Individual Strategies \u2014 Relaxation Techniques (learn these by name)"),
('tbl', (["Technique", "How it is done"],
         [["**Deep / diaphragmatic breathing**", "Sit comfortably; inhale slowly through the nose expanding the abdomen; hold briefly; exhale slowly through the mouth. The **4-7-8 pattern** (inhale 4, hold 7, exhale 8) or simple paced breathing at about 6 breaths per minute activates the parasympathetic system. Effective within minutes and can be done at the bench"],
          ["**Jacobson's Progressive Muscle Relaxation (PMR)**", "Systematically tense each muscle group for about 5\u201310 seconds and then release for 20\u201330 seconds, working from the feet upwards to the face, while noticing the contrast between tension and relaxation"],
          ["**Meditation**", "Focused attention on the breath, a word or an object, allowing thoughts to pass without engagement; 10\u201320 minutes daily"],
          ["**Mindfulness (MBSR)**", "Deliberate, non-judgemental attention to present-moment experience; includes body scan, mindful breathing and mindful daily activity"],
          ["**Yoga and *pranayama***", "Combination of *asanas* (postures), breath regulation and meditation; *shavasana* is a classic relaxation posture; *anulom-vilom* and *bhramari* are commonly taught"],
          ["**Guided imagery / visualisation**", "Vividly imagining a calm, safe, pleasant place using all the senses"],
          ["**Autogenic training**", "Self-suggestion of warmth and heaviness in the limbs to induce relaxation"],
          ["**Biofeedback**", "Using instruments to display heart rate, muscle tension or skin conductance so that the person learns voluntary control"],
          ["**Massage, hydrotherapy, warm bath**", "Physical reduction of muscle tension"],
          ["**Music therapy, art, hobbies, gardening, pets**", "Diversional activities that reliably lower arousal"],
          ["**Laughter therapy**", "Voluntary laughter exercises; reduces cortisol and improves mood"],
          ["**Grounding / '5-4-3-2-1' technique**", "Name 5 things you can see, 4 you can touch, 3 you can hear, 2 you can smell, 1 you can taste \u2014 rapidly interrupts acute panic"]],
         [4.6, 12.6],
         "Relaxation techniques \u2014 name at least five in any answer")),
('h3', "E. Social Strategies"),
('b', [
    "**Build and maintain a social support network** \u2014 family, friends, colleagues; social support is one of the strongest known buffers against stress.",
    "**Peer support and debriefing** after a difficult incident (a death, an error, an assault).",
    "**Work\u2013life balance** \u2014 protect time for family, hobbies, worship and rest; do not take work home habitually.",
    "**Communicate** \u2014 much stress arises from unresolved conflict that was never voiced.",
    "**Take your leave** \u2014 planned holidays and genuine days off, with the phone off.",
    "**Join professional associations** \u2014 a sense of collective identity and shared experience reduces isolation.",
    "**Mentorship** \u2014 for juniors, a mentor is a powerful protective factor.",
    "**Help others / volunteer** \u2014 altruism is associated with lower stress and higher meaning."
]),
('h3', "F. Organisational Strategies (do not omit these \u2014 they carry marks)"),
('n', [
    "**Adequate staffing and rational workload norms.**",
    "**Well-designed rosters** \u2014 forward-rotating shifts, adequate recovery after nights, predictable schedules, no excessive consecutive duties.",
    "**Clear job descriptions**, defined scope of practice and reporting lines \u2014 removing role ambiguity and role conflict.",
    "**Participation in decision-making** and reasonable autonomy \u2014 low control with high demand is the classic recipe for occupational stress (**Karasek's demand\u2013control model**).",
    "**Blame-free incident-reporting and just culture** \u2014 systems, not scapegoats; this single change removes an enormous burden of fear.",
    "**Recognition and fair reward**, career progression, and respect for the allied-health professional's status.",
    "**Training and competency development**, including induction and periodic updates \u2014 competence reduces anxiety.",
    "**Adequate resources** \u2014 functioning equipment, reagents in stock, PPE available.",
    "**Ergonomic and safe workplace design**, with rest areas and a place to eat.",
    "**Zero tolerance of violence and harassment**; security arrangements; a functional **Internal Complaints Committee (POSH Act, 2013)**.",
    "**Occupational health services** \u2014 immunisation, PEP protocol, periodic health check-ups, and confidential **employee assistance/counselling programmes**.",
    "**Grievance redressal mechanism** that is used and trusted.",
    "**Stress-management and communication-skills training** as part of continuing education.",
    "**Team-building activities** and recognition events; supportive supervision rather than policing."
]),
('mne', ("\u201CS-T-R-E-S-S-E-D\u201D \u2014 an eight-point personal action plan",
         ["**S** \u2013 **S**leep adequately (7\u20138 hours; protect daytime sleep after nights)",
          "**T** \u2013 **T**ime management and prioritisation",
          "**R** \u2013 **R**elaxation daily (breathing, PMR, meditation, yoga)",
          "**E** \u2013 **E**xercise regularly (about 150 minutes a week)",
          "**S** \u2013 **S**ocial support \u2014 talk, share, debrief",
          "**S** \u2013 **S**ay 'no' assertively; set boundaries",
          "**E** \u2013 **E**at well; avoid alcohol, tobacco and excess caffeine",
          "**D** \u2013 **D**iversion (hobbies) and **D**octor/counsellor when needed"])),

('h2', "10.9  Stress and Patient Safety \u2014 The Professional Argument"),
('b', [
    "A stressed, sleep-deprived technologist makes **more identification, labelling, transcription and pipetting errors**.",
    "Stress narrows attention (**'tunnel vision'**), so warning signs and flags are missed.",
    "Stress impairs **working memory** \u2014 hence a verbal result is misheard and misrecorded.",
    "Stress erodes **empathy first** \u2014 producing the rudeness that generates complaints and lawsuits.",
    "Stressed staff **take short-cuts with safety procedures** \u2014 not wearing gloves, recapping needles, skipping QC.",
    "**Burnout is statistically associated with increased medical error.**",
    "Therefore stress management is **not a welfare luxury but a core patient-safety and risk-management activity** \u2014 make this your concluding sentence."
]),

('key', [
    "**Stress** = the non-specific response of the body to any demand (**Selye, 1936**); psychologically, demand exceeding perceived coping ability. **Perception is central.**",
    "**Eustress** (positive, motivating) vs **distress** (negative, harmful); also hyperstress, hypostress, acute, episodic acute, chronic and traumatic stress.",
    "**Yerkes\u2013Dodson law** \u2014 inverted-U: performance is best at an **optimum** level of arousal. The goal is optimisation, not elimination.",
    "**GAS = Alarm \u2192 Resistance \u2192 Exhaustion** (Selye). Adrenaline/noradrenaline acutely; **cortisol** via the **HPA axis**; 'diseases of adaptation' in exhaustion.",
    "**Fight-or-flight** and **homeostasis** \u2014 Walter Cannon. **Allostatic load** = cumulative wear of chronic stress.",
    "Effects are **physical, emotional, cognitive, behavioural and interpersonal**; chronic stress causes hypertension, CAD, diabetes, peptic ulcer, immunosuppression, insomnia, anxiety and depression.",
    "**Burnout (Maslach) = Emotional exhaustion + Depersonalisation/cynicism + Reduced personal accomplishment**; classified by WHO ICD-11 as an **occupational phenomenon**.",
    "**Burnout is work-specific; depression is pervasive.** Compassion fatigue arises from empathic exposure to suffering.",
    "Coping: **problem-focused** (when the stressor is controllable \u2014 most effective), **emotion-focused** (when it is not), meaning-focused, social support; and **maladaptive/avoidant** (alcohol, denial, withdrawal), which must be replaced.",
    "Relaxation techniques: deep/diaphragmatic breathing, **Jacobson's PMR**, meditation, **MBSR mindfulness**, yoga and *pranayama*, guided imagery, autogenic training, biofeedback, music, laughter therapy, 5-4-3-2-1 grounding.",
    "**Organisational measures matter more than individual ones** \u2014 staffing, rosters, autonomy, just culture, recognition, safety, POSH committee, occupational health and counselling.",
    "**Stress management is a patient-safety measure**, because stress and burnout increase error."
]),

('tip', [
    "**Expected questions from this chapter:**",
    "- *Long (10 marks):* 'Define stress. Describe the General Adaptation Syndrome, the causes and effects of stress, and the measures for its management in a health-care setting.'",
    "- *Long (10 marks):* 'What is burnout? Discuss the occupational stressors of a laboratory professional and the individual and organisational strategies to manage stress.'",
    "- *Short (5 marks):* GAS/Selye's stages; Eustress vs distress; Burnout; Coping mechanisms; Relaxation techniques; Occupational stressors in a laboratory; Yerkes\u2013Dodson law; Type A personality; Effects of chronic stress.",
    "- *Very short (2 marks):* Who described GAS and in which year; expand MBSR and PMR; name the three stages of GAS; two types of stress; the three components of burnout; which hormone is the main stress hormone (**cortisol**).",
    "**Presentation tip:** **draw the three stages of GAS as a flow diagram** and add the resistance-level change at each stage; then give the effects under the five domain headings; then split management into **individual (physical / psychological / relaxation / social)** and **organisational**. Finish with the patient-safety argument \u2014 it shows professional maturity."
]),

('qa', ("QUESTION BANK \u2014 CHAPTER 10", [
    ("Define stress and describe the General Adaptation Syndrome.",
     ["Definition as in section 10.2 (Selye, 1936), noting that stress depends on **perceived** demand versus **perceived** coping ability.",
      "**GAS \u2014 three stages.** **1. Alarm reaction:** recognition of the stressor; sympatho-adrenal discharge with adrenaline and noradrenaline; HPA axis activation (CRH \u2192 ACTH \u2192 **cortisol**); tachycardia, raised blood pressure, tachypnoea, sweating, pupillary dilatation, hyperglycaemia, blood diverted to muscle, digestion inhibited; resistance initially dips then rises. **2. Stage of resistance (adaptation):** the body adapts, symptoms subside, resistance is above normal but reserves are being consumed; complete recovery is possible if the stressor is removed here. **3. Stage of exhaustion:** reserves depleted, resistance falls below normal; sustained cortisol causes immunosuppression, hypertension, hyperglycaemia and peptic ulceration; clinically fatigue, burnout, depression, infection, and the **'diseases of adaptation'** \u2014 hypertension, coronary artery disease, peptic ulcer, diabetes, asthma, autoimmune disease. Draw the three-stage flow diagram."]),
    ("Differentiate between eustress and distress.",
     ["**Eustress** \u2014 positive, motivating stress within coping capacity; improves performance, learning and satisfaction; example: preparing for an examination or taking charge of a new analyser. **Distress** \u2014 negative, excessive or prolonged stress exceeding coping capacity; impairs performance, health, judgement and relationships; example: chronic understaffing or fear of litigation. Add the **Yerkes\u2013Dodson inverted-U law** \u2014 performance peaks at an optimum level of arousal \u2014 and conclude that the aim of stress management is to **optimise, not abolish**, stress. Mention also hyperstress and hypostress."]),
    ("Enumerate the occupational stressors of a medical laboratory technologist.",
     ["Work overload and understaffing; time pressure and constant urgency; **fear of error and of litigation**; shift work, night duty and sleep deprivation; exposure to biological and chemical hazards and the anxiety following a needle-stick injury; violence and verbal abuse from attendants; role ambiguity and role conflict; **moral distress** at being pressed to release doubtful results; poor interpersonal relations, hostile supervision and bullying; lack of recognition, autonomy and career progression, with inadequate pay; equipment breakdown and resource shortage; monotony in some sections (hypostress); adverse physical environment \u2014 noise, heat, crowding, poor ergonomics, long standing; exposure to suffering and death; organisational change; and job insecurity in contractual employment."]),
    ("Describe the effects of chronic stress on the body.",
     ["Present system by system: **neuroendocrine** \u2014 sustained hypercortisolaemia and HPA dysregulation; **cardiovascular** \u2014 hypertension, coronary artery disease, arrhythmia, stroke; **respiratory** \u2014 hyperventilation, aggravated asthma; **gastrointestinal** \u2014 peptic ulcer, gastritis, irritable bowel syndrome, appetite and weight change; **metabolic** \u2014 type 2 diabetes, dyslipidaemia, central obesity; **immune** \u2014 immunosuppression with frequent infection, delayed wound healing, autoimmune flare; **musculoskeletal** \u2014 tension headache, neck and back pain, bruxism; **reproductive** \u2014 menstrual irregularity, reduced libido, subfertility; **psychological** \u2014 insomnia, anxiety, depression, impaired memory and concentration, burnout; **skin** \u2014 eczema, psoriasis, acne, alopecia. Add the behavioural consequences: increased errors, absenteeism, substance use and short-cutting of safety procedures."]),
    ("What is burnout? Describe its components, causes and prevention.",
     ["Definition (Maslach; WHO ICD-11 \u2014 an **occupational phenomenon** arising from unmanaged chronic workplace stress). **Three components:** emotional exhaustion; depersonalisation/cynicism; reduced personal accomplishment. Stages: honeymoon \u2192 onset of stress \u2192 chronic stress \u2192 burnout \u2192 habitual burnout. Causes: chronic overload, long hours and night duty, low control with high demand, lack of recognition and reward, unfairness, value conflict and moral distress, inadequate resources, and exposure to suffering. Consequences: increased medical error and poorer patient care; depression, substance misuse and illness in the professional; turnover and absenteeism for the organisation. Prevention: **individual** \u2014 boundaries, sleep, exercise, hobbies, social and peer support, mindfulness, counselling; **organisational (more important)** \u2014 adequate staffing, rational rosters, realistic workload, just culture with blame-free reporting, recognition, autonomy, clear roles, training, resources, zero tolerance of violence, occupational health and employee-assistance programmes. Distinguish from depression (pervasive) and compassion fatigue."]),
    ("Discuss the coping strategies for stress.",
     ["Classify: **problem-focused** \u2014 act on the stressor itself; the most effective approach when the stressor is controllable (request staff, repair the analyser, learn the LIS, obtain PEP). **Emotion-focused** \u2014 manage the emotional response when the stressor cannot be changed (relaxation, exercise, sharing, acceptance, prayer, humour). **Meaning/appraisal-focused** \u2014 cognitive restructuring of how the stressor is viewed. **Social-support seeking** \u2014 debriefing, peer groups, family. **Maladaptive/avoidant coping** \u2014 alcohol, tobacco, drugs, overeating, denial, aggression, absenteeism and withdrawal \u2014 which give short-term relief and long-term harm and must be identified and replaced. Conclude with the rule: **change the stressor if you can; change your response if you cannot.**"]),
    ("Describe any five relaxation techniques.",
     ["**Deep/diaphragmatic breathing** \u2014 slow abdominal breathing, e.g. the 4-7-8 pattern or paced breathing at about 6 per minute, activating the parasympathetic system. **Jacobson's progressive muscle relaxation** \u2014 systematic tensing and releasing of muscle groups from feet to face. **Meditation and mindfulness (MBSR)** \u2014 non-judgemental focused attention on the present moment. **Yoga and *pranayama*** \u2014 postures, breath regulation and *shavasana*. **Guided imagery/visualisation** \u2014 vivid imagining of a calm, safe place. Others: autogenic training, biofeedback, massage and warm baths, music and art therapy, laughter therapy, and the **5-4-3-2-1 grounding technique** for acute panic."]),
    ("What organisational measures can reduce stress among laboratory staff?",
     ["Adequate staffing and rational workload norms; well-designed forward-rotating rosters with recovery after night duty; clear job descriptions and defined scope of practice; participation in decision-making and reasonable autonomy (**Karasek's demand\u2013control model** \u2014 high demand with low control is the most damaging combination); a **blame-free, just culture** of incident reporting; recognition, fair reward and career progression; training and competency development; adequate equipment, reagents and PPE; ergonomic workplace design with rest and eating areas; zero tolerance of violence and harassment with security and a **POSH Internal Complaints Committee**; occupational health services including immunisation, PEP and periodic check-ups; confidential counselling/employee-assistance programmes; a trusted grievance mechanism; stress-management and communication training; and team-building with supportive rather than punitive supervision."]),
    ("Write short notes on Type A personality.",
     ["Described by **Friedman and Rosenman**. Features: excessive competitiveness and achievement-orientation; chronic **time urgency** and impatience; hostility, aggressiveness and irritability; rapid, emphatic speech; doing several things at once; difficulty in relaxing and guilt when idle. Significance: associated with a higher incidence of **coronary artery disease and hypertension**, hostility being the most cardiotoxic component. Contrast with **Type B** \u2014 relaxed, patient, non-competitive, lower cardiac risk \u2014 and **Type D** ('distressed') \u2014 negative affectivity plus social inhibition, also linked to adverse cardiac outcomes. Management: awareness, cognitive restructuring, relaxation training, realistic goal-setting and hostility reduction."]),
    ("How does stress affect patient safety in a laboratory?",
     ["Stress and sleep deprivation increase identification, labelling, transcription and pipetting errors; stress produces attentional narrowing or 'tunnel vision' so that flags and warning signs are missed; it impairs working memory, so verbal results are misheard and misrecorded; it erodes empathy first, producing the rudeness that generates complaints and litigation; stressed staff take short-cuts with safety procedures such as gloves, needle disposal and quality control; and **burnout is statistically associated with increased medical error**. Therefore stress management is a **core patient-safety and risk-management activity**, not a welfare luxury, and the employer has both an ethical and a legal interest in providing it."]),
])),

('recap', [
    "Stress = non-specific response to demand (**Selye 1936**); depends on **perception**.",
    "**GAS: Alarm \u2192 Resistance \u2192 Exhaustion**; adrenaline acutely, **cortisol** via **HPA axis**; 'diseases of adaptation'.",
    "**Eustress** helps, **distress** harms; **Yerkes\u2013Dodson inverted-U** \u2192 optimise, don't abolish.",
    "Effects: physical, emotional, cognitive, behavioural, interpersonal.",
    "**Burnout = Exhaustion + Depersonalisation + Reduced accomplishment** (Maslach; WHO ICD-11 occupational phenomenon).",
    "Burnout is **work-specific**; depression is **pervasive**.",
    "Coping: **problem-focused** if controllable, **emotion-focused** if not; avoid **alcohol/denial/withdrawal**.",
    "Relaxation: breathing, **Jacobson PMR**, meditation, **MBSR**, yoga, imagery, biofeedback.",
    "Personal plan = **S-T-R-E-S-S-E-D**; and **organisational fixes matter most**.",
    "Stress management = **patient-safety measure**.",
]),

]
