# -*- coding: utf-8 -*-
"""Chapter 11 - Leadership Qualities and Team Work in Health Care Professionals"""

BLOCKS = [

('ch', (11, "Leadership Qualities and Team Work in Health Care Professionals",
        "Leadership \u2022 Styles \u2022 Theories \u2022 Qualities \u2022 Teams \u2022 Tuckman \u2022 Conflict resolution \u2022 Team failure")),

('h2', "11.1  Introduction"),
('p', "No diagnostic result is ever produced by one person. Between the clinician's order and the treatment decision stand a nurse, a phlebotomist, a courier, a receptionist, a technologist, a pathologist and a data-entry operator. **A laboratory result is a team product**, and it fails at whichever link is weakest. Similarly, no laboratory improves without someone who sets direction, secures resources, resolves conflict and holds the standard \u2014 that is **leadership**. This chapter therefore closes the syllabus by asking: how do professionals work *together*, and who takes them forward?"),
('p', "Note an important point for your answer: in health care, leadership is **not** the same as holding a senior post. A technologist who stops an unsafe run, who trains a junior properly, or who insists that a critical value be telephoned, is exercising leadership \u2014 this is called **'leadership at every level'** or **followership-leadership**."),

('h2', "11.2  Leadership \u2014 Definition and Concepts"),
('def', ("Leadership",
         "Leadership is the **process of influencing, motivating, guiding and directing** the behaviour and work of others towards the achievement of a common goal, in a manner that gains their willing cooperation and confidence.",
         ["**Keith Davis:** 'Leadership is the ability to persuade others to seek defined objectives enthusiastically.'",
          "**Peter Drucker:** 'The only definition of a leader is someone who has followers.'",
          "**Core elements:** (i) a **leader**, (ii) **followers**, (iii) a **shared goal**, (iv) **influence** (not force), and (v) a **situation/context**."])),
('def', ("Leader vs Manager \u2014 and why the difference matters",
         "A **manager** administers existing systems to produce predictable results; a **leader** creates direction and change and takes people with him. Health care needs both, and in practice most senior professionals must be both.")),
('tbl', (["Basis", "**Leader**", "**Manager**"],
         [["Focus", "**Doing the right things** \u2014 effectiveness, direction, vision", "**Doing things right** \u2014 efficiency, systems, procedures"],
          ["Basis of authority", "**Personal influence**, trust, credibility \u2014 followers choose to follow", "**Formal/positional authority** conferred by the organisation"],
          ["Orientation", "**Change, innovation, the future**", "**Stability, order, the present**"],
          ["Approach to people", "**Inspires and motivates**; develops people", "**Directs and controls**; allocates and supervises"],
          ["Question asked", "'**What** and **why**?'", "'**How** and **when**?'"],
          ["Time horizon", "Long-term vision", "Short-term targets and budgets"],
          ["Attitude to risk", "Takes calculated risks", "Minimises risk"],
          ["Relationship with subordinates", "Followers", "Subordinates"],
          ["May exist without the other?", "A leader may have **no formal position** (informal leader)", "A manager may have a position but **no followers**"]],
         [2.4, 7.4, 7.4],
         "Leader vs Manager \u2014 a frequently asked 5-mark comparison")),
('quote', ("Management is doing things right; leadership is doing the right things.", "Peter Drucker")),
('h3', "Sources of Power a Leader May Use (French & Raven)"),
('tbl', (["Type of power", "Source", "Comment"],
         [["**Legitimate power**", "The formal position held", "Necessary but by itself the weakest motivator"],
          ["**Reward power**", "Ability to give rewards \u2014 pay, promotion, appreciation, good duty", "Effective but creates dependence"],
          ["**Coercive power**", "Ability to punish \u2014 memo, transfer, adverse report", "Produces compliance but destroys trust and initiative; use sparingly"],
          ["**Expert power**", "Superior knowledge and skill", "**Highly effective in health care** \u2014 professionals follow competence"],
          ["**Referent power**", "Personal charisma, integrity and the respect others feel", "**The most durable form** \u2014 people follow because of who you are"],
          ["**Informational power**", "Access to and control of information", "Should be used to inform, not to manipulate"]],
         [3.0, 6.4, 7.8],
         "Sources of power")),

('h2', "11.3  Qualities / Attributes of a Good Leader"),
('p', "This is the most frequently asked part of the chapter. Group the qualities \u2014 a grouped answer scores far better than a random list of adjectives."),
('h3', "A. Personal Qualities"),
('b', [
    "**Integrity and honesty** \u2014 the foundation; a leader who is not trusted cannot lead. In a laboratory this means never falsifying data and never asking anyone else to.",
    "**Self-confidence** balanced by **humility** \u2014 willing to say 'I do not know' and 'I was wrong'.",
    "**Self-awareness and emotional intelligence** \u2014 knowing one's own strengths, weaknesses, triggers and impact on others.",
    "**Emotional stability and self-control** \u2014 calm in a crisis; a leader who panics multiplies panic.",
    "**Courage** \u2014 to stop an unsafe practice, to report an error, to defend a junior, to say no to a superior's improper instruction.",
    "**Enthusiasm, energy and initiative** \u2014 leaders start things.",
    "**Perseverance and resilience** \u2014 the ability to absorb setbacks.",
    "**Discipline and punctuality** \u2014 the leader sets the standard by example.",
    "**Positive attitude and optimism**, without denial of reality."
]),
('h3', "B. Professional / Intellectual Qualities"),
('b', [
    "**Technical and professional competence** \u2014 in health care, credibility comes first from competence (**expert power**).",
    "**Vision and foresight** \u2014 the ability to see where the department should be in three years, and to articulate it.",
    "**Sound and timely decision-making**, including under uncertainty and under time pressure.",
    "**Problem-solving and analytical ability**; using data rather than impressions.",
    "**Planning and organising ability**; realistic goal-setting.",
    "**Knowledge of ethics, law and regulation** governing the field.",
    "**Continuous learning** and openness to new methods and evidence.",
    "**Innovation and adaptability** \u2014 particularly in a rapidly automating field."
]),
('h3', "C. Interpersonal / Social Qualities"),
('b', [
    "**Excellent communication skills** \u2014 clear briefing, active listening, effective feedback (see Chapter 4).",
    "**Empathy and compassion** \u2014 towards patients *and* towards staff; knowing that the technologist on the third consecutive night duty needs help, not criticism.",
    "**Ability to motivate and inspire**; recognising and appreciating good work publicly.",
    "**Team-building ability** \u2014 selecting, developing and welding individuals into a team.",
    "**Delegation** \u2014 with clear authority and follow-up, and without abdicating accountability.",
    "**Fairness and impartiality** \u2014 no favouritism in rosters, leave, promotion or blame. Perceived unfairness is the fastest destroyer of team morale.",
    "**Conflict-resolution skill** \u2014 addressing disputes early and directly.",
    "**Mentoring and developing others** \u2014 the true measure of a leader is the quality of the people he leaves behind.",
    "**Approachability** \u2014 juniors must feel safe to bring bad news; **psychological safety** is now recognised as the most important single determinant of team effectiveness.",
    "**Cultural sensitivity and inclusiveness.**"
]),
('h3', "D. Ethical and Organisational Qualities"),
('b', [
    "**Accountability and responsibility** \u2014 'the buck stops here'; taking the blame and sharing the credit.",
    "**Leading by example (role modelling)** \u2014 the most powerful teaching tool in any hospital; if the leader wears gloves and washes hands, so does the team.",
    "**Advocacy** \u2014 speaking up for the patient, and for the staff, to higher authority.",
    "**Commitment to quality and patient safety** \u2014 insisting on QC, SOPs and accreditation even when it is inconvenient.",
    "**Transparency** in decisions, criteria and information.",
    "**Stewardship** \u2014 responsible use of the organisation's resources.",
    "**Willingness to be led** \u2014 good **followership** is part of leadership."
]),
('mne', ("\u201CL-E-A-D-E-R-S-H-I-P\u201D \u2014 qualities of a leader",
         ["**L** \u2013 **L**istening and communication",
          "**E** \u2013 **E**mpathy and emotional intelligence",
          "**A** \u2013 **A**ccountability (and Accessibility)",
          "**D** \u2013 **D**ecision-making and **D**elegation",
          "**E** \u2013 **E**xample \u2014 leads by it; **E**thical integrity",
          "**R** \u2013 **R**esponsibility and **R**esilience",
          "**S** \u2013 **S**elf-awareness and **S**elf-control",
          "**H** \u2013 **H**umility and **H**onesty",
          "**I** \u2013 **I**nitiative, **I**nnovation, **I**nspiration",
          "**P** \u2013 **P**rofessional competence and **P**lanning (vision)"])),

('h2', "11.4  Styles of Leadership"),
('h3', "A. The Classical Three Styles (Kurt Lewin, 1939) \u2014 learn these first"),
('tbl', (["Style", "Characteristics", "Advantages", "Disadvantages", "Best used when"],
         [["**Autocratic / Authoritarian**", "The leader alone decides and instructs; centralised authority; one-way communication; obedience expected", "**Fast decisions**; clear direction; effective in a crisis; suits inexperienced staff", "Kills initiative and morale; creates dependence and resentment; errors go unreported", "**Emergencies** \u2014 a mass-casualty incident, a fire in the laboratory, a cardiac arrest; also with wholly untrained staff"],
          ["**Democratic / Participative**", "The leader consults the team and decides with them; two-way communication; shared responsibility", "**High morale, motivation and ownership**; better decisions; develops people; encourages reporting of problems", "**Slow**; unsuitable in an emergency; may cause indecision if consensus fails", "**Routine day-to-day management** \u2014 the best general style for a laboratory; quality improvement, SOP writing, roster planning"],
          ["**Laissez-faire / Free-rein / Delegative**", "The leader gives minimal direction and lets the team decide; hands-off", "Maximum freedom and creativity; suits highly skilled, self-motivated experts", "**Risk of chaos, drift, low accountability and poor quality**; the most dangerous style with untrained staff", "A team of experienced, self-directed professionals working on research or a specialised project"]],
         [2.8, 4.6, 3.4, 3.4, 3.4],
         "Lewin's three classical leadership styles")),
('h3', "B. Other Important Styles and Models"),
('tbl', (["Style / Model", "Essence"],
         [["**Transactional leadership**", "An exchange relationship \u2014 performance for reward, deviation for correction; management by exception; focuses on tasks, targets and rules. Effective for maintaining standards and turnaround times"],
          ["**Transformational leadership**", "Inspires and transforms followers through the '**four I's**': **Idealised influence** (role model), **Inspirational motivation** (vision), **Intellectual stimulation** (encourages questioning and innovation) and **Individualised consideration** (mentors each person). **Widely regarded as the most effective style in health care**, and associated with better staff retention and patient outcomes"],
          ["**Servant leadership** (Robert Greenleaf)", "The leader's first role is to **serve** \u2014 to remove obstacles, provide resources and develop people; 'leader as servant of the team'. Fits health-care values particularly well"],
          ["**Situational leadership** (Hersey & Blanchard)", "There is **no one best style**; the leader adapts to the follower's *maturity/readiness*: **Directing (telling)** for low competence and low commitment \u2192 **Coaching (selling)** \u2192 **Supporting (participating)** \u2192 **Delegating** for high competence and high commitment"],
          ["**Contingency theory** (Fiedler)", "Effectiveness depends on the match between the leader's style (task-oriented or relationship-oriented) and the favourability of the situation \u2014 leader\u2013member relations, task structure and position power"],
          ["**Bureaucratic leadership**", "Strict adherence to rules and procedures. Appropriate where safety, law and standardisation are paramount \u2014 e.g. blood banking, radiation safety, biomedical waste \u2014 but rigid and slow to innovate"],
          ["**Charismatic leadership**", "Influence based on personal magnetism and conviction; highly motivating but dependent on the individual and risky if the person departs or errs"],
          ["**Paternalistic leadership**", "The leader acts as a benevolent parent \u2014 caring but decision-making retained. Common in Indian organisations; builds loyalty but limits autonomy"],
          ["**Coaching leadership**", "Focus on developing each individual's capability through feedback and stretch assignments"],
          ["**Collaborative / Shared / Distributed leadership**", "Leadership is distributed across the team according to expertise \u2014 the emerging model in multidisciplinary health care"],
          ["**Ethical / Authentic leadership**", "Decisions grounded in declared values, with self-awareness, transparency and moral courage"],
          ["**Clinical leadership**", "Leadership exercised by front-line clinical staff in improving care, irrespective of formal position \u2014 'leadership at every level'"]],
         [4.6, 12.6],
         "Other leadership styles and models")),
('warn', ["**The examiner's expected conclusion on styles: there is no single best style.** An effective leader **diagnoses the situation** \u2014 the urgency, the competence and commitment of the staff, and the nature of the task \u2014 and **flexibly adapts** the style. Autocratic in an emergency, democratic in routine quality work, delegative with experienced experts, coaching with a new recruit. State this explicitly and you demonstrate understanding rather than memorisation."]),
('h3', "C. Classical Theories of Leadership (mention in a long answer)"),
('b', [
    "**Trait theory (Great Man theory)** \u2014 leaders are born with certain innate traits; criticised because no universal set of traits has ever been established.",
    "**Behavioural theories** \u2014 leadership is a set of learnable *behaviours*, not innate traits; includes the Ohio State studies (**initiating structure** and **consideration**) and the Michigan studies (**production-centred** and **employee-centred**).",
    "**Managerial Grid (Blake & Mouton)** \u2014 plots *concern for production* against *concern for people* on a 9 \u00d7 9 grid: 1,1 **impoverished**; 9,1 **task/authority-compliance**; 1,9 **country club**; 5,5 **middle of the road**; **9,9 team management \u2014 the ideal**.",
    "**Contingency and situational theories** \u2014 Fiedler, Hersey & Blanchard, path\u2013goal theory (House), Vroom\u2013Yetton decision model.",
    "**Transactional\u2013Transformational theory** (Burns, Bass) \u2014 as above.",
    "**Emotional intelligence theory (Goleman)** \u2014 the competencies of **self-awareness, self-regulation, motivation, empathy and social skill** distinguish outstanding leaders; Goleman also described six styles: **coercive, authoritative (visionary), affiliative, democratic, pacesetting and coaching**."
]),

('h2', "11.5  Functions of a Leader in a Health-Care Setting"),
('n', [
    "**Setting direction** \u2014 defining the vision, goals and standards of the section or laboratory.",
    "**Planning and organising** \u2014 workload, rosters, resources, workflow, space.",
    "**Staffing and developing** \u2014 recruitment, orientation, training, competency assessment, career development.",
    "**Directing and coordinating** \u2014 assigning work, integrating shifts and sections, liaising with wards, blood bank and clinicians.",
    "**Motivating** \u2014 recognition, appreciation, fair reward, meaningful work.",
    "**Communicating** \u2014 upward, downward and laterally; running effective meetings; ensuring handovers happen.",
    "**Decision-making and problem-solving**, including in crises.",
    "**Controlling and monitoring** \u2014 quality indicators, TAT, rejection rates, QC and EQAS performance, audit.",
    "**Maintaining discipline and standards**, fairly and consistently.",
    "**Resolving conflict** within the team and with other departments.",
    "**Representing the team** \u2014 advocating for staff and resources to higher management, and representing the laboratory in hospital committees.",
    "**Ensuring safety** \u2014 biosafety, waste management, incident reporting, staff immunisation.",
    "**Change management** \u2014 introducing a new analyser, LIS or accreditation programme, and managing the resistance it provokes.",
    "**Mentoring and succession planning** \u2014 developing the next generation of leaders.",
    "**Modelling ethical behaviour** \u2014 the leader's conduct becomes the department's norm."
]),

('h2', "11.6  Teamwork"),
('def', ("Team",
         "A **small group of people with complementary skills**, who are **committed to a common purpose, performance goals and approach**, and who hold themselves **mutually accountable** for the outcome (Katzenbach & Smith).")),
('def', ("Teamwork",
         "The **cooperative and coordinated effort** of the members of a group to achieve a common goal efficiently and effectively, in which individual interests are subordinated to the unity and objectives of the group.")),
('def', ("Health-care team",
         "A group of health professionals from **different disciplines**, each contributing specific expertise, who work **interdependently** in the planning and delivery of care for a patient, with a shared goal and shared accountability.")),
('h3', "Difference Between a Group and a Team"),
('tbl', (["Basis", "**Group**", "**Team**"],
         [["Goal", "Individual goals; members may work on unrelated tasks", "**One shared, common goal**"],
          ["Accountability", "**Individual** accountability only", "**Individual *and* mutual** accountability"],
          ["Skills", "Random or similar skills", "**Complementary** skills, deliberately combined"],
          ["Interdependence", "Low \u2014 members can work independently", "**High** \u2014 the output depends on coordination"],
          ["Leadership", "Usually one clear appointed leader", "Leadership may be **shared/rotated** by expertise"],
          ["Output", "Sum of individual contributions", "**Collective work product \u2014 synergy** (output greater than the sum of parts)"],
          ["Example", "All the staff of a hospital; people waiting at a bus stop", "The transfusion team; a code-blue team; the phlebotomy\u2013laboratory\u2013reporting chain for one patient"]],
         [2.4, 7.4, 7.4],
         "Group vs Team")),
('h3', "Types of Health-Care Teams"),
('b', [
    "**Multidisciplinary team** \u2014 members of different disciplines each assess and treat separately within their own boundaries, and then share information (parallel working).",
    "**Interdisciplinary team** \u2014 members work jointly, share decision-making and produce an integrated plan (collaborative working).",
    "**Transdisciplinary team** \u2014 roles deliberately blur and members cross traditional boundaries.",
    "**Intradisciplinary team** \u2014 members of the same discipline, e.g. all the technologists of the haematology section.",
    "**Functional / departmental team** \u2014 the biochemistry section team.",
    "**Cross-functional team** \u2014 members drawn from several departments for a purpose, e.g. the hospital infection-control committee or a NABL accreditation team.",
    "**Project team / Quality circle / Task force** \u2014 temporary, formed for a specific problem, e.g. a team to reduce sample-rejection rates.",
    "**Self-managed team** \u2014 plans and controls its own work, e.g. a night-shift team.",
    "**Virtual team** \u2014 works across locations through technology, e.g. tele-pathology reporting.",
    "**Emergency / code team** \u2014 assembled instantly with predefined roles, e.g. a code-blue or trauma team."
]),

('h2', "11.7  Stages of Team Development \u2014 Tuckman's Model (1965)"),
('p', "**This is highly examinable.** Learn the five stages in order, with a one-line description and the leader's task in each."),
('flow', ["**1. FORMING** \u2014 Members meet, are polite, anxious and dependent on the leader. Roles and goals are unclear; there is little real work. *Leader's task:* **direct** \u2014 introduce, clarify goals, roles and ground rules.",
          "**2. STORMING** \u2014 Conflict emerges over roles, authority, methods and status; cliques form; morale may dip; some resist the task. *Leader's task:* **coach** \u2014 surface and resolve conflict, re-clarify roles, keep the focus on the goal. **This stage is normal and necessary \u2014 not a failure.**",
          "**3. NORMING** \u2014 Norms, trust and cohesion develop; roles are accepted; the team begins to cooperate and to give feedback constructively. *Leader's task:* **support and facilitate**; reinforce standards.",
          "**4. PERFORMING** \u2014 The team is mature, interdependent, motivated and highly productive; it solves problems itself; leadership is shared. *Leader's task:* **delegate**; remove obstacles; develop members.",
          "**5. ADJOURNING (Mourning)** \u2014 Added by Tuckman and Jensen (1977). The team disbands after achieving its purpose; members feel loss. *Leader's task:* **recognise, celebrate, evaluate, document learning and reassign** people well."]),
('mne', ("\u201CForm \u2013 Storm \u2013 Norm \u2013 Perform \u2013 Adjourn\u201D",
         ["A rhyming sequence that is easy to reproduce under exam pressure. Add the leader's role in each: **Direct \u2192 Coach \u2192 Support \u2192 Delegate \u2192 Close** (which conveniently matches Hersey & Blanchard's situational leadership)."])),

('h2', "11.8  Characteristics of an Effective Team"),
('n', [
    "**A clear, shared, understood goal** which all members accept.",
    "**Clearly defined roles and responsibilities** \u2014 everyone knows who does what, and who is accountable.",
    "**Open, honest and frequent communication**, in all directions, with structured handovers (SBAR).",
    "**Mutual trust and respect** for each member's contribution \u2014 including the phlebotomist and the housekeeping staff.",
    "**Psychological safety** \u2014 members can raise concerns, admit mistakes and ask questions without fear of humiliation. *(This is the single strongest predictor of team effectiveness in the research literature \u2014 quote it.)*",
    "**Complementary skills** and appropriate skill-mix.",
    "**Shared leadership and participative decision-making**; expertise, not rank, decides.",
    "**Mutual accountability** \u2014 'we succeed or fail together'.",
    "**Effective conflict management** \u2014 conflict is addressed openly and early, focused on the issue and not the person.",
    "**Cohesion and a sense of belonging**, with a positive team identity.",
    "**Flexibility and adaptability** \u2014 members cover for each other.",
    "**Competent, supportive leadership** and adequate resources.",
    "**Continuous learning and reflection** \u2014 debriefs, audits, incident reviews, root-cause analysis.",
    "**Recognition and celebration** of achievement.",
    "**Situational awareness and cross-monitoring** \u2014 members watch out for each other's errors ('watching each other's back' \u2014 a core TeamSTEPPS concept)."
]),
('mne', ("\u201CT-E-A-M-W-O-R-K\u201D \u2014 characteristics of an effective team",
         ["**T** \u2013 **T**rust and psychological safety",
          "**E** \u2013 **E**ffective, open communication",
          "**A** \u2013 **A**ccountability \u2014 mutual and individual",
          "**M** \u2013 **M**utual respect and support",
          "**W** \u2013 **W**ell-defined roles and responsibilities",
          "**O** \u2013 **O**ne shared goal",
          "**R** \u2013 **R**ecognition and reward",
          "**K** \u2013 **K**nowledge sharing and continuous learning"])),
('h3', "Benefits of Teamwork"),
('b', [
    "**Improved patient safety** \u2014 the strongest argument: most serious errors are traced to teamwork and communication failure, so functioning teams prevent harm.",
    "**Better quality of care** and better clinical outcomes.",
    "**Synergy** \u2014 output greater than the sum of individual efforts.",
    "**Reduced turnaround time** through coordination and elimination of duplication.",
    "**Fewer errors** \u2014 cross-monitoring catches slips before they reach the patient.",
    "**Shared workload** \u2014 less individual stress and burnout.",
    "**Better decisions** \u2014 more information, more perspectives.",
    "**Learning and skill transfer** between members.",
    "**Higher morale, motivation and job satisfaction**; lower turnover and absenteeism.",
    "**Innovation** \u2014 diverse teams generate better ideas.",
    "**Continuity of care** across shifts and departments.",
    "**Efficient use of resources** \u2014 equipment, staff and reagents."
]),

('h2', "11.9  Barriers to Effective Teamwork"),
('tbl', (["Category", "Barriers"],
         [["**Communication**", "Poor or absent handover; jargon and abbreviation; hierarchy preventing juniors from speaking; no structured tool such as SBAR; language differences; reliance on assumption rather than confirmation"],
          ["**Structural / Organisational**", "Unclear or overlapping roles; **steep hierarchy**; departmental silos and 'us vs them' between laboratory and ward; frequent staff rotation destroying familiarity; shift systems with no overlap; understaffing; inadequate resources; conflicting departmental targets"],
          ["**Interpersonal**", "Lack of trust; personality clashes; **blame culture**; bullying and incivility; favouritism; gossip; refusal to accept the competence of another discipline; professional territorialism ('this is not my job')"],
          ["**Leadership**", "Absent, weak or autocratic leadership; unfair rosters and unequal workload; no recognition; leader who shoots the messenger; no follow-up on raised concerns"],
          ["**Individual**", "**Social loafing / free-riding** \u2014 reduced individual effort in a group; ego and status-seeking; resistance to change; poor competence; stress and burnout reducing cooperation; absenteeism and unpunctuality"],
          ["**Group process**", "**Groupthink** \u2014 the desire for consensus suppressing dissent and critical evaluation; **group polarisation**; dominance by one loud member; **diffusion of responsibility** (everyone assumes someone else has phoned the critical value); risky shift"],
          ["**Cultural**", "Differences in language, gender norms, caste or region; inter-professional stereotypes; disrespect towards allied-health staff"]],
         [3.4, 13.8],
         "Barriers to teamwork")),
('warn', ["**Three terms examiners like to test \u2014 be able to define them:**",
          "- **Groupthink** (Irving Janis): a mode of thinking in a cohesive group in which the desire for harmony and consensus overrides realistic appraisal of alternatives; symptoms include the illusion of invulnerability, self-censorship, pressure on dissenters and an illusion of unanimity. *Remedy:* encourage dissent, appoint a devil's advocate, invite outside opinion, and let the leader state his view **last**.",
          "- **Social loafing** (Ringelmann effect): the tendency of individuals to exert **less effort** when working in a group than when working alone, because individual contribution is not identifiable. *Remedy:* define individual responsibilities, make contributions visible, keep teams small, set individual as well as team goals.",
          "- **Diffusion of responsibility:** where a task is everybody's, it becomes nobody's. *Remedy:* name a single accountable owner for every task \u2014 this is precisely why a critical-value SOP must specify **who** telephones."]),

('h2', "11.10  Conflict and Its Resolution"),
('def', ("Conflict",
         "A process that begins when one party perceives that another party has **negatively affected, or is about to negatively affect, something that the first party cares about** \u2014 arising from incompatible goals, values, interests, perceptions or resource claims.")),
('b', [
    "**Not all conflict is bad.** **Functional (constructive) conflict** about *ideas and methods* improves decisions and drives improvement. **Dysfunctional (destructive) conflict** about *persons and personalities* damages the team. The leader's job is to encourage the first and eliminate the second.",
    "**Common sources in a laboratory:** disputes over duty rosters, leave and night shifts; blame for rejected samples between ward and laboratory; workload inequity; credit and recognition; scarce equipment or space; unclear role boundaries; personality clashes; poor communication; and perceived favouritism."
]),
('h3', "Five Strategies of Conflict Resolution (Thomas\u2013Kilmann model)"),
('tbl', (["Strategy", "Assertiveness / Cooperativeness", "Description", "When appropriate"],
         [["**Competing / Forcing**", "High assertive, low cooperative \u2014 *win\u2013lose*", "Pursuing one's own position at the other's expense; using authority", "A genuine **emergency**; when patient safety demands an immediate decision; on non-negotiable safety or legal issues"],
          ["**Accommodating / Smoothing**", "Low assertive, high cooperative \u2014 *lose\u2013win*", "Yielding to the other's position to preserve the relationship", "The issue is **trivial** to you but important to the other; to build goodwill; when you are wrong"],
          ["**Avoiding / Withdrawal**", "Low assertive, low cooperative \u2014 *lose\u2013lose*", "Sidestepping, postponing or withdrawing", "The issue is trivial; emotions are too hot and a cooling-off period is needed; someone else can resolve it better. **Never** for a safety issue"],
          ["**Compromising**", "Moderate on both \u2014 *partial win\u2013partial lose*", "Each side gives up something to reach a mutually acceptable middle position", "Both goals are moderately important; time is short; a temporary settlement is needed; parties are of equal power"],
          ["**Collaborating / Problem-solving**", "High assertive, high cooperative \u2014 ***win\u2013win***", "Working jointly to find a solution fully satisfying both parties' underlying interests", "**The ideal approach** where the issue is important, time permits and the relationship must be preserved \u2014 e.g. redesigning the sample-transport system with the ward instead of blaming it"]],
         [3.0, 3.6, 5.4, 5.2],
         "Thomas\u2013Kilmann conflict-resolution strategies")),
('h3', "Steps in Resolving a Conflict"),
('n', [
    "**Acknowledge that the conflict exists** \u2014 ignoring it lets it grow.",
    "**Act early**, and in **private** \u2014 never confront a colleague in front of patients or juniors.",
    "**Gather the facts** from all sides before forming a view; separate fact from perception.",
    "**Attack the problem, not the person** \u2014 use 'I' statements and describe behaviour, not character.",
    "**Listen actively** to each party in full; let them ventilate.",
    "**Identify the underlying interests**, not just the stated positions \u2014 the ward wants reliable results; the laboratory wants valid samples; the shared interest is the patient.",
    "**Find common ground** \u2014 the patient's welfare is always common ground in health care.",
    "**Generate options** together and evaluate them against the shared goal.",
    "**Agree on a specific solution**, with who will do what by when.",
    "**Document** the agreement where appropriate, and communicate it to those affected.",
    "**Follow up** to confirm the solution is working and the relationship has healed.",
    "**Escalate** to a higher authority or a formal grievance mechanism only if resolution fails, or where misconduct, harassment or patient safety is involved."
]),

('h2', "11.11  Leadership and Teamwork in the Laboratory \u2014 Practical Application"),
('tbl', (["Situation", "Leadership / teamwork behaviour expected"],
         [["**A junior mislabels a sample**", "Do not humiliate publicly. Correct the immediate risk to the patient; then teach privately; ask 'what in the system allowed this?'; strengthen the bedside-labelling process; document the incident in a **blame-free** report. **Fix the system, not just the person**"],
          ["**The ward blames the laboratory for a delay**", "Do not counter-blame. Collaborate: map the actual sample journey together, find where the time was lost, agree a joint fix (transport slots, a dedicated STAT window), and report the improvement back to them. This is **collaborating (win\u2013win)**"],
          ["**Night shift is short-staffed**", "Advocate upward with data (workload figures, TAT, error rates), not with complaints; redistribute tasks fairly in the meantime; ensure the person on duty is supported and relieved"],
          ["**Introducing a new analyser or LIS**", "Change management: explain the *why* first; involve the staff early; train thoroughly before go-live; run parallel systems; identify and support the resisters; celebrate the first successful week"],
          ["**A colleague is repeatedly rude to patients**", "Address it privately and specifically; describe the behaviour and its effect; listen for underlying stress or burnout; set a clear expectation; follow up; escalate only if it continues"],
          ["**A senior instructs you to release results despite failed QC**", "Assertive refusal with the reason; offer the alternative (re-run, repeat calibration, inform the clinician of the delay); escalate in writing if pressed. **Moral courage is a leadership quality**"],
          ["**Building a quality culture**", "Lead by example \u2014 wear the PPE, run the QC, document; make incident reporting safe; hold short daily huddles; display the quality indicators publicly; recognise the person who *reports* an error, not only the person who avoids one"],
          ["**Team morale is low**", "Find out why by asking and listening; address fairness in rosters and leave first (perceived unfairness is the biggest morale-killer); recognise good work publicly; create small wins; involve the team in one visible improvement project"]],
         [4.4, 12.8],
         "Leadership and teamwork in action in the laboratory")),

('key', [
    "**Leadership** = influencing and motivating people towards a common goal; elements = leader, followers, goal, influence, situation.",
    "**Leader vs Manager:** leader does the **right things** (vision, change, personal influence); manager does **things right** (systems, stability, positional authority).",
    "Sources of power (**French & Raven**): legitimate, reward, coercive, **expert**, **referent**, informational. Expert and referent power matter most in health care.",
    "**Lewin's three styles:** **Autocratic** (fast, for emergencies), **Democratic** (best for routine \u2014 high morale), **Laissez-faire** (only for expert, self-motivated teams).",
    "Other styles: **transactional, transformational (the four I's \u2014 best in health care), servant, situational (Hersey & Blanchard), contingency (Fiedler), bureaucratic, charismatic, paternalistic, coaching, distributed, authentic**.",
    "**Blake & Mouton's Managerial Grid \u2014 9,9 'team management' is the ideal.** **Goleman** \u2014 emotional intelligence: self-awareness, self-regulation, motivation, empathy, social skill.",
    "**No single best style** \u2014 the effective leader diagnoses the situation and adapts. Say this in the conclusion.",
    "**Group vs Team:** a team has one shared goal, complementary skills, high interdependence, **mutual accountability** and **synergy**.",
    "**Tuckman: Forming \u2192 Storming \u2192 Norming \u2192 Performing \u2192 Adjourning**; the leader's role shifts **Direct \u2192 Coach \u2192 Support \u2192 Delegate \u2192 Close**.",
    "**Psychological safety** is the strongest single predictor of team effectiveness \u2014 people must be able to speak up without fear.",
    "Barriers: poor communication and handover, steep hierarchy, silos, blame culture, unclear roles, **groupthink**, **social loafing**, **diffusion of responsibility**, understaffing.",
    "**Thomas\u2013Kilmann conflict styles:** competing, accommodating, avoiding, compromising and **collaborating (win\u2013win \u2014 the ideal)**.",
    "Teamwork is a **patient-safety intervention** \u2014 most serious errors arise from communication and teamwork failure."
]),

('tip', [
    "**Expected questions from this chapter:**",
    "- *Long (10 marks):* 'Define leadership. Describe the qualities of a good leader and the different styles of leadership with their merits and demerits.'",
    "- *Long (10 marks):* 'What is teamwork? Discuss the characteristics of an effective team, the stages of team development and the barriers to teamwork in a health-care setting.'",
    "- *Short (5 marks):* Leader vs Manager; Lewin's leadership styles; Transformational leadership; Tuckman's stages; Group vs Team; Barriers to teamwork; Conflict-resolution strategies; Groupthink; Qualities of a leader.",
    "- *Very short (2 marks):* Name Lewin's three styles; the five stages of team development; two differences between a leader and a manager; expand the 'four I's' of transformational leadership; define groupthink; what is social loafing.",
    "**Presentation tip:** for the styles question, **draw the five-column table** (style / characteristics / advantages / disadvantages / when to use). For teamwork, **draw Tuckman's five-stage flow diagram**. Always conclude with the patient-safety argument \u2014 that leadership and teamwork are not 'soft skills' but direct determinants of whether patients are harmed."
]),

('qa', ("QUESTION BANK \u2014 CHAPTER 11", [
    ("Define leadership. Enumerate the qualities of a good leader.",
     ["Definition as in section 11.2, with the five elements \u2014 leader, followers, shared goal, influence and situation \u2014 and Drucker's remark that a leader is 'someone who has followers'.",
      "Qualities, grouped: **personal** \u2014 integrity, confidence with humility, self-awareness and emotional intelligence, emotional stability, courage, enthusiasm, resilience, discipline; **professional/intellectual** \u2014 technical competence, vision, sound and timely decision-making, problem-solving, planning, knowledge of ethics and law, continuous learning, adaptability; **interpersonal** \u2014 communication, empathy, ability to motivate, team-building, delegation, fairness, conflict resolution, mentoring, approachability, cultural sensitivity; **ethical/organisational** \u2014 accountability, leading by example, advocacy, commitment to quality and safety, transparency, stewardship, good followership. *(Mnemonic: LEADERSHIP.)*"]),
    ("Differentiate between a leader and a manager.",
     ["Reproduce the comparison table \u2014 focus (right things vs things right), basis of authority (personal influence vs formal position), orientation (change vs stability), approach to people (inspires vs directs), question asked (what and why vs how and when), time horizon, attitude to risk, and followers vs subordinates. Conclude that health care needs both and that senior professionals must combine the two roles."]),
    ("Describe the styles of leadership with their advantages and disadvantages.",
     ["**Lewin's three:** **Autocratic** \u2014 leader alone decides; fast and clear, good in an emergency and with untrained staff; but kills initiative and morale and suppresses error reporting. **Democratic/participative** \u2014 consults the team; high morale, ownership and better decisions; but slow and unsuitable in a crisis. **Laissez-faire** \u2014 minimal direction; suits expert self-motivated staff; risks chaos and poor accountability.",
      "Add **transactional** and **transformational** (the four I's \u2014 idealised influence, inspirational motivation, intellectual stimulation, individualised consideration), **servant**, **situational** (Hersey & Blanchard \u2014 directing, coaching, supporting, delegating), **bureaucratic**, **charismatic** and **paternalistic**. Conclude that **there is no single best style**; the effective leader adapts to the urgency, the task and the maturity of the staff."]),
    ("Write short notes on transformational leadership.",
     ["Concept (Burns, developed by Bass): the leader transforms followers by raising their motivation, values and aspirations, so that they achieve more than they believed possible. The **four I's**: **Idealised influence** \u2014 acts as a role model and earns trust; **Inspirational motivation** \u2014 communicates a compelling vision and high expectations; **Intellectual stimulation** \u2014 encourages questioning, creativity and challenge to assumptions; **Individualised consideration** \u2014 mentors and attends to each member's growth. Contrast with **transactional leadership**, which is based on exchange, targets and management by exception. Significance: in health care, transformational leadership is associated with higher staff satisfaction and retention, stronger safety culture and better patient outcomes."]),
    ("Differentiate between a group and a team.",
     ["Reproduce the table \u2014 goal (individual vs one shared), accountability (individual vs individual **and** mutual), skills (random vs complementary), interdependence (low vs high), leadership (single appointed vs often shared), output (sum of parts vs **synergy**), and examples. Emphasise **mutual accountability** and **synergy** as the defining features of a team."]),
    ("Describe Tuckman's stages of team development.",
     ["**Forming** \u2014 polite, anxious, dependent on the leader; goals and roles unclear; leader must **direct**. **Storming** \u2014 conflict over roles, authority and methods; cliques; dip in morale; leader must **coach** and resolve conflict; this stage is normal and necessary. **Norming** \u2014 norms, trust and cohesion develop; roles accepted; leader **supports**. **Performing** \u2014 mature, interdependent, highly productive, self-correcting; leader **delegates**. **Adjourning/Mourning** (Tuckman & Jensen, 1977) \u2014 the team disbands; leader should recognise, celebrate, evaluate, capture the learning and reassign members well. Draw the flow diagram and note that the leader's role shifts **Direct \u2192 Coach \u2192 Support \u2192 Delegate \u2192 Close**."]),
    ("What are the characteristics of an effective health-care team?",
     ["A clear shared goal; clearly defined roles and responsibilities; open, frequent communication with structured handover (SBAR); mutual trust and respect; **psychological safety** \u2014 the strongest predictor of team effectiveness; complementary skills and appropriate skill-mix; shared leadership and participative decisions; mutual accountability; effective conflict management; cohesion and team identity; flexibility with members covering for each other; competent supportive leadership and adequate resources; continuous learning through debriefs and audits; recognition of achievement; and **situational awareness with cross-monitoring** so that members catch each other's errors. *(Mnemonic: TEAMWORK.)*"]),
    ("Enumerate the barriers to effective teamwork and how to overcome them.",
     ["Classify as **communication** (poor handover, jargon, hierarchy silencing juniors, no SBAR), **structural/organisational** (unclear roles, steep hierarchy, departmental silos, staff rotation, understaffing, conflicting targets), **interpersonal** (mistrust, personality clashes, **blame culture**, bullying, favouritism, territorialism), **leadership** (absent, autocratic or unfair leadership, no recognition, shooting the messenger), **individual** (social loafing, ego, resistance to change, burnout, absenteeism) and **group process** (**groupthink**, dominance by one member, **diffusion of responsibility**).",
      "Remedies: structured communication tools and handovers; clear role definition with a named owner for every task; flattening hierarchy and building **psychological safety**; a just, blame-free culture; team training and joint meetings between laboratory and wards; fair rosters and recognition; adequate staffing; encouraging dissent and appointing a devil's advocate against groupthink; and making individual contributions visible to prevent social loafing."]),
    ("What is groupthink? How can it be prevented?",
     ["Groupthink (Irving Janis) is a mode of thinking in a highly cohesive group in which the desire for unanimity and harmony overrides the realistic appraisal of alternatives, leading to poor decisions. Symptoms: illusion of invulnerability; collective rationalisation; belief in the group's inherent morality; stereotyping of outsiders; direct pressure on dissenters; **self-censorship**; illusion of unanimity; and self-appointed 'mindguards'. Prevention: the leader should state his own view **last** and encourage open criticism; appoint a **devil's advocate**; invite outside experts; break into independent sub-groups; take an anonymous poll; conduct a 'second-chance' meeting before finalising; and reward those who raise objections. Laboratory relevance: a team that unanimously agrees to 'release results despite failed QC because it is always fine' is exhibiting groupthink."]),
    ("Describe the strategies of conflict resolution.",
     ["**Thomas\u2013Kilmann's five strategies**, along the axes of assertiveness and cooperativeness: **Competing/forcing** (win\u2013lose) \u2014 for emergencies and non-negotiable safety issues; **Accommodating** (lose\u2013win) \u2014 when the issue is trivial to you and important to the other, or when you are wrong; **Avoiding** (lose\u2013lose) \u2014 for trivial issues or a cooling-off period, never for a safety issue; **Compromising** \u2014 when both goals are moderately important and time is short; **Collaborating/problem-solving** (**win\u2013win**) \u2014 the ideal, when the issue matters, time permits and the relationship must be preserved.",
      "Add the steps: acknowledge the conflict; act early and in private; gather facts from all sides; attack the problem not the person; listen actively; identify underlying interests rather than positions; find common ground (the patient's welfare); generate and evaluate options; agree a specific solution with owners and deadlines; document; follow up; and escalate only if resolution fails or misconduct or patient safety is involved. Note that **functional conflict about ideas is useful**, while dysfunctional conflict about persons is destructive."]),
    ("How do leadership and teamwork contribute to patient safety?",
     ["The great majority of serious adverse events in health care are traced to failures of **communication, handover and teamwork** rather than to lack of technical knowledge. Effective teams practise cross-monitoring and catch errors before they reach the patient; structured communication (SBAR, read-back, checklists, huddles) prevents mis-transmission of critical information; **psychological safety** ensures that a junior will speak up about a wrong label or an unsafe instruction; a **just, blame-free culture** produces incident reports, which are the raw material of system improvement; and clear allocation of responsibility prevents **diffusion of responsibility** so that the critical value is actually telephoned. Leaders create these conditions \u2014 by role modelling, by resourcing, by fairness and by insisting on quality. Hence leadership and teamwork are not 'soft skills' but **direct determinants of whether patients are harmed**."]),
])),

('recap', [
    "**Leadership** = influencing people towards a shared goal; leader \u2260 manager (**right things** vs **things right**).",
    "Power: legitimate, reward, coercive, **expert**, **referent**, informational.",
    "**Lewin:** Autocratic (emergency) | **Democratic (best for routine)** | Laissez-faire (experts only).",
    "**Transformational = the four I's** \u2014 idealised influence, inspirational motivation, intellectual stimulation, individualised consideration.",
    "**No single best style** \u2014 diagnose the situation and adapt (Hersey & Blanchard).",
    "**Team** = shared goal + complementary skills + interdependence + **mutual accountability** + **synergy**.",
    "**Tuckman: Form \u2192 Storm \u2192 Norm \u2192 Perform \u2192 Adjourn**; leader: Direct \u2192 Coach \u2192 Support \u2192 Delegate \u2192 Close.",
    "**Psychological safety** = the strongest predictor of team effectiveness.",
    "Watch for **groupthink, social loafing, diffusion of responsibility, blame culture**.",
    "**Conflict:** compete | accommodate | avoid | compromise | **collaborate (win\u2013win, ideal)**.",
    "Teamwork is a **patient-safety intervention**, not a soft skill.",
]),

]
